### PR TITLE
[Bugfix] Import a prog. exercise by cloning instead of forking

### LINKED ISSUE #2451: Do not fork repositories on programming exercise import
### Describe the bug
Programming exercises can't be imported because the maximum depth of the fork hierarchy exceeds 5.

Exemplary error message:
`"message":"GBS2021NTHREADS/gbs2021nthreads-exercise cannot be forked. For performance reasons, fork hierarchies are limited to a maximum depth of 5 beneath a given root repository. Please create your fork from a repository higher up in the hierarchy, such as GBS2021NPROZESSE/gbs2021nprozesse-exercise."`

The error and possible solutions are documented in the [Bitbucket documentation](https://confluence.atlassian.com/bitbucketserverkb/repo-cannot-be-forked-fork-hierarchies-are-limited-to-a-maximum-depth-of-5-872264209.html).

As a workaround, programming exercises higher in the fork hierarchy should be imported.
To prevent this error in the future, we should stop using forks to import programming exercises with Bitbucket.

#### To Reproduce

1. Import a programming exercise
2. Import the imported programming exercise
3. Repeat step 1. and 2. five times to produce the error.

### PR DESCRIPTION
**Pull request by derLalla**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

@kloessst found an issue (#2451) when importing programming exercises more than 5 times. Bitbucket does not allow forking for more than 5 times of the same root repository.

### Description

We solve this issue by not forking at all but rather pushing the content of a source repository into a target's repository. 
Closes #2451 

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a new programming exercise A
4. Import this exercise and name it A1
5. Import exercise A1 and name it A2. 
6. Repeat step 4 and 5 five times until you get the exercises A1-A5
7. Import the exercise A5 and verify that the sixth importing still succeeds

### Test Coverage

BitbucketService.java: 76%
GitService.java: 79%

### CODE REVIEW

**Review by DenizShabani — DISMISSED** [review]
Tested on TS1 and imported it 10 times and everything seemed to work.

**Review by airelawaleria — DISMISSED** [review]
Tested on ts1 with 10 imports from A1-A10. All imports were successful.

**Review by sjagla27 — APPROVED** [review]
Was able to import one exercise more than five times. Code looks good too.

**Review by jpbernius — DISMISSED** [review]

**Review by JannisBittlmayer — DISMISSED** [review]
Tested on TS1, works as intended.

**Review by FlorianStang — DISMISSED** [review]
Tested on TS1, everything worked as intended.

**Review by LudwigWeide — DISMISSED** [review]
Tested on TS2. Works with more than 5 imports, but I had to chose a name with at least 3 characters for both short name and title (Not an issue, but maybe mention this in the testing steps).

**Review by marvinchimeka — DISMISSED** [review]
Everything worked as intended.

**Review by EneaGore — DISMISSED** [review]
Worked as intended on ts2.

**Review by balazs-czopf — APPROVED** [review]
Code lgtm and works as expected on TS2. Nice work.

**Review by nutatuna — DISMISSED** [review]
Confirm worked as intended on ts2

**Review by JohannesWeiss — APPROVED** [review]
Worked as intended for me as well.

File: src/main/java/de/tum/in/www1/artemis/service/connectors/bitbucket/BitbucketService.java [hunk 1]
```diff
@@ -265,6 +270,29 @@ public VcsRepositoryUrl copyRepository(String sourceProjectKey, String sourceRep
...
     }
 
+    @Override
+    public VcsRepositoryUrl copyRepository(String sourceProjectKey, String sourceRepositoryName, String targetProjectKey, String targetRepositoryName) {
+        final var targetRepoSlug = targetProjectKey.toLowerCase() + "-" + targetRepositoryName.toLowerCase();
+        try {
+            var sourceRepoUrl = getCloneRepositoryUrl(sourceProjectKey, sourceRepositoryName.toLowerCase());
+            URL sourceRepositoryUrlAsUrl = new URL(sourceRepoUrl.toString());
+            // checkout the source repo
+            Repository sourceRepo = gitService.getOrCheckoutRepository(sourceRepositoryUrlAsUrl, true);
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/bitbucket/BitbucketService.java:280]: what happens in the following scenario (which happens rather often)? 

1) An instructor works in the online code editor in the source template repository, commits&pushes changes.
2) The instructor also works offline in his IDE and commits&pushes changes
3) There is a merge conflict in the template repository on the Artemis server
4) Sometimes later, the instructor imports the exercise.

I would assume that `getOrCheckoutRepository(...)` will reuse the existing repository (which is in a conflict state), and will try to pull the latest changes, which will fail. Then the whole import would fail.

I think we should avoid this issue. I see the following easy fix: Instead of reusing the existing repository with `getOrCheckoutRepository(url, boolean)`, we should rather clone the repository from Bitbucket again into a new folder (this is e.g. also done when we export git repos) using the method `getOrCheckoutRepository(URL repoUrl, boolean pullOnGet, String targetPath)`. The targetPath could e.g. be `REPO_CLONE_PATH`

**Review by krusche — CHANGES_REQUESTED** [review]
The changes look good 👍  I only see one issue when there is a merge conflict due to prior editing in the online editor. I think we can easily avoid this, by using a different folder

File: src/main/java/de/tum/in/www1/artemis/service/connectors/bitbucket/BitbucketService.java (hunk 1 above)
Comment (krusche) [reply src/main/java/de/tum/in/www1/artemis/service/connectors/bitbucket/BitbucketService.java:280]: In this case, we should also delete the newly cloned repository after it has been copied successfully.

Comment (derLalla) [reply src/main/java/de/tum/in/www1/artemis/service/connectors/bitbucket/BitbucketService.java:280]: But won't the repository directly from Bitbucket be also in a conflict state unless the merge conflict was fixed? 
And in case the merge conflict was solved, is the repo on Artemis still broken? This would mean that (independent from importing) the source template repo on Artemis would not work, right?

**Review by airelawaleria — APPROVED** [review]
Tested again on t3 with 10 sequentiall imports, still works. Re-approve

**Review by marvinchimeka — APPROVED** [review]
Tested on ts3. Re-approve.

**Review by JohannesWeiss — APPROVED** [review]
Re-Approve, works as intended.

**Review by EneaGore — APPROVED** [review]
Retested and still works.

**Review by LudwigWeide — APPROVED** [review]
Tested on TS1. Works as intended.

File: src/main/java/de/tum/in/www1/artemis/service/connectors/bitbucket/BitbucketService.java (hunk 1 above)
Comment (derLalla) [reply src/main/java/de/tum/in/www1/artemis/service/connectors/bitbucket/BitbucketService.java]: resolved in the latest commit

**Review by simonzilker — APPROVED** [review]
Works as intended on ts3

**Review by kloessst — APPROVED** [review]
Tested multiple chained imports and also the conflict state problem mentioned by @krusche. Participating also worked as expected.

Code looks fine to me. Well done 💯

**Review by krusche — APPROVED** [review]

**Comment by krusche** [comment]
Thanks for this contribution 👍
