### PR TITLE
[Bugfix] Gitlab/Jenkins fails when deleting non-existant build plans/repositories

### LINKED ISSUE #1778: Deleting a course leaves Repos and Build plans in the other servers
### Describe the bug
When deleting a course, the repos and build plans are not deleted. However, when deleting each single exercise they are.

#### To Reproduce
Create a course with an exercise and then delete the course.

#### Expected behavior
A warning should be given and all exercise materials should be deleted.

### Environment
<details><pre>
 - OS: Linux server, Mac Client
 - Browser Firefox
 - Version HEAD
</pre></details>

#### Additional context
Gitlab and Jenkins connector

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

Resolves #1778

Deleting a programming exercise including its associated build plans and code repositories fail with a 500 Internal Error in the Jenkins/Gitlab environments if one or more build plans and/or repositories do not exist. This bug also prevents users from deleting courses. 
### Description

This PR adds extra exception handling and checks if deletion failure is caused by a 404 status code (build plan or repository not found). If that's the case, we don't throw the exception. Other errors are thrown as normal. 

### Steps for Testing

**Use TS2**
1. Log in to Artemis
2. Navigate to Course Administration
3. Generate some programming exercises (1 or more)
4. Participate in one or more exercise
4. Go to Gitlab and delete some repositories that belong to the exercise (e.g Templates or Tests)
5. Go to Jenkins and delete some build plans that belong to the exercises (you can also delete the entire project)
6. Go back to Artemis and either delete the entire course that contains the exercises or delete the programming exercises separately (make sure to check the options to also delete the build plans and repositories)
7. Deletion should be successful

### Test Coverage

GitLabService.java 82%
JenkinsBuildPlanService.java 90%
JenkinsService 79%
JenkinsJobService 67%

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabService.java [hunk 1]
```diff
@@ -260,7 +263,10 @@ public void deleteRepository(VcsRepositoryUrl repositoryUrl) {
             gitlab.getProjectApi().deleteProject(repositoryId);
         }
         catch (GitLabApiException e) {
-            throw new GitLabException("Error trying to delete repository on GitLab: " + repositoryName, e);
+            // Do not throw an exception if we try to delete a non-existant repository.
+            if (e.getHttpStatus() != 404) {
```
Comment (derLalla) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabService.java:267]: couldn't you use also the `HttpStatus.SC_NOT_FOUND` as in the deleteBuildPlan exception handling?

File: src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/JenkinsService.java [hunk 2]
```diff
@@ -250,6 +251,13 @@ public void deleteProject(String projectKey) {
         try {
             jenkinsServer.deleteJob(projectKey, useCrumb);
         }
+        catch (HttpResponseException e) {
+            // We don't throw an exception if the project doesn't exist in Jenkins (404 status)
+            if (e.getStatusCode() != org.apache.http.HttpStatus.SC_NOT_FOUND) {
```
Comment (derLalla) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/JenkinsService.java:256]: you could optimise the import here ;)

File: src/test/java/de/tum/in/www1/artemis/connector/jenkins/JenkinsRequestMockProvider.java [hunk 3]
```diff
@@ -434,15 +435,20 @@ private void mockAddInstructorAndTAPermissionsToUsersForFolder(String folderName
     public void mockDeleteBuildPlan(String projectKey, String planName, boolean shouldFail) throws IOException {
         mockGetFolderJob(projectKey, new FolderJob());
         if (shouldFail) {
-            doThrow(IOException.class).when(jenkinsServer).deleteJob(any(FolderJob.class), eq(planName), eq(useCrumb));
+            doThrow(new HttpResponseException(40, "Bad Request")).when(jenkinsServer).deleteJob(any(FolderJob.class), eq(planName), eq(useCrumb));
```
Comment (derLalla) [inline src/test/java/de/tum/in/www1/artemis/connector/jenkins/JenkinsRequestMockProvider.java:438]: do you mean 400?

```suggestion
            doThrow(new HttpResponseException(400, "Bad Request")).when(jenkinsServer).deleteJob(any(FolderJob.class), eq(planName), eq(useCrumb));
```

**Review by derLalla — CHANGES_REQUESTED** [review]
These are nice changes! I have left some small comments.

File: src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/JenkinsService.java (hunk 2 above)
Comment (ivanchimeno) [reply src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/JenkinsService.java:256]: Sadly it won't work here because the class uses another `HttpStatus` from the Spring package

**Review by derLalla — APPROVED** [review]
approving code changes

**Review by krusche — APPROVED** [review]
