### PR TITLE
`General`: Fix ordered list formatting command in the Markdown editor

### LINKED ISSUE #5054: Markdown Editor: Ordered list command breaks text
### Describe the bug

The ordered list command for the markdown editor does not properly reformed the selected lines into a list, but instead removed some parts from the beginning of the lines.

E.g.,
```
We want the application to apply different algorithms for sorting a `List` of `Date` objects.
Use the strategy pattern to select the right sorting algorithm at runtime.
```
is turned into
```
want the application to apply different algorithms for sorting a `List` of `Date` objects.
 the strategy pattern to select the right sorting algorithm at runtime.
```
instead of
```
1. We want the application to apply different algorithms for sorting a `List` of `Date` objects.
2. Use the strategy pattern to select the right sorting algorithm at runtime.
```

### To Reproduce

1. Go to text input with the markdown editor, e.g., the exercise problem statement.
2. Select two lines.
3. Click on the ordered list button above the editor.
4. The text has not been turned into a list.

### Expected behavior

The text is reformatted as a markdown list as described above.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Firefox

### Additional context

It seems that the command also cannot handle empty lines, as then the next line afterwards gets two numbers (`1.` and the proper number). Maybe both issues are part of the same bug.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Dominik-Weinzierl**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

Closes #5054: Currently the markdown editor had some issues with dots somewhere in the line. This results in unexpected behavior.

### Description

To find out whether the point belongs to our number or not, we split the line at the point and check whether it is a number or not. If it is a valid number, we assume that it is part of an ordered list and remove it accordingly. If not, we assume that we need to add this line to an ordered list.

Additional the issue with more than 9 elements should also be fixed.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exercise

1. Log in to Artemis
2. Navigate to a Markdown editor (e.g. exercise details)
3. Insert multiple lines and create an ordered list
4. Select the orderd list and revert it back to text
5. Insert empty lines and create again an ordered list
6. Check that everything works as expected

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| orderedListCommand.ts | 100% | 100% |

### CODE REVIEW

**Review by akesfeden — COMMENTED** [review]
Tested on TS2, it seems to be working fine when I select the whole text but if I select a line partially then it splits the line like below:

Before:
image

After clicking `Ordered List` button:
image

If we want to handle this case, maybe a solution can be extending the selected text to the whole lines before starting the numbering operations. I have the impression that GitHub's Markdown editor does something similar because it always selects the whole line after I click the `Ordered List` button there.

File: src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts [hunk 1]
```diff
@@ -8,54 +8,62 @@ export class OrderedListCommand extends Command {
...
+                    manipulatedText = '1. ';
+                    continue;
+                }
+                position = 1;
+            } else {
+                // Manipulate the line, e.g. remove the number or add the number.
+                manipulatedText += this.manipulateLine(line, position);
+                position++;
+            }
+            manipulatedText += '\n';
```
Comment (b-fein) [inline src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts:41]: This adds an additional newline after the selection when using the command. It’s not a significant issue, but just slightly unexpected behaviour.

**Review by b-fein — COMMENTED** [review]
Thanks for the quick fix. Works properly for the most frequent use cases of adding/removing numbers to multiple lines and when starting a new numbered list. :+1: 

I think just fixing the base-case of selecting whole lines is enough for this issue. Implementing the fix when selecting partial lines can be moved to a separate PR where the same underlying issue can also be fixed for the unordered lists.

I noticed two more special cases that are handled unexpectedly:

### Indented Lists
Sometimes I might want to use indented numbered lists, where I want to change the last four lines of
```md
- Some overall concept that should be done split into several steps:
    We want the application to apply different algorithms for sorting a `List` of `Date` objects.
    Use the strategy pattern to select the right sorting algorithm at runtime.
    We want the application to apply different. algorithms for sorting a `List` of `Date` objects.
    Use the strategy pattern to select the right sorting algorithm at runtime.
```
into a numbered list. This is turned into
```md
- Some overall concept that should be done split into several steps:
    1. We want the application to apply different algorithms for sorting a `List` of `Date` objects.
2.     Use the strategy pattern to select the right sorting algorithm at runtime.
3.     We want the application to apply different. algorithms for sorting a `List` of `Date` objects.
4.     Use the strategy pattern to select the right sorting algorithm at runtime.
```
when selecting the last four lines. The additional numbers should probably be added after the already present leading spaces.

### Mixed Numbering
A contrived edge-case:
```md
We want the application to apply different algorithms for sorting a `List` of `Date` objects.
Use the strategy pattern to select the right sorting algorithm at runtime.
3. We want the application to apply different. algorithms for sorting a `List` of `Date` objects.
Use the strategy pattern to select the right sorting algorithm at runtime.
```
will be turned into
```md
1. We want the application to apply different algorithms for sorting a `List` of `Date` objects.
2. Use the strategy pattern to select the right sorting algorithm at runtime.
We want the application to apply different. algorithms for sorting a `List` of `Date` objects.
4. Use the strategy pattern to select the right sorting algorithm at runtime.
```
and back again. I suppose this special edge-case doesn’t need to be handled by the command. In real usage this should rarely be relevant.

**Review by joaquinmurcia — COMMENTED** [review]
Perhaps unrelated to this specific PR, but when you put two ordered list one after the other, the numbering is not reset (in the visual view):
image
image
If there is some text in the middle, it's fixed, though:
image

Apart from what @akesfeden and @b-fein mentioned, the new functionality works.

**Comment by Dominik-Weinzierl** [comment]
@b-fein Thank you for your great review!

- Indented Lists: This issue should be fixed now and whitespaces should work as expected
- Mixed Numbering: Yes, this is a case that I could also reproduce, but I'm not sure what the correct expectation would be. So I think we leave the behavior as it is, since this is really an edge case.

**Comment by Dominik-Weinzierl** [comment]
@joaquinmurcia Mhm, yes, you are right, there is a lot of strange behavior in the preview. Could you please open an issue for that?

File: src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts (hunk 1 above)
Comment (Dominik-Weinzierl) [reply src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts]: Yes that was the old behavior - removed now :+1

**Review by b-fein — APPROVED** [review]
Thank you very much, great work!
Lines having leading whitespaces keep them now and the additional newline at the end is no longer added. ⟹ Clear Approval :+1:

Code looks good, too.


As mentioned in the original comment, the mixed numbering should not be a problem in real-world use-cases, so not handling it with the command is perfectly fine.

File: src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts [hunk 2]
```diff
@@ -8,54 +8,69 @@ export class OrderedListCommand extends Command {
...
-        for (const element of parseArray) {
-            this.replaceText(element, parseArray.length - addAmount);
-            addAmount--;
-        }
+        let manipulatedText = '';
+        let position = 1;
+
+        parseArray.forEach((line, index) => {
+            // Empty line -> we start again
+            if (line === '') {
```
Comment (bottbenj) [inline src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts:30]: as noted https://github.com/ls1intum/Artemis/pull/5072#pullrequestreview-971134377 in markdown an unordered list doesn't reset until there is a line with some content (at least `&nbsp;`) that is not part of the list so resetting the list numbering here is misleading.

**Review by bottbenj — APPROVED** [review]
The Issues described were resolved. There are still issues were the numbers of the list items in the source don't match the rendered text (even beyond my comment) but that is probably beyond the scope of this PR.

File: src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts (hunk 2 above)
Comment (b-fein) [reply src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts:30]: I had a look at the CommonMark specification and it looks like there can be an arbitrary number of empty lines between list elements (https://spec.commonmark.org/0.30/#lists, Section 5.3, first paragraph: ‘The list items may be separated by any number of blank lines.’). Therefore, the current behaviour of not resetting the numbering in the preview is actually correct.

Adapting the current numbering implementation to keep empty lines as-is but not increase the index should not be a big change.

Comment (Dominik-Weinzierl) [reply src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts]: I changed the logic to be similar to GitHub:


```
Test

Test
```
will result in (and vice versa):

```
1. Test
2.
3. Test
```

Is that what you would expect?

Comment (Dominik-Weinzierl) [reply src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts]: image

But i guess the Preview has still some issues which should be addressed in another PR

Comment (b-fein) [reply src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts]: Thanks, but I think that GitHub’s implementation in this case is not optimal. I think that it would be closest to the specification if
```
first item

second item
```
would be turned into
```
1. first item

2. second item
```
even if there are an arbitrary number of empty lines between the two items.

Comment (bottbenj) [reply src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts:30]: ok, the 3 being nested into the 2 is definitely not what i would expect to happen when using the command, but to be honest i am not sure if i would expect to happen there if i were to use the commands (i just write markdown directly and don't use them) but probably to skip over the empty lines and to continue the numbering with the next non-empty line

Comment (Dominik-Weinzierl) [reply src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts:30]: Okay should work now as expected :D

File: src/test/javascript/spec/component/markdown-editor/ordered-list-command.spec.ts [hunk 3]
```diff
@@ -43,6 +43,60 @@ describe('OrderedListCommand', () => {
...
+        expect(comp.aceEditorContainer.getEditor().getValue()).toBe('1. Test\n\n2. Test');
+    });
+
+    it('should handle empty lines and remove lists', () => {
+        comp.aceEditorContainer.getEditor().setValue('1. Test\n2.\n3. Test');
+        command.execute();
+        expect(comp.aceEditorContainer.getEditor().getValue()).toBe('Test\n\nTest');
+    });
+
+    it('should handle empty lines and remove lists', () => {
```
Comment (b-fein) [inline src/test/javascript/spec/component/markdown-editor/ordered-list-command.spec.ts:61]:
```suggestion
    it('should handle multiple sequential empty lines and remove lists', () => {
```
The test above has the same name. I suppose Jest doesn’t care but that potentially might create problems when some test report XML parser wants to display the results.

Comment (Dominik-Weinzierl) [reply src/test/javascript/spec/component/markdown-editor/ordered-list-command.spec.ts:61]: Yes you are right. That could be a problem :+1:

**Review by bottbenj — APPROVED** [review]

**Comment by akesfeden** [comment]
> @akesfeden This also affects the unordered list, so I would suggest addressing this as an enhancement in another PR - what are your thoughts on this?
Alright, sounds good to me.

**Review by akesfeden — APPROVED** [review]
Tested again after changes, works good if we ignore the issue about splitting the line at selection start that will be implemented in a new PR.
