### PR TITLE
`Plagiarism checks`: Fix display of plagiarism matches for text and programming exercises

### LINKED ISSUE #6579: `Plagiarism`, `Programming Exercises`: Broken code view
### Describe the bug

In the plagiarism view for programming exercises the file view on the right side remains empty. 

### To Reproduce

1. Have a programming exercise with a few submissions.
2. Run the plagiarism check.
3. Select a case marked as potential plagiarism.
4. The file for student1 on the left side loads, the one on the right side does not.
   - See log output in your browser console as attached at the end of this issue.
5. Changing to different files does not change that.

### Secondary bug, same underlying issue

1. Steps 1-3 from above.
2. Change to another student pair on the left side.
3. Try selecting different files in either left/right view.
4. The shown file contents now no longer match the selected names at the top. (Most of the time, for some files it seems to work.)
5. The same console error appears.

### Expected behaviour

Both files are shown.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.1.5

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

```shell
ERROR TypeError: c[D] is undefined
    insertMatchTokens text-submission-viewer.component.ts:244
    next text-submission-viewer.component.ts:178
    RxJS 29
    Angular 17
    RxJS 64
    handleFileSelect text-submission-viewer.component.ts:175
    RxJS 16
core.mjs:8416:22
```

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
Fixes part of #6579.

@coderabbitai ignore

### Description

Commit 8e081134ddbe87721c7f6a8d6bc270f76e703d5c contains the actually relevant change:
The `PlagiarismComparison` contains a set of `PlagiarismMatch`es:
https://github.com/ls1intum/Artemis/blob/d76fc4171b93faddf61b7383fb910d5ca57f7948/src/main/java/de/tum/in/www1/artemis/domain/plagiarism/PlagiarismComparison.java#L65

Since the `PlagiarismMatch` did not implement an `equals` method, however, it used the object identity equality as fallback and the set contained any duplicates returned from the database. Implementing an `equals` method prevents this now.
When converting the JPlag-report into the Artemis domain models, the conversion is applied correctly and only one copy is actually stored in the database. This issue only occurs in how Hibernate can no longer determine proper equality when fetching the data across joins and turns it into objects.

The `PlagarismMatch` is not a full domain object that has its own unique identifier column. Therefore, the equality check using the ID as used in other Artemis classes extending `DomainObject` is not applied/relevant.

Commit 157ff897381915c862113e2bf0e3a7a45a60c446 only has some small code refactoring that happened during debugging the bug. It only extracts some code from the long method into smaller methods without any actual changes to the logic.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise or 1 text exercise
  - **Note**: make sure that the students are _only_ students in the exercise and do _not_ have any other role in the course. Otherwise their submissions are filtered as part of the plagiarism check.

1. Have a programming/text exercise with a few identical/similar submissions.
2. Run the plagiarism check.
3. Select a case marked as potential plagiarism.
4. The file content looks as submitted with a few coloured highlights where the plagiarism was found. The matches are not repeated.
   - Note: This PR only fixes the repetition of highlighted sections. Especially for programming exercises the actual sections that are highlighted might not make sense. This is out of scope for this PR. See #6579 for an extended discussion. 

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
n/a, see linked issue for examples how it was before:
https://github.com/ls1intum/Artemis/issues/6579#issuecomment-1570332616
https://github.com/ls1intum/Artemis/issues/6579#issuecomment-1814360375

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/domain/plagiarism/PlagiarismMatch.java [hunk 1]
```diff
@@ -66,6 +68,24 @@ public void setLength(int length) {
         this.length = length;
     }
 
+    @Override
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/domain/plagiarism/PlagiarismMatch.java:71]: please add a comment why `equals` is needed here. In other domain classes we avoid it, in particular when they inherit from DomainObject, because then, the id of the database is the unique identifier and DomainObject already offers the equals method. 

For some developers, it's apparently unclear when equals is needed and when not.

**Comment by coolchock** [comment]
Tested on ts4 using test user 15. The matches are not duplicated anymore, however the highlighting of the matches doesn't seem to work properly:
image

Since the plagiarism is 100%, I would expect that both texts are blue.

**Comment by b-fein** [comment]
@coolchock Thanks for testing. This is to be expected:
This PR only fixes the repetition. Fixing the actual sections that are highlighted is out of scope for this PR (see #6579) for more infos. 
I added an additional remark about this to the PR description/steps to test.

**Review by MaximilianJG — APPROVED** [review]
Tested on Ts4. Works as expected. 

Screenshot 2024-01-05 at 08 28 36

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts [hunk 2]
```diff
@@ -53,12 +53,12 @@ export class TextSubmissionViewerComponent implements OnChanges {
...
      * Token that marks the beginning of a highlighted match.
      */
-    public tokenStart = '<span class="plagiarism-match">';
+    private readonly tokenStart = '<span class="plagiarism-match">';
 
     /**
      * Token that marks the end of a highlighted match.
      */
-    public tokenEnd = '</span>';
+    private readonly tokenEnd = '</span>';
```
Comment (Strohgelaender) [inline src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts:62]: Optional: Since this is only used for the string construction and not in the component, you could move these above the component as `const` variables.

**Review by Strohgelaender — APPROVED** [review]
changes make sense and look good to me. Thanks for also improving the code structure, looks much better than that one long method.

**Review by coolchock — APPROVED** [review]
Works as expected, matches aren't duplicated anymore. Tested on ts4

**Review by jakubriegel — APPROVED** [review]

**Review by jakubriegel — APPROVED** [review]
Tested on ts1. No duplicates on:
- plagiarism checks results
- plagiarism case view

For both programming and test exercises.

(The client still highlights duplicated code wrong way.)
