### PR TITLE
`General`: Improve participation user experience

### LINKED ISSUE #12391: `Chore`: Modeling E2E tests failing since Apollon 2 migration
### Describe the bug

In the migration to Apollon 2, selectors and models where not updated in the E2E tests, resulting in test failures because of missing selectors and wrong model formats.

### To Reproduce

Run modeling e2e tests
Notice that the tests fail because of missing selectors / wrong model formats (v3 instead of v4)

### Expected behavior

Tests should pass

### Screenshots

Image

### Which version of Artemis are you seeing the problem on?

9.0.0

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by DominikRemo**
### Summary

This PR improves the student experience for exercise participation by consolidating all exercise-related views into a single, unified split-panel interface. Previously, students had to navigate multiple inconsistent pages to start an exercise, submit work, and review results. Now everything lives in one place, with the problem statement, editor/submission area, and supporting panels (Iris chatbot, discussion, example solution, complaints) all accessible without leaving the page.

Additionally, this PR extends AI feedback (Athena) support in practice mode to **text and modeling exercises**, which previously only worked for programming exercises.

#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.tum.de/developer/guidelines/language).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.tum.de/developer/development-process#pr-naming-conventions).

#### Server
This PR focuses on the client. You can find the previous server-side PR here: #12251

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding guidelines](https://docs.artemis.tum.de/developer/guidelines/client-development).
- [x] I **strictly** followed the [AET UI-UX guidelines](https://ls1intum.github.io/ui-ux-guidelines/).
- [x] Following the [theming guidelines](https://docs.artemis.tum.de/developer/guidelines/client-theming), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Vitest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.tum.de/developer/guidelines/client-tests).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I translated all newly inserted strings into English and German.
- [x] I added multiple screenshots/screencasts of my UI changes.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [ ] I tested all changes and their related features with all corresponding user types on a test server configured with LocalVC and Jenkins.

### Motivation and Context

Students used to bounce between several pages during an exercise — one page to start/submit, another to view results, another for complaints. This was confusing and made it harder, e.g., to compare the current submission with a previous result. The new unified layout keeps students in context throughout the entire participation lifecycle.

The Athena AI feedback integration was previously limited to programming exercises in practice mode. Text and modeling exercises now also support requesting AI feedback during practice, making this feature accessible to a broader set of exercise types.

### Description

**Unified exercise split panel:**
- Introduced a new `ExerciseSplitPanelComponent` that serves as the single entry point for all student exercise participation. It uses a resizable split-panel layout (split.js + PrimeNG Tabs) with panels for the problem statement, editor/submission area, Iris chatbot, and discussion feed.
- Added dedicated participation routes for all exercise types (programming, text, modeling, file upload, quiz) that render inside the split panel via router outlet.
- The old separate "start exercise", "view results", and "submission" pages are now consolidated into this view.

**New exercise header components:**
- `ExerciseHeaderComponent` and `ExerciseHeaderActionsComponent`: extracted and consolidated the exercise title, metadata, and all student action buttons (start, resume, submit, practice, request AI feedback, clone repo, etc.) into a unified header. Instructor actions are grouped in a dropdown.
- `ResultHistoryDropdownComponent`: students can now browse their previous results directly from the header without navigating away.
- `ParticipationModeToggleComponent`: a toggle to switch between graded and practice participation when both exist.
- `ExerciseSubmitButtonComponent`: standalone submit button shared across exercise types.

**AI feedback in practice mode for text and modeling exercises:**
- Server-side: `ParticipationService` and `ParticipationFilterService` updated to support practice participations for text and modeling exercises.
- Client-side: the request feedback button and Athena integration are now wired up for text and modeling exercise practice participations.

**Quiz improvements:**
- Added a new REST endpoint (`GET /quiz-exercises/{exerciseId}/participations/{participationId}/result`) to retrieve a specific quiz submission/result by submission ID, enabling the result history dropdown to work for quiz exercises too.
- The quiz participation component now supports being embedded in the split panel and can render a specific historical submission.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- Exercises of each type: Programming (with LocalVC/LocalCI), Text, Modeling, File Upload, Quiz
- Athena is enabled on the test server for AI feedback

**Unified participation flow:**
1. Log in as a student.
2. Navigate to a course and open any exercise.
3. Verify you land on the new split-panel view — problem statement on the left, editor/submission area on the right.
4. Start the exercise from the header. Confirm no page navigation occurs.
5. Make a submission. Confirm the result appears inline without redirecting.
6. Use the result history dropdown in the header to switch between past results.

**Practice mode + AI feedback (text and modeling):**
1. After the due date, open a text or modeling exercise.
2. Toggle to "Practice" mode using the participation mode toggle.
3. Start a practice participation and submit.
4. Click "Request AI Feedback" and confirm feedback is returned.

**Quiz result history:**
1. Complete a quiz exercise.
2. Open the exercise detail page and verify that past quiz results are browsable in the result history dropdown.

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming, Text, Modeling, File Upload, and Quiz exercise

1. Log in as a student and participate in the exam.
2. Verify that the programming and text exercise editors render correctly inside the exam view.
3. Confirm no regression in exam submission flow.

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

#### Client

| Class/File | Line Coverage | Lines | Expects | Ratio |
|------------|-------------:|------:|--------:|------:|
| discussion-section.component.ts | 88.52% | 286 | 45 | 15.7 |
| course-exercise-row.component.ts | 77.63% | 156 | 1 | 0.6 |
| course-exercise-details.component.ts | 71.53% | 543 | 42 | 7.7 |
| exercise-split-panel.component.ts | 65.46% | 260 | ? | ? |
| request-feedback-button.component.ts | 95.95% | 202 | 49 | 24.3 |
| start-practice-mode-button.component.ts | 90.90% | 76 | 10 | 13.2 |
| exercise-details-student-actions.component.ts | 94.07% | 257 | 40 | 15.6 |
| exercise-header-actions.component.ts | not found (added) | 470 | ? | ? |
| exercise-header.component.ts | not found (added) | 82 | 2 | 2.4 |
| exercise-headers-information.component.ts | not found (modified) | 348 | 27 | 7.8 |
| result-history-dropdown.component.ts | not found (added) | 257 | 39 | 15.2 |
| participation-mode-toggle.component.ts | not found (added) | 21 | ? | ? |
| participation.service.ts | 85.82% | 240 | 17 | 7.1 |
| result.utils.ts | 85.05% | 289 | 6 | 2.1 |
| exercise-submit-button.component.ts | 19.04% | 61 | ? | ? |
| exercise.utils.ts | 61.85% | 167 | 15 | 9.0 |
| file-upload-submission.component.ts | 93.29% | 300 | 47 | 15.7 |
| iris-base-chatbot.component.ts | 82.36% | 519 | 150 | 28.9 |
| modeling-submission.component.ts | 85.12% | 689 | 83 | 12.0 |
| code-editor-build-output.component.ts | 87.09% | 182 | 42 | 23.1 |
| code-editor-container.component.ts | 96.90% | 333 | 66 | 19.8 |
| code-editor-file-browser.component.ts | 94.55% | 537 | 223 | 41.5 |
| code-editor-header.component.ts | 100.00% | 31 | 4 | 12.9 |
| code-editor-student-container.component.ts | 86.36% | 155 | 3 | 1.9 |
| code-editor-actions.component.ts | 94.33% | 291 | 64 | 22.0 |
| code-editor-grid.component.ts | 72.50% | 187 | 14 | 7.5 |
| code-editor-monaco.component.ts | 95.00% | 677 | 112 | 16.5 |
| apollon-diagram-detail.component.ts | 92.85% | 210 | 38 | 18.1 |
| quiz-exercise-generator.ts | 90.65% | 177 | 60 | 33.9 |
| quiz-participation.component.ts | 78.70% | 835 | 73 | 8.7 |
| code-button.component.ts | not found (modified) | 350 | 65 | 18.6 |
| exercise-action-button.component.ts | not found (modified) | 33 | ? | ? |
| resizable-panels.component.ts | 14.75% | 123 | ? | ? |
| resizeable-container.component.ts | 81.25% | 69 | 1 | 1.4 |
| search-filter.component.ts | 100.00% | 25 | 4 | 16.0 |
| text-editor.component.ts | 76.58% | 412 | 38 | 9.2 |

#### Server

| Class/File | Line Coverage | Lines |
|------------|-------------:|------:|
| ParticipationFilterService.java | 97.14% | 76 |
| ParticipationService.java | 66.67% | 510 |
| ParticipationResource.java | 87.68% | 299 |
| IrisTextExerciseChatSessionService.java | 87.88% | 153 |
| ModelingSubmissionService.java | 89.58% | 119 |
| QuizParticipationResource.java | 54.24% | 147 |
| TextSubmissionService.java | 85.71% | 111 |

_Last updated: 2026-04-05 21:24:41 UTC_

### Screenshots

1. The new unified split-panel participation view (problem statement + editor side by side)

2. The new exercise header with action buttons and result history dropdown

3. AI feedback in a text exercise practice participation

4. AI feedback in a modeling exercise practice participation

5. Screencast of Text Exercise Participation with AI Feedback

https://github.com/user-attachments/assets/a39d716d-dfb5-4823-8748-f64eb695b22f

6. Screencast of Modeling Exercise Participation with AI Feedback

https://github.com/user-attachments/assets/50b4f8fb-d257-4200-b437-951ae776f7db

## Summary by CodeRabbit

* **New Features**
  * Resizable split-panel workspace (Editor / Problem / Chat/Iris), result history dropdown, participation-mode toggle, AI-feedback submit popover, and viewing a specific quiz participation result.

* **Improvements**
  * Redesigned exercise header and action controls; unified split-panel across exercise types; broader practice-mode support; refined editor navbar/sidebar behavior and responsive layouts; simplified discussion feed integration.

* **Documentation**
  * Template READMEs: removed top-level headings for cleaner presentation.

### CODE REVIEW

File: src/main/webapp/app/communication/shared/discussion-section/discussion-section.component.ts [hunk 1]
```diff
@@ -1,217 +1,30 @@
-import { AfterViewInit, Component, ElementRef, OnDestroy, effect, inject, input, viewChild, viewChildren } from '@angular/core';
+import { AfterViewInit, Component, input } from '@angular/core';
```
Comment (Claudia-Anthropica) [inline src/main/webapp/app/communication/shared/discussion-section/discussion-section.component.ts]: @DominikRemo [critical] CI is broken — the `client-tests` job fails because `DiscussionSectionComponent` tests still reference properties that were moved to `DiscussionFeedComponent` (`course`, `posts`, `channel`, `currentPost`, `formGroup`, `setChannel`, `fetchNextPage`, etc.). The `CourseExerciseDetailsComponent` spec references `hasMoreResults` (renamed to `showMoreResults`), and `TextEditorComponent` spec references `loadIrisSettings`/`irisSettings` which no longer exist. These test files need to be updated to match the refactoring.

<details><summary>🤖 Prompt for AI agents</summary>

The refactoring in `discussion-section.component.ts` moved most logic to `discussion-feed.component.ts`, but the test file `discussion-section.component.spec.ts` still references old properties (`course`, `posts`, `channel`, `currentPost`, `formGroup`, `setChannel`, `fetchNextPage`, `content`, `messages`, etc.). Update the spec to test the slimmed-down `DiscussionSectionComponent` and create a new spec for `DiscussionFeedComponent`. Also fix `course-exercise-details.component.spec.ts` (rename `hasMoreResults` to `showMoreResults`), `text-editor.component.spec.ts` (remove `loadIrisSettings`/`irisSettings` references), and any other spec files that reference `DiscussionSectionComponent` members like `content` or `messages` (e.g., `learning-path-lecture-unit.component.spec.ts`, `course-lecture-details.component.spec.ts`).

</details>

File: src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.html [hunk 2]
```diff
@@ -1,5 +1,26 @@
...
+
+        <jhi-exercise-split-panel
+            class="d-flex flex-fill"
+            [exercise]="exercise"
+            [studentParticipation]="activeParticipation()"
+            [irisEnabled]="irisEnabled() && irisChatEnabled()"
+        />
+    </div>
+
+    <div id="course-exercise-details" class="px-3 pt-2 pb-3 scrollable-content module-bg">
```
Comment (Claudia-Anthropica) [inline src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.html]: @DominikRemo [high] Both the new layout (lines 2–21: `jhi-exercise-header` + `jhi-exercise-split-panel`) and this old `#course-exercise-details` div render simultaneously — there's no condition toggling between them. This means users see duplicate headers, problem statements, and discussion sections stacked on top of each other. You probably want to conditionally render one or the other, or remove the old layout entirely if the split panel is the replacement.

<details><summary>🤖 Prompt for AI agents</summary>

In `src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.html`, both the new split-panel layout (lines 2-21) and the old `#course-exercise-details` div (line 23 onwards) render unconditionally inside `@if (exercise)`. Add a condition to show only one — e.g., show the split panel when a child route is active (participation mode), and the old detail view otherwise. Or remove the old view if the split panel fully replaces it.

</details>

File: src/main/webapp/app/exercise/exercise-headers/exercise-headers-information/result-history-dropdown/result-history-dropdown.component.html [hunk 3]
```diff
@@ -0,0 +1,42 @@
+@if (sortedHistoryResults().length > 0) {
+    <span #dropdownArrow>
+        <fa-icon [icon]="faAngleDown" class="ms-1 fw-bold" style="font-size: 0.875rem" />
+    </span>
+}
+<p-popover #resultsPopover [pt]="{ root: { style: 'margin-left: -8px' }, content: { style: 'padding: 0' } }">
+    <div class="d-flex align-items-center justify-content-between px-3 bg-light border-bottom" style="height: 40px">
+        <div class="d-flex align-items-center gap-2">
+            <fa-icon [icon]="faClock" class="text-body-tertiary" style="font-size: 14px" />
+            <span class="fw-medium text-body-secondary" style="font-size: 13px">Result History</span>
```
Comment (Claudia-Anthropica) [inline src/main/webapp/app/exercise/exercise-headers/exercise-headers-information/result-history-dropdown/result-history-dropdown.component.html]: @DominikRemo [medium] Multiple hardcoded English strings here: "Result History" (line 10), "results" (line 12), "Feedback" (line 37). The TS file also has hardcoded English in `getResultFeedbackMessage()` — "Goal reached! Excellent work.", "Nice progress!", "Your build failed!", etc. Artemis requires all user-facing text to use translation keys (`jhiTranslate` / `artemisTranslate`). Add i18n keys for all of these and provide both English and German translations.

<details><summary>🤖 Prompt for AI agents</summary>

In `result-history-dropdown.component.html`, replace hardcoded English strings with translation directives: "Result History" (line 10), the "results" count text (line 12), and the "Feedback" button label (line 37). In `result-history-dropdown.component.ts`, replace all hardcoded strings in `getResultFeedbackMessage()` with calls to the translate service or pipe. Add corresponding keys to the English and German i18n JSON files.

</details>

File: src/main/webapp/app/exercise/exercise-headers/participation-mode-toggle/participation-mode-toggle.component.html [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+            <span jhiTranslate="artemisApp.exerciseActions.practice"></span>
+        </button>
+        <button
+            class="segmented-control__button"
+            [class.segmented-control__button--active]="mode() === 'graded'"
+            [class.segmented-control__button--graded]="mode() === 'graded'"
+            (click)="selectMode('graded')"
+        >
+            <fa-icon [icon]="faGraduationCap" />
+            <span>Graded</span>
```
Comment (Claudia-Anthropica) [inline src/main/webapp/app/exercise/exercise-headers/participation-mode-toggle/participation-mode-toggle.component.html]: @DominikRemo [medium] "Graded" is hardcoded English. The "Practice" button correctly uses `jhiTranslate="artemisApp.exerciseActions.practice"` but the "Graded" button doesn't. Add a translation key and use `jhiTranslate` here too.

<details><summary>🤖 Prompt for AI agents</summary>

In `participation-mode-toggle.component.html` line 19, replace the hardcoded `<span>Graded</span>` with `<span jhiTranslate="artemisApp.exerciseActions.graded"></span>`. Add the translation key `artemisApp.exerciseActions.graded` to both the English and German i18n JSON files.

</details>

File: src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.ts [hunk 5]
```diff
@@ -0,0 +1,420 @@
...
+import { RequestFeedbackButtonComponent } from 'app/core/course/overview/exercise-details/request-feedback-button/request-feedback-button.component';
+import { CourseExerciseService } from 'app/exercise/course-exercises/course-exercise.service';
+import { StartPracticeModeButtonComponent } from 'app/core/course/overview/exercise-details/start-practice-mode-button/start-practice-mode-button.component';
+import { OpenCodeEditorButtonComponent } from 'app/core/course/overview/exercise-details/open-code-editor-button/open-code-editor-button.component';
+import { ProfileService } from 'app/core/layouts/profiles/shared/profile.service';
+import { ArtemisQuizService } from 'app/quiz/shared/service/quiz.service';
+import { HttpErrorResponse } from '@angular/common/http';
+import { getAllResultsOfAllSubmissions } from 'app/exercise/shared/entities/submission/submission.model';
+
+interface InstructorActionItem {
```
Comment (Claudia-Anthropica) [inline src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.ts:56]: @DominikRemo [medium] The `InstructorActionItem` interface and all the instructor action methods (`createTutorActions`, `createEditorActions`, `getDefaultItems`, `getQuizItems`, `getParticipationItem`, `getStatisticItem`, `getGradingItem`, `getQuizEditItem`, `getReEvaluateItem`) are duplicated verbatim between this new component and `CourseExerciseDetailsComponent`. Extract these into a shared utility or have one component delegate to the other to avoid maintaining the same logic in two places.

<details><summary>🤖 Prompt for AI agents</summary>

The `InstructorActionItem` interface and ~9 instructor action builder methods are duplicated between `exercise-header-actions.component.ts` and `course-exercise-details.component.ts`. Extract the `InstructorActionItem` interface and the methods (`createTutorActions`, `createEditorActions`, `getDefaultItems`, `getQuizItems`, `getParticipationItem`, `getStatisticItem`, `getGradingItem`, `getQuizEditItem`, `getReEvaluateItem`) into a shared utility function or service, then import and use it in both components.

</details>

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo The split-panel approach and the new participation UX direction look promising, but there are a few things blocking this. CI is broken — the DiscussionSectionComponent refactoring removed properties that tests still reference. Both the new split-panel layout and the old exercise details view render simultaneously (no toggle/condition between them). And there are several hardcoded English strings that need i18n. See inline comments.

**Comment by DominikRemo** [comment]
@coderabbitai full review

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo The new commit switching resizable-panels to PrimeNG Tabs looks good — nice alignment with project conventions. However, none of the issues from my previous review have been addressed yet: CI is still broken (client-tests, server-tests, E2E all failing), both old and new layouts still render simultaneously, and the hardcoded English strings are still there. Please address those before this can move forward.

File: src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.html (hunk 2 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.html]: @DominikRemo Nice, the old div is gone now — no more duplicate rendering. Looks good.

File: src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.ts [hunk 6]
```diff
@@ -0,0 +1,216 @@
...
+        ResetRepoButtonComponent,
+        ComplaintsStudentViewComponent,
+        RatingComponent,
+        ModelingEditorComponent,
+        ProgrammingExerciseExampleSolutionRepoDownloadComponent,
+        CompetencyContributionComponent,
+        LtiInitializerComponent,
+        FaIconComponent,
+        NgbTooltip,
+        TranslateDirective,
```
Comment (Claudia-Anthropica) [inline src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.ts]: @DominikRemo [low] `TranslateDirective` is listed twice in the imports array (lines 50 and 60). Remove the duplicate.

<details><summary>🤖 Prompt for AI agents</summary>

In `src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.ts`, `TranslateDirective` appears twice in the `imports` array (lines 50 and 60). Remove the duplicate entry on line 60.

</details>

File: src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.html [hunk 7]
```diff
@@ -0,0 +1,112 @@
...
+        <ng-template jhiPanel label="Quiz" [icon]="getIcon(exercise().type)">
+            <div class="d-flex align-items-center justify-content-center h-100 text-body-secondary">
+                <span jhiTranslate="artemisApp.courseOverview.exerciseList.quizNotOpened"></span>
+            </div>
+        </ng-template>
+    }
+
+    <ng-template
+        jhiPanel
+        [label]="exercise().type === ExerciseType.QUIZ ? 'Quiz info' : 'Problem statement'"
```
Comment (Claudia-Anthropica) [inline src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.html]: @DominikRemo [medium] Same i18n issue as the other components — the panel tab labels are hardcoded English: `"Editor"` (line 3), `"Quiz"` (line 12), `"Quiz info"` / `"Problem statement"` (line 21), `"Chat"` (line 107). These are user-visible strings that need translation keys via `jhiTranslate` or the `artemisTranslate` pipe. ("Iris" on line 101 is fine as a proper noun.)

<details><summary>🤖 Prompt for AI agents</summary>

In `src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.html`, the `jhiPanel` `label` attributes on lines 3, 12, 21, and 107 use hardcoded English strings ("Editor", "Quiz", "Quiz info", "Problem statement", "Chat"). Replace each with a translated string using the `artemisTranslate` pipe or `jhiTranslate` directive. Add the corresponding translation keys to `en/student-dashboard.json` and `de/student-dashboard.json`.

</details>

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo Good progress — the duplicate rendering issue is resolved now. But CI is still broken (client-tests fail at TypeScript compilation), the i18n issues from my last review are still open (hardcoded English in result-history-dropdown and participation-mode-toggle), and the InstructorActionItem duplication remains. I also spotted a couple of new things in the latest commits — see inline.

File: src/main/webapp/app/communication/shared/discussion-section/discussion-section.component.ts (hunk 1 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/communication/shared/discussion-section/discussion-section.component.ts]: @DominikRemo Still seeing client-tests and server-tests failing in CI. The test files still reference the old component properties.

File: src/main/webapp/app/exercise/exercise-headers/exercise-headers-information/result-history-dropdown/result-history-dropdown.component.html (hunk 3 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/exercise/exercise-headers/exercise-headers-information/result-history-dropdown/result-history-dropdown.component.html]: @DominikRemo Still hardcoded — "Result History" (line 10), "results" (line 12), "Feedback" (line 37), and all the feedback messages in the TS file.

File: src/main/webapp/app/exercise/exercise-headers/participation-mode-toggle/participation-mode-toggle.component.html (hunk 4 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/exercise/exercise-headers/participation-mode-toggle/participation-mode-toggle.component.html]: @DominikRemo Still hardcoded on line 19.

File: src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.ts (hunk 5 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.ts:56]: @DominikRemo Still duplicated between both components.

File: src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.ts (hunk 6 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.ts]: @DominikRemo Still listed twice (lines 50 and 60).

File: src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.html (hunk 7 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.html]: @DominikRemo Labels still hardcoded — "Editor", "Quiz info"/"Problem statement", "Chat".

File: src/main/java/de/tum/cit/aet/artemis/quiz/web/QuizParticipationResource.java [hunk 8]
```diff
@@ -128,4 +140,58 @@ else if (quizBatch.isPresent() && quizBatch.get().isStarted()) {
...
+        participationAuthCheckService.checkCanAccessParticipationElseThrow(participation);
+
+        if (!exercise.getId().equals(participation.getExercise().getId())) {
+            throw new BadRequestAlertException("The participation does not belong to the specified exercise", "participation", "exerciseMismatch");
+        }
+
+        QuizSubmission submission;
+        Result result;
+        if (submissionId != null) {
+            submission = quizSubmissionRepository.findWithEagerResultAndFeedbackById(submissionId)
```
Comment (Claudia-Anthropica) [inline src/main/java/de/tum/cit/aet/artemis/quiz/web/QuizParticipationResource.java:174]: @DominikRemo [high] `findWithEagerResultAndFeedbackById` loads results and feedback but does NOT fetch `submittedAnswers`. The else branch correctly uses `findWithEagerSubmittedAnswersByResultId` which does. When a student views a specific past quiz submission via the result history dropdown, they'll see an empty quiz with no answers filled in. Use a query that also fetches `submittedAnswers`, or chain a second fetch.

<details><summary>🤖 Prompt for AI agents</summary>

In `src/main/java/.../quiz/web/QuizParticipationResource.java` line 169, `findWithEagerResultAndFeedbackById` does not load `submittedAnswers`. Replace it with a repository method that also fetches `submittedAnswers` (like `findWithEagerSubmittedAnswersByResultId` does in the else branch), or add a `LEFT JOIN FETCH submission.submittedAnswers` to the existing query.

</details>

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo The new commits add practice mode for text/modeling and quiz submission viewing — nice progress on the feature. However, none of the previously flagged issues have been addressed yet: CI is still broken, all user-facing strings are still hardcoded English without i18n, and the InstructorActionItem code is still duplicated. I also spotted a new bug in the quiz endpoint — see inline. Please address the existing feedback before adding more features.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo The button rework and SCA info box are nice additions. However, none of the issues from my previous reviews have been addressed yet — CI is still broken (client-tests failing), i18n strings are still hardcoded in multiple components, the QuizParticipationResource still loads the wrong data for the submissionId branch, and the duplicate TranslateDirective import is still there. Please address those before adding more features.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo None of the previously requested changes have been addressed yet. CI is still broken (client-tests and server-tests failing), the hardcoded English strings (result-history-dropdown, participation-mode-toggle, split-panel tab labels) still need i18n, the `TranslateDirective` duplicate import is still there, and the quiz endpoint still uses `findWithEagerResultAndFeedbackById` which doesn't load `submittedAnswers`. Please take a look at the existing inline comments.

File: src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.html (hunk 7 above)
Comment (DominikRemo) [reply src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.html]: Fixed

Comment (Claudia-Anthropica) [reply src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.html]: @DominikRemo Verified — all panel labels now use translation keys and the i18n entries are in place. Nice work.

File: src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.ts (hunk 6 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.ts]: @DominikRemo Duplicate import is gone now, looks good.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo The panel label i18n and the duplicate import are fixed — nice. But CI is still broken (client-tests fail at TypeScript compilation due to spec files referencing old DiscussionSectionComponent properties), the result-history-dropdown and participation-mode-toggle still have hardcoded English strings, the InstructorActionItem duplication is still there, and the quiz endpoint still uses findWithEagerResultAndFeedbackById which doesn't load submittedAnswers. See the open threads for details.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo The new commits fixed the duplicate rendering and the split-panel tab labels (nice work on those), but the other issues from my previous review are still open: CI is still failing (client-tests-selected), hardcoded English strings in result-history-dropdown and participation-mode-toggle, the InstructorActionItem duplication, and the missing submittedAnswers fetch in QuizParticipationResource. See the existing inline threads for details.

File: src/main/webapp/i18n/en/exercise-actions.json [hunk 9]
```diff
@@ -13,7 +13,6 @@
             "requestManualFeedback": "Request feedback",
             "requestManualFeedbackTooltip": "Send a manual feedback request before the due date for review.",
             "requestAutomaticFeedback": "Request AI feedback",
```
Comment (Claudia-Anthropica) [inline src/main/webapp/i18n/en/exercise-actions.json:16]: @DominikRemo [medium] The `requestAutomaticFeedbackTooltip` key was deleted from the English file but still exists in `de/exercise-actions.json` line 16. This is what's causing the "Check if translation keys are consistent" CI failure. Either remove the German key too, or restore the English one if you still need it.

<details><summary>🤖 Prompt for AI agents</summary>

In `src/main/webapp/i18n/en/exercise-actions.json`, the key `requestAutomaticFeedbackTooltip` was removed but it still exists in `src/main/webapp/i18n/de/exercise-actions.json` at line 16. Remove the `requestAutomaticFeedbackTooltip` entry from the German file as well to fix the translation key consistency CI check.

</details>

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo Third pass — the panel label i18n and duplicate import are fixed (nice), but the other 5 threads from my previous reviews are still open. CI is still broken: `client-tests-selected` fails on TypeScript compilation because test files reference old `DiscussionSectionComponent` properties, and the translation consistency check fails because `requestAutomaticFeedbackTooltip` was removed from English but left in German. See the existing threads plus the new inline comment.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo None of the 6 open threads from my previous reviews have been addressed yet — CI tests still broken (client-tests reference old DiscussionSectionComponent properties), the i18n key mismatch still causes the translation consistency check to fail, hardcoded English strings in result-history-dropdown and participation-mode-toggle are still there, InstructorActionItem is still duplicated, and the QuizParticipationResource submittedAnswers issue remains. Please take a look at the existing inline threads.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo The new commits (docs fix, merge, panel border removal) don't address the issues from my previous review. CI is still broken — client-tests and translation-consistency checks both fail. The hardcoded English strings, the missing `submittedAnswers` fetch in `QuizParticipationResource`, and the duplicated `InstructorActionItem` code are all still present. Please take a look at the open threads.

File: src/main/webapp/content/scss/global.scss [hunk 10]
```diff
@@ -1456,6 +1468,10 @@ Note: This class assumes that the scrollbar is already present (e.g. overflow-y
     white-space: pre-line;
 }
 
+// Override Bootstrap's default popover max-width for AI feedback popover.
+.ai-feedback-popover {
+    max-width: 500px;
```
Comment (Claudia-Anthropica) [inline src/main/webapp/content/scss/global.scss:1475]: @DominikRemo [critical] `.ai-feedback-popover` is missing its closing `}`. This creates an unclosed CSS block that breaks the Prettier check in CI. The next rule (`.iris-split-left .result-metadata`) ends up nested inside it, which also changes its specificity.

```suggestion
    max-width: 500px;
}
```

<details><summary>🤖 Prompt for AI agents</summary>

In `src/main/webapp/content/scss/global.scss`, the `.ai-feedback-popover` block opened around line 1472 is missing its closing brace after `max-width: 500px;`. Add a closing `}` after line 1473 so the block is properly closed before the `.iris-split-left .result-metadata` rule.

</details>

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo The new result history dropdown improvements look like a nice step forward. However, the previously flagged issues (broken client tests, hardcoded English strings, missing submittedAnswers fetch, orphaned translation key) are still unresolved. There's also a new CSS syntax error in `global.scss` that's breaking the Prettier check — see inline comment.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo The revert commit landed but none of the open feedback threads have been addressed yet. The two critical items (unclosed CSS brace in global.scss breaking Prettier, and client-tests still failing) plus the high-priority missing submittedAnswers fetch in QuizParticipationResource, the hardcoded English strings, the translation key inconsistency, and the duplicated instructor actions code are all still outstanding. See the existing inline threads for details.

File: src/main/webapp/app/communication/shared/discussion-section/discussion-section.component.ts (hunk 1 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/communication/shared/discussion-section/discussion-section.component.ts]: @DominikRemo The DiscussionFeedComponent refactoring was reverted and DiscussionSectionComponent has all its properties back, so this is no longer an issue. Resolving.

File: src/main/webapp/content/scss/global.scss (hunk 10 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/content/scss/global.scss:1475]: @DominikRemo Nice, the closing brace is there now. Prettier should be happy.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo The CSS brace fix and the DiscussionSectionComponent revert resolve two threads — nice. Five threads are still open though: hardcoded English strings in result-history-dropdown and participation-mode-toggle, the duplicated InstructorActionItem logic between exercise-header-actions and course-exercise-details, the missing submittedAnswers fetch in QuizParticipationResource, and the translation key mismatch (requestAutomaticFeedbackTooltip removed from English but still in German — this is what's failing the translation-consistency CI check).

File: src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.html [hunk 11]
```diff
@@ -1,206 +1,34 @@
...
+            class="p-2 rounded-3 module-bg mb-2"
+            [exercise]="exercise"
+            [courseId]="courseId"
+            [studentParticipation]="gradedStudentParticipation()"
+            [practiceParticipation]="practiceStudentParticipation()"
+            [submissionPolicy]="submissionPolicy()"
+            [onSubmitExercise]="splitPanel()?.canSubmit() ? submitExercise : undefined"
+            [plagiarismCaseInfo]="plagiarismCaseInfo()"
+            [participationMode]="participationMode()"
+            [athenaEnabled]="true"
```
Comment (Claudia-Anthropica) [inline src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.html]: @DominikRemo [medium] `[athenaEnabled]="true"` hardcodes the flag to always on. This means the AI feedback counter will show in the info section even on servers where Athena isn't enabled. `ExerciseHeaderActionsComponent` already does it right with `this.profileService.isProfileActive(PROFILE_ATHENA)` — inject `ProfileService` here and pass the actual value.

<details><summary>🤖 Prompt for AI agents</summary>

In `src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.html`, line 13 hardcodes `[athenaEnabled]="true"`. Instead, inject `ProfileService` into `CourseExerciseDetailsComponent` and pass `profileService.isProfileActive(PROFILE_ATHENA)` as the value.

</details>

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo The new commits restore proper guards in the feedback button and add the AI feedback counter to the info section — nice cleanup. But all 5 open threads from my previous reviews are still unaddressed: hardcoded English strings in result-history-dropdown and participation-mode-toggle, the InstructorActionItem duplication, the missing submittedAnswers fetch in QuizParticipationResource, and the translation key mismatch in exercise-actions.json (still failing CI). Also spotted a new issue with athenaEnabled hardcoded to true — see inline.

File: src/main/java/de/tum/cit/aet/artemis/quiz/web/QuizParticipationResource.java (hunk 8 above)
Comment (DominikRemo) [reply src/main/java/de/tum/cit/aet/artemis/quiz/web/QuizParticipationResource.java:174]: findWithEagerResultAndFeedbackById already fetches and joins the submitted answers

File: src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.ts (hunk 5 above)
Comment (DominikRemo) [reply src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.ts:56]: Removed duplication

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo The new commit wiring `newParticipation` through to the websocket service is a good fix. But the 4 open threads from previous reviews are still unaddressed: hardcoded English strings in result-history-dropdown and participation-mode-toggle, the `requestAutomaticFeedbackTooltip` key mismatch between en/de (which is failing the translation consistency CI check), and `[athenaEnabled]="true"` still hardcoded. CI is still red — client-tests and translation-consistency both fail.

File: src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.ts (hunk 5 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.ts:56]: @DominikRemo Looks good, duplication is gone.

File: src/main/java/de/tum/cit/aet/artemis/quiz/web/QuizParticipationResource.java (hunk 8 above)
Comment (Claudia-Anthropica) [reply src/main/java/de/tum/cit/aet/artemis/quiz/web/QuizParticipationResource.java:174]: @DominikRemo Fair enough — I was looking at the JPQL which only shows `results`, `feedbacks`, and `assessor` in the JOIN FETCH clauses but if it works at runtime, all good.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo Nice progress on the test fixes — compilation issues are cleaned up. Four things are still open from earlier: the hardcoded English strings in `result-history-dropdown` ("Result History", "results", "Feedback", and the feedback messages in the TS), the "Graded" button in `participation-mode-toggle` missing its i18n key, the `requestAutomaticFeedbackTooltip` key deleted from en but still in de (this is what's failing the translation consistency CI check), and `[athenaEnabled]="true"` hardcoded in the template instead of being derived from the profile service.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo Good progress — 7 of 11 threads are resolved and the big issues (CI-breaking refactoring, duplicate rendering, CSS syntax error, code duplication) are all fixed. Four things still need attention: the hardcoded English strings in result-history-dropdown and participation-mode-toggle, the missing `requestAutomaticFeedbackTooltip` key in the English translation file (which is why the translation consistency CI check keeps failing), and the hardcoded `[athenaEnabled]="true"` in course-exercise-details. CI is also still red on client-tests, server-tests, server-style, and bean-instantiation-check — worth investigating those.

File: src/main/webapp/app/exercise/exercise-headers/exercise-headers-information/result-history-dropdown/result-history-dropdown.component.html (hunk 3 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/exercise/exercise-headers/exercise-headers-information/result-history-dropdown/result-history-dropdown.component.html]: @DominikRemo Still seeing hardcoded English here — "Result History" (line 10), "results" (line 12), "Feedback" (line 36), plus the motivational strings in `getResultFeedbackMessage()`. These all need i18n keys.

File: src/main/webapp/app/exercise/exercise-headers/participation-mode-toggle/participation-mode-toggle.component.html (hunk 4 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/exercise/exercise-headers/participation-mode-toggle/participation-mode-toggle.component.html]: @DominikRemo Still not addressed — line 19 has hardcoded "Graded". Needs a translation key like the "Practice" button above it.

File: src/main/webapp/i18n/en/exercise-actions.json (hunk 9 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/i18n/en/exercise-actions.json:16]: @DominikRemo This is still causing the "Check if translation keys are consistent" CI failure. `requestAutomaticFeedbackTooltip` was removed from the English file but line 16 in `de/exercise-actions.json` still has it.

File: src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.html (hunk 11 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.html]: @DominikRemo Still hardcoded — line 13 has `[athenaEnabled]="true"`. This should be wired to the actual Athena profile status from the course/server config so it doesn't show the AI feedback counter on servers without Athena.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo Nice work on resolving the CI breakage and the duplicate layout issue — those were the critical blockers and they're fixed. Four items from my previous review are still open though: hardcoded English strings in the result history dropdown and participation toggle, the translation key mismatch causing the CI "translation keys consistent" check to fail, and `athenaEnabled` still hardcoded to `true`. See the thread replies for details.

File: src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.html (hunk 11 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.html]: @DominikRemo Fixed — `athenaEnabled` is now wired to the profile service. Nice.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo Good progress — the `athenaEnabled` hardcoding is fixed and the submit/continue flow refactoring looks solid. Three things still need attention though: hardcoded English strings in result-history-dropdown ("Result History", "results", "Feedback"), the "Graded" label in participation-mode-toggle still missing i18n, and the `requestAutomaticFeedbackTooltip` key inconsistency between EN/DE that's breaking the translation consistency CI check. See the existing inline threads for details.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo Thanks for fixing the tests and several of the earlier issues. Three things from my previous review are still open though: the hardcoded English strings in result-history-dropdown ("Result History", "results", "Feedback", and the motivational messages in `getResultFeedbackMessage()`), the hardcoded "Graded" in participation-mode-toggle, and the missing `requestAutomaticFeedbackTooltip` key in `en/exercise-actions.json` which is still causing the "Check if translation keys are consistent" CI failure.

File: src/main/webapp/i18n/en/exercise-actions.json (hunk 9 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/i18n/en/exercise-actions.json:16]: @DominikRemo Nice, German key removed — translation consistency check passes now.

**Review by Claudia-Anthropica — CHANGES_REQUESTED** [review]
@DominikRemo Thanks for fixing the translation key mismatch — resolved that thread. Two things still need attention: the hardcoded English strings in result-history-dropdown ("Result History", "results", "Feedback") and the hardcoded "Graded" in participation-mode-toggle. See the open threads for details.

File: src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.ts [hunk 12]
```diff
@@ -0,0 +1,420 @@
...
+
+    readonly exercise = input.required<Exercise>();
+    readonly courseId = input.required<number>();
+    readonly smallButtons = input<boolean>(false);
+    readonly examMode = input<boolean>(false);
+    readonly isGeneratingFeedback = input<boolean>(false);
+    readonly onSubmitExercise = input<() => void>();
+
+    readonly generatingFeedback = output<void>();
+
```
[the remark this answers is not in the document]
Comment (DominikRemo) [reply src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.ts:130]: done

File: src/main/webapp/app/fileupload/overview/file-upload-submission/file-upload-submission.component.html [hunk 13]
```diff
@@ -1,4 +1,4 @@
-@if (displayHeader() && fileUploadExercise() && participation()) {
+@if (displayHeader() && examMode() && fileUploadExercise() && participation()) {
```
[the remark this answers is not in the document]
Comment (DominikRemo) [reply src/main/webapp/app/fileupload/overview/file-upload-submission/file-upload-submission.component.html:1]: We added a submit button in the wrapping parent component (exercise details > header). This way, all action buttons for all editor types are always in the same place and consistent.

File: src/main/webapp/app/exercise/exercise-headers/exercise-headers-information/result-history-dropdown/result-history-dropdown.component.html (hunk 3 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/exercise/exercise-headers/exercise-headers-information/result-history-dropdown/result-history-dropdown.component.html]: @DominikRemo All the hardcoded strings are translated now — title, results count, feedback button, and all the motivational messages in getResultFeedbackMessage(). Both EN and DE keys are in place. Nice work.

File: src/main/webapp/app/exercise/exercise-headers/participation-mode-toggle/participation-mode-toggle.component.html (hunk 4 above)
Comment (Claudia-Anthropica) [reply src/main/webapp/app/exercise/exercise-headers/participation-mode-toggle/participation-mode-toggle.component.html]: @DominikRemo Fixed — both "Practice" and "Graded" buttons use translation keys now, with both EN and DE entries in place.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All feedback addressed — i18n strings, CSS brace, duplicate imports, duplication removal, athena flag wiring. Nice work getting everything translated with both EN and DE keys.

**Comment by DominikRemo** [comment]
@coderabbitai full review

File: src/main/webapp/app/modeling/overview/modeling-submission/modeling-submission.component.html [hunk 14]
```diff
@@ -1,5 +1,5 @@
 <div [id]="'exercise-' + modelingExercise?.id">
-    @if (displayHeader()) {
+    @if (displayHeader() && examMode) {
```
[the remark this answers is not in the document]
Comment (DominikRemo) [reply src/main/webapp/app/modeling/overview/modeling-submission/modeling-submission.component.html:2]: This is intended behavior. We did not want to change how exam exercises work, but we moved the information and buttons from individual exercises into a shared exercise header for course exercises (non-exam mode).

File: src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationService.java [hunk 15]
```diff
@@ -643,7 +643,15 @@ public Optional<StudentParticipation> findOneByExerciseAndStudentLoginWithEagerS
...
+        // After the due date, prefer the practice participation for submission context (student is in practice mode)
+        if (exercise.getDueDate() != null && ZonedDateTime.now().isAfter(exercise.getDueDate())) {
+            Optional<StudentParticipation> practiceParticipation = studentParticipationRepository.findWithEagerSubmissionsByExerciseIdAndStudentLoginAndTestRun(exercise.getId(),
+                    username, true);
+            if (practiceParticipation.isPresent()) {
+                return practiceParticipation;
+            }
+        }
+        return studentParticipationRepository.findWithEagerSubmissionsByExerciseIdAndStudentLoginAndTestRun(exercise.getId(), username, false);
     }
```
[the remark this answers is not in the document]
Comment (DominikRemo) [reply src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationService.java]: That is correct. Please note that we do not yet support the practice mode for file upload exercises.

File: src/test/playwright/fixtures/exercise/programming/python/template.json [hunk 16]
```diff
@@ -18,7 +18,7 @@
...
...\n  <color:testsColor(test_policy_methods)>+configure()</color>\n}\n\nclass Context {\n  <color:testsColor(test_context_attributes)>numbers: List<int></color>\n  <color:testsColor(test_context_methods)>+sort()</color>\n}\n\nabstract class SortStrategy {\n  <color:testsColor(test_sort_strategy_methods)>+perform_sort(List<int>)</color>\n}\n\nclass BubbleSort {\n  <color:testsColor(test_bubble_sort_struct)>+performSort(List<int>)</color>\n}\n\nclass MergeSort {\n  <color:testsColor(test_merge_sort_struct)>+perform_sort(List<int>)</color>\n}\n\nMergeSort -up-|> SortStrategy #testsColor(test_merge_sort_class)\nBubbleSort -up-|> SortStrategy #testsColor(test_bubble_sort_class)\nPolicy -right-> Context #testsColor(test_policy_attributes): context\nContext -right-> SortStrategy #testsColor(test_context_attributes): sortAlgorithm\nClient .down.> Policy\nClient .down.> Context\n\nhide empty fields\nhide empty methods\n\n@enduml\n\n\n### Part 3: Optional Challenges\n\n(These are not tested)\n\n1. Create a new class `QuickSort` that inherits from `SortStrategy` and implement the Quick Sort algorithm.\n\n2. Think about a useful decision in `Policy` when to use the new `QuickSort` algorithm.\n",
```
[the remark this answers is not in the document]
Comment (DominikRemo) [reply src/test/playwright/fixtures/exercise/programming/python/template.json]: I'll also fix it in the actual exercise template then 👍

File: src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.ts [hunk 17]
```diff
@@ -0,0 +1,481 @@
...
+    faPaperPlane,
+    faPlayCircle,
+    faRedo,
+    faRobot,
+    faSignal,
+    faTable,
+    faUsers,
+    faWrench,
+} from '@fortawesome/free-solid-svg-icons';
+import { NgbDropdown, NgbDropdownItem, NgbDropdownMenu, NgbDropdownToggle, NgbPopover, NgbTooltip } from '@ng-bootstrap/ng-bootstrap';
```
[the remark this answers is not in the document]
Comment (DominikRemo) [reply src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.ts:19]: The PR is already quite large. We are reusing components that already existed. For simplicity, we stick with the original code we copied.

File: src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.ts [hunk 18]
```diff
@@ -0,0 +1,240 @@
...
+import { TranslateDirective } from 'app/shared/language/translate.directive';
+import { ResetRepoButtonComponent } from 'app/core/course/overview/exercise-details/reset-repo-button/reset-repo-button.component';
+import { ComplaintsStudentViewComponent } from 'app/assessment/overview/complaints-for-students/complaints-student-view.component';
+import { RatingComponent } from 'app/exercise/rating/rating.component';
+import { ModelingEditorComponent } from 'app/modeling/shared/modeling-editor/modeling-editor.component';
+import { ProgrammingExerciseExampleSolutionRepoDownloadComponent } from 'app/programming/shared/actions/example-solution-repo-download/programming-exercise-example-solution-repo-download.component';
+import { CompetencyContributionComponent } from 'app/atlas/shared/competency-contribution/competency-contribution.component';
+import { LtiInitializerComponent } from 'app/core/course/overview/exercise-details/lti-initializer/lti-initializer.component';
+import { FaIconComponent } from '@fortawesome/angular-fontawesome';
+import { NgbTooltip } from '@ng-bootstrap/ng-bootstrap';
```
[the remark this answers is not in the document]
Comment (DominikRemo) [reply src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.ts:29]: For consistency with the code tooltip, we use the bootstrap tooltip here. The pull request is already quite large. Migration to primeng components can be done in another PR.

File: src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.html [hunk 19]
```diff
@@ -0,0 +1,99 @@
...
+            <jhi-problem-statement [exerciseInput]="exercise()" [participationInput]="studentParticipation()" />
+            @if (exercise().type === ExerciseType.PROGRAMMING && exercise().studentParticipations && exercise().studentParticipations!.length) {
+                <jhi-reset-repo-button [exercise]="exercise()" [participations]="exercise().studentParticipations!" [smallButtons]="false" />
+            }
+            @if (exampleSolutionInfo()?.exampleSolutionPublished) {
+                <div class="row mb-2 mt-2 align-items-baseline">
+                    <div class="control-label" (click)="onChangeExampleSolution()?.()">
+                        <span class="h3 pe-2" jhiTranslate="artemisApp.exercise.exampleSolution"></span>
+                        <fa-icon class="pe-3" [icon]="exampleSolutionCollapsed() ? faAngleDown : faAngleUp" />
+                    </div>
```
[the remark this answers is not in the document]
Comment (DominikRemo) [reply src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.html]: Using primeng panel instead. A panel can be toggleable and we don't have to manage the collapsed state manually anymore.

File: src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.html [hunk 20]
```diff
@@ -0,0 +1,272 @@
...
+    }
+    @if (exercise().isAtLeastTutor) {
+        <div ngbDropdown class="d-inline">
+            <button id="instructor-actions-dropdown" class="btn btn-secondary" ngbDropdownToggle>
+                <fa-icon [icon]="faWrench" />
+                <span class="d-none d-md-inline">
+                    {{ 'artemisApp.courseOverview.exerciseDetails.instructorActions.title' + (exercise().isAtLeastInstructor ? '' : 'Tutor') | artemisTranslate }}</span
+                >
+            </button>
+            <div ngbDropdownMenu aria-labelledby="instructor-actions-dropdown">
```
[the remark this answers is not in the document]
Comment (DominikRemo) [reply src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.html:19]: These action buttons where partly moved from the previous exercise details header. To make buttons appear consistent to students and to prevent the pr from getting even bigger, this PR does not migrate bootstrap components (that already existed before, only in other places) to primeng components.

[the remark this answers is not in the document]
Comment (DominikRemo) [reply src/main/webapp/app/exercise/exercise-headers/exercise-header-actions/exercise-header-actions.component.html:19]: No thank you. There will likely be a bigger migration from bootstrap to primeng anyway.

File: src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.ts (hunk 18 above)
[the remark this answers is not in the document]
Comment (DominikRemo) [reply src/main/webapp/app/core/course/overview/exercise-details/exercise-split-panel/exercise-split-panel.component.ts:29]: No thanks. There'll likely be a bigger migration in the future anyway.

**Comment by DominikRemo** [comment]
@coderabbitai full review

File: src/main/webapp/app/programming/shared/code-editor/layout/code-editor-grid/code-editor-grid.component.ts [hunk 21]
```diff
@@ -26,6 +26,8 @@ export class CodeEditorGridComponent implements AfterViewInit, OnDestroy {
     @ViewChild('instructions') instructionsElement: ElementRef;
 
     @Input() isTutorAssessment = false;
+    @Input() showEditorNavbar = true;
+    @Input() showEditorSidebarRight = true;
```
[the remark this answers is not in the document]
Comment (DominikRemo) [reply src/main/webapp/app/programming/shared/code-editor/layout/code-editor-grid/code-editor-grid.component.ts:30]: This component was not yet migrated to Angular 21 and a migration is out of scope for this PR

File: src/main/webapp/app/exercise/exercise-headers/exercise-headers-information/result-history-dropdown/result-history-dropdown.component.ts [hunk 22]
```diff
@@ -0,0 +1,255 @@
...
+        const exercise = this.exercise();
+        const courseId = getCourseFromExercise(exercise)?.id;
+
+        if (exercise.type === ExerciseType.QUIZ) {
+            if (isPracticeMode(participation)) {
+                const submissionId = result.submission?.id;
+                this.router.navigate(['/courses', courseId, 'exercises', 'quiz-exercises', exercise.id, 'practice', participation.id, 'submission', submissionId]);
+            } else {
+                this.router.navigate(['/courses', courseId, 'exercises', 'quiz-exercises', exercise.id, 'live']);
+            }
```
[the remark this answers is not in the document]
Comment (DominikRemo) [reply src/main/webapp/app/exercise/exercise-headers/exercise-headers-information/result-history-dropdown/result-history-dropdown.component.ts:248]: But quizzes should only have one graded submission. It doesn't make sense to allow students to retake a graded quiz, since quizzes have time constraints for a good reason.

File: src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.ts [hunk 23]
```diff
@@ -447,17 +413,24 @@ export class CourseExerciseDetailsComponent implements OnInit, OnDestroy {
...
+        } else {
+            this._studentParticipations.set([...current, participation]);
+            if (participation.id && this.exercise) {
+                this.participationWebsocketService.addParticipation(participation, this.exercise);
+            }
+        }
+        this.sortResults();
+        if (participation.testRun) {
+            this.participationMode.set('practice');
+        }
```
[the remark this answers is not in the document]
Comment (laadvo) [reply src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.ts:456]: the practice participation is created once user clicks on the start practice button. this button is only visible after the due date, and the student is not able to continue the graded participation after the due date.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All feedback addressed — nice work getting everything resolved. The CI failures (client-tests, server-tests) are unrelated to your changes (build-job-detail spec, MessageIntegrationTest, ProgrammingExerciseVersionIntegrationTest — none in your diff). Approving.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All feedback addressed, nice work. The hardcoded strings are translated, the duplicate rendering is gone, the instructor action duplication is removed, and the athenaEnabled flag is properly wired. CI client-tests exit code 1 is a Vitest EnvironmentTeardownError during worker shutdown — all 785 test files actually pass.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All my previous feedback has been addressed — i18n strings, duplicate rendering, the CSS brace, translation key consistency, the instructor action duplication, and the hardcoded Athena flag. Nice work iterating on all of it. Approving from my side.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All my previous feedback has been addressed — hardcoded strings are translated, duplicate rendering is fixed, the CSS brace issue is resolved, instructor action duplication is cleaned up, and athenaEnabled is properly wired. Nice work getting all of that sorted out.

File: src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.ts (hunk 23 above)
[the remark this answers is not in the document]
Comment (laadvo) [reply src/main/webapp/app/core/course/overview/exercise-details/course-exercise-details.component.ts:456]: Do you think we can resolve the comment?

File: src/main/webapp/app/core/course/overview/exercise-details/request-feedback-button/request-feedback-button.component.ts [hunk 24]
```diff
@@ -85,7 +85,11 @@ export class RequestFeedbackButtonComponent implements OnInit, OnDestroy {
         if (this.exercise().id) {
             this.exerciseService.getExerciseDetails(this.exercise().id!).subscribe({
                 next: (exerciseResponse: HttpResponse<ExerciseDetailsType>) => {
-                    this.participation = this.participationService.getSpecificStudentParticipation(exerciseResponse.body!.exercise.studentParticipations ?? [], false);
+                    const participations = exerciseResponse.body!.exercise.studentParticipations ?? [];
+                    const practiceParticipation = this.participationService.getSpecificStudentParticipation(participations, true);
+                    const gradedParticipation = this.participationService.getSpecificStudentParticipation(participations, false);
+                    // Prefer practice participation when it exists (student is working in practice mode)
+                    this.participation = practiceParticipation ?? gradedParticipation;
```
[the remark this answers is not in the document]
Comment (laadvo) [reply src/main/webapp/app/core/course/overview/exercise-details/request-feedback-button/request-feedback-button.component.ts:92]: after the due date the student can no longer participate in the graded participation and only do practice mode. meaning the student can only submit and request feedback for practice submission whenever one exists. The graded participation is no longer relevant then

File: src/main/webapp/app/exercise/exercise-headers/participation-mode-toggle/participation-mode-toggle.component.scss [hunk 25]
```diff
@@ -0,0 +1,41 @@
+$practice-color: #3e8acc;
+$graded-color: #28a745;
```
[the remark this answers is not in the document]
Comment (laadvo) [reply src/main/webapp/app/exercise/exercise-headers/participation-mode-toggle/participation-mode-toggle.component.scss:2]: no we actually want to use these colors since they are already used in Artemis in other places

File: src/main/webapp/app/shared/components/resizable-panels/resizable-panels.component.scss [hunk 26]
```diff
@@ -0,0 +1,73 @@
...
+        &.p-tab-active {
+            color: var(--bs-body-color);
+            border-color: var(--bs-primary);
+            background: transparent;
+        }
+
+        &:not(.p-disabled):focus-visible {
+            box-shadow: none;
+            outline: none;
+        }
```
[the remark this answers is not in the document]
Comment (laadvo) [reply src/main/webapp/app/shared/components/resizable-panels/resizable-panels.component.scss:62]: can you explain this?

File: src/main/webapp/app/programming/overview/programming-exercise-participation.route.ts [hunk 27]
```diff
@@ -0,0 +1,15 @@
...
+export const programmingExerciseParticipationRoute: Routes = [
+    {
+        path: 'code-editor/:participationId',
+        loadComponent: () => import('./code-editor-student-container/code-editor-student-container.component').then((m) => m.CodeEditorStudentContainerComponent),
+        data: {
+            authorities: IS_AT_LEAST_STUDENT,
+            pageTitle: 'artemisApp.programmingExercise.home.title',
+        },
+        canActivate: [UserRouteAccessService],
+    },
```
[the remark this answers is not in the document]
Comment (laadvo) [reply src/main/webapp/app/programming/overview/programming-exercise-participation.route.ts:14]: Claude said: This finding is not valid. CodeEditorStudentContainerComponent does not implement the ComponentCanDeactivate interface — it has no canDeactivate() method. Adding canDeactivate:  
  [PendingChangesGuard] to the route would cause a runtime error when the guard calls component.canDeactivate() on a component that doesn't have that method.                       
                                                                                                                                                                                    
  The programming code editor works fundamentally differently from text/modeling editors — unsaved file changes are managed within the code editor's own tab system, not at the     
  route level. Simply adding the guard without the component contract would break navigation.                                                                                       
                                                                                                                                                                                    
  No change needed here.

File: src/main/webapp/app/shared/resizeable-container/resizeable-container.component.html [hunk 28]
```diff
@@ -1,35 +1,35 @@
...
     </div>
     <!--endregion LEFT SIDE-->
     <!--region RIGHT SIDE-->
-    @if (!examTimeline) {
-        @if (collapsed && !expandProblemStatement) {
-            <div class="collapsed right text-white bg-primary" (click)="collapsed = !collapsed">
+    @if (!examTimeline() && showRightPanel()) {
+        @if (collapsed() && !expandProblemStatement()) {
+            <div class="collapsed right text-white bg-primary" (click)="collapsed.set(!collapsed())">
                 <fa-icon [icon]="faChevronLeft" />
```
[the remark this answers is not in the document]
Comment (laadvo) [reply src/main/webapp/app/shared/resizeable-container/resizeable-container.component.html:20]: is this really necessary?

[the remark this answers is not in the document]
Comment (laadvo) [reply src/main/webapp/app/shared/resizeable-container/resizeable-container.component.html:20]: for now I would say it is out of scope.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All feedback addressed, nice work. The i18n strings, duplicate rendering, CSS brace, instructor action duplication, Athena flag wiring, and CodeRabbit suggestions are all resolved. CI is still running but the key checks (compilation, translation consistency, code quality) pass.

File: src/main/webapp/app/programming/overview/code-editor-student-container/code-editor-student-container.component.ts [hunk 29]
```diff
@@ -53,6 +53,9 @@ export class CodeEditorStudentContainerComponent implements OnInit, OnDestroy {
 
     @ViewChild(CodeEditorContainerComponent, { static: false }) codeEditorContainer: CodeEditorContainerComponent;
     readonly IncludedInOverallScore = IncludedInOverallScore;
+
+    readonly participationId = input<number>();
+    readonly lightweight = signal(false);
```
[the remark this answers is not in the document]
Comment (laadvo) [reply src/main/webapp/app/programming/overview/code-editor-student-container/code-editor-student-container.component.ts:58]: what do you think about this response from Claude?
● This finding is not needed. The current code already handles both sources correctly at line 90:                                                                                   
                                                                                                                                                                                    
  const participationId = this.participationId() ?? Number(params['participationId']);                                                                                              
                                                                                                                                                                                    
  The route.params subscription fires on route changes and reads the participationId() signal inside the callback, preferring it over route params. The only theoretical gap is if  
  participationId() changes independently of route params — but checking the usages, this component is always loaded via routing (code-editor/:participationId), and no consumer    
  dynamically changes the participationId input after init. The exercise-split-panel.component.ts only calls component.commit() on it, never rebinds inputs.                        
                                                                                                                                                                                    
  Converting to effect() would also require toSignal(this.route.params) to make the observable reactive, adding complexity without solving an actual problem. No change needed.

[the remark this answers is not in the document]
Comment (laadvo) [reply src/main/webapp/app/programming/overview/code-editor-student-container/code-editor-student-container.component.ts:58]: This finding is not needed. The current code already handles both sources correctly at line 90:

const participationId = this.participationId() ?? Number(params['participationId']);

The route.params subscription fires on route changes and reads the participationId() signal inside the callback, preferring it over route params. The only theoretical gap is if
participationId() changes independently of route params — but checking the usages, this component is always loaded via routing (code-editor/:participationId), and no consumer
dynamically changes the participationId input after init. The exercise-split-panel.component.ts only calls component.commit() on it, never rebinds inputs.

Converting to effect() would also require toSignal(this.route.params) to make the observable reactive, adding complexity without solving an actual problem. No change needed.

File: src/main/webapp/app/exercise/shared/exercise-submit-button/exercise-submit-button.component.html [hunk 30]
```diff
@@ -0,0 +1,31 @@
...
+    <span
+        [ngbPopover]="popContent"
+        [autoClose]="false"
+        placement="bottom-end bottom-start bottom auto"
+        container="body"
+        triggers="manual"
+        popoverClass="ai-feedback-popover"
+        #popoverRef="ngbPopover"
+    >
+        <jhi-button [title]="title()" [disabled]="disabled()" [isLoading]="isLoading()" [btnType]="btnType()" [tooltip]="tooltip()" (onClick)="submitAndShowPopover()" />
```
[the remark this answers is not in the document]
Comment (laadvo) [reply src/main/webapp/app/exercise/shared/exercise-submit-button/exercise-submit-button.component.html:11]: implemented in latest commit

File: src/main/webapp/app/communication/shared/discussion-section/discussion-section.component.html [hunk 31]
```diff
@@ -125,7 +114,13 @@ <h5 class="mb-0 fw-medium" jhiTranslate="artemisApp.metis.communication.label"><
...
                                 </form>
                                 <div class="bold-line row mt-1 mb-2"></div>
-                                <div #itemsContainer class="items-container" infinite-scroll [scrollWindow]="false" (scrolledUp)="fetchNextPage()">
+                                <div
+                                    #itemsContainer
+                                    [class]="embedded() ? 'overflow-y-auto flex-grow-1' : 'items-container'"
+                                    infinite-scroll
+                                    [scrollWindow]="false"
+                                    (scrolledUp)="fetchNextPage()"
+                                >
```
[the remark this answers is not in the document]
Comment (laadvo) [reply src/main/webapp/app/communication/shared/discussion-section/discussion-section.component.html:123]: implemented in latest commit

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All feedback addressed, nice work. The i18n strings, duplicated instructor actions, hardcoded Athena flag, and CSS issues are all fixed. The new quiz result endpoint and practice mode extensions for text/modeling look solid.

**Review by Claudia-Anthropica — APPROVED** [review]
@DominikRemo All previous feedback addressed — nice work iterating on this. The unified split-panel UX, i18n fixes, Athena practice mode expansion, and the recent read-only text editor / quiz practice fixes all look solid. Approving.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All feedback addressed, nice work. The practice mode extension for text and modeling exercises looks solid, and the new quiz result endpoint has proper auth checks. CI failures are all infrastructure-related (Weaviate container flakiness), not caused by your changes.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All previously requested changes are addressed — hardcoded strings translated, duplicate rendering fixed, CSS syntax corrected, Athena flag wired properly, and duplication eliminated. The quiz submission integration via router outlet activate/deactivate signals is clean. Nice work pulling this together.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All previous feedback addressed — nice work. The new commits integrating quiz submit state with the split panel look solid, and the E2E test adaptations for the new UI and Apollon v4 are clean. Approving.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All previous feedback addressed — nice work iterating on the quiz integration and E2E fixes. The split-panel UX is coming together well. Approving.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All previous feedback addressed. The new quiz submit state sync, Athena result navigation, and LLM gating look solid. Nice work on this massive UX overhaul.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All feedback addressed — i18n strings, duplicate rendering, hardcoded Athena flag, CSS brace, duplicate code, and translation consistency are all fixed. Nice work getting this massive PR into shape.

**Review by Claudia-Anthropica — APPROVED** [review]
@DominikRemo All feedback addressed, nice work. The CI failure in `client-tests-selected` is unrelated to your changes — it's a missing `UrlTree` import in `landing-route-guard.spec.ts`, which wasn't touched in this PR.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All feedback addressed, nice work. The i18n strings, duplication, hardcoded athena flag, and CSS issues are all fixed. The `client-tests-selected` CI failure is unrelated to your changes (it's a `UrlTree` import issue in `landing-route-guard.spec.ts` from the develop merge).

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All feedback addressed — i18n strings, duplicate rendering, CSS syntax, Athena hardcoding, instructor action duplication, and the translation key consistency issue are all fixed. The new quiz practice restart logic in the latest commit looks clean too. Nice work.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All feedback addressed, nice work. The LOCAL_AI acceptance fix in the latest commit makes sense. CI failures (client-tests) are unrelated — missing `UrlTree` import in `landing-route-guard.spec.ts` from a different PR.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All previously requested changes have been addressed — i18n strings, the duplicated instructor actions, the CSS brace, the Athena profile wiring, and the translation consistency issue are all fixed. The new quiz integration with the split panel looks clean. Nice work on this massive PR.

**Review by Claudia-Anthropica — DISMISSED** [review]
@DominikRemo All feedback addressed — nice work. The quiz submit state syncing, practice restart flow, and split panel width fix all look solid. Approving.

**Review by Claudia-Anthropica — APPROVED** [review]
@DominikRemo All feedback addressed, nice work. The i18n fixes, duplicate removal, Athena wiring, and CSS fixes all look good. The vitest coverage thresholds dropped a bit — might be worth adding tests for the lower-coverage new components (exercise-submit-button at 19%, resizable-panels at 14%) in a follow-up.

**Review by krusche — APPROVED** [review]
