### PR TITLE
`Lectures`: Trim leading and trailing whitespaces in video lecture URLs

### LINKED ISSUE #5185: Remove leading and trailing spaces of the pasted URL in a video lecture unit
### Describe the bug

When the user wants to create a new lecture unit of type video and paste the url containing leading or trailing spaces, they are not recognized and therefore not removed from the source. That leads to the failed video loading.
To resolve the issue, the leading and trailing spaces need to be removed before the value is inserted into the text field.

### To Reproduce

1. Go to some existing course → Lectures → Units
2. Click on 'Add a new Lecture Unit' of type video
3. Give some name
4. Enter the URL containing spaces and save
5. The video cannot be watched if the user opens the unit

### Expected behavior

The system checks the inserted URL before assigning it to the text field and removes the spaces. The result URL is already cleaned by the system.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Dominik-Weinzierl**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).

### Motivation and Context

Closes #5185: Remove leading and trailing whitespaces

### Description

To handle leading and trailing whitespaces, we remove them on the server when we create or update URLs.

### Steps for Testing

Prerequisites:
- 1 Instructor
- Lecture

1. Go to some existing course → Lectures → Units
2. Click on 'Add a new Lecture Unit' of type video
3. Give some name
4. Enter the URL containing spaces and save
5. The video should be watchable
6. Update the URL and add again whitespaces
7. The video should be still watchable

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### CODE REVIEW

**Comment by ge65cer** [comment]
I guess that works. Just out of curiosity, why did you implement it server-side and not client-side?

**Comment by Dominik-Weinzierl** [comment]
> I guess that works. Just out of curiosity, why did you implement it server-side and not client-side?

Since this is a "public" endpoint, validation on the client is not sufficient in most cases. Therefore, I decided to handle this case entirely on the server. Otherwise we need to handle this on the client and on the server :thinking:

**Review by bassner — APPROVED** [review]
Tested on TS5. Whitespace on the beginning and end of the URL is removed.
Code looks good to me 👍

File: src/main/java/de/tum/in/www1/artemis/web/rest/lecture/VideoUnitResource.java [hunk 1]
```diff
@@ -90,6 +90,10 @@ public ResponseEntity<VideoUnit> updateVideoUnit(@PathVariable Long lectureId, @
 
         // Validate the URL
         try {
+            // Remove leading and trailing whitespaces
+            if (videoUnit.getSource() != null) {
+                videoUnit.setSource(videoUnit.getSource().strip());
+            }
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/web/rest/lecture/VideoUnitResource.java:96]:
```suggestion
        normalizeVideoUrl(videoUnit);

        // Validate the URL
        try {
```

Two suggestions:
- The new code should be in a small helper method to avoid duplication. This also makes possible future necessary changes to the URL easier.
- It should not be part of the `try`-block of the validation. (Sidenote: The validation should probably be moved to a separate small method to remove duplication as well).

**Review by b-fein — CHANGES_REQUESTED** [review]

**Comment by ge65cer** [comment]
I think the core problem was that the [RegEx](https://github.com/ls1intum/Artemis/blob/f8d07e2175a6587d7d242404bb218fe775226097/src/main/webapp/app/overview/course-lectures/video-unit/video-unit.component.ts#L20) did not match TUM-RGB URLs with whitespace, therefore `videoUrl` in the client component was undefined?
I'll take a note, as I will be doing some other enhancements in the video-unit-form component anyways soon.

File: src/main/java/de/tum/in/www1/artemis/web/rest/lecture/VideoUnitResource.java (hunk 1 above)
Comment (Dominik-Weinzierl) [reply src/main/java/de/tum/in/www1/artemis/web/rest/lecture/VideoUnitResource.java]: Yes you are right :+1: extracted both duplicated code parts :+1:

File: src/main/java/de/tum/in/www1/artemis/web/rest/lecture/VideoUnitResource.java [hunk 2]
```diff
@@ -41,6 +41,31 @@ public class VideoUnitResource {
...
+            videoUnit.setSource(videoUnit.getSource().strip());
+        }
+    }
+
+    /**
+     * Validates the provided video Url.
+     * @param videoUnit provided video unit
+     */
+    private void validateVideoUrl(VideoUnit videoUnit) {
+        // Validate the URL
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/web/rest/lecture/VideoUnitResource.java:60]:
```suggestion
```

**Review by b-fein — APPROVED** [review]
Thanks! Code changes look good now. :+1:

**Review by ge65cer — APPROVED** [review]

**Review by Strohgelaender — APPROVED** [review]

**Review by mallgaier — COMMENTED** [review]
Tested, works as expected.
Code changes look good to me. 
Exzellent job 👍

**Review by mallgaier — APPROVED** [review]
Tested, works as expected.
Code changes look good to me. 
Exzellent job 👍
