### PR TITLE
`General`: Fix exercise archival for courses and exams

### LINKED ISSUE #8521: `Programming exercises`: Archiving a course is not possible
### Describe the bug

I cannot archive a course. There always an error message occur, and no zip file is provided.

### To Reproduce

1. Create a new course (name `Some Testing`), with end in a view minutes
2. Create a programming exercise (name `abc`) in this course (recommendation: enable online editor)
3. Make a submission for this exercise (you can use the same Artemis user for this)
4. Wait until the course ends (or adjust the end)
5. Go to the course management for the course `Some Testing`
6. Click on "Archive Course" and confirm the message
7. After the processing you get the error `Did not archive course 'Some Testing': Nothing to export.`

### Expected behavior

The browser downloads a zip file after the process is finished.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

7.0.3 (Branch: develop • Commit Hash: 1073503 • Committer Date: Wed, 01 May 2024 09:27:56 GMT)

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

<details>
```shell
2024-05-01T17:29:17.154+02:00 ERROR 39359 --- [Artemis] [ artemis-task-2] d.t.i.w.a.aop.logging.LoggingAspect      : Exception in de.tum.in.www1.artemis.service.export.ProgrammingExerciseExportService.exportProgrammingExerciseForArchival() with cause = 'NULL' and exception = 'could not initialize proxy [de.tum.in.www1.artemis.domain.plagiarism.PlagiarismDetectionConfig#6] - no Session'

org.hibernate.LazyInitializationException: could not initialize proxy [de.tum.in.www1.artemis.domain.plagiarism.PlagiarismDetectionConfig#6] - no Session
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:165)
	at org.hibernate.proxy.pojo.BasicLazyInitializer.invoke(BasicLazyInitializer.java:78)
	at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:42)
	at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:102)
	at de.tum.in.www1.artemis.domain.plagiarism.PlagiarismDetectionConfig$HibernateProxy$1JhzQaD7.setId(Unknown Source)
	at de.tum.in.www1.artemis.service.export.ExerciseWithSubmissionsExportService.lambda$exportExerciseDetails$0(ExerciseWithSubmissionsExportService.java:224)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at de.tum.in.www1.artemis.service.export.ExerciseWithSubmissionsExportService.exportExerciseDetails(ExerciseWithSubmissionsExportService.java:224)
	at de.tum.in.www1.artemis.service.export.ExerciseWithSubmissionsExportService.exportProblemStatementAndEmbeddedFilesAndExerciseDetails(ExerciseWithSubmissionsExportService.java:74)
	at de.tum.in.www1.artemis.service.export.ProgrammingExerciseExportService.exportProblemStatementAndEmbeddedFilesAndExerciseDetails(ProgrammingExerciseExportService.java:189)
	at de.tum.in.www1.artemis.service.export.ProgrammingExerciseExportService.exportProgrammingExerciseMaterialWithStudentReposOptional(ProgrammingExerciseExportService.java:178)
	at de.tum.in.www1.artemis.service.export.ProgrammingExerciseExportService.exportProgrammingExerciseForArchival(ProgrammingExerciseExportService.java:204)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at de.tum.in.www1.artemis.aop.logging.LoggingAspect.logAround(LoggingAspect.java:89)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at de.tum.in.www1.artemis.service.export.ProgrammingExerciseExportService$$SpringCGLIB$$0.exportProgrammingExerciseForArchival(<generated>)
	at de.tum.in.www1.artemis.service.export.CourseExamExportService.exportExercises(CourseExamExportService.java:415)
	at de.tum.in.www1.artemis.service.export.CourseExamExportService.exportCourseExercises(CourseExamExportService.java:279)
	at de.tum.in.www1.artemis.service.export.CourseExamExportService.exportCourseAndExamExercises(CourseExamExportService.java:244)
	at de.tum.in.www1.artemis.service.export.CourseExamExportService.exportCourse(CourseExamExportService.java:128)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at de.tum.in.www1.artemis.aop.logging.LoggingAspect.logAround(LoggingAspect.java:89)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at de.tum.in.www1.artemis.service.export.CourseExamExportService$$SpringCGLIB$$0.exportCourse(<generated>)
	at de.tum.in.www1.artemis.service.CourseService.archiveCourse(CourseService.java:857)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at de.tum.in.www1.artemis.aop.logging.LoggingAspect.logAround(LoggingAspect.java:89)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
	at tech.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createCallable$0(ExceptionHandlingAsyncTaskExecutor.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

2024-05-01T17:29:17.154+02:00 ERROR 39359 --- [Artemis] [ artemis-task-2] d.t.i.w.a.s.e.CourseExamExportService    : Failed to export exercise 'abc' (id: 3): could not initialize proxy [de.tum.in.www1.artemis.domain.plagiarism.PlagiarismDetectionConfig#6] - no Session

org.hibernate.LazyInitializationException: could not initialize proxy [de.tum.in.www1.artemis.domain.plagiarism.PlagiarismDetectionConfig#6] - no Session
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:165)
	at org.hibernate.proxy.pojo.BasicLazyInitializer.invoke(BasicLazyInitializer.java:78)
	at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:42)
	at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:102)
	at de.tum.in.www1.artemis.domain.plagiarism.PlagiarismDetectionConfig$HibernateProxy$1JhzQaD7.setId(Unknown Source)
	at de.tum.in.www1.artemis.service.export.ExerciseWithSubmissionsExportService.lambda$exportExerciseDetails$0(ExerciseWithSubmissionsExportService.java:224)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at de.tum.in.www1.artemis.service.export.ExerciseWithSubmissionsExportService.exportExerciseDetails(ExerciseWithSubmissionsExportService.java:224)
	at de.tum.in.www1.artemis.service.export.ExerciseWithSubmissionsExportService.exportProblemStatementAndEmbeddedFilesAndExerciseDetails(ExerciseWithSubmissionsExportService.java:74)
	at de.tum.in.www1.artemis.service.export.ProgrammingExerciseExportService.exportProblemStatementAndEmbeddedFilesAndExerciseDetails(ProgrammingExerciseExportService.java:189)
	at de.tum.in.www1.artemis.service.export.ProgrammingExerciseExportService.exportProgrammingExerciseMaterialWithStudentReposOptional(ProgrammingExerciseExportService.java:178)
	at de.tum.in.www1.artemis.service.export.ProgrammingExerciseExportService.exportProgrammingExerciseForArchival(ProgrammingExerciseExportService.java:204)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at de.tum.in.www1.artemis.aop.logging.LoggingAspect.logAround(LoggingAspect.java:89)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at de.tum.in.www1.artemis.service.export.ProgrammingExerciseExportService$$SpringCGLIB$$0.exportProgrammingExerciseForArchival(<generated>)
	at de.tum.in.www1.artemis.service.export.CourseExamExportService.exportExercises(CourseExamExportService.java:415)
	at de.tum.in.www1.artemis.service.export.CourseExamExportService.exportCourseExercises(CourseExamExportService.java:279)
	at de.tum.in.www1.artemis.service.export.CourseExamExportService.exportCourseAndExamExercises(CourseExamExportService.java:244)
	at de.tum.in.www1.artemis.service.export.CourseExamExportService.exportCourse(CourseExamExportService.java:128)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at de.tum.in.www1.artemis.aop.logging.LoggingAspect.logAround(LoggingAspect.java:89)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at de.tum.in.www1.artemis.service.export.CourseExamExportService$$SpringCGLIB$$0.exportCourse(<generated>)
	at de.tum.in.www1.artemis.service.CourseService.archiveCourse(CourseService.java:857)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at de.tum.in.www1.artemis.aop.logging.LoggingAspect.logAround(LoggingAspect.java:89)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
	at tech.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createCallable$0(ExceptionHandlingAsyncTaskExecutor.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
</details>

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [X] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [X] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [X] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

### Motivation and Context

Fixes #8521

### Description

- I ensured that the exercise detail configurations get loaded on export to prevent the initialization error.
- I fixed some minor code issues along the way.
- I added the team config to the export for consistency.
- I added two tests covering the issue, I confirmed that they fail on develop.
- While fixing tests, I had to fix the issue that the plagiarism detection config wasn't transferred on import

### Steps for Testing

Prerequisites:
- 1 Course with each type of exercise, activate plagiarism control wherever possible. Set one exercise as team exercise
- 1 Instructor
- 1+ Student

1. Participate in all exercises
2. Wait for the course to end/set end date
3. Navigate to the course detail view
4. Hit "Archive Course" on the right; expect no error and success alert
5. Download the archive, expect no issues

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Exam with each type of exercise spread over exercise groups

1. Participate in the exam as a student
2. Wait for the exam to end as an instructor
3. Go to the exam detail page and export the exam; expect no error and a success alert
6. Download the archive; expect no issues

#### Performance Review
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [ ] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### Test Coverage

Only significant change coverage-wise was an auto-transformation if-else to switch-case.

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/service/export/CourseExamExportService.java [hunk 1]
```diff
@@ -410,30 +411,24 @@ private List<Path> exportExercises(String notificationTopic, Set<Exercise> exerc
...
-                }
-                else {
-                    // Exercise is not supported so skip
+                switch (exercise) {
+                    case ProgrammingExercise programmingExercise ->
+                        // Download the repositories' template, solution, tests and students' repositories
+                        programmingExerciseExportService.exportProgrammingExerciseForArchival(programmingExercise, exportErrors, Optional.of(exerciseExportDir), reportData)
+                                .ifPresent(exportedExercises::add);
+
+                    // Export the other exercises types
```
Comment (JohannesStoehr) [inline src/main/java/de/tum/in/www1/artemis/service/export/CourseExamExportService.java:420]: What information does this comment add?

File: src/main/java/de/tum/in/www1/artemis/service/export/CourseExamExportService.java [hunk 2]
```diff
@@ -410,30 +411,24 @@ private List<Path> exportExercises(String notificationTopic, Set<Exercise> exerc
...
+                    case FileUploadExercise fileUploadExercise -> exportedExercises.add(fileUploadExerciseWithSubmissionsExportService
+                            .exportFileUploadExerciseWithSubmissions(fileUploadExercise, submissionsExportOptions, exerciseExportDir, exportErrors, reportData));
+                    case TextExercise textExercise -> exportedExercises.add(textExerciseWithSubmissionsExportService.exportTextExerciseWithSubmissions(textExercise,
+                            submissionsExportOptions, exerciseExportDir, exportErrors, reportData));
+                    case ModelingExercise modelingExercise -> exportedExercises.add(modelingExerciseWithSubmissionsExportService
+                            .exportModelingExerciseWithSubmissions(modelingExercise, submissionsExportOptions, exerciseExportDir, exportErrors, reportData));
+                    case QuizExercise quizExercise ->
+                        exportedExercises.add(quizExerciseWithSubmissionsExportService.exportExerciseWithSubmissions(quizExercise, exerciseExportDir, exportErrors, reportData));
+                    default -> {
+                        // Exercise is not supported so skip
```
Comment (JohannesStoehr) [inline src/main/java/de/tum/in/www1/artemis/service/export/CourseExamExportService.java:430]: Maybe throw an error that the user notices that an exercise was not handled correctly?

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
Can you also adapt the test that covers this export to include these additional things?

**Review by BaumiCoder — DISMISSED** [review]
Tested on my local machine (with Jenkins & Gitlab) for course and exam.

File: src/main/java/de/tum/in/www1/artemis/repository/CourseRepository.java [hunk 3]
```diff
@@ -139,8 +139,8 @@ SELECT COUNT(c) > 0
     @EntityGraph(type = LOAD, attributePaths = { "lectures", "lectures.attachments" })
     Optional<Course> findWithEagerLecturesById(long courseId);
 
-    @EntityGraph(type = LOAD, attributePaths = { "exercises", "lectures", "lectures.attachments" })
-    Optional<Course> findWithEagerExercisesAndLecturesById(long courseId);
+    @EntityGraph(type = LOAD, attributePaths = { "exercises", "exercises.plagiarismDetectionConfig", "exercises.teamAssignmentConfig", "lectures", "lectures.attachments" })
+    Optional<Course> findWithEagerExercisesAndExerciseDetailsAndLecturesById(long courseId);
```
Comment (JohannesWt) [inline src/main/java/de/tum/in/www1/artemis/repository/CourseRepository.java:143]: Maybe one could be more precise in the naming when fetching the details instead of `...AndExerciseDetails`

**Review by JohannesWt — CHANGES_REQUESTED** [review]
One small remark (see comment)

File: src/main/java/de/tum/in/www1/artemis/repository/CourseRepository.java (hunk 3 above)
Comment (julian-christl) [reply src/main/java/de/tum/in/www1/artemis/repository/CourseRepository.java:143]: Sure, but honestly, it doesn't really add anything but length. If you want to know what exercise details are included, you can check it out.

Do you consider it critical to include the precise terms?

File: src/main/java/de/tum/in/www1/artemis/service/export/CourseExamExportService.java (hunk 2 above)
Comment (julian-christl) [reply src/main/java/de/tum/in/www1/artemis/service/export/CourseExamExportService.java:430]: I'd prefer to leave it like that:
If you have an erroneous exercise, the export breaks. And you don't have a chance to export anything unless you - at worst delete the exercise.

The best solution would be to write an export summary that gets displayed to the user; however, that's a completely new feature implementation.

Comment (julian-christl) [reply src/main/java/de/tum/in/www1/artemis/service/export/CourseExamExportService.java:430]: I added an error to the error list

File: src/main/java/de/tum/in/www1/artemis/domain/plagiarism/PlagiarismDetectionConfig.java [hunk 4]
```diff
@@ -115,6 +115,20 @@ public static PlagiarismDetectionConfig createDefault() {
...
+     *
+     * @return a clone of this instance or null on failure
+     */
+    public PlagiarismDetectionConfig clone() {
+        try {
+            return (PlagiarismDetectionConfig) super.clone();
+        }
+        catch (CloneNotSupportedException e) {
+            return null;
+        }
```
[the remark this answers is not in the document]
Comment (julian-christl) [reply src/main/java/de/tum/in/www1/artemis/domain/plagiarism/PlagiarismDetectionConfig.java]: done

**Review by BaumiCoder — APPROVED** [review]
Re-tested on my local machine after changes.

File: src/main/java/de/tum/in/www1/artemis/repository/CourseRepository.java (hunk 3 above)
Comment (JohannesWt) [reply src/main/java/de/tum/in/www1/artemis/repository/CourseRepository.java:143]: It is not critical that's true I just thought, it does increase the length but when you call the method one would always know what you get without digging deeper. But except that code looks good to me. If you want to keep it that way, just let me know and I'll approve.

File: src/test/java/de/tum/in/www1/artemis/service/export/CourseExamExportServiceTest.java [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+    @Autowired
+    private CourseRepository courseRepository;
+
+    @Autowired
+    private ExerciseRepository exerciseRepository;
+
+    @BeforeEach
+    void setup() {
+        // setup users
+        userUtilService.addUsers(TEST_PREFIX, 5, 5, 0, 1);
```
Comment (DominikRemo) [inline src/test/java/de/tum/in/www1/artemis/service/export/CourseExamExportServiceTest.java:48]: Can we use a smaller number of users in this test? Instantiating users takes time and lengthens the tests

File: src/test/java/de/tum/in/www1/artemis/service/export/CourseExamExportServiceTest.java [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+        assertThatNoException().isThrownBy(() -> courseExamExportService.exportExam(exam, Path.of("tmp/export"), exportErrors));
+
+        assertThat(exportErrors).isEmpty();
+    }
+
+    @Test
+    @WithMockUser(username = TEST_PREFIX + "instructor1", roles = "INSTRUCTOR")
+    void testExportCourse() throws IOException {
+        var course = courseUtilService.createCourseWithExamExercisesAndSubmissions(TEST_PREFIX);
+        var courseWithExercises = courseUtilService.addCourseWithExercisesAndSubmissions(TEST_PREFIX, "", 5, 5, 4, 2, true, 1, "");
```
Comment (DominikRemo) [inline src/test/java/de/tum/in/www1/artemis/service/export/CourseExamExportServiceTest.java:66]: Similar to above, can we use a smaller amount of exercises and submissions?

**Review by laadvo — APPROVED** [review]
Tested the exam mode on ts2, exporting the finished exam with partitipations in all exercises worked without any problems. I was able to download the archive :+1:

File: src/test/java/de/tum/in/www1/artemis/service/export/CourseExamExportServiceTest.java (hunk 5 above)
Comment (julian-christl) [reply src/test/java/de/tum/in/www1/artemis/service/export/CourseExamExportServiceTest.java:48]: I reduced them a bit, but due to the nature of the code in the test services, I have to have a minimum number. Refactoring such code to be more flexible is out of scope.

**Review by JohannesStoehr — APPROVED** [review]
Code

**Review by JohannesWt — APPROVED** [review]
Code looks good 👍

**Review by laadvo — APPROVED** [review]
Reapprove exam mode test

**Review by DominikRemo — APPROVED** [review]
Thank you for addressing my comments

**Review by BBesrour — APPROVED** [review]
Exam mode:
Tested on TS3: [Created exam](https://artemis-test3.artemis.cit.tum.de/course-management/48/exams/10)
- Created exam with 5 exercise groups each with a different exercise type
- Participated with a student
- end exam
- **Archive Exam -> No errors**
- Archive file downloadable

Normal mode:
Tested locally:
- Created 5 exercises (programming, modeling, and text exercise with plagiarism / Text exercise in teams)
- Create a team for text exercise
- Participated with a student in all exercises
- end course
- **Archive Exam -> No errors**
- Archive file downloadable
