### PR TITLE
`Development`: Hide sidebar entry when module feature is disabled

### LINKED ISSUE #12494: Tutorials shown in left sidebar even if disabled in server config
### Describe the bug

In the instructor view for a course, the tutorials are shown in the left sidebar even if they are disabled in the server config (`artemis.tutorialgroup.enabled: false`). Clicking on the ‘Tutorials’ item results in an error.

### To Reproduce

1. Disable tutorials in the server config.
2. Go to the instructor view of a course.
3. Click on Tutorials in the left sidebar.
4. Observe the error.

### Expected behavior

Tutorials item not shown in the left sidebar.

### Screenshots

Image

### Which version of Artemis are you seeing the problem on?

9.0.0

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by krusche**
### Summary
When the `artemis.tutorialgroup.enabled` module feature is disabled on the server, the "Tutorials" item was still shown in the instructor course sidebar and clicking it led to an error. This PR hides the entry consistently with the existing pattern used for lecture, atlas, and iris.

#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.tum.de/developer/guidelines/language).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.tum.de/developer/development-process#pr-naming-conventions).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding guidelines](https://docs.artemis.tum.de/developer/guidelines/client-development).
- [x] I added multiple integration tests (Vitest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.tum.de/developer/guidelines/client-tests).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
Closes #12494.

In the instructor view for a course, the "Tutorials" item is shown in the left sidebar even if tutorial groups are disabled in the server config (`artemis.tutorialgroup.enabled: false`). Clicking the entry then results in an error, since the feature is not available on the server.

The root cause is in `CourseManagementContainerComponent.addTutorialGroupsItem`, which adds the entry whenever the user is an instructor without consulting the `MODULE_FEATURE_TUTORIALGROUP` module feature flag.

### Description
- Added `tutorialGroupEnabled` to `BaseCourseContainerComponent`, initialized from `profileService.isModuleFeatureActive(MODULE_FEATURE_TUTORIALGROUP)`. This follows the same pattern already in place for `atlasEnabled`, `lectureEnabled`, `irisEnabled`, and `ltiEnabled`.
- Gated the "Tutorials" sidebar entry in the instructor container on this flag, so it is only shown when the module feature is active.
- Added a Vitest test in `course-management-container.component.spec.ts` that asserts the entry is hidden when the tutorial group module feature is disabled (instructor + course with `tutorialGroupsConfiguration` still must not show the entry). Updated the existing "should create sidebar items based on course properties" test to enable the new flag.

### Steps for Testing
Prerequisites:
- 1 Instructor
- A course where the instructor has access to course management

1. In the server config, set `artemis.tutorialgroup.enabled: false` and start Artemis.
2. Log in as an instructor and navigate to Course Management for any course.
3. Verify that the left sidebar no longer contains a "Tutorials" entry.
4. Open any other sidebar entry (e.g. Exercises) to confirm navigation still works.
5. Restart with `artemis.tutorialgroup.enabled: true` and verify that the "Tutorials" entry reappears and still opens the tutorial groups view as expected.

### Screenshots
**Before the fix** (tutorial groups disabled server-side, instructor view) — the "Tutorials" entry is still shown, as reported in #12494:

Sidebar with Tutorials entry visible despite disabled module

**After the fix**: the "Tutorials" entry is not rendered. No other sidebar entries are affected; the rest of the sidebar is identical to the screenshot above but without the "Tutorials" row.

## Release Notes

* **New Features**
  * Tutorial groups sidebar item visibility is now controlled by a feature flag, allowing selective enable/disable at the module level.

* **Tests**
  * Added test coverage verifying tutorial groups sidebar item visibility based on feature flag status.

### CODE REVIEW

File: src/main/webapp/app/core/course/shared/course-base-container/course-base-container.component.ts [hunk 1]
```diff
@@ -73,6 +73,7 @@ export abstract class BaseCourseContainerComponent implements OnInit, OnDestroy,
     lectureEnabled: boolean = false;
     irisEnabled: boolean = false;
     ltiEnabled: boolean = false;
+    tutorialGroupEnabled: boolean = false;
```
Comment (Claudia-Anthropica) [inline src/main/webapp/app/core/course/shared/course-base-container/course-base-container.component.ts:76]: @krusche [low] Nice that this is in the base class now. Worth noting that the student-side `CourseOverviewComponent.getSidebarItems()` (line 332) checks `this.hasTutorialGroups()` but doesn't also check `this.tutorialGroupEnabled` — unlike lectures and atlas which are gated by their respective flags. Might be worth a quick follow-up for consistency, though it probably doesn't manifest as a visible bug if the server omits `numberOfTutorialGroups` when the module is off.

**Review by Claudia-Anthropica — DISMISSED** [review]
@krusche Clean fix, follows the existing pattern for other module features perfectly. Just one minor observation about the student-side sidebar inline — not blocking.

**Review by Claudia-Anthropica — APPROVED** [review]
@krusche Looks good — the fix follows the exact same pattern as the other module feature gates (lectures, atlas, iris, lti) and now covers both instructor and student sidebars. Thanks for picking up the student-side fix too. Nice work.
