### PR TITLE
`Plagiarism checks`: Fix comparison highlighting and introduce full line highlighting for programming exercises

### LINKED ISSUE #6579: `Plagiarism`, `Programming Exercises`: Broken code view
### Describe the bug

In the plagiarism view for programming exercises the file view on the right side remains empty. 

### To Reproduce

1. Have a programming exercise with a few submissions.
2. Run the plagiarism check.
3. Select a case marked as potential plagiarism.
4. The file for student1 on the left side loads, the one on the right side does not.
   - See log output in your browser console as attached at the end of this issue.
5. Changing to different files does not change that.

### Secondary bug, same underlying issue

1. Steps 1-3 from above.
2. Change to another student pair on the left side.
3. Try selecting different files in either left/right view.
4. The shown file contents now no longer match the selected names at the top. (Most of the time, for some files it seems to work.)
5. The same console error appears.

### Expected behaviour

Both files are shown.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.1.5

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

```shell
ERROR TypeError: c[D] is undefined
    insertMatchTokens text-submission-viewer.component.ts:244
    next text-submission-viewer.component.ts:178
    RxJS 29
    Angular 17
    RxJS 64
    handleFileSelect text-submission-viewer.component.ts:175
    RxJS 16
core.mjs:8416:22
```

### PR DESCRIPTION
**Pull request by jakubriegel**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Fixes #6579.

For some programming and text submissions the plagiarism comparison view was presenting invalid results. Such results either differed from expected results, caused loading errors on the client side or were repeated multiple times. @b-fein fixed the last issue in #7841.

The issue with matches different than expected was caused by an invalid calculation of start of some matches, particularly start of the fist match in a file.

Loading errors were caused by an `undefined` reference to a submission element, that happened due to invalid order of submission elements in the server response.

### Description
This PR introduces 3 improvements to the plagiarism comparison split view:
1. A fix for submission rendering issue caused by `undefined` array element and described in #6579
2. A fix for invalid highlighting location (like the described in this [comment](https://github.com/ls1intum/Artemis/issues/6579#issuecomment-1814360375))
3. A an improvement of always highlighting full lines of programming exercises when at least one match occurred in the particular line, so that the ambiguity from situations like the one described [here](https://github.com/ls1intum/Artemis/issues/6579#issuecomment-1882639690) is gone

Notes for **1**: The issue was fixed by introducing client-side sorting of submission elements.

Notes for **3**: Imprecise matches come directly from JPlag and are not caused by any Artemis logic. This change is required only for programming exercises, as for text exercises (due to different comparison approach) matches are always correct.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise
- 1 Text Exercise

**Path for testing the fix 1:**
Due to legal constraints this path will be tested only by @b-fein using the actual affected submission from #6579.

**Path for testing the fix 2:**
1. Prepare two identical (min. 300 words) submission for a text exercise from two different students accounts.
2. Change one of them is a few places. For example by: adding more words or replacing some existing words.
3. As instructor run plagiarism tests.
4. Verify that duplicated text parts are highlighted.

**Path for testing the improvement 3:**
1. Prepare two identical submission for a programming exercise from two different students accounts.
2. Change one of them is a few places. For example by: adding more lines of code or renaming some existing variables.
3. As instructor run plagiarism checks.
4. Verify that lines with duplicated code are highlighted.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| text-submission-viewer.component.spec.ts | 91% | ✅              |

### Screenshots

Fixed comparison view for text exercises:
image

Fixed and improved comparison view for programming exercises:
image

@coderabbitai ignore

### CODE REVIEW

**Comment by b-fein** [comment]
The new ordering of the elements in the last commit seems to have fixed the problem. The pairs that are matched now make sense. ⇒ I guess the original problem described in issue #6579 is fixed.

However, I‘m not sure if the new column calculation is correct (don’t know how it looked like before). There are quite a few places where the highlighting ends in the middle of tokens:
image

**Review by MarkusPaulsen — COMMENTED** [review]
Code looks good, waiting for reviews.

**Review by nata-81 — DISMISSED** [review]
tested on ts5:
  text: with users 1 and 2 works as expected.
  programming exercise: try to test with 1 but could not start the exercise. then with users 
  2 and 3 and received this error: 
image
What is the problem why can't I see the comparison? Thank you in advance!

**Comment by jakubriegel** [comment]
> tested on ts5:
> 
>   text: with users 1 and 2 works as expected.
> 
>   programming exercise: try to test with 1 but could not start the exercise. then with users 
> 
>   2 and 3 and received this error: 
> 
> image
> 
> What is the problem why can't I see the comparison? Thank you in advance! 

TS5 has some issues with GitLab integration. You can try on TS1 where the set up works fin

**Review by konrad2002 — APPROVED** [review]
manually tested on legacy ts1, works as expected

**Review by basak-akan — DISMISSED** [review]
Tested on TS1 for fix 2 and 3, worked well. Also code lgtm.

**Review by xHadie — APPROVED** [review]
_Manually tested on TS11_Legacy_
Works as expected!

**Review by coolchock — APPROVED** [review]
code lgtm

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/plagiarism-split-view.component.ts [hunk 1]
```diff
@@ -123,22 +123,23 @@ export class PlagiarismSplitViewComponent implements AfterViewInit, OnChanges, O
      * @param submission the submission to map the elements of
      */
     mapMatchesToElements(matches: SimpleMatch[], submission: PlagiarismSubmission<TextSubmissionElement>) {
+        const elements = submission.elements?.sort((a, b) => a.id - b.id);
```
Comment (b-fein) [inline src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/plagiarism-split-view.component.ts:126]: Please add a comment describing why this order is important.

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts [hunk 2]
```diff
@@ -226,9 +226,44 @@ export class TextSubmissionViewerComponent implements OnChanges {
...
         }
 
+        if (this.exercise?.type === ExerciseType.PROGRAMMING) {
+            return this.buildFileContentWithHighlightedMatchesAsWholeLines(fileContent, matches);
+        }
         return this.buildFileContentWithHighlightedMatches(fileContent, matches);
     }
 
+    /**
+     * Builds the required HTML to highlight the lines with matches in the file content.
```
Comment (b-fein) [inline src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts:236]: Please extend the comment to describe _why_ only full lines are highlighted (in case of programming exercises).

**Review by b-fein — CHANGES_REQUESTED** [review]
For programming exercises, the highlighted sections now match the ones shown in the JPlag report. :+1:

Change requested: During debugging of this issue we collected a lot of non-trivial information that might be helpful for someone working in this area in the future. Please extend the code comments a bit to explain the rationale of the changes.

**Review by b-fein — APPROVED** [review]

**Review by konrad2002 — APPROVED** [review]
retested on legacy ts1, works as expected

**Review by xHadie — APPROVED** [review]

**Review by MarkusPaulsen — APPROVED** [review]
Code looks good and tested on TS1
