### PR TITLE
[Enchancement] Improve Account Registration

### LINKED ISSUE #2354: Accounts get created without a GitLab Account
### Describe the bug
Users report a missing gitlab accounts (10% of users have this issue). 

#### To Reproduce

1. Register
2. Register again
3. Activate account
4. You now have no gitlab account

Not sure if it works 100% of the time or if it is a race condition. We had a big problem with this because our emails apparently take up to an hour to be delivered, hence a lot of impatient students registered multiple times. If it does not work go wild on the register button that will definitely work.

#### Research in the gitlab/artemis logs
Showed everything work according to plan(almost)
1. User registers
2. GitLab user gets created
3. Email sent
4. User registers again
5. Old GitLab account gets deleted
6. Artemis asks GitLab if a GitLab user already exists with given name (I can not see the result of the request in the logs but that is was made)
7. Artemis does not make a request to create a Gitlab user even if it should do that(Only logical explanation is that the answer from 6. was that is already existed, because Artemis has a check for that)
8. Email sent
9. User activates his account
10. User is missing a GitLab account

## Possible fixes
- Move GitLab creation to activation. But then you don't know if the user choose a valid gitlab username.
- Create the GitLab account in step 9 if missing. Still makes edge cases possible where users choose invalid usernames for GitLab.
- Wait for GitLab to return that the user actually got deleted(just ask the api if it exists)

Concerning the first two one could just enforce gitlab username restrictions on registration by hand.

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

The way user registration currently works is not optimal and e.g lead to race conditions with GitLab. 

### Description

This PR attempts to improve the overall registration process and should also resolve #2354.

The following changes were made:
- Jenkins accounts are not created upon registration anymore because normal users shouldn't have access to it in the first place.
- When a user registers, the external VCS account is deactivated as the Artemis account. Both accounts are activated when the user clicks on the registration link.
- If the user re-registers with the same email and login, Artemis updates the existing non-activated user and re-sends the activation email.
- Each account that is registered is automatically deleted if the user does not activate it after a certain amount of time. The time is configurable through `artemis.user-management.registrationcleanup-time-minutes`. The default is 60 minutes
- The registration is blocked if a user tries to re-register an account with the same email or login until the previous non-activated account is cleaned up by the system.

### Steps for Testing

This PR should be tested on TS2.

#### Check that the user is deactivated ####
1. Register a new user. 
2. Navigate to the User Management and check that the user has been created and is deactivated
3. Log into Gitlab with that user and check that the account is blocked.

#### Check that the activation email is sent again ####
4. Register a new user and use the same email and login used for the previous user. 
5. Check your email, you should have two activation mails. 
6. Click on the activation link of the oldest mail -> it should not work
7. Click on the activation link of the new mail -> it should work
6. Log into Artemis and Gitlab with that account and make sure it works.

#### Check that email/login are already in use ####
7. Re-register with the same email and make sure you get an error since it's already used
8. Re-register with the same login and make sure you get an error since it's already used

#### Test the automated cleanup of non-activated users ####
9. Delete the user(s) you used in the previous steps
10. Register a new user but do not activate it
11. Re-register again with the same email but different login -> the registration should be blocked for ca 2 mins
12. Re-register again with the same login but different email -> the registration should be blocked for ca 2 mins
12. If you try again in 2 minutes it should work because the previous non-activated user was deleted

### Test Coverage

GitLabUserManagementService.java 97%
UserService.java 84%
JenkinsUserManagementService.java 97%
UserScheduleService.java 91%
UserResource.java 93%
MainInstanceMessageSendService.java 100%
InstanceMessageReceiveService.java 78%
DistributedInstanceMessageSendService.java 11%

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabUserManagementService.java [hunk 1]
```diff
@@ -54,6 +54,33 @@ public void createVcsUser(User user) {
...
+    @Override
+    public boolean canCreateVcsUser(User user) {
+        try {
+            var gitlabUser = gitlabApi.getUserApi().getUser(user.getLogin());
+            if (gitlabUser != null) {
+                return false;
+            }
+
+            createVcsUser(user);
+            deleteVcsUser(user.getLogin());
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabUserManagementService.java:75]: To be honest I am not a big fan of such a logic, because something like this should be avoided in my opinion. Can we not find out differently if a user can be created?

In any case, I suggest to move the deleteVcsUser into the finally block.
then getUser would need to be in a separate try catch block

File: src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/JenkinsUserManagementService.java [hunk 2]
```diff
@@ -128,6 +128,28 @@ public void createUser(User user) throws ContinuousIntegrationException {
...
+     * attempts to create it. If the creation is successful, the
+     * Jenkins user is deleted and a boolean value is returned.
+     *
+     * @param user The user to check
+     * @return whether the user can be created in Jenkins or not
+     */
+    @Override
+    public boolean canCreateUser(User user) {
+        try {
+            createUser(user);
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/JenkinsUserManagementService.java:143]: To be honest I am not a big fan of such a logic, because something like this should be avoided in my opinion. Can we not find out differently if a user can be created?

In any case, I suggest to move the deleteVcsUser into the finally block.

File: src/main/java/de/tum/in/www1/artemis/service/user/UserService.java [hunk 3]
```diff
@@ -236,10 +240,26 @@ public User registerUser(UserDTO userDTO, String password) {
...
         // we need to save first so that the user can be found in the database in the subsequent method
-        optionalVcsUserManagementService.ifPresent(vcsUserManagementService -> vcsUserManagementService.createVcsUser(newUser));
-        optionalCIUserManagementService.ifPresent(ciUserManagementService -> ciUserManagementService.createUser(newUser));
+        saveUser(newUser);
+
+        optionalVcsUserManagementService.ifPresent(vcsUserManagementService -> {
+            if (!vcsUserManagementService.canCreateVcsUser(newUser)) {
+                // Delete the user that was previously saved and throw
+                deleteUser(newUser);
+                throw new VCSAccountExistsException();
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/service/user/UserService.java:251]: provide more details in the exception for better error handling (e.g. the username)

File: src/main/java/de/tum/in/www1/artemis/service/user/UserService.java [hunk 4]
```diff
@@ -236,10 +240,26 @@ public User registerUser(UserDTO userDTO, String password) {
...
+            }
+        });
+
+        optionalCIUserManagementService.ifPresent(ciUserManagementService -> {
+            if (!ciUserManagementService.canCreateUser(newUser)) {
+                // Delete the user that was previously saved and throw
+                deleteUser(newUser);
+                throw new CIAccountExistsException();
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/service/user/UserService.java:259]: provide more details in the exception for better error handling (e.g. the username)

File: src/main/java/de/tum/in/www1/artemis/service/user/UserService.java [hunk 5]
```diff
@@ -236,10 +240,26 @@ public User registerUser(UserDTO userDTO, String password) {
...
+
         // we need to save first so that the user can be found in the database in the subsequent method
-        optionalVcsUserManagementService.ifPresent(vcsUserManagementService -> vcsUserManagementService.createVcsUser(newUser));
-        optionalCIUserManagementService.ifPresent(ciUserManagementService -> ciUserManagementService.createUser(newUser));
+        saveUser(newUser);
+
+        optionalVcsUserManagementService.ifPresent(vcsUserManagementService -> {
+            if (!vcsUserManagementService.canCreateVcsUser(newUser)) {
+                // Delete the user that was previously saved and throw
+                deleteUser(newUser);
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/service/user/UserService.java:250]: are you sure there can be no edge cases here where you actually would delete an actual user here?
What happens if an administrator creates an account manually between the registration and activation of a user account?

File: src/main/java/de/tum/in/www1/artemis/service/user/UserService.java [hunk 6]
```diff
@@ -236,10 +240,26 @@ public User registerUser(UserDTO userDTO, String password) {
...
+                throw new VCSAccountExistsException();
+            }
+        });
+
+        optionalCIUserManagementService.ifPresent(ciUserManagementService -> {
+            if (!ciUserManagementService.canCreateUser(newUser)) {
+                // Delete the user that was previously saved and throw
+                deleteUser(newUser);
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/service/user/UserService.java:258]: are you sure there can be no edge cases here where you actually would delete an actual user here?
What happens if an administrator creates an account manually between the registration and activation of a user account?

**Review by krusche — CHANGES_REQUESTED** [review]
To be honest, the changes feel like a hack that can lead to very problematic edge cases. I would propose that we investigate different approaches here.

One alternative approach could be that the user accounts in VCS and CI are created but stay inactive upon registration (so that users cannot login). Artemis accounts always get created automatically but stay inactive.

In case the user does not confirm the email within a given timeframe (e.g. 1h, could be configurable), the accounts will be deleted again using a scheduling mechanism. This could then also delete the Artemis account itself.

An alternative to the scheduling could be to keep the inactive accounts until the next attempt (as it is done with the internal Artemis accounts), but I would prefer to clean up wrongly created accounts that have never been used.

In any way, we should also handle internal accounts for the second attempt in case they have not been delete (for what ever reason)

Can you please investigate (and discuss) if such an approach would be feasible?

**Comment by ivanchimeno** [comment]
@krusche You are correct, this does seem a bit as a hack. 

I looked into the GitLab API and it's possible to activate and deactivate accounts. I can therefore simply create the account and deactivate it when the user registers. When the user activates the account, I would then also activate the GitLab account.

Jenkins doesn't support account activation/deactivation. I think in this case the only way would be to just create the account?

File: src/main/java/de/tum/in/www1/artemis/service/user/UserService.java (hunk 5 above)
Comment (ivanchimeno) [reply src/main/java/de/tum/in/www1/artemis/service/user/UserService.java:250]: This just happens during registration so I think it's safe. The user is first created in Artemis. If a VCS/CI exists, it checks if the user can be created there too. If that's not the case, we cancel registration by removing that user from Artemis and return an error.

**Review by JohannesStoehr — APPROVED** [review]
Tested on TS2, Code looks fine as well!

**Review by SimonEntholzer — APPROVED** [review]
Checked the code, looks good. Also tested on TS2 in testing session, registering with my TUM account works fine, and everything else too.

**Review by lschlesinger — APPROVED** [review]
Tested on TS2. Registration worked fine!

**Review by imstreetspirit — DISMISSED** [review]
tested on ts2 during the session. everything works well..

**Review by tobiasjungmann — APPROVED** [review]
Tested on ts2 during the testing session. Everything worked as expected.

File: src/main/java/de/tum/in/www1/artemis/service/scheduled/UserScheduleService.java [hunk 7]
```diff
@@ -0,0 +1,124 @@
...
+import de.tum.in.www1.artemis.exception.VersionControlException;
+import de.tum.in.www1.artemis.repository.UserRepository;
+import de.tum.in.www1.artemis.service.connectors.VcsUserManagementService;
+
+@Service
+@Profile("scheduling")
+public class UserScheduleService {
+
+    @Value("${artemis.user-management.registration.cleanup-time-minutes}")
+    private Long removeNonActivatedUserDelayTime;
```
Comment (jpbernius) [inline src/main/java/de/tum/in/www1/artemis/service/scheduled/UserScheduleService.java:24]: Can this value be optional, so that Artemis will start without configuring this value?

Comment (ivanchimeno) [reply src/main/java/de/tum/in/www1/artemis/service/scheduled/UserScheduleService.java:24]: I could do that. I could also assign a default value of 60 minutes if it's not present?

Comment (jpbernius) [reply src/main/java/de/tum/in/www1/artemis/service/scheduled/UserScheduleService.java:24]: I like the default value idea.

**Review by jpbernius — APPROVED** [review]
