### PR TITLE
`Programming exercises`: Export and import build plan from file

### LINKED ISSUE #7606: `Programming exercise`: Missing build plan for exercise file export
### Describe the bug

Programming exercises in GitLab/Jenkins and GitLab/GitLab-CI can have a build plan that is stored in the Artemis database. This build plan is not exported as part of the ZIP file export for an exercise.

### To Reproduce

Gitlab/Jenkins setup:

1. Go to a programming exercise as instructor.
2. ‘Download Exercise’
3. Inspect the downloaded zip-file. It does not contain the build plan.

### Expected behavior

The build plan is exported in the zip as an additional text file.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.6.6

### What browsers are you seeing the problem on?

Firefox

### Additional context

When the export contains the build plan as text file, it would be nice if it then would also be used during import from file.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tobias-lippert**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

The build plan of a programming exercise is at the moment neither imported nor exported.
Closes #7606 

### Description

Export it now as a txt file and import it if the jenkins or gitlabci profile is active.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming Exercise with a build plan (on the jenkins setup)
- 1 TS with an Atlassian setup (e.g. ts1 legacy)
- 1 TS with a Gitlab/Jenkins setup (e.g. ts2 legacy)

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to the exercise details page of a (newly created) programming exercise (ideally create a new one because issues occurred with older existing exercises). 
4. Click on download exercise
5. Download the export
6. If you are on a jenkins/gitlab setup (e.g. legacy ts2) it should contain a file named buildPlan.txt.
  - If it is missing: Check if the ‘Edit Build Plan’ button on the exercise detail page shows one. Then it is working as intended. Please use another exercise that has a build plan to test the feature.
  - If it is there: The content should be equal to the one shown in the editor if you click on edit build plan.
7. If you are on an Atlassian setup, the export should still succeed but no buildPlan.txt should exist.
8.  Import the exercise by clicking import programming exercise, selecting from file and uploading the previously downloaded zip file. Try all the variants (gitlab-> gitlab, atlassian -> atlassian, gitlab -> atlassian, atlassian -> gitlab)
9. The build plan should be imported when importing gitlab -> gitlab. In all other cases, the import should just succeed.

#### Exam Mode Testing
The logic doesn't differ for exam exercises

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [BuildPlanRepository.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5755/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.repository/BuildPlanRepository.html) | 82% | ✅|
| [ProfileService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5755/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/ProfileService.html) | 100% | ✅|
| [ProgrammingExerciseExportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5755/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.export/ProgrammingExerciseExportService.html) | 86% | ✅ |
| [ProgrammingExerciseImportFromFileService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5755/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.programming/ProgrammingExerciseImportFromFileService.html) | 95% |✅  |

## Summary by CodeRabbit

- **New Features**
  - Introduced a method to identify active GitLab CI or Jenkins profiles.
  - Implemented build plan export and import functionalities for programming exercises.

- **Enhancements**
  - Optimized the process of querying build plans by programming exercise ID.

- **Tests**
  - Added and updated integration tests for programming exercise import and export with build plans.

- **Refactor**
  - Improved code organization with the use of wildcard imports.
  - Streamlined constructor dependencies for services handling programming exercises.

### CODE REVIEW

**Review by Strohgelaender — DISMISSED** [review]
code lgtm

**Comment by krusche** [comment]
Can you include the new Aeolus build config as well in case it is used?
@reschandreas

**Comment by reschandreas** [comment]
@krusche I tested it and since the whole entry in `programming_exercise_details` is exported it's already included. 

Somehow the import from file results in a completely empty form for me, can somebody confirm this?

File: src/main/java/de/tum/in/www1/artemis/service/export/ProgrammingExerciseExportService.java [hunk 1]
```diff
@@ -142,6 +147,15 @@ private Path exportProgrammingExerciseMaterialWithStudentReposOptional(Programmi
                     pathsToBeZipped.add(path);
                 }
             });
+
+            // Export the build plan of a programming exercise, if one exists. Only relevant for Gitlab/Jenkins or Gitlab/GitlabCI setups.
+            var buildPlan = buildPlanRepository.findByProgrammingExercises_IdWithProgrammingExercises(exercise.getId());
+            if (buildPlan.isPresent()) {
+                Path buildPlanPath = exportDir.orElseThrow().resolve(BUILD_PLAN_FILE_NAME);
+                FileUtils.writeStringToFile(buildPlanPath.toFile(), buildPlan.orElseThrow().getBuildPlan(), Charsets.UTF_8);
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/export/ProgrammingExerciseExportService.java:155]:
```suggestion
                FileUtils.writeStringToFile(buildPlanPath.toFile(), buildPlan.orElseThrow().getBuildPlan(), StandardCharsets.UTF_8);
```
The Java standard library variant should be used rather than the Google one.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java [hunk 2]
```diff
@@ -95,6 +115,25 @@ public ProgrammingExercise importProgrammingExerciseFromFile(ProgrammingExercise
...
+     * If the file cannot be read, the build plan is skipped
+     *
+     * @param programmingExercise the programming exercise for which the build plan should be imported
+     * @param importExerciseDir   the directory where the extracted zip file is located
+     */
+    private void importBuildPlanIfExisting(ProgrammingExercise programmingExercise, Path importExerciseDir) {
+        Path buildPlanPath = importExerciseDir.resolve(BUILD_PLAN_FILE_NAME);
+        if (Files.exists(buildPlanPath)) {
+            try {
+                buildPlanRepository.setBuildPlanForExercise(FileUtils.readFileToString(buildPlanPath.toFile(), Charsets.UTF_8), programmingExercise);
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java:129]:
```suggestion
                buildPlanRepository.setBuildPlanForExercise(FileUtils.readFileToString(buildPlanPath.toFile(), StandardCharsets.UTF_8), programmingExercise);
```

File: src/main/java/de/tum/in/www1/artemis/service/export/ProgrammingExerciseExportService.java [hunk 3]
```diff
@@ -142,6 +147,15 @@ private Path exportProgrammingExerciseMaterialWithStudentReposOptional(Programmi
                     pathsToBeZipped.add(path);
                 }
             });
+
+            // Export the build plan of a programming exercise, if one exists. Only relevant for Gitlab/Jenkins or Gitlab/GitlabCI setups.
+            var buildPlan = buildPlanRepository.findByProgrammingExercises_IdWithProgrammingExercises(exercise.getId());
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/export/ProgrammingExerciseExportService.java:152]:
```suggestion
            var buildPlan = buildPlanRepository.findByProgrammingExercises_Id(exercise.getId());
```
An additional query in the repository could avoid fetching data we do not need anyway.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java [hunk 4]
```diff
@@ -13,21 +15,28 @@
...
+import de.tum.in.www1.artemis.repository.BuildPlanRepository;
 import de.tum.in.www1.artemis.service.*;
 import de.tum.in.www1.artemis.service.connectors.GitService;
+import de.tum.in.www1.artemis.service.export.ProgrammingExerciseExportService;
 import de.tum.in.www1.artemis.web.rest.errors.BadRequestAlertException;
 
 @Service
 public class ProgrammingExerciseImportFromFileService {
 
+    private final Logger log = LoggerFactory.getLogger(ProgrammingExerciseExportService.class);
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java:38]:
```suggestion
    private final Logger log = LoggerFactory.getLogger(ProgrammingExerciseImportFromFileService.class);
```

File: src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseTestService.java [hunk 5]
```diff
@@ -1416,11 +1418,15 @@ void exportProgrammingExerciseInstructorMaterial_shouldReturnFile(boolean saveEm
...
-                    .anyMatch((filename) -> filename.toString().matches(EXPORTED_EXERCISE_DETAILS_FILE_PREFIX + ".*.json"));
+                    .anyMatch((filename) -> filename.toString().matches(EXPORTED_EXERCISE_DETAILS_FILE_PREFIX + ".*.json"))
+                    .anyMatch((filename) -> BUILD_PLAN_FILE_NAME.equals(filename.toString()));
             if (saveEmbeddedFiles) {
                 assertThat(listOfIncludedFiles).anyMatch((filename) -> filename.toString().equals(embeddedFileName1))
                         .anyMatch((filename) -> filename.toString().equals(embeddedFileName2));
             }
+            Path buildPlanPath = listOfIncludedFiles.stream().filter(file -> BUILD_PLAN_FILE_NAME.equals(file.getFileName().toString())).findFirst().orElseThrow();
+            String buildPlanContent = Files.readString(extractedZipDir.resolve(buildPlanPath), StandardCharsets.UTF_8);
+            assertThat(buildPlanContent).isEqualTo("my build plan");
```
Comment (b-fein) [inline src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseTestService.java:1429]: The method is called from both the `ProgrammingExerciseBitbucketBambooIntegrationTest` and its GitlabJenkins counterpart. Where does the distinction happen if the build plan should be there or not? I would expected the build plan file to be missing in the Bamboo case since that feature is not supported there.

**Review by b-fein — COMMENTED** [review]
Implementation looks to be pretty straightforward. Only two smaller suggestions and a question about the test.

---

I assumed _ready for review_ since no longer draft, but PR-label seems to be missing.

File: src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseTestService.java (hunk 5 above)
Comment (tobias-lippert) [reply src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseTestService.java:1429]: i adjusted the test now that it only adds a build plan to the exercise if it is a gitlab/jenkins setup. because initially I just always added it to the exercise ignoring the setup.

**Comment by tobias-lippert** [comment]
@reschandreas 

This is unrelated to this PR. I tested it with the branch  feature/communication/messaging-for-communication-only  on ts4 and it was broken as well. The browser console reveals that it happens because options concerning the continuous plagiarism control introduced in PR #7302 are undefined.
cc @jakubriegel

**Comment by jakubriegel** [comment]
CPC was indeed the issue. Here is a PR with fix: #7640

**Review by chrisknedl — DISMISSED** [review]
Code looks good to me, thanks for fixing this. I'll also test it tomorrow*

**Comment by chrisknedl** [comment]
Seems like I can't deploy something twice in a row. If the error is somehow regex related, maybe this comment fixes it.

File: src/main/java/de/tum/in/www1/artemis/repository/BuildPlanRepository.java [hunk 6]
```diff
@@ -23,6 +23,15 @@ public interface BuildPlanRepository extends JpaRepository<BuildPlan, Long> {
             """)
     Optional<BuildPlan> findByProgrammingExercises_IdWithProgrammingExercises(@Param("exerciseId") long exerciseId);
 
+    @Query("""
+
```
Comment (Strohgelaender) [inline src/main/java/de/tum/in/www1/artemis/repository/BuildPlanRepository.java:27]:
```suggestion
```

**Review by Strohgelaender — APPROVED** [review]
code lgtm

**Review by b-fein — APPROVED** [review]
Code looks good.

**Review by Predixx — CHANGES_REQUESTED** [review]
tested on ts2 and ts1 together with Vincent Clifford. No build plan on ts1, that worked. When I download on ts2 I get no build plan either, but teh import still works.

**Review by vinceclifford — CHANGES_REQUESTED** [review]
Tested on TS1 and TS2 together with Liam. When downloading an exercise on TS2 I don't receive a file named buildPlan.txt. Everything else works fine.

**Comment by chrisknedl** [comment]
It also worked for me, I only tested TS2 -> TS2 so far, but the download contained the build plan, and the imported exercise as well.

**Review by b-fein — CHANGES_REQUESTED** [review]
When exporting the exercise, a `buildPlan.txt` is part of the zip.
If I then manually edit the file and import the exercise, a default build plan is created rather than using the one from the zip file.

**Comment by chrisknedl** [comment]
Also the same problem for me. @b-fein

**Comment by tobias-lippert** [comment]
@b-fein @chrisknedl Thanks for testing. This should be fixed now and I've added a test for the import that checks that the correct build plan is used.

**Review by chrisknedl — APPROVED** [review]
Tested all cases, and code also looks good to me. Thanks again.

**Review by LenaKahle — COMMENTED** [review]
Tested on ts2, I tried different courses and exercises that were recently created, I did not get a .txt file in the downloaded zip file.

**Comment by tobias-lippert** [comment]
@LenaKahle Thanks for testing.
Could you share one of the exercises pls, so I can have a look at it?

**Review by reschandreas — APPROVED** [review]
tested locally, works as expected with GitLab and Atlassian setup

**Review by konrad2002 — APPROVED** [review]
tested with newly created exercises on ts2 (gitlab+jenkins) and ts1; all combinations of imports and exports worked as expected
