### PR TITLE
`Development`: Migrate practice and preview quiz submissions to data transfer objects

### LINKED ISSUE #11658: Quiz preview does not display score
### Describe the bug

When an instructor previews a quiz and clicks on `Submit`, a message is displayed on the screen, stating that the submission was successfull, and that the results will soon appear. However, no results will become visible.

The Client receives a Result from the server and attempts to resolve
`Result` -> `Submission` -> `Participation` -> `QuizExercise`
however, because preview submissions don't contain a participation, the resolution fails.

### To Reproduce

1. Go to course administration
2. Select `Preview` for any quiz exercise
3. Answer the questions and click `Submit`
4. No results will be displayed

### Expected behavior

The correct results should be displayed.

### Screenshots

Image

Image

### Which version of Artemis are you seeing the problem on?

8.5.1

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by KonstiAnon**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
Currently for submitting preview and practice submissions domain objects are being used. In alignment with the goal of switching to more robust data transfer, this PR migrates the `submitForPractice` and `submitForPreview` endpoints to DTOs.

This PR also fixes #11658, by ensuring that for preview submissions, the score gets displayed correctly.

### Description
I introduced several new DTOs, for the Client -> Server & Server -> Client communication. These DTOs only contain essential data and make use of validations, to ensure that data received by the server is in the correct format and no important fields are omitted.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Quiz Exercise

1. Log in to Artemis
2. Navigate to Course Administration
3. Select `Preview` for the Quiz Exercise
4. Enter your answers and submit the quiz
5. Ensure that the correct score is displayed
6. Navigate back to Course Administration
7. Open the quiz for practice mode (can be done after the due date has passed)
8. Enter the practice mode for the quiz
9. Perform a practice submission
10. Ensure the correct score is displayed

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

* **New Features**
  * New DTO format for student quiz submissions with client-side serializer and converters.
  * Submission endpoints now return combined evaluation + submission details.

* **Bug Fixes**
  * Improved null-safety for lazy/uninitialized quiz associations to avoid runtime errors.
  * Validation now rejects missing or duplicate submitted answers with clear errors.

* **Refactor**
  * Centralized flow: client DTOs are converted into internal submissions before processing.

* **Tests**
  * Integration tests updated to exercise the DTO-based submission flow and error cases.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/main/java/de/tum/cit/aet/artemis/quiz/dto/submission/QuizSubmissionAfterEvaluationDTO.java [hunk 1]
```diff
@@ -16,11 +18,27 @@
...
+     * @return a DTO containing the evaluated submission data
+     */
     public static QuizSubmissionAfterEvaluationDTO of(QuizSubmission submission) {
+        List<ResultAfterEvaluationDTO> results = null;
+        Set<SubmittedAnswerAfterEvaluationDTO> submittedAnswers = Set.of();
+        if (Hibernate.isInitialized(submission.getResults()) && submission.getResults() != null) {
+            results = submission.getResults().stream().map(ResultAfterEvaluationDTO::of).toList();
+        }
+        if (Hibernate.isInitialized(submission.getSubmittedAnswers()) && submission.getSubmittedAnswers() != null) {
+            submittedAnswers = submission.getSubmittedAnswers().stream().map(SubmittedAnswerAfterEvaluationDTO::of).collect(Collectors.toSet());
```
Comment (SamuelRoettgermann) [inline src/main/java/de/tum/cit/aet/artemis/quiz/dto/submission/QuizSubmissionAfterEvaluationDTO.java]: It works this way around, but I would prefer:
```
if (xyz != null && Hibernate.isInitialized(xyz))
```

File: src/main/java/de/tum/cit/aet/artemis/quiz/service/QuizSubmissionService.java [hunk 2]
```diff
@@ -395,4 +418,177 @@ protected QuizSubmission save(QuizExercise quizExercise, QuizSubmission quizSubm
...
+                else {
+                    throw new EntityNotFoundException("DragItem with id " + mapping.dragItemId() + " or DropLocation with id " + mapping.dropLocationId()
+                            + " not found in DragAndDropQuestion with id " + dragAndDropQuestion.getId());
+                }
+            }
+            dragAndDropSubmittedAnswer.setMappings(mappings);
+            return dragAndDropSubmittedAnswer;
+        }
+        else {
+            throw new BadRequestException("QuizQuestion with id " + submittedAnswer.questionId() + " is not a DragAndDropQuestion");
```
Comment (SamuelRoettgermann) [inline src/main/java/de/tum/cit/aet/artemis/quiz/service/QuizSubmissionService.java]: Are you sure this shouldn't be a `BadRequestAlertException`?
