### PR TITLE
`General`: Fix an issue with course deletion summary entries

### LINKED ISSUE #9722: `General`: Course confirm delete operation does not display the correct numbers
### Describe the bug

The numbers of lectures, exercises, exams and posts do not match.

### To Reproduce

1. Go to a course with lectures, exercises, exams and posts
2. Delete the course
3. See the dialog with the `Confirm delete operation`
4. See that the displayed numbers are not correct

### Expected behavior

The dialog should display the proper numbers.

### Screenshots

image

image

### Which version of Artemis are you seeing the problem on?

7.7.0

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ole-ve**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.

### Motivation and Context
Fixes #9722. On the course DTO, there are some fields that have no assigned values on the course management page.
These changes load the required values from the server.

### Steps for Testing
Create a course with exercises for each type, lectures, and exams. Verify that all of these values are correct.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
	- Enhanced course deletion summary with more detailed metrics
	- Added counts for various exercise types, exams, and lectures
	- Improved tracking of course-related content during deletion process

- **Technical Improvements**
	- Updated data transfer objects and repositories to support more comprehensive course information
	- Added new query methods to retrieve detailed course statistics

The changes provide a more comprehensive overview of course content before deletion, giving users more insight into the course's components.

### CODE REVIEW

**Review by BBesrour — DISMISSED** [review]
tested on TS3, lgtm

**Review by coolchock — DISMISSED** [review]
tested on ts3, all counts are displayed correctly

**Review by AjayvirS — APPROVED** [review]
Tested locally and shows the correct summary

File: src/main/java/de/tum/cit/aet/artemis/exercise/dto/ExerciseTypeCount.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
+package de.tum.cit.aet.artemis.exercise.dto;
+
+import java.util.Objects;
+
+import de.tum.cit.aet.artemis.exercise.domain.Exercise;
+import de.tum.cit.aet.artemis.exercise.domain.ExerciseType;
+
+public class ExerciseTypeCount {
```
Comment (krusche) [inline src/main/java/de/tum/cit/aet/artemis/exercise/dto/ExerciseTypeCount.java:8]: please use a record here

File: src/main/java/de/tum/cit/aet/artemis/communication/repository/PostRepository.java [hunk 2]
```diff
@@ -48,7 +48,13 @@ default Post findPostOrMessagePostByIdElseThrow(Long postId) throws EntityNotFou
 
     List<Post> findAllByConversationId(Long conversationId);
 
-    List<Post> findAllByCourseId(Long courseId);
+    @Query("""
+            SELECT p
+            FROM Post p
+            LEFT JOIN p.conversation conversation
```
Comment (krusche) [inline src/main/java/de/tum/cit/aet/artemis/communication/repository/PostRepository.java:54]: left joins should be indented

File: src/main/java/de/tum/cit/aet/artemis/exercise/repository/ExerciseRepository.java [hunk 3]
```diff
@@ -627,4 +628,21 @@ SELECT count(e) > 0
...
+     *
+     * @param courseId the courseId to get the exerciseType->count mapping for
+     * @return a list of mappings from exercise type to count
+     */
+    @Query("""
+            SELECT new de.tum.cit.aet.artemis.exercise.dto.ExerciseTypeCount(TYPE(e), COUNT(e))
+            FROM Course c
+                JOIN c.exercises e
+            WHERE c.id = :courseId
+            AND TYPE(e) IN (ModelingExercise, TextExercise, ProgrammingExercise, QuizExercise, FileUploadExercise)
```
Comment (krusche) [inline src/main/java/de/tum/cit/aet/artemis/exercise/repository/ExerciseRepository.java:644]: AND should be indented

**Review by krusche — CHANGES_REQUESTED** [review]
please address my inline feedback

**Review by SimonEntholzer — DISMISSED** [review]
Works on Ts3 :+1:

**Review by coolchock — APPROVED** [review]
re-approve, tested during testing session on ts3

**Review by muradium — APPROVED** [review]
Tested on TS3, values show correctly now

**Review by SimonEntholzer — APPROVED** [review]
reapprove after renaming DAO to DTO

**Review by coolchock — APPROVED** [review]
re-approve after renaming DAO to DTO

**Review by krusche — APPROVED** [review]
