### PR TITLE
`Exam mode`: Fix missing tutor comments in the second correction round

### LINKED ISSUE #5030: `Exam Mode`: Not all annoations are shown in the editor (programming tasks)
### Describe the bug

After our exams of the last term, we have recognized some missing annotations that are present in the REST Response and also visible in the List of all Annotations. Nevertheless, inline the annotation is not visible.

I'll mark it as prio high (feel free to change that) as it effects the assessment of tasks directly.

### To Reproduce

Unknown. I can provide further details in Slack. But no error is shown in the logs of the client.

### Expected behavior

Annotations shall appear inline.

### Screenshots

REST Response
image

Editor Excerpt:
image

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Dominik-Weinzierl**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).

### Motivation and Context

Closes #5030: Missing annotations of second exam correction round.

### Description

Thanks to @Shirkanesi and @dfuchss: The results of the second round of corrections are not part of the first result, so we need to look at the last result.

### Steps for Testing

Prerequisites:
- 1 Instructor + Tutor
- 1 Students
- 1 Programming Exercise
- 1 Exam with second correction round enabled

1. Log in to Artemis
2. Create an Exam with a Programming Exercise
3. Assess the submission in both correction rounds
4. Verify that the tutor/instructor sees the correct comments for the the current correction round

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Comment by Shirkanesi** [comment]
Maybe someone who knows more about the server-code can confirm tha last result will alwas be the newest?

**Comment by dfuchss** [comment]
At least, we assume this as well :D 

https://github.com/kit-sdq/programming-lecture-eclipse-artemis/blob/cc8f27bffc2851112e84207242068af8aab8b9eb/bundles/edu.kit.kastel.sdq.eclipse.common.client/src/edu/kit/kastel/sdq/eclipse/common/client/mappings/lock/LockResult.java#L30-L32

**Comment by Dominik-Weinzierl** [comment]
Tested it on the TS2 (gitlab + jenkins) and it seems to work - the student was able to see the details of both corrections rounds (but i also checked the develop branch and received the same details :thinking:). But as you said we need to check if this is always the case :)

**Comment by dfuchss** [comment]
Did you've checked whether deletion & additions & modification work?

**Comment by Dominik-Weinzierl** [comment]
I tested the addition of additional comments, but these comments were not linked to a specific grading instruction or line of code. I am not sure how to link a feedback to a specific line of code (as shown in your issue) since i am not really familiar with this specific assessment process, unfortunately. Maybe another developer or tutor can assist you on these specific tests.

**Review by jbllhff — COMMENTED** [review]
Hi, I tested on ts2. My test student was not able to see neither the feedback of assessing round 1 nor 2. It was not displayed in the exam and the button "Review is now open" did not work. I am new to exam mode, maybe there is another way.

**Comment by jbllhff** [comment]
One additional comment: When I tried to start the exam, the checkbox for confirming the exam terms was displayed only as a small line. This is probably not of your concern but I considered it worth mentioning.

**Comment by Dominik-Weinzierl** [comment]
You checked the correct page and the configuration of the exam is also correct? 
In your case: `TS2/courses/[course-id]/exams/[exam-id]` as student who participated

**Comment by dfuchss** [comment]
> I tested the addition of additional comments, but these comments were not linked to a specific grading instruction or line of code. I am not sure how to link a (programming exercise) feedback to a specific line of code (as shown in your issue) since i am not really familiar with this specific assessment process, unfortunately. Maybe another developer or tutor can assist you on these specific tests.

image

You can click on the left side of the editor to get a "+"

**Comment by dfuchss** [comment]
Yes I agree, assessments of round 1 of a student submission shall not be modified if the second round (for the student) has been started or exists :)

**Comment by Shirkanesi** [comment]
> @dfuchss @Shirkanesi instead of filtering the results on the client side, we could just send only the required result 🤔

Would be a posibility, however I do like the fact of the API reporting both results (as this could be used for other applications).
Looking at the request, there is a GET-Parameter `correction-round`, maybe the filtering could be applied if this is set and both will be returned, if not set 🤔

**Comment by Dominik-Weinzierl** [comment]
Yes you are right. So the additional checks aren't needed since the result should always be available :+1: I test this again on a test server and verify that everything works as expected

**Review by Shirkanesi — CHANGES_REQUESTED** [review]

File: src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingSubmissionResource.java [hunk 1]
```diff
@@ -399,7 +399,7 @@ public ResponseEntity<ProgrammingSubmission> lockAndGetProgrammingSubmission(@Pa
         // prepare programming submission for response
         programmingSubmissionService.hideDetails(programmingSubmission, user);
         // remove automatic results before sending to client
-        programmingSubmission.setResults(programmingSubmission.getManualResults());
+        programmingSubmission.setResults(List.of(programmingSubmission.getManualResults().get(correctionRound)));
```
[the remark this answers is not in the document]
Comment (Dominik-Weinzierl) [reply src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingSubmissionResource.java]: Usually this shouldn't happen but yes you are right, a check is always useful :D Re-added the check

**Review by Shirkanesi — APPROVED** [review]

File: src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingSubmissionResource.java [hunk 2]
```diff
@@ -399,7 +399,12 @@ public ResponseEntity<ProgrammingSubmission> lockAndGetProgrammingSubmission(@Pa
         // prepare programming submission for response
         programmingSubmissionService.hideDetails(programmingSubmission, user);
         // remove automatic results before sending to client
-        programmingSubmission.setResults(programmingSubmission.getManualResults());
+        if (correctionRound >= programmingSubmission.getManualResults().size()) {
+            programmingSubmission.setResults(List.of());
+        }
+        else {
+            programmingSubmission.setResults(List.of(programmingSubmission.getManualResults().get(correctionRound)));
+        }
```
Comment (Strohgelaender) [inline src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingSubmissionResource.java:407]: Maybe that's just personal preference, but I like to use these methods in such cases to signal the clear intention. With List.of() someone else could just add other elements to this list.
```suggestion
        if (correctionRound >= programmingSubmission.getManualResults().size()) {
            programmingSubmission.setResults(Collections.emptyList());
        }
        else {
            programmingSubmission.setResults(Collections.singletonList(programmingSubmission.getManualResults().get(correctionRound)));
        }
```

Comment (Dominik-Weinzierl) [reply src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingSubmissionResource.java:407]: Yes, sounds reasonable :+1: thank you Lucas

**Review by dfuchss — APPROVED** [review]
Code LGTM 👍

File: src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingSubmissionResource.java [hunk 3]
```diff
@@ -399,7 +396,12 @@ public ResponseEntity<ProgrammingSubmission> lockAndGetProgrammingSubmission(@Pa
         // prepare programming submission for response
         programmingSubmissionService.hideDetails(programmingSubmission, user);
         // remove automatic results before sending to client
-        programmingSubmission.setResults(programmingSubmission.getManualResults());
+        if (correctionRound >= programmingSubmission.getManualResults().size()) {
```
Comment (dfuchss) [inline src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingSubmissionResource.java:399]: You could think about using the getter once instead of multiple times

**Review by Shirkanesi — APPROVED** [review]

File: src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingSubmissionResource.java (hunk 3 above)
Comment (Dominik-Weinzierl) [reply src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingSubmissionResource.java:399]: I think since we are only calling this getter twice, we can leave it as is. But yes, if we need to call it often in the future, we should extract it to a variable :+1:

Comment (dfuchss) [reply src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingSubmissionResource.java:399]: It's not only about performance :)
I never expect a getter to return the same result in a program with multiple threads.

(Nevertheless, in most cases they will return the same value :) )

**Review by dfuchss — APPROVED** [review]

**Review by SimonPaul02 — APPROVED** [review]
Reviewed code together with @yuling-sun , looks good to us! Even better would be if you changed "var" to a type in our opinion.

**Review by yuling-sun — COMMENTED** [review]
Tested on TS2 together with @SimonPaul02. Worked as expected for 2 instructors. We couldn't find a way to correct an exam as a tutor even though we are registered for the course.

**Review by rhubinger — APPROVED** [review]
Tested on TS2. Worked like described. Was also able to correct the exam as a tutor.

**Comment by dfuchss** [comment]
@Dominik-Weinzierl I would suggest to mark it as ready for merge soon :)
