### PR TITLE
`Programming exercises`: Fix result processing for ocaml exercises

### LINKED ISSUE #8298: `Programming Exercises`: solution repository is not cloned (even with "Check out repository of sample solution" enabled)
### Describe the bug

When building and testing programming exercises, the LocalCI does not clone the solution repository, even though "Check out repository of sample solution" was checked during exercise creation.

### To Reproduce

1. Create new programming exercise
2. During exercise creation:
  - Enable "Check out repository of sample solution"
  - Select OCaml as programming language
3. To show that the repository is not being cloned:
  - Enable "Customize Build Plan"
  - add a call to `find` to the build script (prints all paths, ignoring `.git` folders):
    ```diff
     build_and_test_the_code () {
       echo '⚙️ executing build_and_test_the_code'
    +  find -name .git -prune -o -print
       cd "tests"
       # the build process is specified in `run.sh` in the test repository
       chmod +x run.sh
       ./run.sh -s
     
     }
    ```
4. Run the template or solution, download the build log, and see that the `find` call only prints paths in `assignment/` and `tests/`

### Expected behavior

Solution repository is cloned.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.9.5

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

The API (https://artemis.cit.tum.de/api/programming-exercises/XXXX/) tells us that `checkoutSolutionRepository` is `false`...

### Relevant log output

```shell
2024-04-02T23:20:59.782715315+02:00[Europe/Berlin]	⚙️ executing build_and_test_the_code
2024-04-02T23:20:59.784297720+02:00[Europe/Berlin]	.
./assignment
./assignment/src
./assignment/src/dune
./assignment/src/assignment.mli
./assignment/src/assignment.ml
./assignment/.ocamlformat
./assignment/.gitattributes
./assignment/.gitignore
./tests
./tests/overrides
./tests/overrides/dune
./tests/overrides/overrides.ml
./tests/assignment
./tests/assignment/dune
./tests/assignment/assignment.mli
./tests/.ocamlformat
./tests/.gitattributes
./tests/solution
./tests/solution/dune
./tests/solution/solution.mli
./tests/test
./tests/test/test.ml
./tests/test/dune
./tests/run.sh
./tests/.gitignore
./tests/checker
./tests/checker/dune
./tests/checker/checker.ml
```

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context
Closes #8298

### Description
This PR enables the "checkout solution repository" per default for ocaml exercises and places the option into the correct subsection.

We also add support for the legacy JUnit report format which is still in use for OCAML exercises.

### Steps for Testing
1. Create a new OCAML programming exercise
2. check that "checkout solution repository" is active by default during exercise creation
3. check that results get created and that the feedback text is readable.

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
test added

### CODE REVIEW

File: src/main/webapp/app/exercises/programming/manage/update/programming-exercise-update.component.ts [hunk 1]
```diff
@@ -276,8 +276,13 @@ export class ProgrammingExerciseUpdateComponent implements AfterViewInit, OnDest
             this.programmingExercise.maxStaticCodeAnalysisPenalty = undefined;
         }
 
-        // Automatically enable the checkout of the solution repository for Haskell exercises
-        this.programmingExercise.checkoutSolutionRepository = this.checkoutSolutionRepositoryAllowed && language === ProgrammingLanguage.HASKELL;
+        if (language == ProgrammingLanguage.HASKELL) {
+            // Automatically enable the checkout of the solution repository for Haskell exercises
+            this.programmingExercise.checkoutSolutionRepository = this.checkoutSolutionRepositoryAllowed;
+        }
```
Comment (Strohgelaender) [inline src/main/webapp/app/exercises/programming/manage/update/programming-exercise-update.component.ts:282]: Question to the OCAML-Instructors (@just-max and @jerhard):
Do you always need the solution repository for OCAML exercises? Would it make sense to also activate this option per default for OCAML?

Comment (just-max) [reply src/main/webapp/app/exercises/programming/manage/update/programming-exercise-update.component.ts:282]: Yes, the OCaml exercise template and all the exercises we use always need the solution checkout. Activating by default would make sense :+1:

**Review by pzdr7 — APPROVED** [review]
Tested on TS3.

- Checking out the solution repo was enabled by default ✅ 
- I can view the results for the solution and template repositories. ✅ 

grafik

(The solution repo had some hidden test failures. Is that unrelated?)

**Review by pzdr7 — DISMISSED** [review]
Reapprove

**Review by pzdr7 — APPROVED** [review]

**Review by mateusmm01 — DISMISSED** [review]
Code looks good ! Also tested on ts6 and works as expected. Feedback text is shown and box is ticked as default

**Review by pzdr7 — APPROVED** [review]

File: src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobExecutionService.java [hunk 2]
```diff
@@ -398,14 +397,18 @@ private void processTestCaseNode(XMLStreamReader xmlStreamReader, List<LocalCIBu
         // Check if there is a failure node inside the testcase node.
         // Call next() until there is an end element (no failure node exists inside the testcase node) or a start element (failure node exists inside the
         // testcase node).
-        xmlStreamReader.next();
-        while (!(xmlStreamReader.isEndElement() || xmlStreamReader.isStartElement())) {
+        do {
             xmlStreamReader.next();
         }
+        while (!(xmlStreamReader.isEndElement() || xmlStreamReader.isStartElement()));
         if (xmlStreamReader.isStartElement() && "failure".equals(xmlStreamReader.getLocalName())) {
```
Comment (just-max) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobExecutionService.java:404]: Tests can also fail with `error` nodes whose text should be extracted, see https://github.com/testmoapp/junitxml/blob/main/examples%2Fjunit-complete.xml#L109. Is this covered anywhere?

File: src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobExecutionService.java [hunk 3]
```diff
@@ -416,6 +419,34 @@ else if (!"skipped".equals(xmlStreamReader.getLocalName())) {
         }
     }
 
+    private String readTestMessageFromLegacyReport(XMLStreamReader xmlStreamReader) throws XMLStreamException {
+        // JUnit legacy report format:
+        // The old report format does not use the message attribute, but instead has the error message as a child element
```
Comment (just-max) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobExecutionService.java:424]: I'm not sure what makes this the "legacy" format, is there any indication that tools (JUnit itself or third-party) don't produce this output anymore?

Is there any documentation or reference implementation that Artemis tries to follow? E.g. https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd ?

File: src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobExecutionService.java [hunk 4]
```diff
@@ -398,14 +397,18 @@ private void processTestCaseNode(XMLStreamReader xmlStreamReader, List<LocalCIBu
...
-        while (!(xmlStreamReader.isEndElement() || xmlStreamReader.isStartElement())) {
+        do {
             xmlStreamReader.next();
         }
+        while (!(xmlStreamReader.isEndElement() || xmlStreamReader.isStartElement()));
         if (xmlStreamReader.isStartElement() && "failure".equals(xmlStreamReader.getLocalName())) {
             // Extract the message attribute from the "failure" node.
             String error = xmlStreamReader.getAttributeValue(null, "message");
 
+            if (error == null && xmlStreamReader.hasNext()) {
```
Comment (just-max) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobExecutionService.java:408]: Failures and errors can contain both the message attribute and inner text, which should be combined (probably with a newline)

**Review by just-max — COMMENTED** [review]
See comments, looks almost correct.

File: src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobExecutionService.java (hunk 4 above)
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobExecutionService.java:408]: I'll have another look at the format in detail and will fix that in a followup.

**Review by MaximilianAnzinger — APPROVED** [review]
Code LGTM

File: src/main/webapp/app/exercises/programming/manage/update/programming-exercise-update.component.ts [hunk 5]
```diff
@@ -276,8 +276,13 @@ export class ProgrammingExerciseUpdateComponent implements AfterViewInit, OnDest
...
 
-        // Automatically enable the checkout of the solution repository for Haskell exercises
-        this.programmingExercise.checkoutSolutionRepository = this.checkoutSolutionRepositoryAllowed && language === ProgrammingLanguage.HASKELL;
+        if (language == ProgrammingLanguage.HASKELL || language == ProgrammingLanguage.OCAML) {
+            // Instructors typically test against the example solution for Haskell and OCAML exercises, activate this option per default.
+            this.programmingExercise.checkoutSolutionRepository = this.checkoutSolutionRepositoryAllowed;
+        }
+        if (!this.checkoutSolutionRepositoryAllowed) {
+            this.programmingExercise.checkoutSolutionRepository = false;
+        }
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/programming/manage/update/programming-exercise-update.component.ts:285]: I think what confuses me the most is that you wrote "activate this option per default" and then set the value. Technically, the value can only be true at this point, but that only becomes clear once you dig deeper.
I assume, you do it as a failsafe in case the value changes in the future? I'd recommend then, making this clear in the comment.

File: src/main/webapp/app/exercises/programming/manage/update/update-components/programming-exercise-language.component.html [hunk 6]
```diff
@@ -172,6 +172,23 @@
             <jhi-help-icon placement="auto" text="artemisApp.programmingExercise.recordTestwiseCoverageTooltip" />
         </div>
     }
+    <!-- Setting whether the solution repository should be checked out is only supported for OCAML and Haskell exercises and is only available for new exercises -->
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/programming/manage/update/update-components/programming-exercise-language.component.html:175]:
```suggestion
```
I think we can remove this. The selection functionality here is independent of that and in the section setting the flag, it's mentioned.

File: src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobExecutionService.java (hunk 3 above)
Comment (julian-christl) [reply src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobExecutionService.java:430]: I would be interested in some kind of reference/link in the comment too. In order for other developers to be able to look it up.

File: src/main/webapp/app/exercises/programming/manage/update/programming-exercise-update.component.ts (hunk 5 above)
Comment (Strohgelaender) [reply src/main/webapp/app/exercises/programming/manage/update/programming-exercise-update.component.ts:285]: > I assume, you do it as a failsafe in case the value changes in the future?

Yes. As of right now, OCAML is only supported by LocalCI and it also supports checking out the solution repository. But there might me a case in the future where GitLab has a OCAML template, but does not allow checking out the solution repository.

File: src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobExecutionService.java (hunk 3 above)
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobExecutionService.java:430]: I name it legacy since I remembered reading about a report format change in the JUnit change logs at some point.

Looking it up now, I was thinking of Release 5.9.0: https://junit.org/junit5/docs/5.9.0/release-notes/

> XML reports in new [Open Test Reporting](https://github.com/ota4j-team/open-test-reporting) format

However, this format is not active by default and we actually need to add support for this in the future.

File: src/main/webapp/app/exercises/programming/manage/update/programming-exercise-update.component.ts [hunk 7]
```diff
@@ -276,8 +276,14 @@ export class ProgrammingExerciseUpdateComponent implements AfterViewInit, OnDest
             this.programmingExercise.maxStaticCodeAnalysisPenalty = undefined;
         }
 
-        // Automatically enable the checkout of the solution repository for Haskell exercises
-        this.programmingExercise.checkoutSolutionRepository = this.checkoutSolutionRepositoryAllowed && language === ProgrammingLanguage.HASKELL;
+        if (language == ProgrammingLanguage.HASKELL || language == ProgrammingLanguage.OCAML) {
+            // Instructors typically test against the example solution for Haskell and OCAML exercises.
+            // If supported, activate this option per default.
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/programming/manage/update/programming-exercise-update.component.ts:281]:
```suggestion
            // If supported by the current CI configuration, this line activates the option per default.
```

**Review by MaximilianAnzinger — APPROVED** [review]
Code

**Review by mateusmm01 — APPROVED** [review]
aprove changes
