### PR TITLE
`General`: Fix counting of participating students in exercise

### LINKED ISSUE #11517: Participation rate wrongly calculated
### Describe the bug

The participation rate of an exercise seems to consider the instructors for the participation amount, but not the overall. For an example, see section 'screenshots'.

### To Reproduce

1. Go to a course that has at least one instructor and two students
2. Create an exercise (I noticed it on a modeling exercise, but this should be independent)
3. Participate in the exercise with one student and one instructor account.
4. See error on exercise overview in instructor view: '2 of 2 participated' (instead of _1 of 2_ (better) or _2of 3_)

### Expected behavior

I expect the participation rate to either
1. Do not count instructors as participants and exclude them from the '100%'.
2. Count instructor participations to 

I consider 1. the better solution, as instructors will usually not participate and are not relevant to the statistics if you, e.g., want to see if everyone participated in an exercise.

### Screenshots

**27** of 27 participated
Image

But the first **two of the participants are instructors**, while only 25 students participated.
(would expect to see 25 of 27)
Image

### Which version of Artemis are you seeing the problem on?

8.4.3

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by vivienxr**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

This PR fixes #11517.

### Description

The method getStudentParticipationCountById() in the ExerciseRepository now only counts participants of an exercise who have the role of a student. This method is called by two methods in two services (setStudentsAndParticipationsAmountForStatisticsDTO() in ExerciseService.java and ExerciseManagementStatisticsDTO() in StatisticsService.java) which both require the number of student participants instead of the number of all participants. 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exercise of any type

1. Log in to Artemis.
2. Let the instructor and 1 students start the exercise.
3. Check the exercise overview in instructor view.
4. It is supposed to show 1 out of 2.

Also check this for exercises inside an exam.

### Testserver States
No testserver tests done yet.

#### Performance Review

- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
#### Manual Tests
- [x] Test 1

### Test Coverage

No tests added since its only the change effectively consists of one line. 

### Screenshots

See screenshot of the issue. 

## Summary by CodeRabbit

* **Bug Fixes**
  * Participation statistics now only count students who are members of the course student group, preventing inflated numbers from non-enrolled users across course and exam exercises.

* **Tests**
  * Added integration tests for course and exam exercises to verify participation counts exclude individuals not in the course student group, ensuring statistics remain accurate and reliable.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by florian-glombik — COMMENTED** [review]
Some things that I noticed:
- The PR title does not follow the conventions yet https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests
- I don't think you need the check `- [ ] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.` for this PR as you directly edited the query
- Can you link the respective issue with a keyword? https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword? The issue will then be closed automatically
- I think the method name could be better chosen, e.g. `countStudentParticipationsByExerciseId` or `getStudentParticipationCountByExerciseId` - but not 100% sure if it interferes with JPA
- Can we add a small test for it? I think you can add another test in `StatisticsIntegrationTest` that checks this value

File: src/main/java/de/tum/cit/aet/artemis/core/repository/UserRepository.java [hunk 1]
```diff
@@ -1070,6 +1070,18 @@ default Long countUserInGroup(String groupName) {
         return countByDeletedIsFalseAndGroupsContains(groupName);
     }
 
+    @Query(value = """
+            SELECT COUNT(DISTINCT u.id)
+            FROM User u
+                JOIN Course c ON c.id = :courseId
```
Comment (krusche) [inline src/main/java/de/tum/cit/aet/artemis/core/repository/UserRepository.java]: can you check if this would lead to performance issues on production systems with 50k users and 2k courses?

**Comment by vivienxr** [comment]
> Tested on TS6. The general count appears to work, but there is one edge case I wanted to confirm before approving:
> 
> If an instructor also has the student role (so technically participates twice in the course), his participations are also counted. Is this intentional? If yes, I can approve, otherwise, we might need to adapt the db query

Thanks for the feedback. As agreed in our direct chat, I won’t incorporate it because the groups are defined specifically per course. So, if someone belongs to multiple group roles (e.g., student and something else), then it should generally be the case that this is intended.
Trying to incorporate the feedback to cover the theoretically possible but not realistic edge case (someone belonging to the student group of a specific course without being a student in that course) has shown that the performance impact would not be proportionate.

File: src/main/java/de/tum/cit/aet/artemis/core/repository/UserRepository.java [hunk 2]
```diff
@@ -1070,6 +1070,18 @@ default Long countUserInGroup(String groupName) {
...
+            WHERE u.deleted = FALSE
+                AND c.studentGroupName MEMBER OF u.groups
+                AND c.instructorGroupName NOT MEMBER OF u.groups
+                AND c.teachingAssistantGroupName NOT MEMBER OF u.groups
+                AND c.editorGroupName NOT MEMBER OF u.groups
+                """)
+    Long countOnlyStudents(long courseId);
```
[the remark this answers is not in the document]
Comment (vivienxr) [reply src/main/java/de/tum/cit/aet/artemis/core/repository/UserRepository.java]: This part of code is no longer part of the PR.

File: src/main/java/de/tum/cit/aet/artemis/core/repository/UserRepository.java (hunk 1 above)
Comment (vivienxr) [reply src/main/java/de/tum/cit/aet/artemis/core/repository/UserRepository.java]: This code is no longer part of the PR due to deciding to not incorporate the feedback anymore. More details are in the comment below.

File: src/main/java/de/tum/cit/aet/artemis/exercise/repository/ExerciseRepository.java [hunk 3]
```diff
@@ -462,13 +462,13 @@ AND TYPE(e) <> de.tum.cit.aet.artemis.quiz.domain.QuizExercise
...
      * @param exerciseId the id of the exercise to get the amount for
-     * @return The number of participations as <code>Long</code>
+     * @return The number of student participations as <code>Long</code>
      */
     @Query("""
             SELECT COUNT(DISTINCT p.student.id)
             FROM Exercise e
                 JOIN e.studentParticipations p
-            WHERE e.id = :exerciseId
+            WHERE e.id = :exerciseId AND e.course.studentGroupName MEMBER OF p.student.groups
```
Comment (florian-glombik) [inline src/main/java/de/tum/cit/aet/artemis/exercise/repository/ExerciseRepository.java]: I am not sure if `MEMBER OF` is a good approach in this context or whether we should do it like the suggestion below, which I think should be better performance wise as `MEMBER OF` might evaluate to a for each loop?

```suggestion
            FROM Exercise e
                JOIN e.studentParticipations p
                JOIN p.student.groups g
            WHERE e.id = :exerciseId
                 AND g = e.course.studentGroupName
```

**Comment by vivienxr** [comment]
Here are some performance tests for this PR: 

A course with 1 student and one with 22.5k students was created. For both courses the discussed method (getStudentParticipationCountById()) was run 20 times and the average duration was calculated: 

- No modification (old version which counts every participant and not only participating students):
    - course with 1 student: 99.50 ms
    - course with 22.5k students: 201.44 ms
- Modification with MEMBER OF:
    - course with 1 student: 108.88 ms
    - course with 22.5k students: 217.33 ms
- Modification with JOIN (version used in this PR):
    - course with 1 student: 108.82 ms
    - course with 22.5k students: 212.93 ms

In these tests all versions have similar duration so there are no performance issues recognizable.

File: src/main/java/de/tum/cit/aet/artemis/exercise/repository/ExerciseRepository.java (hunk 3 above)
Comment (vivienxr) [reply src/main/java/de/tum/cit/aet/artemis/exercise/repository/ExerciseRepository.java]: Thanks for the feedback!

As stated in the comment below there should be very few difference in performance between these two versions. 

Nevertheless I incorporated your version. In scenarios where many participants belong to multiple roles, your solution is likely more robust, as it avoids running a long loop for each participant with several roles.

**Comment by vivienxr** [comment]
@coderabbitai full review

**Review by LeZhen1105 — APPROVED** [review]
tested locally, worked as expected! thanks for updating performance tests table

File: src/main/java/de/tum/cit/aet/artemis/exercise/service/ExerciseService.java [hunk 4]
```diff
@@ -613,7 +613,8 @@ private void setStudentsAndParticipationsAmountForStatisticsDTO(CourseManagement
                 exerciseStatisticsDTO.setParticipationRateInPercent(teams == null || teams == 0 ? 0.0 : Math.round(participations * 1000.0 / teams) / 10.0);
             }
             else {
-                Long studentParticipations = exerciseRepository.getStudentParticipationCountById(exercise.getId());
+                Long studentParticipations = exerciseRepository.getStudentParticipationCountById(exercise.getId(),
+                        exercise.getCourseViaExerciseGroupOrCourseMember().getStudentGroupName());
```
[the remark this answers is not in the document]
Comment (vivienxr) [reply src/main/java/de/tum/cit/aet/artemis/exercise/service/ExerciseService.java:632]: The other course group fields are also not annotated with `@NotNull`, so adding it here would break consistency within the data model.

If a student group does not exist (i.e. the value is null), it makes sense that no meaningful number of students can be returned.

**Comment by vivienxr** [comment]
> In general the implementation looks good, however this would break for exam exercises. After reviewing its usage, I think this is also used for exam exercises. I would suggest to get the student group (either `exercise.course.studentGroup` or `exercise.exerciseGroup.course.studentGroup`) in Java and pass it into the query to avoid an `OR` clause, which is problematic in terms of performance

Thanks for the feedback! I incorporated it the way you described.

**Comment by vivienxr** [comment]
Still working on this PR.

**Comment by vivienxr** [comment]
@coderabbitai full review

**Review by florian-glombik — APPROVED** [review]
Code
