### PR TITLE
`Integrated code lifecycle`: Improve logging when build job times out

### LINKED ISSUE #9877: `Programming Exercise`: Improve feedback on build job timeout
### Describe the bug

Whenever a build job reaches the set timeout, it errors which leads to a build fail. This does not really tell the students what went wrong in any way since their code compiles locally.

### To Reproduce

I don't know a good way to reproduce this, but the logs in the end of this report have build job ids that may help you track this down hopefully.

### Expected behavior

Give the student some feedback and tell them why the build job failed. It should also include actionable items that will help the student resolve this build failure similar to when a timeout is specified in the tests using ares.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

7.7.2

### What browsers are you seeing the problem on?

Safari

### Additional context

_No response_

### Relevant log output

```shell
Build Error:
2024-11-26 19:22:30
~~~~~~~~~~~~~~~~~~~~ Start Build Job 87467971732645349998 ~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~ Inspecting docker image ls1tum/artemis-maven-template:java17-21 ~~~~~~~~~~~~~~~~~~~~
2024-11-26 19:22:32
~~~~~~~~~~~~~~~~~~~~ Started container local-ci-87467971732645349998 for build job 87467971732645349998 ~~~~~~~~~~~~~~~~~~~~
2024-11-26 19:22:32
~~~~~~~~~~~~~~~~~~~~ Populating build job container with repositories and build script ~~~~~~~~~~~~~~~~~~~~
2024-11-26 19:22:32
~~~~~~~~~~~~~~~~~~~~ Executing Build Script for Build job 87467971732645349998 ~~~~~~~~~~~~~~~~~~~~
2024-11-26 19:22:32
⚙️ executing gradle
2024-11-26 19:22:37
> Task :clean UP-TO-DATE
2024-11-26 19:22:39
> Task :compileJava
> Task :processResources
NO-SOURCE
> Task :classes
2024-11-26 19:22:41
> Task :compileTestJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2024-11-26 19:22:41
> Task :processTestResources
> Task :testClasses
2024-11-26 19:22:43
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by de.tum.in.test.api.security.ArtemisSecurityManager (file:/root/.gradle/caches/modules-2/files-2.1/de.tum.in.ase/artemis-java-test-sandbox/1.13.0/5e95697c1512e5a58fe4b4265f9b54c9624d1851/artemis-java-t
de.tum.in.test.api.security.ArtemisSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
2024-11-26 19:22:43
> Task :test
SearchEngineTests STANDARD_ERROR
[DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing.
NOTICE: The warning above is expected and the issue is already known. Visit https://github.com/ls1intum/Ares/discussions/113 for more details.
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional.empty, executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01**" (GLOB) in WHITELIST; level READ], PathRule["target" (STARTS_WITH) in WHITELIS
[INFO] [Test worker] Request whitelisting: Thread[ajts-to-1,5,Test-Threadgroup] []
[INFO] [Test worker] Thread whitelisted: Thread[ajts-to-1,5,Test-Threadgroup]
[INFO] [Test worker] Request uninstall
SearchEngineTests > Structure test for DocumentListElement STANDARD_ERROR [DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing.
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[public void pgdp.searchengine.SearchEngineTests.testStructureDocumentListElement()], executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01**"
[INFO] [Test worker] Thread whitelisted: Thread[ajts-to-2,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall
SearchEngineTests STANDARD_ERROR
2024-11-26 19:22:43
[INFO] [Test worker] Request whitelisting: Thread[ajts-to-3,5,Test-Threadgroup] []
[INFO] [Test worker] Thread whitelisted: Thread[ajts-to-3,5,Test-Threadgroup]
[INFO] [Test worker] Request uninstall
SearchEngineTests > Structure test for Bucket STANDARD_ERROR
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[public void pgdp.searchengine.SearchEngineTests.testStructureBucket()], executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01**" (GLOB) in WH
[INFO] [Test worker] Thread whitelisted: Thread[ajts-to-4,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional.empty, executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01**" (GLOB) in WHITELIST; level READ], PathRule["target" (STARTS_WITH) in WHITELIS
[INFO] [Test worker] Thread whitelisted: Thread[ajts-to-5,5,Test-Threadgroup]
SearchEngineTests > Structure test for DocumentCollection STANDARD_ERROR
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[public void pgdp.searchengine.SearchEngineTests.testStructureDocumentCollection()], executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01**"
[INFO] [Test worker] Request whitelisting: Thread[ajts-to-6,5,Test-Threadgroup] [] [INFO] [Test worker] Thread whitelisted: Thread[ajts-to-6,5,Test-Threadgroup]
2024-11-26 19:22:43
SearchEngineTests > Structure test for DocumentCollection FAILED
org.opentest4j.MultipleFailuresError at SearchEngineTests.java:69
[DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing. [INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional.empty, executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathR
[INFO] [Test worker] Request whitelisting: Thread[ajts-to-7,5,Test-Threadgroup] []
[INFO] [Test worker] Thread whitelisted: Thread[ajts-to-7,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall SearchEngineTests > DocumentListElement Constructor STANDARD_ERROR
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[public void pgdp.searchengine.SearchEngineTests.testDocumentListElementConstructor()], executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01*
[INFO] [Test worker] Request whitelisting: Thread[ajts-to-8,5,Test-Threadgroup] [] [INFO] [Test worker] Thread whitelisted: Thread[ajts-to-8,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall SearchEngineTests STANDARD_ERROR [DEBU
Document() STANDARD_ERROR
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[public void pgdp.searchengine.SearchEngineTests.testDocumentListElementGetDocument()], executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01*
[INFO] [Test worker] Thread whitelisted: Thread[ajts-to-10,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall
[INFO] [Test worker] Request whitelisting: Thread[ajts-to-11,5,Test-Threadgroup] []
2024-11-26 19:22:43
[INFO] [Test worker] Thread whitelisted: Thread[ajts-to-11,5,Test-Threadgroup]
SearchEngineTests > DocumentCollection Constrcutor STANDARD_ERROR
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[public void pgdp.searchengine.SearchEngineTests.testConstructor()], executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01**" (GLOB) in WHITEL
[INFO] [Test worker] Thread whitelisted: Thread[ajts-to-12,5,Test-Threadgroup]
2024-11-26 19:22:58
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-12,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-12,5,Test-Threadgroup], state: RUNNABLE
2024-11-26 19:22:59
SearchEngineTests > DocumentCollection Constrcutor FAILED org.opentest4j.AssertionFailedError at Messages.java:34
SearchEngineTests STANDARD_ERROR [DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing.
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional.empty, executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01**" (GLOB) in WHITELIST; level READ], PathRule["target" (STARTS_WITH) in WHITELIS
[INFO] [Test worker] Thread whitelisted: Thread[ajts-to-13,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall SearchEngineTests > DocumentCollection indexFunction() STANDARD_ERROR
[DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing. [INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[public void pgdp.searchengine.SearchEngineTests.testIndexFunction()], execu
[INFO] [Test worker] Thread whitelisted: Thread[ajts-to-14,5,Test-Threadgroup]
2024-11-26 19:23:14
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-14,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-14,5,Test-Threadgroup], state: RUNNABLE SearchEngineTests > DocumentCollection indexFunction
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional.empty, executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01**" (GLOB) in WHITELIST; level READ], PathRule["target" (STARTS_WITH) in WHITELIS
SearchEngineTests > DocumentCollection add() Basic STANDARD_ERROR
[DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing. [INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[public void pgdp.searchengine.SearchEngineTests.testAdd()], executionPath=/
[INFO] [Test worker] Request whitelisting: Thread[ajts-to-16,5,Test-Threadgroup] [] [INFO] [Test worker] Thread whitelisted: Thread[ajts-to-16,5,Test-Threadgroup]
2024-11-26 19:23:30
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-16,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-16,5,Test-Threadgroup], state: RUNNABLE SearchEngineTests > DocumentCollection add() Basic F
org.opentest4j.AssertionFailedError at Messages.java:34 SearchEngineTests STANDARD_ERROR
[INFO] [Test worker] Request whitelisting: Thread[ajts-to-17,5,Test-Threadgroup] []
[INFO] [Test worker] Thread whitelisted: Thread[ajts-to-17,5,Test-Threadgroup]
2024-11-26 19:23:30
SearchEngineTests > DocumentCollection add() Edge Cases STANDARD_ERROR [DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing. [INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[pub
2024-11-26 19:23:45
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-18,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-18,5,Test-Threadgroup], state: RUNNABLE SearchEngineTests > DocumentCollection add() Edge Ca
ts-to-19,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall
SearchEngineTests > DocumentCollection isEmpty() STANDARD_ERROR [DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing.
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[void pgdp.searchengine.SearchEngineTests.testDocumentCollectionisEmpty()], executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01**" (GLOB) in
2024-11-26 19:24:01
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-20,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-20,5,Test-Threadgroup], state: RUNNABLE SearchEngineTests > DocumentCollection isEmpty() FAI
[DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing. [INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional.empty, executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathR
SearchEngineTests > DocumentCollection find() Basic STANDARD_ERROR [DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing.
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[public void pgdp.searchengine.SearchEngineTests.testFindBasic()], executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01**" (GLOB) in WHITELIS
2024-11-26 19:24:16
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-22,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-22,5,Test-Threadgroup], state: RUNNABLE SearchEngineTests > DocumentCollection find() Basic
o-23,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall
SearchEngineTests > DocumentCollection find() Edge Cases STANDARD_ERROR [DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing. [INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[p
2024-11-26 19:24:32
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-24,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-24,5,Test-Threadgroup], state: RUNNABLE SearchEngineTests > DocumentCollection find() Edge C
[DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing. [INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional.empty, executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathR
[DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing. [INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[public void pgdp.searchengine.SearchEngineTests.testRemoveDocument()], exe
2024-11-26 19:24:47
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-26,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-26,5,Test-Threadgroup], state: RUNNABLE SearchEngineTests > DocumentCollection removeDocumen
ts-to-27,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall
2024-11-26 19:24:47
SearchEngineTests > DocumentCollection removeDocumentsFromAuthor() STANDARD_ERROR [DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing. [INFO] [Test worker] Request install with ASC-Impl [testMethod=O
2024-11-26 19:25:03
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-28,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-28,5,Test-Threadgroup], state: RUNNABLE SearchEngineTests > DocumentCollection removeDocumen
: Thread[ajts-to-29,5,Test-Threadgroup]
[INFO] [Test worker] Request uninstall SearchEngineTests > DocumentCollection removeAll() STANDARD_ERROR
[DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing. [INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[public void pgdp.searchengine.SearchEngineTests.testRemoveAll()], execution
[INFO] [Test worker] Thread whitelisted: Thread[ajts-to-30,5,Test-Threadgroup]
2024-11-26 19:25:18
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-30,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-30,5,Test-Threadgroup], state: RUNNABLE SearchEngineTests > DocumentCollection removeAll() F
-31,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall SearchEngineTests > DocumentCollection removeOldDocuments() STANDARD_ERROR [DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing.
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[public void pgdp.searchengine.SearchEngineTests.testRemoveOldDocuments()], executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01**" (GLOB) in
2024-11-26 19:25:34
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-32,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-32,5,Test-Threadgroup], state: RUNNABLE SearchEngineTests > DocumentCollection removeOldDocu
d[ajts-to-33,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall
SearchEngineTests > DocumentCollection getHead() STANDARD_ERROR [DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing.
[INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[public void pgdp.searchengine.SearchEngineTests.testDocumentCollectionGetHead()], executionPath=/var/tmp/testing-dir, whitelistedPaths=Optional[[PathRule["../pgdp2425*w06h01**" (G
2024-11-26 19:25:49
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-34,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-34,5,Test-Threadgroup], state: RUNNABLE SearchEngineTests > DocumentCollection getHead() FAI
5,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall
SearchEngineTests > DocumentCollection getTail() STANDARD_ERROR [DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing. [INFO] [Test worker] Request install with ASC-Impl [testMethod=Optional[void pgdp
2024-11-26 19:26:05
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-36,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-36,5,Test-Threadgroup], state: RUNNABLE SearchEngineTests > DocumentCollection getTail() FAI
2024-11-26 19:26:05
[INFO] [Test worker] Request whitelisting: Thread[ajts-to-37,5,Test-Threadgroup] [] [INFO] [Test worker] Thread whitelisted: Thread[ajts-to-37,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall SearchEngineTests > DocumentCollection c
Test-Threadgroup]
2024-11-26 19:26:21
[DEBUG] [Test worker] State RUNNABLE after interrupt and join of Thread[ajts-to-38,5,Test-Threadgroup] [DEBUG] [Test worker] Try 1 to stop Thread[ajts-to-38,5,Test-Threadgroup], state: RUNNABLE SearchEngineTests > DocumentCollection contains() FA
39,5,Test-Threadgroup] [INFO] [Test worker] Request uninstall SearchEngineTests > DocumentCollection size() STANDARD_ERROR [DEBUG] [Test worker] Validated build configuration regarding trusted package rules, 0 are missing. [INFO] [Test worker
2024-11-26 19:26:30
Error while executing build job 87467971732645349998: null java.util.concurrent.TimeoutException at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204) at de.tum.cit.aet.artemis.buildagent.service.BuildJobManagementService.lambda$executeB
2024-11-26 19:26:35
~~~~~~~~~~~~~~~~~~~~ Finished Executing Build Script for Build job 87467971732645349998 ~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by BBesrour**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

Resolves #9877 

A new line is now added at the end of the logs
```
Timed out after X seconds. This may be due to an infinite loop or inefficient code. Please review your code for potential issues. If the problem persists, contact your instructor for assistance. (Build job ID: XYZ) 
```

### Steps for Testing

Prerequisites:
- 1 Instructor
- Server with ICL (TS1-4)

1. Create a programming exercise (or edit a existing one)
2. Edit the timeout to lowest possible number. This can be found when checking Edit build script and you will find the timeout slider there (make sure to use exercise creation advanced mode). Save
3. Submit to that exercise
4. Build should fail. Check that the last log is the similar to the string above

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

image

## Summary by CodeRabbit

- **New Features**
	- Enhanced logging for container management and build job execution processes.
	- Added detailed warnings for timeout exceptions during build job execution, providing actionable guidance for users.

- **Bug Fixes**
	- Improved error handling for stopping containers and collecting test results, ensuring better traceability and feedback.

- **Documentation**
	- Updated logging messages to clarify operations and enhance user experience during build job execution.

### CODE REVIEW

**Review by SimonEntholzer — DISMISSED** [review]
Timeout log makes sense (code + tested on ts1)

**Review by EneaGore — APPROVED** [review]
Tested on TS1 during testing session. works as expected

**Review by coolchock — DISMISSED** [review]
tested on ts1, LGTM

**Review by magkue — APPROVED** [review]
Tested on TS1 (as part of a testing session). Worked fine. No problems.

File: src/main/java/de/tum/cit/aet/artemis/buildagent/service/BuildJobManagementService.java [hunk 1]
```diff
@@ -176,6 +177,13 @@ public CompletableFuture<BuildResult> executeBuildJob(BuildJobQueueItem buildJob
                 }
                 else {
                     finishBuildJobExceptionally(buildJobItem.id(), containerName, e);
+                    if (e instanceof TimeoutException) {
+                        String msg = "Timed out after " + buildJobTimeoutSeconds + " seconds. "
+                                + "This may be due to an infinite loop or inefficient code. Please review your code for potential issues. "
+                                + "If the problem persists, contact your instructor for assistance. (Build job ID: " + buildJobItem.id() + ")";
```
Comment (krusche) [inline src/main/java/de/tum/cit/aet/artemis/buildagent/service/BuildJobManagementService.java:183]: Build logs cannot be read by students. Only instructors and admins have access. I suggest to change the message here and instead write that instructors should check for short and strict timeouts in the tests to prevent infinite loops in the student code

**Review by krusche — CHANGES_REQUESTED** [review]
See my inline feedback for changing the message

**Review by krusche — APPROVED** [review]
After discussing the changes with @BBesrour I agree that they make sense because students would see the logs when a build fails
