### PR TITLE
`Communication`: Enable save button when multi-line content is copied into new posts

### LINKED ISSUE #5244: The "Save" button stays disabled after copy and paste into the "new post" Content text field
### Describe the bug

When the user copies and pastes the text into the content field of the new post dialog, the system does not recognize the text and the state of the save button does not change.

### To Reproduce

1. Go to some course, e.g. EIST 22
2. Click on Discussion Tab → + New Post
3. Fill in the title and paste the text from the clipboard into the Content text field
4. See the state of the Safe button does not change.

### Expected behavior

When the user filled in the title and pasted or written the text into the content field, the system should recognize the change and the Safe button state must be changed to enabled.

### Screenshots

image

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by canberkanar**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
Previously while using the Discussion page, users were not able to save posts when they pasted the content part instead of typing, due to the 'Save' button not being enabled. Fixes #5244.

### Description
 After some debugging, we realized that the issue is present because the Regex pattern that verifies the validity of posting contents was not handling the edge case when the pasted text included the 'Carriage Return Character (\r)'. With this PR, we make sure that content with this escape character is also accepted by the posting content validator.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Course with Postings enabled

1. Log in to Artemis
2. Navigate to Course Discussion page
3. Create or edit a Posting
4. Copy multiple lines 
5. Paste into the context of the Posting
6. Make sure that the "Save" button is enabled and postings can be saved.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
Not changed.

### Screenshots
https://user-images.githubusercontent.com/67344158/175520057-ab06f6be-699e-4da8-91dc-6b32e208534d.mp4

### CODE REVIEW

**Review by xlieA — APPROVED** [review]
Tested on ts1. I followed the testing steps and everything worked as described. The save button worked.

**Review by alaraozdenler — DISMISSED** [review]
Tested on ts2, works as described/shown

**Review by babyygemperor — DISMISSED** [review]
Tested on ts2, works as described

File: src/main/webapp/app/shared/metis/posting-create-edit-modal/answer-post-create-edit-modal/answer-post-create-edit-modal.component.ts [hunk 1]
```diff
@@ -42,7 +42,7 @@ export class AnswerPostCreateEditModalComponent extends PostingCreateEditModalDi
     resetFormGroup(): void {
         this.formGroup = this.formBuilder.group({
             // the pattern ensures that the content must include at least one non-whitespace character
-            content: [this.posting.content, [Validators.required, Validators.maxLength(this.maxContentLength), Validators.pattern(/^(\n|.)*\S+(\n|.)*$/)]],
+            content: [this.posting.content, [Validators.required, Validators.maxLength(this.maxContentLength), Validators.pattern(/^(\n|\r|.)*\S+(\n|\r|.)*$/)]],
```
Comment (Strohgelaender) [inline src/main/webapp/app/shared/metis/posting-create-edit-modal/answer-post-create-edit-modal/answer-post-create-edit-modal.component.ts:45]: On Windows, both \r\n get used. 
```suggestion
            content: [this.posting.content, [Validators.required, Validators.maxLength(this.maxContentLength), Validators.pattern(/^(\r\n|\n|\r|.)*\S+(\r\n|\n|\r|.)*$/)]],
```
Since the comment talks about "whitespace" instead of newlines, I think also this would work (see https://www.w3schools.com/jsref/jsref_regexp_whitespace.asp)
```suggestion
            content: [this.posting.content, [Validators.required, Validators.maxLength(this.maxContentLength), Validators.pattern(/^(\s|.)*\S+(\s|.)*$/)]],
```
It would also be great if you could find a way to remove the duplicated regex. In fact, this whole method looks duplicated and should probably be changed.

**Review by Strohgelaender — CHANGES_REQUESTED** [review]

**Review by max-bergmann — APPROVED** [review]
Tested on TS1. Works as described.

File: src/main/webapp/app/shared/metis/posting-create-edit-modal/answer-post-create-edit-modal/answer-post-create-edit-modal.component.ts (hunk 1 above)
Comment (canberkanar) [reply src/main/webapp/app/shared/metis/posting-create-edit-modal/answer-post-create-edit-modal/answer-post-create-edit-modal.component.ts:45]: > On Windows, both \r\n get used.
> 
> Since the comment talks about "whitespace" instead of newlines, I think also this would work (see https://www.w3schools.com/jsref/jsref_regexp_whitespace.asp)
> 
> It would also be great if you could find a way to remove the duplicated regex. In fact, this whole method looks duplicated and should probably be changed.
> 
> Edit: I did not see the Star at first glance, so \r\n is actually already matched. But still, I think \s would be a cleaner option.

I'm working on Windows and currently with the new REGEX pattern, the save button is activated as intended. I will not use '\s' because we want to keep the button deactivated when whitespace is entered into the post body.

Comment (canberkanar) [reply src/main/webapp/app/shared/metis/posting-create-edit-modal/answer-post-create-edit-modal/answer-post-create-edit-modal.component.ts]: Duplication removed

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]

**Review by Strohgelaender — APPROVED** [review]
code

**Review by TheTrueVester — APPROVED** [review]
Tested during testing session on ts1. Everything worked as expected.

**Review by babyygemperor — APPROVED** [review]
Tested in ts1 in a testing session, works as described

**Review by minrows — APPROVED** [review]
Tested on ts1 during testing session. Functionality works as described. 👍

**Review by nadinesamyy — APPROVED** [review]
works as described on ts2
