### PR TITLE
`Programming exercises`: Always give students read permissions for their repository

### LINKED ISSUE #5876: `Exam programming exercises`: Artemis tries to remove user from repository if not necessary
### Describe the bug

When an exam is over, Artemis removes the write permission from all student repositories. However, if only the online editor is allowed for an exercise, then the students did not have direct write permissions in the first place. Therefore, the operation always fails.

### To Reproduce

I tested it in a test exam. Artemis 5.12.3 connected to GitLab.

1. Create an exam that contains a programming exercise for which only the online editor is enabled.
2. Participate as student in the exam.
3. The repo is created in GitLab, the student should not be a member.
4. Finish the exam.
5. Artemis tries to change user permissions for the repo but fails to do so as the user is not a member of the repository.

### Expected behavior

Artemis does not try to remove the user from the repo if not necessary.

Alternatively, give them the reporter role on the repo after the due date so that the users can look at their solutions when receiving feedback as this does not seem to be possible from within Artemis currently (→ #5877, #5025, #3031).

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

```shell
de.tum.in.www1.artemis.service.connectors.gitlab.GitLabException: Unable to set permissions for user <omitted>. Trying to set permission 20
        at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.updateMemberPermissionInRepository(GitLabService.java:485)
        at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.lambda$setRepositoryPermissionsToReadOnly$6(GitLabService.java:468)
        at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.setRepositoryPermissionsToReadOnly(GitLabService.java:468)
        at de.tum.in.www1.artemis.service.programming.ProgrammingExerciseParticipationService.lockStudentRepository(ProgrammingExerciseParticipationService.java:209)
        at de.tum.in.www1.artemis.service.exam.StudentExamService.lockStudentRepositories(StudentExamService.java:367)
        at de.tum.in.www1.artemis.service.exam.StudentExamService.submitStudentExam(StudentExamService.java:142)
        at de.tum.in.www1.artemis.web.rest.StudentExamResource.submitStudentExam(StudentExamResource.java:249)
        at de.tum.in.www1.artemis.web.rest.StudentExamResource$$FastClassBySpringCGLIB$$12ee3abb.invoke(<generated>)
        […]
Caused by: org.gitlab4j.api.GitLabApiException: 404 Not found
        […]
        at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.updateMemberPermissionInRepository(GitLabService.java:482)
```

### LINKED ISSUE #5877: `Exam programming exercises`: Students cannot review their own code for submitted exercises
### Describe the bug

Related to #5876

Users cannot see their own code after the exam ended. Therefore, the review is difficult.

Possibly only happens for test exams.

Important, as reviewing their own code after receiving feedback does not seem to be possible from within Artemis currently (→ https://github.com/ls1intum/Artemis/issues/5025, https://github.com/ls1intum/Artemis/issues/3031).

### To Reproduce

Same steps as in #5876. Then,

1. On the summary page there is a link to the GitLab repo.
2. The link does not work as the user is not a member of the repository.

### Expected behavior

The student is a member of the repository with read-only rights (reporter).

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
Closes #5876
Closes #5877

### Description
Ensures that students always get read permissions for their repositories, even if only the online editor is enabled. This enables the review of the code for exam programming exercises. For regular exercises this is enabled as well, both for consistency and as I can see no disadvantage.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 2 Programming Exercises
  - one that has the offline IDE disabled
  - one for which the offline IDE is enabled

1. Ensure that a due date is set for the programming exercise.
2. As student: participate in the exercise.
3. If offline IDE disabled: check that you cannot push to the repo to any branch.
4. After the due date: Check that you can no longer push to the repository.
5. For a fresh exercise repeat the steps, but as instructor change the settings for the offline IDE while the exercise is running. The permissions should be removed from the student repo when disabling the offline IDE, and added back when allowing it again.

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 (Test) Exam with two Programming Exercises

1. Configure one programming exercise to only allow the online editor, one that also/alternatively allows the offline IDE.
6. Participate in the exam as a student. You should be able to submit to the programming exercise.
7. After the exam, on the summary page: There is a link to the repository for the exercise. That link should work so that you can view the code in the version control system, but not commit further changes.

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [ ] Test

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| ExerciseService.java | 85% | 77% |
| AbstractVersionControlService.java | 100% of changed code | 100% of changed code |
| BitbucketService.java | 100% of changed code | 100% of changed code |
| GitLabService.java | 50% | 82% |

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Codechanges look good.
Could you make sure that updating the exercise `handleRepoAccessRightChanges()` also works as intended with this fix and add it to the testing steps?

**Comment by b-fein** [comment]
> Could you make sure that updating the exercise handleRepoAccessRightChanges() also works as intended with this fix

Good call: Verified that it still works. :+1: 

> and add it to the testing steps?

done

**Review by frederik-kt — CHANGES_REQUESTED** [review]
Tested on TS1. For the case where the offline IDE usage was allowed, when the instructor creates the exercise without a due date and then adds the due date later on, I was still able to push from my local IDE.

**Comment by b-fein** [comment]
@frederik-kt Thanks for testing! I can’t reproduce that issue. I tried
- not setting a due date initially, submitting as student, then setting a due date in the future,
- not setting a due date initially, submitting as student, then setting a due date in the past.

In both cases I got the notification as instructor that all student repositories were locked. The student could no longer push to the repo.

File: src/main/java/de/tum/in/www1/artemis/service/connectors/AbstractVersionControlService.java [hunk 1]
```diff
@@ -173,4 +173,20 @@ public String getOrRetrieveBranchOfExercise(ProgrammingExercise programmingExerc
...
+
+    /**
+     * Determines if a user should get read-only or also write permissions for their repository.
+     *
+     * @param programmingExercise The programming exercise the repository belongs to.
+     * @return The permissions the user should receive for a repository.
+     */
+    protected RepositoryPermissions determineRepositoryPermissions(final ProgrammingExercise programmingExercise) {
+        // NOTE: null values are interpreted as offline IDE is allowed
+        if (Boolean.FALSE.equals(programmingExercise.isAllowOfflineIde())) {
```
Comment (JohannesStoehr) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/AbstractVersionControlService.java:185]: Should we move this check into isAllowOfflineIde, since no occurrence actually needs the null value and all calls to this method always have to wrap the call into an equals check

**Review by JohannesStoehr — APPROVED** [review]
Code still looks good, left one optional comment

File: src/main/java/de/tum/in/www1/artemis/service/connectors/AbstractVersionControlService.java (hunk 1 above)
Comment (b-fein) [reply src/main/java/de/tum/in/www1/artemis/service/connectors/AbstractVersionControlService.java:185]: Probably a good idea. There are a few more `Boolean` attributes in the programming exercise, though, that should be changed as well in the same refactoring (online editor enabled, static code analysis enabled, publish build plan, …).
They are all used in quite a few places, so any change there should be part of a separate refactoring PR to ensure there that the logic does not change. ⇒ opened as issue #6079

**Review by nikirovast — CHANGES_REQUESTED** [review]
I tested on ts1:

- As an instructor I have created an exercise with only online editor, then while the exercise was running I also added an offline editing.

- As the student I cloned the repo. 

- Then as an instructor I disabled an offline editing.

- After that as a student I still was able to pus my changes and get them graded.

This was a normal exercise, not an exam mode.

**Review by laadvo — APPROVED** [review]
Everything working as expected. When the offline IDE gets disabled while the exercise is running, the student is not able to push to the repository anymore. Pushing after the due date is also not possible. The students is still able to see the repository in the online IDE after the due date. Tested on ts2.

**Review by frederik-kt — APPROVED** [review]
Retested on TS2. I was not able to replicate any of the issues mentioned. I.e., the following worked as expected:

- instructor creates programming exercise without due date with offline IDE usage allowed
- student clones the repository and submits
- instructor adds a due date in the past
- student attempts to submit again -> 403

- instructor creates programming exercises with only online editor allowed (no offline IDE)
- instructor edits programming exercise to also allow for offline IDE usage
- student clones repository and submits
- instructor edits programming exercise again to not allow for offline IDE usage
- student attempts to submit again -> 403
