### PR TITLE
Bugfix/quiz/negative question score

### LINKED ISSUE #1393: Question score can be set to a negative number
### Describe the bug
The score of Multiple-Choice, Drag-And-Drop and Short-Answer questions on quiz exercises can be set to a negative number. Scoring 100% on that quiz leads to a decrease in total points for the student.

#### To Reproduce
As an instructor
1. Go to Course Management > Exercises > Quiz Exercises
2. Create a new Quiz Exercise
3. Add a Multiple-Choice question
4. Set the score of that question to -100
5. Save the quiz exercise

#### Expected behavior
It should not be possible to save the quiz exercise if the Max. Score of that quiz is <= 0
It should not be possible to enter a negative number into the score input box.

#### Screenshots
negative

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Google Chrome
 - Version  81.0.4044.129
</pre></details>

### PR DESCRIPTION
**Pull request by florian-glombik**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (instructor, admin) on the test server https://artemistest.ase.in.tum.de
- [x] I tested *all* changes and *all* related features with different users (instructor, admin) locally
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Description

Closes #1393 

### Steps for Testing

1. Log in to Artemis
2. Navigate to _Course Management_
3. Go to _Exercises_
4. Create a new quiz
5. ~try to save a quiz with a score <= 0~
try to save a quiz with a (question) score < 0

### Screenshots

saving quiz with question scores <= 0 not possible
1393 - saving quiz with non positive question score not possible

save button for quizzes with invalid question scores not available
1393 - save button, non positive score

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/domain/quiz/QuizQuestion.java [hunk 1]
```diff
@@ -261,8 +261,8 @@ public void filterForStatisticWebsocket() {
      */
     @JsonIgnore
     public Boolean isValid() {
-        // check title
-        return getTitle() != null && !getTitle().equals("");
+        // check title and score
+        return getTitle() != null && !getTitle().equals("") && getScore() > 0;
```
Comment (stefanwaldhauser) [inline src/main/java/de/tum/in/www1/artemis/domain/quiz/QuizQuestion.java:265]: What about multiple whitespaces. You should maybe trim the string before you do the validation. Could be also a problem in the frontend. Please check this! 💯

Comment (florian-glombik) [reply src/main/java/de/tum/in/www1/artemis/domain/quiz/QuizQuestion.java:265]: getScore() returns an Integer, therefore no trimming/parsing is needed at this place.


_I just tested the behaviour of the server when entering letters and whitespace, but since the input is a number, everything behaves as expected._
image

Comment (florian-glombik) [reply src/main/java/de/tum/in/www1/artemis/domain/quiz/QuizQuestion.java:265]: I do agree on that, but since the related issue #1393 refers to the non-positive number score I didn't want to change too much here - only the things related to the issue.

I think it would make more sense to create a new issue regarding this.

Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/domain/quiz/QuizQuestion.java:265]:
```suggestion
        return getTitle() != null && !getTitle().equals("") && getScore() >= 0;
```

File: src/main/webapp/app/exercises/quiz/manage/quiz-exercise-detail.component.ts [hunk 2]
```diff
@@ -694,6 +697,12 @@ export class QuizExerciseDetailComponent implements OnInit, OnChanges, Component
                     translateValues: { index: index + 1 },
                 });
             }
+            if (question.score <= 0) {
```
Comment (krusche) [inline src/main/webapp/app/exercises/quiz/manage/quiz-exercise-detail.component.ts:700]:
```suggestion
            if (question.score < 0) {
```

File: src/main/webapp/app/exercises/quiz/manage/quiz-exercise-detail.component.ts [hunk 3]
```diff
@@ -574,6 +574,9 @@ export class QuizExerciseDetailComponent implements OnInit, OnChanges, Component
             this.quizExercise.quizQuestions &&
             !!this.quizExercise.quizQuestions.length;
         const areAllQuestionsValid = this.quizExercise.quizQuestions.every(function (question) {
+            if (question.score <= 0) {
```
Comment (krusche) [inline src/main/webapp/app/exercises/quiz/manage/quiz-exercise-detail.component.ts:577]:
```suggestion
            if (question.score < 0) {
```
