### PR TITLE
`General`: Hide organization buttons for non-admin users in course edit screen

### LINKED ISSUE #6188: `Edit Course`: Hide "Add Organization" Button If I'm Not Allowed to See It
### Describe the bug

When editing a course, I see a button for "adding an organization" but when I click it, I see an empty popup and instantly an alert pops up telling me that I am not allowed to do this.

### To Reproduce

1. Log into Artemis with an account that can edit courses
2. Go to a course and click edit
3. See and click the "Add Organization" button

### Expected behavior

If I am not allowed to do that, I should not see the button in the first place or it should be disabled (maybe with a tooltip when hovering).

### Screenshots

Bildschirm­foto 2023-02-03 um 03 47 15

### Which version of Artemis are you seeing the problem on?

6.0.2

### What browsers are you seeing the problem on?

Safari

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by terlan98**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Closes #6188 

### Description
Added a new field named `isAdmin` for conditionally rendering the organization add and remove buttons. The value of the field depends on whether the current user is an admin or not.

### Steps for Testing
Prerequisites:
- 1 Admin
- 1 Any non-admin account (instructor, ta, etc.)
- 1 Course

1. Log in to Artemis as Admin
2. Navigate to Course Management
3. Select a course (click on the title)
4. Click the yellow edit button located on the top right
5. The Course Organizations section must show an add button and cross (x) buttons for each added organization. The addition and removal functionalities must work.
6. Repeat the same process (steps 1-5) with a non-admin account. The aforementioned buttons must be invisible

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
```diff
@@              Coverage Diff              @@
##             develop    #6360      +/-   ##
=============================================
+ Coverage      76.42%   80.37%   +3.95%     
- Complexity         0    12976   +12976     
=============================================
  Files           1241     2310    +1069     
  Lines          46826    88798   +41972     
  Branches        8742    13141    +4399     
=============================================
+ Hits           35786    71370   +35584     
- Misses          5674     9626    +3952     
- Partials        5366     7802    +2436     
```

| [Impacted Files](https://codecov.io/gh/ls1intum/Artemis/pull/6360?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ls1intum) | Coverage Δ | |
|---|---|---|
| [...ebapp/app/course/manage/course-update.component.ts](https://codecov.io/gh/ls1intum/Artemis/pull/6360?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ls1intum#diff-c3JjL21haW4vd2ViYXBwL2FwcC9jb3Vyc2UvbWFuYWdlL2NvdXJzZS11cGRhdGUuY29tcG9uZW50LnRz) | `77.10% <100.00%> (+0.43%)` | :arrow_up: |

### Screenshots
For admin:
Screenshot 2023-03-21 at 11 35 56

For other users:
Screenshot 2023-03-29 at 22 18 02

For admin (no organizations added yet):
Screenshot 2023-03-29 at 22 19 28

For other users (no organizations added yet):
Screenshot 2023-03-29 at 22 20 48

### CODE REVIEW

File: src/main/webapp/app/course/manage/course-update.component.ts [hunk 1]
```diff
@@ -61,6 +62,7 @@ export class CourseUpdateComponent implements OnInit {
     faTimes = faTimes;
     faQuestionCircle = faQuestionCircle;
     faExclamationTriangle = faExclamationTriangle;
+    isAllowedToChangeOrganizations = false;
```
Comment (Strohgelaender) [inline src/main/webapp/app/course/manage/course-update.component.ts:65]: I'd use a more generic name here, this way you can use the same attribute at other places in the template as well if needed.

Also please move it a bit more upwards, you paced it below the icon attributes.
```suggestion
    isAdmin = false;
```

Comment (terlan98) [reply src/main/webapp/app/course/manage/course-update.component.ts]: Thank you for your comment. I addressed it in my latest commit

File: src/test/javascript/spec/component/course/course-update.component.spec.ts [hunk 2]
```diff
@@ -30,6 +30,9 @@ import dayjs from 'dayjs/esm';
 import { ImageCropperModule } from 'app/shared/image-cropper/image-cropper.module';
 import { ProgrammingLanguage } from 'app/entities/programming-exercise.model';
 import { CourseAdminService } from 'app/course/manage/course-admin.service';
+import { AccountService } from 'app/core/auth/account.service';
+import { MockAccountService } from '../../helpers/mocks/service/mock-account.service';
+import { By } from '@angular/platform-browser';
```
Comment (b-fein) [inline src/test/javascript/spec/component/course/course-update.component.spec.ts:35]:
```suggestion
```
unused import

**Review by b-fein — APPROVED** [review]
code looks good

**Review by b-fein — DISMISSED** [review]

File: src/test/javascript/spec/component/course/course-update.component.spec.ts [hunk 3]
```diff
@@ -487,4 +492,18 @@ describe('Course Management Update Component', () => {
...
+            jest.spyOn(accountService, 'isAdmin').mockReturnValue(true);
+            fixture.detectChanges();
+            expect(comp.isAdmin).toBeTrue();
+        });
+
+        it('should not allow adding / removing organizations if not admin', () => {
+            jest.spyOn(accountService, 'isAdmin').mockReturnValue(false);
+            fixture.detectChanges();
+            expect(comp.isAdmin).toBeFalse();
+        });
```
Comment (JohannesStoehr) [inline src/test/javascript/spec/component/course/course-update.component.spec.ts:507]: You can also make sure that the correlating button is shown/hidden. Otherwise you are more or less only testing the variable assignment

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]

**Review by mertyldrr — COMMENTED** [review]
Tested in the testing session. Agree with the proposed changes. UI behaves as described.

File: src/main/webapp/i18n/de/course.json [hunk 4]
```diff
@@ -197,7 +197,9 @@
                 "averageStudentScoreTitle": "Durchschnittliche Punktzahl der Studierenden"
             },
             "activeStudents": "Aktive Studierende: {{ students }}",
-            "notStartedYet": "Der Kurs hat noch nicht offiziell begonnen. Offizieller Kursstart:"
+            "notStartedYet": "Der Kurs hat noch nicht offiziell begonnen. Offizieller Kursstart:",
+            "noOrganizations": "Keine Organisationen",
+            "organizationAddingHint": "Administratoren können Organisationen zu Kursen hinzufügen"
```
Comment (b-fein) [inline src/main/webapp/i18n/de/course.json:202]:
```suggestion
            "organizationAddingHint": "Administratoren können Organisationen zu Kursen hinzufügen."
```

File: src/main/webapp/i18n/en/course.json [hunk 5]
```diff
@@ -197,7 +197,9 @@
                 "averageStudentScoreTitle": "Average Student Score"
             },
             "activeStudents": "Active students: {{ students }}",
-            "notStartedYet": "The course has not officially started yet. Official course start:"
+            "notStartedYet": "The course has not officially started yet. Official course start:",
+            "noOrganizations": "No Organizations",
+            "organizationAddingHint": "Administrators can add organizations to courses"
```
Comment (b-fein) [inline src/main/webapp/i18n/en/course.json:202]:
```suggestion
            "organizationAddingHint": "Administrators can add organizations to courses."
```

**Review by b-fein — APPROVED** [review]

**Review by b-fein — APPROVED** [review]

**Review by sven0311 — APPROVED** [review]
Retested on TS1. Looks perfect now

**Review by mertyldrr — APPROVED** [review]
Tested on ts1. Looks good!

**Review by frederik-kt — APPROVED** [review]
Tested on TS2. Looks good!
