### PR TITLE
`Communication`: Fix display name of group chats

### LINKED ISSUE #8253: Group Chats are always called "Only You"
### Describe the bug

When creating a group chat, its name is always "Only You", irrespective of how many people are part of it.

### To Reproduce

1. Go to course -> messages
2. Click on the "+" Icon next to group chats
3. Add multiple people to the group chat
4. See that it is called "only you"

### Expected behavior

The group chat name should contain the names of all its participants

### Screenshots

image

### Which version of Artemis are you seeing the problem on?

6.9.3

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rstief**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context
Fixes #8253 

### Description
- Changes the database query to correctly fetch all group members again, thus correctly displaying the auto-generated names. 
- Fixes a small bug in the client that caused a wrong number to be displayed.
- Adds tests to verify that the correct group members are returned for one-to-one and group conversations

### Steps for Testing

Prerequisites:
- 1 course with multiple people
- 1 user in that course of any role

1. Log in to Artemis
2. Navigate to Course -> Messages
3. Create a new group chat
4. See that the group chat name is made of the name of all participants (up to 2, then it's "... and X others")

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
unchanged

## Summary by CodeRabbit

- **Refactor**
	- Improved the efficiency of fetching group chats for users, ensuring more relevant results within courses.
- **Documentation**
    - Updated method names and parameter descriptions for better clarity and consistency.
- **Tests**
    - Added assertions to verify the correctness of group chat and one-to-one chat data.

### CODE REVIEW

**Review by laurenzfb — APPROVED** [review]
tested on ts1, worked. Thanks for the fix :)

**Review by milljoniaer — APPROVED** [review]

File: src/main/java/de/tum/in/www1/artemis/repository/metis/conversation/GroupChatRepository.java [hunk 1]
```diff
@@ -17,14 +17,24 @@
...
+                LEFT JOIN groupChat.conversationParticipants conversationParticipant
+                LEFT JOIN FETCH groupChat.conversationParticipants conversationParticipants
+                LEFT JOIN FETCH conversationParticipants.user user
                 LEFT JOIN FETCH user.groups
             WHERE groupChat.course.id = :courseId
-                AND user.id = :userId
+                AND conversationParticipant.user.id = :userId
             ORDER BY groupChat.lastMessageDate DESC
             """)
     List<GroupChat> findGroupChatsOfUserWithParticipantsAndUserGroups(@Param("courseId") Long courseId, @Param("userId") Long userId);
```
Comment (Jan-Thurner) [inline src/main/java/de/tum/in/www1/artemis/repository/metis/conversation/GroupChatRepository.java:40]: Is this query currently used by anything else?

**Review by Jan-Thurner — APPROVED** [review]
Code LGTM
