### PR TITLE
`Development`: Enhance LLM selection UI and update translations for improved clarity

### LINKED ISSUE #12111: LLM usage selection - inconsistent naming and UI improvements
### Describe the bug

Settings pages states:
"You have accepted the usage of external LLMs on xyz"
vs.
"You have accepted the usage of internal LLMs on xyz"

However this is inconsistent with the actual modal to choose LLM models.

Also the modal to choose LLM models should show the currently selected option.

### To Reproduce

/user-settings/llm-usage

### Expected behavior

Consistent naming
Showing the current state in the modal

### Screenshots

Image

Image

### Which version of Artemis are you seeing the problem on?

8.8.0

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by wasnertobias**
### Summary 
Fixes #12111

#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.tum.de/developer/guidelines/language).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.tum.de/developer/development-process#pr-naming-conventions).

### Motivation and Context

Fixes #12111
  The LLM usage selection modal and the user settings page had inconsistent naming — the settings page referred to      
  "external LLMs" and "internal LLMs" while the modal used "Cloud" and "On-Premise". Additionally, the modal did not
  indicate the user's currently selected option, making it unclear what was already active. The code also used two
  nearly identical types (LLMSelectionChoice and LLMSelectionDecision) to represent the same concept, requiring
  unnecessary mapping logic between them.

### Description

  - Fix inconsistent naming between the LLM selection modal and the user settings page by aligning translations to use
  "Cloud" and "On-Premise" consistently
  - Show the user's current LLM selection in the modal with a "Current" badge, so users can see which option is already
  active before making a change
  - Pass the current selection through the modal service so it can be highlighted in the UI
  - Combine LLMSelectionChoice (string union type) and LLMSelectionDecision (enum) into a single LLMSelectionDecision
  enum with a new NONE value for modal dismissal, eliminating redundant mapping methods
  - Add and update tests for all changed components and services

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Go to settings page /user-settings/llm-usage
3. See that translations are updated and also this is fullfilled: "The modal to choose LLM models should show the currently selected option."

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

#### Client

| Class/File | Line Coverage | Lines | Expects | Ratio |
|------------|-------------:|------:|--------:|------:|
| request-feedback-button.component.ts | 74.54% | 184 | 18 | 9.8 |
| llm-usage-settings.component.ts | 100.00% | 41 | 31 | 75.6 |
| updateLLMSelectionDecision.dto.ts | 100.00% | 10 | ? | ? |
| iris-base-chatbot.component.ts | 85.39% | 586 | 115 | 19.6 |
| llm-selection-popup.component.ts | 100.00% | 73 | 35 | 47.9 |
| llm-selection-popup.service.ts | 100.00% | 19 | 19 | 100.0 |

_Last updated: 2026-02-18 11:09:31 UTC_

### Screenshots

on premise selected:
image
image

no ai selected:
image
image

cloud ai selected:
image
image

## Summary by CodeRabbit

* **New Features**
  * Visual "Current" badge highlights your selected AI option.
  * AI selection modal opens pre-filled with your current choice for easier review and update.
  * Explicit "None" selection is recognized to indicate no AI choice.

* **Translations**
  * Terminology updated: "External" → "Cloud AI", "Internal" → "On-Premise AI".
  * Added localized label for "Current" selection in supported languages.

### CODE REVIEW

File: src/main/webapp/app/core/user/settings/llm-usage-settings/llm-usage-settings.component.ts [hunk 1]
```diff
@@ -60,5 +62,18 @@ export class LlmUsageSettingsComponent implements OnInit {
...
     }
 
+    private mapDecisionToChoice(decision: LLMSelectionDecision | undefined): LLMSelectionChoice | undefined {
+        switch (decision) {
+            case LLMSelectionDecision.CLOUD_AI:
+                return 'cloud';
+            case LLMSelectionDecision.LOCAL_AI:
+                return 'local';
+            case LLMSelectionDecision.NO_AI:
+                return 'no_ai';
```
Comment (IcanCUthere) [inline src/main/webapp/app/core/user/settings/llm-usage-settings/llm-usage-settings.component.ts]: I don't really like the usage of raw strings instead of an enums for LLMSelectionChoice. It seems like a code smell. (Not just in this location but there are a lot of other occurrences in other files)

It is defined as `export type LLMSelectionChoice = 'cloud' | 'local' | 'no_ai' | 'none';` which should be an enum in my opinion. I know this type was not introduced in this PR, but I think it would be a good idea to combine `LLMSelectionChoice` and `LLMSelectionDecision` as they are almost identical. Then we would also not need this mapping method.

File: src/main/webapp/app/core/user/shared/dto/updateLLMSelectionDecision.dto.ts [hunk 2]
```diff
@@ -5,6 +5,7 @@ export enum LLMSelectionDecision {
     CLOUD_AI = 'CLOUD_AI',
     LOCAL_AI = 'LOCAL_AI',
     NO_AI = 'NO_AI',
+    NONE = 'NONE',
```
Comment (krusche) [inline src/main/webapp/app/core/user/shared/dto/updateLLMSelectionDecision.dto.ts]: **[High]** `NONE` value risks being sent to the server

The server-side `AiSelectionDecision` enum (`src/main/java/.../core/domain/AiSelectionDecision.java`) only has `NO_AI`, `LOCAL_AI`, `CLOUD_AI`. Adding `NONE` to this client-side enum — which is also used in the `UpdateLLMSelectionDecisionDto` — means if `NONE` is accidentally passed through to a server API call, it will cause a deserialization error (400 Bad Request).

Currently the callers guard against this (e.g., `if (choice && choice !== LLMSelectionDecision.NONE)`), but it's fragile — a future caller could easily forget the guard.

Consider either:
1. Using a separate client-only type for the modal dismissal result (e.g., `type ModalResult = LLMSelectionDecision | 'DISMISSED'`), keeping the enum aligned with the server.
2. Or at minimum, adding a clear JSDoc comment that `NONE` is client-only and must never be sent to the server.

File: src/main/webapp/app/iris/overview/base-chatbot/iris-base-chatbot.component.ts [hunk 3]
```diff
@@ -274,18 +274,18 @@ export class IrisBaseChatbotComponent implements AfterViewInit {
         const choice = await this.llmModalService.open();
```
Comment (krusche) [inline src/main/webapp/app/iris/overview/base-chatbot/iris-base-chatbot.component.ts]: **[Medium]** Missing `currentSelection` parameter

`this.llmModalService.open()` is called without passing the user's current LLM selection. This means when the modal is opened from the Iris chatbot, the "Current" badge won't be displayed — inconsistent with the settings page behavior where `this.llmModalService.open(this.currentLLMSelectionDecision())` is used.

Suggested fix:
```typescript
const choice = await this.llmModalService.open(this.accountService.userIdentity()?.selectedLLMUsage);
```

File: src/main/webapp/app/core/course/overview/exercise-details/request-feedback-button/request-feedback-button.component.ts [hunk 4]
```diff
@@ -109,17 +109,17 @@ export class RequestFeedbackButtonComponent implements OnInit, OnDestroy {
         const choice = await this.llmModalService.open();
```
Comment (krusche) [inline src/main/webapp/app/core/course/overview/exercise-details/request-feedback-button/request-feedback-button.component.ts]: **[Medium]** Missing `currentSelection` parameter

Same issue as in `iris-base-chatbot.component.ts` — `this.llmModalService.open()` is called without the current selection, so the "Current" badge won't appear when the modal is opened from the feedback button.

Suggested fix:
```typescript
const choice = await this.llmModalService.open(this.accountService.userIdentity()?.selectedLLMUsage);
```

File: src/main/webapp/app/logos/llm-selection-popup.component.html [hunk 5]
```diff
@@ -89,6 +89,9 @@ <h1 id="ai-modal-title" jhiTranslate="artemisApp.llmSelectionPopup.header"></h1>
 
                     <div class="card-header">
                         <h2 jhiTranslate="artemisApp.llmSelectionPopup.cloud"></h2>
+                        @if (currentSelection === 'CLOUD_AI') {
```
Comment (krusche) [inline src/main/webapp/app/logos/llm-selection-popup.component.html]: **[Low]** String literal comparison instead of enum reference

Comparing `currentSelection === 'CLOUD_AI'` with a string literal works at runtime since TypeScript string enums have string values, but it bypasses type safety. If the enum value were ever renamed, these comparisons would silently break.

Consider exposing `LLMSelectionDecision` as a protected field in the component (similar to how `Theme` is already exposed) and comparing against it in the template:
```html
@if (currentSelection === LLMSelectionDecision.CLOUD_AI) {
```

File: src/main/webapp/app/core/user/settings/llm-usage-settings/llm-usage-settings.component.spec.ts [hunk 6]
```diff
@@ -97,65 +97,110 @@ describe('LlmUsageSettingsComponent', () => {
...
-            expect(llmModalService.open).toHaveBeenCalledOnce();
+            expect(llmModalService.open).toHaveBeenCalledWith(LLMSelectionDecision.CLOUD_AI);
             expect(updateSpy).toHaveBeenCalledWith(LLMSelectionDecision.CLOUD_AI);
         });
 
-        it('should handle local choice', async () => {
-            (llmModalService.open as jest.Mock).mockResolvedValue('local');
+        it('should handle LOCAL_AI choice', async () => {
+            component.ngOnInit();
+            (llmModalService.open as jest.Mock).mockResolvedValue(LLMSelectionDecision.LOCAL_AI);
```
Comment (krusche) [inline src/main/webapp/app/core/user/settings/llm-usage-settings/llm-usage-settings.component.spec.ts:113]: **[Nitpick]** Hardcoded expected value may confuse readers

This test is named `should handle LOCAL_AI choice` but asserts `expect(llmModalService.open).toHaveBeenCalledWith(LLMSelectionDecision.CLOUD_AI)`. This is correct because the default `mockUser` has `selectedLLMUsage: LLMSelectionDecision.CLOUD_AI`, but it reads confusingly. Consider adding a brief comment like `// default mock user has CLOUD_AI selected` to clarify why the open call receives CLOUD_AI in a LOCAL_AI test.
