### PR TITLE
`Exam mode`: Fix import with programming exercises

### LINKED ISSUE #11172: Import exam -> Does not import programming exercises
### Describe the bug

When I import an exam, the programming exercises are not imported. 

### To Reproduce

1. Import any previous exam with programming exercises 
2. You get the error (screenshot)
3. Verify the programming exercises are not imported. 
4. 

### Expected behavior

If I import an exam, all the exercises should be added also. 

### Screenshots

Image

### Which version of Artemis are you seeing the problem on?

8.2.4

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by tobias-lippert**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

#### Changes affecting Programming Exercises
Change doesn't affect VCS or CIS

### Motivation and Context

Closes #11172 

### Description

Grading criteria have previously been eagerly fetched for the target instead of the source exercise.
It should be the other way round.
Unfortunately, exam import with programming exercises was not covered with our tests. I added a test for it.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to course
4. Import an exam. Make sure the imported exam contains a programming exercise
5. The import should succeed 

#### Exam Mode Testing

Covered with the testing steps above

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
### Test Coverage

My changes are covered

## Summary by CodeRabbit

* **New Features**
  * Enhanced exam import functionality to support programming exercises with grading criteria.
  * Added utility methods to create exams containing all exercise types, including programming exercises with grading criteria.

* **Bug Fixes**
  * Resolved issues with grading criteria not being properly imported for programming exercises.

* **Tests**
  * Expanded integration tests to cover importing exams with programming exercises and their grading criteria.
  * Enabled and improved tests to verify correct handling of grading criteria during programming exercise import.
  * Added mocks and utility functions to better support programming exercise testing.

### CODE REVIEW

File: src/main/java/de/tum/cit/aet/artemis/exam/service/ExamImportService.java [hunk 1]
```diff
@@ -353,10 +354,6 @@ private void prepareProgrammingExerciseForExamImport(final ProgrammingExercise n
         newExercise.setAssessmentDueDate(null);
         newExercise.setExampleSolutionPublicationDate(null);
 
-        // Fetch grading criterion into exercise. For course exercises, this is performed before sending the exercise to the client.
-        Set<GradingCriterion> gradingCriteria = gradingCriterionRepository.findByExerciseIdWithEagerGradingCriteria(newExercise.getId());
```
Comment (tobias-lippert) [inline src/main/java/de/tum/cit/aet/artemis/exam/service/ExamImportService.java:357]: this was fetched for the wrong exercise.

**Review by jfr2102 — APPROVED** [review]
code looks good 👍

**Review by KonstiAnon — APPROVED** [review]
Code LGTM

**Review by krusche — APPROVED** [review]
Code changes look good 👍🏻 great that a server test covers the functionality now

**Review by badkeyy — APPROVED** [review]
Tested on TS3. Works as expected

**Review by chuuuun — APPROVED** [review]
tested on ts6. worked as described

**Review by timn21 — APPROVED** [review]
Tested on TS4. Importing exams with programming exercises worked as expected.
