### PR TITLE
`General`: Fix an issue during user deletion with existing conversations

### LINKED ISSUE #6365: Admin: Deleting a user fails if they participated in conversations
### Describe the bug

Users cannot be deleted if they participated in conversations.

### To Reproduce

1. As user: participate in a conversation.
2. As admin: Go to user management, try to delete the user.
3. Observe internal server error, log as below.

### Expected behavior

The user is deleted.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.1.1

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

```shell
Caused by: java.sql.BatchUpdateException: Batch entry 0 delete from jhi_user where id=5 was aborted: ERROR: update or delete on table "jhi_user" violates foreign key constraint "fk_conversation_participant_user_id" on table "conversation_participant"
  Detail: Key (id)=(5) is still referenced from table "conversation_participant".  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2367)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:560)
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
        at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:125)
        ... 186 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "jhi_user" violates foreign key constraint "fk_conversation_participant_user_id" on table "conversation_participant"
  Detail: Key (id)=(5) is still referenced from table "conversation_participant".
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        ... 193 common frames omitted
```

### PR DESCRIPTION
**Pull request by terlan98**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.

### Motivation and Context
Closes #6365 

### Description

Modified the `deleteUser(User user)` function of `UserService` to also remove the following from corresponding repositories:
- **Posts** - belonging to the user, to Conversations created by the user, to OneToOneChats where the user is a participant
- **OneToOneChats** - where the user is a participant
- **Conversations** - created by the user
- **ConversationParticipants** - created by the user

Also added necessary tests to ensure the deletion of the aforementioned objects when a mock user is deleted.

### Steps for Testing

Prerequisites:
- 1 Admin
- 2 Users (any role)
- 1 Course

1. **Log in as Admin**
2. Navigate to the Messages section of a Course
3. Create a channel that the Users can join
4. **Log in as the User that will be deleted**
5. Register to the course (if not already registered)
6. Navigate to the Messages section of the Course
7. Send a direct message to another user
8. Send a message to a group
9. Send a message to a channel
10. **Log in as the 2nd user**
11. Send a direct message to the user that will be deleted
12. **Log in as Admin**
13. Delete the user (should succeed)

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/service/user/UserService.java [hunk 1]
```diff
@@ -473,6 +486,9 @@ protected void deleteUser(User user) {
         studentScoreRepository.deleteAllByUserId(user.getId());
         learningGoalProgressRepository.deleteAllByUserId(user.getId());
         exerciseHintActivationRepository.deleteAllByUser(user);
+        postRepository.deleteAllByAuthor(user);
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/user/UserService.java:489]: This should fix #6331 then, too, right?

Comment (terlan98) [reply src/main/java/de/tum/in/www1/artemis/service/user/UserService.java:489]: I think these changes don't affect course deletion. 🤔  To solve #6331, the `delete(Course course)` function in `CourseService` should be changed instead.

Comment (b-fein) [reply src/main/java/de/tum/in/www1/artemis/service/user/UserService.java:489]: Oh, you are right. I misremembered my own issue. :facepalm:  I thought that was also about user deletion.

File: src/main/java/de/tum/in/www1/artemis/service/user/UserService.java [hunk 2]
```diff
@@ -473,6 +486,9 @@ protected void deleteUser(User user) {
...
+        conversationRepository.deleteAllByCreator(user);
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/user/UserService.java:490]: Should OneToOneChats also be deleted if the user is only a participant, regardless if they are the creator or not?

I assume that other code and especially the client assumes that such a conversation always has _exactly two_ participants and could potentially break here.

**Review by b-fein — COMMENTED** [review]
Thanks for the bugfix!

I’ve got one question about a special conversation case that might have to be handled, looks good otherwise.

File: src/main/java/de/tum/in/www1/artemis/service/user/UserService.java (hunk 2 above)
Comment (terlan98) [reply src/main/java/de/tum/in/www1/artemis/service/user/UserService.java:490]: Good point. I'll make the necessary changes to ensure that they are deleted.

**Review by sven0311 — DISMISSED** [review]
Tested on TS2. Works fine 👍

**Review by frederik-kt — APPROVED** [review]
Tested on TS2. Sent some messages from the user and to the user and deleted the user. All messages were gone.

**Review by TimOrtel — APPROVED** [review]
Works as expected.

**Review by mertyldrr — COMMENTED** [review]
Tested in a testing session. It worked as described.

The "deleteUser_isSuccessful" server test should be fixed before merging.

**Review by mertyldrr — DISMISSED** [review]
Re-tested on ts2. Works as expected and the server test is fixed 💯

**Review by frederik-kt — DISMISSED** [review]
Reapprove

**Review by sven0311 — DISMISSED** [review]
Reapprove

File: src/main/java/de/tum/in/www1/artemis/service/user/UserService.java [hunk 3]
```diff
@@ -474,6 +493,25 @@ protected void deleteUser(User user) {
...
+        // deleting Posts belonging to the user and belonging to the conversations created by the user
+        var conversationsByUser = conversationRepository.findAllByCreator(user);
+        conversationsByUser.forEach(conversation -> postRepository.deleteAllByConversationId(conversation.getId()));
+        postRepository.deleteAllByAuthor(user);
+
+        // deleting Posts belonging to all OneToOneChats where the user is a participant
+        var conversationParticipantEntities = conversationParticipantRepository.findConversationParticipantsByUser(user);
+        var oneToOneChatsToDelete = new HashSet<OneToOneChat>();
+        conversationParticipantEntities.forEach(participant -> oneToOneChatsToDelete.addAll(oneToOneChatRepository.findAllByConversationParticipantsContaining(participant)));
+        oneToOneChatsToDelete.forEach(oneToOneChat -> postRepository.deleteAllByConversationId(oneToOneChat.getId()));
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/user/UserService.java:505]:
```suggestion
        final Set<OneToOneChat> oneToOneChats = oneToOneChatRepository.findAllByParticipatingUser(user);
        postRepository.deleteAllByConversationIn(new HashSet<>(oneToOneChats));
```
with
```java
    @Query("""
            SELECT chat
            FROM OneToOneChat chat
                LEFT JOIN chat.conversationParticipants participants
                LEFT JOIN participants.user user
            WHERE user = :user
            """)
    Set<OneToOneChat> findAllByParticipatingUser(@Param("user") User user);
```
should reduce database calls here, too.

File: src/main/java/de/tum/in/www1/artemis/service/user/UserService.java [hunk 4]
```diff
@@ -474,6 +493,25 @@ protected void deleteUser(User user) {
...
+
+        // deleting Conversations and ConversationParticipants created by the user
+        conversationRepository.deleteAllByCreator(user);
+        conversationParticipantRepository.deleteAllByUser(user);
+
+        // deleting OneToOneChats where the user is a participant
+        oneToOneChatRepository.deleteAll(oneToOneChatsToDelete);
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/user/UserService.java:512]: I’d move this up to the `// deleting Posts belonging to all OneToOneChats where the user is a participant`-block. I think that makes it easier to follow since then all one-to-one-chat actions are resolved before moving on to the next part.

**Review by b-fein — COMMENTED** [review]
Thanks for implementing the suggestion about OneToOneChats.

I had another more detailed look at the code. I think there might be some potential to reduce the number of necessary database queries.

**Comment by terlan98** [comment]
> Thanks for implementing the suggestion about OneToOneChats.
> 
> I had another more detailed look at the code. I think there might be some potential to reduce the number of necessary database queries.

Thank you so much for your suggestions. My latest commit contains the improvements that you suggested.

**Review by b-fein — DISMISSED** [review]
Thanks, code looks good. :+1:

**Review by sven0311 — APPROVED** [review]
Retested on TS2, Still works fine 👍

**Review by frederik-kt — APPROVED** [review]
Re-tested on TS2. Deleting the user still works and all messages are gone.

**Review by mertyldrr — APPROVED** [review]
Looks good to me. Re-approved

**Review by bassner — APPROVED** [review]

File: src/main/java/de/tum/in/www1/artemis/repository/metis/ConversationParticipantRepository.java [hunk 5]
```diff
@@ -52,12 +53,18 @@ default ConversationParticipant findConversationParticipantByConversationIdAndUs
...
 
+    Set<ConversationParticipant> findConversationParticipantsByUser(User user);
+
     Integer countByConversationId(Long conversationId);
 
     @Transactional // ok because of delete
     @Modifying
     void deleteAllByConversationId(Long conversationId);
 
+    @Transactional
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/repository/metis/ConversationParticipantRepository.java:64]:
```suggestion
    @Transactional // ok because of delete
```

File: src/main/java/de/tum/in/www1/artemis/repository/metis/PostRepository.java [hunk 6]
```diff
@@ -57,11 +60,23 @@ default Page<Post> findPosts(PostContextFilter postContextFilter, Long userId, b
         }
     }
 
+    @Transactional
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/repository/metis/PostRepository.java:63]:
```suggestion
    @Transactional // ok because of delete
```

File: src/main/java/de/tum/in/www1/artemis/repository/metis/PostRepository.java [hunk 7]
```diff
@@ -57,11 +60,23 @@ default Page<Post> findPosts(PostContextFilter postContextFilter, Long userId, b
...
+    @Modifying
+    void deleteAllByConversationIn(Set<OneToOneChat> oneToOneChats);
+
     @Transactional
     @Modifying
     // ok because of delete
     void deleteAllByConversationId(Long conversationId);
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/repository/metis/PostRepository.java:70]:
```suggestion
    @Transactional // ok because of delete
    @Modifying
    void deleteAllByConversationId(Long conversationId);
```

File: src/main/java/de/tum/in/www1/artemis/repository/metis/PostRepository.java [hunk 8]
```diff
@@ -57,11 +60,23 @@ default Page<Post> findPosts(PostContextFilter postContextFilter, Long userId, b
...
 
+    @Transactional
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/repository/metis/PostRepository.java:72]:
```suggestion
    @Transactional // ok because of delete
```

File: src/main/java/de/tum/in/www1/artemis/repository/metis/PostRepository.java [hunk 9]
```diff
@@ -57,11 +60,23 @@ default Page<Post> findPosts(PostContextFilter postContextFilter, Long userId, b
...
+    @Modifying
+    void deleteAllByConversationCreator(User user);
+
+    @Transactional
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/repository/metis/PostRepository.java:76]:
```suggestion
    @Transactional // ok because of delete
```

File: src/main/java/de/tum/in/www1/artemis/repository/metis/conversation/ConversationRepository.java [hunk 10]
```diff
@@ -17,8 +20,13 @@ public interface ConversationRepository extends JpaRepository<Conversation, Long
     @Modifying
     void deleteById(@NotNull Long conversationId);
 
+    @Transactional
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/repository/metis/conversation/ConversationRepository.java:23]:
```suggestion
    @Transactional // ok because of delete
```

**Review by krusche — CHANGES_REQUESTED** [review]
While this PR fixes the issue, it could lead to a situation where important information is lost. Let's assume, a tutor leaves (who answered many questions of students) leaves a course for whatever reasons and asks the admin to delete the corresponding user account in Artemis.

Suddenly all the tutor's messages are deleted and get lost. Potentially if the tutor creates a post, all answer posts (from other users) would need to be deleted as well.

This is an undesired behavior, in particular if students' grades depend in some way on the information posted by this particular user.

We should strive for a different solution:
1. We set the author of all the involved posts to null, then the information is still available. However, this might not be supported in some components, in particular if the code assumes that author is always **not null**
2. We create a generic user and assign the posts to this one. However, for chats this might be problematic, because the chat might now suddenly be with a different user
3. We do not delete the user any more, but simply anonymize the user removing all personal information. In the user interface, we could present such a user with "deleted user" instead of "fistname lastname".

I suggest, we discuss the implementation with some of the involved people, e.g. @bassner, @maximiliansoelch, @stefanwaldhauser and me.

**Comment by terlan98** [comment]
> While this PR fixes the issue, it could lead to a situation where important information is lost. Let's assume, a tutor leaves (who answered many questions of students) leaves a course for whatever reasons and asks the admin to delete the corresponding user account in Artemis.
> 
> Suddenly all the tutor's messages are deleted and get lost. Potentially if the tutor creates a post, all answer posts (from other users) would need to be deleted as well.
> 
> This is an undesired behavior, in particular if students' grades depend in some way on the information posted by this particular user.
> 
> We should strive for a different solution:
> 
> 1. We set the author of all the involved posts to null, then the information is still available. However, this might not be supported in some components, in particular if the code assumes that author is always **not null**
> 2. We create a generic user and assign the posts to this one. However, for chats this might be problematic, because the chat might now suddenly be with a different user
> 3. We do not delete the user any more, but simply anonymize the user removing all personal information. In the user interface, we could present such a user with "deleted user" instead of "fistname lastname".
> 
> I suggest, we discuss the implementation with some of the involved people, e.g. @bassner, @maximiliansoelch, @stefanwaldhauser and me.

Thank you for your suggestions. I understand the potential issues. I think the 3rd alternative (anonymizing the user) is the least likely to disrupt the existing components but I would be happy to discuss the options further. Would you like to discuss this on a call or under this PR?

**Comment by krusche** [comment]
Let's schedule a call

**Comment by stefanwaldhauser** [comment]
> While this PR fixes the issue, it could lead to a situation where important information is lost. Let's assume, a tutor leaves (who answered many questions of students) leaves a course for whatever reasons and asks the admin to delete the corresponding user account in Artemis.
> 
> Suddenly all the tutor's messages are deleted and get lost. Potentially if the tutor creates a post, all answer posts (from other users) would need to be deleted as well.
> 
> This is an undesired behavior, in particular if students' grades depend in some way on the information posted by this particular user.
> 
> We should strive for a different solution:
> 
> 1. We set the author of all the involved posts to null, then the information is still available. However, this might not be supported in some components, in particular if the code assumes that author is always **not null**
> 2. We create a generic user and assign the posts to this one. However, for chats this might be problematic, because the chat might now suddenly be with a different user
> 3. We do not delete the user any more, but simply anonymize the user removing all personal information. In the user interface, we could present such a user with "deleted user" instead of "fistname lastname".
> 
> I suggest, we discuss the implementation with some of the involved people, e.g. @bassner, @maximiliansoelch, @stefanwaldhauser and me.

Based on the information given, I would lean towards the third option: not deleting the user but anonymizing them. Here are some possible reasons why:

- This option preserves the integrity and continuity of the posts and chats, without losing any information or creating confusion for other users.
- This option respects the privacy and wishes of the tutor who wants to leave the course and delete their account, by removing all personal information from their profile and posts.
- This option avoids potential errors or inconsistencies that might arise from setting the author to null or assigning the posts to a generic user, which could violate some assumptions or dependencies in the code.


Of course, this option might also have some drawbacks or challenges, such as:

- How to ensure that the anonymization process is thorough and irreversible, and does not leave any traces of personal information in the database and/or logs.
- How to handle cases where the tutor might want to rejoin the course or restore their account in the future, and whether they can reclaim their posts or identity.

**Comment by terlan98** [comment]
## Our decision after the discussion
For now, the user should simply be anonymized instead of performing an actual deletion. This will ensure that we don't lose any important information, such as an important message written by a tutor that could be helpful for students. Later, we should also implement a dialog that will provide the option of a complete user deletion. This will involve the deletion of all objects related to the user. The decision should be implemented as 2 separate PRs.
