### PR TITLE
`Development`: Fix handling of enum attributes when using PostgreSQL databases

### LINKED ISSUE #10636: PostgreSQL setups broken with 8.0.0
### Describe the bug

The conversion to enums of database columns (#10603) is not properly handled in Artemis code.

This appears after the migrations itself have been fixed with #10635.

### To Reproduce

1. Try to create a new programming exercise.
2. Observe error as in log below.

Probably similar issue with posts since they also have attributes that were converted to enums.

### Expected behavior

Exercise creation works. Enums are without problems.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

develop, 8.0.0

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

```shell
2025-04-03T06:12:20.987Z  WARN 1 --- [Artemis] [cat-handler-808] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 42804
2025-04-03T06:12:20.988Z ERROR 1 --- [Artemis] [cat-handler-808] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: column "initialization_state" is of type initialization_state_enum but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 182
2025-04-03T06:12:21.025Z ERROR 1 --- [Artemis] [cat-handler-808] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
Apr 03 08:12:21 artemis-test artemis[411946]:
org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute statement [ERROR: column "initialization_state" is of type initialization_state_enum but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 182] [insert into participation (attempt,exercise_id,individual_due_date,initialization_date,initialization_state,test_run,build_plan_id,repository_url,discriminator) values (?,?,?,?,?,?,?,?,'TPEP') returning id]; SQL [insert into participation (attempt,exercise_id,individual_due_date,initialization_date,initialization_state,test_run,build_plan_id,repository_url,discriminator) values (?,?,?,?,?,?,?,?,'TPEP') returning id]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:277)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:241)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:560)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:343)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:160)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:165)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
        at jdk.proxy2/jdk.proxy2.$Proxy331.save(Unknown Source)
        at de.tum.cit.aet.artemis.programming.service.ProgrammingExerciseService.connectBaseParticipationsToExerciseAndSave(ProgrammingExerciseService.java:548)
        at de.tum.cit.aet.artemis.programming.service.ProgrammingExerciseService.createProgrammingExercise(ProgrammingExerciseService.java:312)
        at de.tum.cit.aet.artemis.programming.web.ProgrammingExerciseResource.createProgrammingExercise(ProgrammingExerciseResource.java:258)
```

### PR DESCRIPTION
**Pull request by b-fein**
You need to execute the following SQL script on local / test systems:

```
UPDATE DATABASECHANGELOG
SET MD5SUM = NULL
WHERE (ID, AUTHOR) IN (
    ('20250329-01-create-enums-postgres', 'krusche'),
    ('20250329-02-alter-columns-postgres', 'krusche'),
    ('20250329-11-create-enums-submission-postgres', 'krusche'),
    ('20250329-12-alter-columns-submission-postgres', 'krusche'),
    ('20250330-01-create-enums-postgres', 'krusche'),
    ('20250330-02a-add-enum-columns-postgres', 'krusche'),
    ('20250330-03-transform-values-postgresql', 'b-fein'),
    ('20250330-04a-rename-columns-postgres', 'krusche')
);
```

#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

Closes #10636

### Description

Use enums only for MySQL. Supporting both in Hibernate/Java code is not as easy. Therefore, PostgreSQL continues to use strings.

### Steps for Testing
1. Create a new exercise.
2. Change something & push a commit to the solution repository.
3. Create some kind of posting.

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1 (PostgreSQL)
- [ ] Test 2 (MySQL)

### Test Coverage
unchanged

@coderabbitai ignore

### CODE REVIEW

**Comment by b-fein** [comment]
ToDo: missed some use of the enum (or does it not recognise the name `submission_type_enum` vs `submission_type`?)
```
2025-04-03T06:56:36.017Z ERROR 1 --- [Artemis] [omcat-handler-6] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: type "submissiontype" does not exist
  Position: 243
2025-04-03T06:56:36.052Z ERROR 1 --- [Artemis] [omcat-handler-6] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
Apr 03 08:56:36 artemis-test artemis[418446]:
org.springframework.dao.InvalidDataAccessResourceUsageException: JDBC exception executing SQL [select count(distinct sp1_0.id) from participation sp1_0 join exercise e1_0 on e1_0.id=sp1_0.exercise_id join submission s1_0 on sp1_0.id=s1_0.participation_id where sp1_0.exercise_id=? and s1_0.submitted=true and (s1_0.jhi_type<>'ILLEGAL'::SubmissionType or s1_0.jhi_type is null) and (e1_0.due_date is null or s1_0.submission_date<=e1_0.due_date) and sp1_0.discriminator in ('SP','PESP')] [ERROR: type "submissiontype" does not exist
  Position: 243] [n/a]; SQL [n/a]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:277)
        ...
        at de.tum.cit.aet.artemis.exercise.service.ExerciseService.setAssessmentsAndSubmissionsForStatisticsDTO(ExerciseService.java:625)
        at de.tum.cit.aet.artemis.exercise.service.ExerciseService.generateCourseManagementDTOs(ExerciseService.java:567)
        at de.tum.cit.aet.artemis.exercise.service.ExerciseService.getStatisticsForCourseManagementOverview(ExerciseService.java:545)
```

File: src/main/java/de/tum/cit/aet/artemis/communication/domain/ForwardedMessage.java [hunk 1]
```diff
@@ -25,7 +27,8 @@ public class ForwardedMessage extends DomainObject {
 
     @NotNull
     @Enumerated(EnumType.STRING)
-    @Column(name = "source_type", nullable = false)
+    @JdbcType(PostgreSQLEnumJdbcType.class)
+    @Column(name = "source_type", nullable = false, columnDefinition = "post_type_enum")
```
Comment (b-fein) [inline src/main/java/de/tum/cit/aet/artemis/communication/domain/ForwardedMessage.java:31]: This is not enough to tell Hibernate the name of the enum in PostgreSQL. When it is part of a JPA query, it still tries to find a `postingtype` rather than the `posting_type_enum`.

**Review by krusche — APPROVED** [review]
