### PR TITLE
`General`: Fix exercise category selection

### LINKED ISSUE #7449: `Programming exercises`: Behavior of labels faulty and inconsistent
### Describe the bug

- When importing a programming exercise, the auto-completion for the exercise labels does not work.
- When entering the whole label manually, the color is inconsistent.
- When clicking on a label there used to be a possibility to select a color. This is not possible anymore.

### To Reproduce

1. Go to 'Course Management>Exercises'
2. Click on 'Import Programming Exercise'
3. Try to set an already existing label
4. Try to click the label and edit the color

### Expected behavior

The auto-completion should work as expected.
The coloring of the labels should be consistent even if the label is entered manually.
We should be able to select the color of a label.

### Screenshots

chrome_kJPYx1AA1x

### Which version of Artemis are you seeing the problem on?

6.6.2

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

independent

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by florian-glombik**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client

- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified
  colors only in the theming variable files and checked that the changes look consistent in both the light and the dark
  theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following
  the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Fixes #7449 and further issues that I encountered when working on the issue.

### Description

* Fixed loading of categories when importing exercises (was broken for text, modeling, and programming exercises)
* Fixed the color selection
    * Preventing that click event is emitted twice and interpreted as close event _(caused the issue that the colorpicker could not be opened)_
    * Adjust the logic for 'click-outside' to be more robust
    * Fixed "jumping" of color picker button
* Fixed transparent categories background on selection with arrow keys _(light and dark theme)_
* Fixed reactivity, when removing a category it was not displayed in the selection anymore (Text, Modeling, Quiz, FileUpload)
* Fixed placement of color picker for programming exercises
* Refactorings
    * Added utils function to reduce code duplication for scrollToTopOfPage
    * Added utils function to reduce code duplication for loading the course exercise categories
    * Refactored code for loading supported programming languages _(programming exercise creation)_

### Steps for Testing
Prerequisites:
- 1 Instructor

1. Create / Edit / Import an exercise
2. Adjust the categories of the exercise
3. See that the categories that are already present in the course can be used
4. See that the color picker opens and can be used when clicking on a category
5. See that when removing a category it can be selected again _(just disappeared from selection before)_
6. Verify that Programming Languages can Still be selected when creating a new programming exercise _(e.g. on ts1 java, python, c, haskell, kotlin, vhdl, assembler, swift, ocaml and empty should be available)_

### Testserver States

> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

#### Code Review

- [x] Code Review 1
- [x] Code Review 2

#### Manual Tests

- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage |  Confirmation (assert/expect) |
|------------|--------------:|------------------------------:|
| [exam-result-summary.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5671/latest/artifact/shared/Coverage-Report-Client-Tests/app/exam/participate/summary/exam-result-summary.component.ts.html) | 91.35% |                             ✅ |
| [file-upload-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5671/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/file-upload/manage/file-upload-exercise-update.component.ts.html) | 85.56% |                             ✅ |
| [example-modeling-submission.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5671/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/modeling/manage/example-modeling/example-modeling-submission.component.ts.html) | 92.24% |                             ✅ |
| [modeling-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5671/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/modeling/manage/modeling-exercise-update.component.ts.html) | 88.18% |                             ✅ |
| [programming-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5671/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/update/programming-exercise-update.component.ts.html) | 80.32% |                             ✅ |
| [programming-exercise-information.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5671/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/update/update-components/programming-exercise-information.component.ts.html) | 100% |                             ❌ |
| [quiz-exercise-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5671/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/quiz/manage/quiz-exercise-detail.component.ts.html) | 92.07% |                             ✅ |
| [course-utils.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5671/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/course-exercises/course-utils.ts.html) | 84.61% |                             ✅ |
| [text-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5671/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/text/manage/text-exercise/text-exercise-update.component.ts.html) | 88.34% |                             ✅ |
| [category-selector.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5671/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/category-selector/category-selector.component.ts.html) | 97.18% |                             ✅ |
| [color-selector.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5671/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/color-selector/color-selector.component.ts.html) | 100% |                             ✅ |
| [utils.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5671/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/util/utils.ts.html) | 96.29% |                             ✅ |

#### fixed version
https://github.com/ls1intum/Artemis/assets/63976129/944d8f6b-d7b2-4cff-b4f3-47a70601c219

#### broken version
* Categories not loaded on import

https://github.com/ls1intum/Artemis/assets/63976129/b3382973-ef56-4a6c-b142-91fb161c7057
* Colorpicker for programming exercises opening somewhere
  category-selection-programming-exercise-broken

* Remove category misaligned and jumping

https://github.com/ls1intum/Artemis/assets/63976129/225a413f-d95b-4b8d-a1dd-b014ad5bddeb

* Selection becomes transparent when using up and down arrows

image

* Removed category not available in selection

https://github.com/ls1intum/Artemis/assets/63976129/8d6419c0-e988-43c6-85b2-f933da2fe27a

### CODE REVIEW

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy ts2. Worked as expected. 

I have noticed two things:
1. If there is already an added category and you write something in the line, the text is not  aligned in the middle. Perhaps you should consider changing this because it will look tidier.
2. The color picker is sometimes placed somewhere and not very near to the category.

**Review by MaximilianAnzinger — APPROVED** [review]
Code lgtm

**Comment by florian-glombik** [comment]
Thanks for your reviews!

@JanaNF I am planning on addressing bought suggestions in a follow-up, as this PR already fixes a bunch of issues related to the categories! :)

File: src/main/webapp/app/shared/category-selector/category-selector.component.ts [hunk 1]
```diff
@@ -76,6 +81,13 @@ export class CategorySelectorComponent implements OnChanges {
      * @param {ExerciseCategory} tagItem
      */
     openColorSelector(event: MouseEvent, tagItem: ExerciseCategory) {
+        /**
+         * without {@link event#stopPropagation} would the color picker would close immediately as the mouseEvent
```
Comment (milljoniaer) [inline src/main/webapp/app/shared/category-selector/category-selector.component.ts:85]: Typo, one "would" is sufficient

**Review by milljoniaer — DISMISSED** [review]
Code looks good, just one typo, but no blocker. LGTM 👍

**Review by JanaNF — DISMISSED** [review]
Reapproved. Manual tested on legacy ts2. Still works. (And thanks for creating the issue with the alignment :))

**Review by milljoniaer — APPROVED** [review]

**Review by MaximilianAnzinger — DISMISSED** [review]

**Review by milljoniaer — APPROVED** [review]
re-approve

**Review by MaximilianAnzinger — APPROVED** [review]
Code

**Review by basak-akan — APPROVED** [review]
Tested on TS1, works as described.

**Review by JanaNF — CHANGES_REQUESTED** [review]
Manual tested on ts2. Things described worked as expected, but if I add a category, which name is longer than the text field, the name goes over the text field layout. 
image
