### PR TITLE
`Assessment`: Fix issues in the scores view for multiple correction rounds and file upload exercises

### LINKED ISSUE #6395: Cannot open Assessments from Score Page
### Describe the bug

Since the "Submission" Page has been removed in #6110 , we have to use the new "Score" Page to open certain assessments.

Unfortunately, this is not possible in our case:
image
 We get an error while clicking on open assessment (for exam tasks with two correction rounds enabled) (Error in the additional comments)

In addition, we wonder about these points:

1. If we click on open editor, we get an editor where we can modify the code and click on a submit button (even after the end of the exam)
image

2. How can we create the assessment of the first (or second round manually), before the merge, this was possible in the submission view. This was very useful to do some manual grading for special submissions.

### To Reproduce

See above

### Expected behavior

No error, and opening of assessment

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.1.2

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

```shell
ERROR Error: Uncaught (in promise): Error: NG04002
P@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1307751
noMatchError@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1539989
apply/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1539726
D/</f<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1115041
t/this._error<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1114505
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
v@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1113284
_trySubscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098710
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098655
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
D/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1115134
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
t/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1117598
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
j@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1118298
U@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1118227
t/this._next<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1114436
next@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1102915
R/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1111824
_trySubscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098710
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098655
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
y@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1118497
f/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1118548
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
g/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1119228
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
Te/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1505143
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
D/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1122455
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
t/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1117598
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
t/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1117598
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
D/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1114992
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
t/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1117598
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
D/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1120986
t/this._next<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1114436
next@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1102915
D/</</m<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1121013
t/this._next<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1114436
next@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1102915
A/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1111932
invoke@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:9156
onInvoke@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1412867
invoke@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:9096
run@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:4508
ue/<@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:19366
invokeTask@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:9774
onInvokeTask@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1412680
invokeTask@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:9695
runTask@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:5131
p@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:11794
invokeTask@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:10858
O@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:23363
I@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:23661
M@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:23926
```
```

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Fix #6395
Additionally fix issue where unassessed file upload participations where not shown in the scores table.

### Description

The scores table now correctly displays the buttons for each assessment of different correction rounds in exams.
Additionally file upload exercises are correctly displayed and allow the redirection to their assessment view.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 File Upload exercise

1. Log in to Artemis
2. Participate as student
3. Verify that the buttons in the scores table still work and redirect the instructor to the correct assessment.

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Exam with two correction rounds

1. Log in to Artemis
2. Participate in the exam as a student
3. Go to the scores table of an exercise and verify that the buttons correctly work in each of these three scenarios:
- Before all assessments
- After the assessment of the first correction round
- After the assessment in the second correction round

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual in Exam mode Tests
- [ ] Test 1
- [ ] Test 2
#### Manual Test verifying that course exercises work
- [ ] Test

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| ParticipationResource.java | 69% | 91% |
| exercise-scores.component.ts.ts | 76% | 90% |

### Screenshots

Bildschirmfoto 2023-04-04 um 15 57 35

### CODE REVIEW

**Review by 1999Markus — DISMISSED** [review]
Worked as expected on ts1. 👍

File: src/main/java/de/tum/in/www1/artemis/repository/StudentParticipationRepository.java [hunk 1]
```diff
@@ -194,9 +194,10 @@ default StudentParticipation findByExerciseIdAndStudentIdAndTestRunWithEagerSubm
             LEFT JOIN FETCH r.submission s
             WHERE p.exercise.id = :#{#exerciseId}
                 AND (r.id = (SELECT max(id) FROM p.results)
+                    OR r.assessmentType <> 'AUTOMATIC'
                     OR r IS NULL)
             """)
-    Set<StudentParticipation> findByExerciseIdWithLatestResult(@Param("exerciseId") Long exerciseId);
+    Set<StudentParticipation> findByExerciseIdWithLatestResults(@Param("exerciseId") Long exerciseId);
```
Comment (julian-christl) [inline src/main/java/de/tum/in/www1/artemis/repository/StudentParticipationRepository.java:200]: imo you should include `manual` in the method name. As you have a manual query, that's not an issue anyway.

File: src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html [hunk 2]
```diff
@@ -305,42 +305,82 @@ <h5 jhiTranslate="artemisApp.exercise.export.options"></h5>
...
+                                <ng-container *ngFor="let correctionRound of correctionRoundIndices">
+                                    <div
+                                        *ngIf="(correctionRound == 0 || value.results?.[correctionRound - 1]?.completionDate) &&
+                                        (newManualResultAllowed || (value.results?.[correctionRound]?.assessmentType && value.results[correctionRound].assessmentType !== AssessmentType.AUTOMATIC))"
+                                    >
+                                        <a
+                                            [routerLink]="getAssessmentLink(value, correctionRound)"
+                                            [queryParams]="{ 'correction-round': correctionRound }"
+                                            class="btn btn-sm me-1 mb-2"
+                                            [class.btn-success]="(!value.results?.[correctionRound]?.assessmentType || value.results?.[correctionRound].assessmentType === AssessmentType.AUTOMATIC) && !value.results?.[0]?.hasComplaint"
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html:318]:
```suggestion
                                            [class.btn-success]="(!value.results?.[correctionRound]?.assessmentType || value.results?.[correctionRound].assessmentType === AssessmentType.AUTOMATIC) && !value.results?.[correctionRound]?.hasComplaint"
```

Did you forget that one?

File: src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html [hunk 3]
```diff
@@ -305,42 +305,82 @@ <h5 jhiTranslate="artemisApp.exercise.export.options"></h5>
...
+                                                {{ 'artemisApp.exerciseAssessmentDashboard.showComplaint' | artemisTranslate }}
+                                            </ng-template>
+                                        </a>
+                                        <button
+                                            *ngIf="
                                         newManualResultAllowed &&
-                                        value.results[0]?.assessmentType &&
+                                        value.results?.[0]?.assessmentType &&
                                         !value.results[0].completionDate &&
                                         value.results[0].assessmentType !== AssessmentType.AUTOMATIC
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html:338]:
```suggestion
                                        value.results?.[correctionRound]?.assessmentType &&
                                        !value.results[correctionRound].completionDate &&
                                        value.results[correctionRound].assessmentType !== AssessmentType.AUTOMATIC
```

Needed? If not, I think it might be hard to understand when what is needed why.

File: src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html [hunk 4]
```diff
@@ -305,42 +305,82 @@ <h5 jhiTranslate="artemisApp.exercise.export.options"></h5>
...
                                     "
-                                    (click)="cancelAssessment(value.results[0].submission)"
-                                    [disabled]="isLoading"
-                                    class="btn btn-danger btn-sm mb-1"
-                                >
-                                    <fa-icon [fixedWidth]="true" [icon]="faBan"></fa-icon>&nbsp;{{ 'artemisApp.assessment.dashboard.actions.cancel' | artemisTranslate }}
-                                </button>
-                            </div>
+                                            (click)="cancelAssessment(value.results[0])"
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html:340]:
```suggestion
                                            (click)="cancelAssessment(value.results[correctionRound])"
```

Same question here

File: src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html [hunk 5]
```diff
@@ -305,42 +305,82 @@ <h5 jhiTranslate="artemisApp.exercise.export.options"></h5>
...
+                                </ng-container>
+                            </ng-container>
+                            <ng-template #singleCorrectionRound>
+                                <div *ngIf="(newManualResultAllowed || (value.results?.[0]?.assessmentType && value.results[0].assessmentType !== AssessmentType.AUTOMATIC))">
+                                    <a
+                                        [routerLink]="getAssessmentLink(value)"
+                                        class="btn btn-sm me-1"
+                                        [class.btn-success]="(!value.results?.[0]?.assessmentType || value.results?.[0].assessmentType === AssessmentType.AUTOMATIC) && !value.results?.[0]?.hasComplaint"
+                                        [class.btn-primary]="value.results?.[0]?.completionDate || value.results?.[0]?.hasComplaint"
+                                        [class.btn-warning]="!value.results?.[0]?.completionDate && !value.results?.[0]?.hasComplaint"
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html:356]:
```suggestion
                                        [class.btn-warning]="value.results[0]&& !value.results?.[0]?.completionDate && !value.results?.[0]?.hasComplaint"
```

File: src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html
Comment (julian-christl) [inline src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html:1]: I'm not sure about these changes.

If I see this correctly, the only differences in both cases (multi and single) are in the `a`-tag (router link and query params) the translation within the `a`-tag and one if-conditional (however, that already includes the exception for correction Round 0).

Is there a reason you didn't choose to only adapt the `a`-tag for both cases differently? It seems like lots of unnecessary duplication to me.

File: src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.ts [hunk 6]
```diff
@@ -382,20 +387,20 @@ export class ExerciseScoresComponent implements OnInit, OnDestroy {
...
             this.exercise.type,
             this.course.id,
             this.exercise.id,
             participation.id,
-            newAssessment ? 'new' : participation.results[0].submission.id,
+            newAssessment ? 'new' : participation.results![correctionRound].submission!.id!,
             this.exercise.exerciseGroup?.exam?.id,
             this.exercise.exerciseGroup?.id,
-            participation.results[0].id,
+            participation.results?.[correctionRound]?.id,
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.ts:403]: Why do you assume the results as optional here, but also required in line 400?

File: src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html [hunk 7]
```diff
@@ -305,42 +305,49 @@ <h5 jhiTranslate="artemisApp.exercise.export.options"></h5>
...
+                                    (newManualResultAllowed || (value.results?.[correctionRound]?.assessmentType && value.results[correctionRound].assessmentType !== AssessmentType.AUTOMATIC))"
                                 >
-                                    <fa-icon [icon]="faFolderOpen" [fixedWidth]="true"></fa-icon>
-                                    <ng-container *ngIf="!value.results?.[0].hasComplaint; else courseComplaint">
-                                        {{ ('artemisApp.assessment.dashboard.actions.' +
-                                            (!value.results?.[0]?.assessmentType || value.results?.[0].assessmentType === AssessmentType.AUTOMATIC ? 'assess' : (value.results?.[0]?.completionDate ? 'open' : 'continue')))
-                                            | artemisTranslate
+                                    <a
+                                        [routerLink]="getAssessmentLink(value, correctionRound)"
+                                        [queryParams]="this.exercise.exerciseGroup ? { 'correction-round': correctionRound } : {}"
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html:315]: Previously, the conditional on whether to render the multi or the single variant was `correctionRoundIndices?.length && correctionRoundIndices.length > 1`. Now you check the exerciseGroup.

What's the reason behind this change? Did you do it on purpose?

File: src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html [hunk 8]
```diff
@@ -305,42 +305,49 @@ <h5 jhiTranslate="artemisApp.exercise.export.options"></h5>
...
+                                        "
+                                        (click)="cancelAssessment(value.results[correctionRound])"
+                                        [disabled]="isLoading"
+                                        class="btn btn-danger btn-sm mb-1"
+                                    >
+                                        <fa-icon [fixedWidth]="true" [icon]="faBan"></fa-icon>&nbsp;
+                                        {{
+                                            'artemisApp.assessment.dashboard.actions.' + (this.exercise.exerciseGroup ? 'examCorrectionRound.' : '') + 'cancel'
+                                                | artemisTranslate : { correctionRound: correctionRound + 1 }
                                         }}
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.html:347]:
```suggestion
                                        <fa-icon [fixedWidth]="true" [icon]="faBan"></fa-icon>
                                        <span>
                                        {{
                                            'artemisApp.assessment.dashboard.actions.' + (this.exercise.exerciseGroup ? 'examCorrectionRound.' : '') + 'cancel'
                                                | artemisTranslate : { correctionRound: correctionRound + 1 }
                                        }}
                                        </span>
```

**Review by julian-christl — COMMENTED** [review]
Very nice. That looks way better.

File: src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.ts (hunk 6 above)
Comment (JohannesStoehr) [reply src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.ts:403]: In line 400 is the ternary that makes sure that the results are present

Comment (julian-christl) [reply src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.ts:403]: I'm not talking about the teneary itself.

line 403: `participation.results?.[correctionRound]?.id`
line 400: `participation.results![correctionRound].submission!.id!`

One time `results?.`, one time `results!`. Either you are sure about the results array existing, then you should mark it in line 403 as existing too, or you aren't, then the results array in line 400 could be undefined too.

Comment (JohannesStoehr) [reply src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.ts:403]: The condition in the ternary is making sure that the results are present in the else part of the ternary.
So I'm sure that the results array is present in line 400 but not in 403

Comment (julian-christl) [reply src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.ts:403]: Ah, I get it. I rechhecked where newAssessment comes from. Makes sense then. Sorry.

**Review by julian-christl — APPROVED** [review]
Thank you for the updates. Code looks good.
