### PR TITLE
`Plagiarism checks`: Avoid displaying unrelated posts in plagiarism cases view

### LINKED ISSUE #5407: `Plagiarism checks`  The posts in the communication are shown in the plagiarism case view when this view is open.
### Describe the bug

If you have opened the plagiarism case view and someone posts anything, you will see the post in the plagiarism case view that post. 

### To Reproduce

First tab
1. Click on course manager
2. Click on Plagiarism Checks
3. Click on a plagiarism case

Second Tab
1. Click on course manager
2. Click on a current exercise 
3. In the communication section post anything
4. check if you can see that post also in the First Tab. 

SEE THE SCREENCAST

### Expected behavior

The plagiarism check view should not show the posts. 

### Screenshots

https://user-images.githubusercontent.com/88991954/179260749-fc57e58a-7548-4b8f-b994-e3863ef753b9.mov

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by akesfeden**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

Closes #5407. Prevents posts sent from Communication view from appearing in Plagiarism Cases view.
### Description

Filters the posts by `plagiarismCase.id` in the post subscription to avoid unrelated post updates from modifying the posts.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Exercise with Plagiarism

1. Follow the "To Reproduce" steps at #5407 and ensure the issue is not reproducible anymore.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| plagiarism-case-instructor-detail-view.component.ts | 82.92% | 94.11% |

### CODE REVIEW

**Review by Santia-go — DISMISSED** [review]
Tested on TS1
Issue #5407 has been fixed. Thank you!

File: src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts [hunk 1]
```diff
@@ -46,8 +46,13 @@ export class PlagiarismCaseInstructorDetailViewComponent implements OnInit, OnDe
...
         });
-        this.postsSubscription = this.metisService.posts.pipe().subscribe((posts: Post[]) => {
-            this.posts = posts;
+        this.postsSubscription = this.metisService.posts.subscribe((posts: Post[]) => {
+            const filteredPosts = posts?.filter((post) => post.plagiarismCase?.id === this.plagiarismCaseId);
+
+            // Handle post deletion case by checking if unfiltered posts are empty.
+            if (filteredPosts.length > 0 || posts.length === 0) {
+                this.posts = filteredPosts;
+            }
```
Comment (JohannesStoehr) [inline src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts:55]:
```suggestion
            if (filteredPosts.length > 0) {
                this.posts = filteredPosts;
            }
```
If the length of posts and filteredPosts is both 0, I don't see a reason, why we should override the variable

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]

File: src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts (hunk 1 above)
Comment (JohannesStoehr) [reply src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts:55]: Why does it matter if `posts.length > 0` is the case, when you check `filteredPosts.length >= 0`?
You would simply override the posts with the filteredPosts in that case

Comment (akesfeden) [reply src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts:55]: Probably the version below would be more explicit, I tried to be concise and made use of the fact that if `posts.length === 0` then `filteredPosts.length` also be 0 and it won't make a difference which array is assigned. But I can change it with the version below if that seems better.
```
 if (posts.length === 0) {
    this.posts = posts;
    return;
}
 if (filteredPosts.length > 0) {
    this.posts = filteredPosts;
}
```

Comment (JohannesStoehr) [reply src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts:55]: But if `posts.length === 0` implies `filteredPosts.length === 0` and you already check `filteredPosts.length > 0`, `filteredPosts.length >== 0` should cover both cases and you can always use fileredPosts to override the variable

Comment (akesfeden) [reply src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts:55]: `filteredPosts.length >= 0` behaves differently when `posts.length > 0` and `filteredPosts.length === 0`, if I didn't overlook something. This distinction can be important if another unrelated post is deleted from the Communication section and it may cause our plagiarism post to be unintentionally removed from the `posts` array.

Comment (JohannesStoehr) [reply src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts:55]: You're right. Could you add a small comment above that statement, which explains it?

**Review by rhubinger — APPROVED** [review]
Tested on TS1, the bug didn't reappear.

File: src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts (hunk 1 above)
Comment (akesfeden) [reply src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts]: I added it at https://github.com/ls1intum/Artemis/pull/5528/commits/2fa496fdd5f40be0aa22b93985dc6e1f4af4f4d3

**Review by JohannesStoehr — APPROVED** [review]
Code looks good. Thanks for clarifying the condition

**Review by rhubinger — APPROVED** [review]
Reapprove due to added comment.

**Review by Santia-go — DISMISSED** [review]
Tested on TS1. 
Still working as expected.

File: src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts [hunk 2]
```diff
@@ -46,8 +46,15 @@ export class PlagiarismCaseInstructorDetailViewComponent implements OnInit, OnDe
                 this.createEmptyPost();
             },
         });
-        this.postsSubscription = this.metisService.posts.pipe().subscribe((posts: Post[]) => {
-            this.posts = posts;
+        this.postsSubscription = this.metisService.posts.subscribe((posts: Post[]) => {
+            const filteredPosts = posts?.filter((post) => post.plagiarismCase?.id === this.plagiarismCaseId);
```
Comment (bassner) [inline src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts:50]: We don't need that here. If ``posts`` were a falsy value, it would throw an error in line 53 as you check the length of undefined references there. If you want to check it, just add a
```js
if (!posts) (
    return;
}
```
---
```suggestion
            const filteredPosts = posts.filter((post) => post.plagiarismCase?.id === this.plagiarismCaseId);
```

File: src/test/javascript/spec/component/plagiarism/plagiarism-case-instructor-detail-view.component.spec.ts [hunk 3]
```diff
@@ -120,4 +122,54 @@ describe('Plagiarism Cases Instructor View Component', () => {
...
+        const metisPostsSpy = jest.spyOn(fixture.debugElement.injector.get(MetisService), 'posts', 'get');
+        const postsSubject = new ReplaySubject<Post[]>(1);
+        metisPostsSpy.mockReturnValue(postsSubject.asObservable());
+
+        postsSubject.next([]);
+
+        component.ngOnInit();
+        tick();
+
+        expect(component.posts).toHaveLength(0);
```
Comment (bassner) [inline src/test/javascript/spec/component/plagiarism/plagiarism-case-instructor-detail-view.component.spec.ts:136]:
```suggestion
        expect(component.posts).toBeEmpty();
```

File: src/test/javascript/spec/component/plagiarism/plagiarism-case-instructor-detail-view.component.spec.ts [hunk 4]
```diff
@@ -120,4 +122,54 @@ describe('Plagiarism Cases Instructor View Component', () => {
...
+
+        const relevantPost = { id: 1, plagiarismCase: { id: component.plagiarismCaseId } };
+        postsSubject.next([relevantPost]);
+        tick();
+
+        expect(component.posts).toHaveLength(1);
+        expect(component.posts[0].id).toBe(relevantPost.id);
+
+        postsSubject.next([]);
+        expect(component.posts).toHaveLength(0);
```
Comment (bassner) [inline src/test/javascript/spec/component/plagiarism/plagiarism-case-instructor-detail-view.component.spec.ts:173]:
```suggestion
        expect(component.posts).toBeEmpty();
```

File: src/test/javascript/spec/component/plagiarism/plagiarism-case-instructor-detail-view.component.spec.ts [hunk 5]
```diff
@@ -120,4 +122,54 @@ describe('Plagiarism Cases Instructor View Component', () => {
...
+        const metisPostsSpy = jest.spyOn(fixture.debugElement.injector.get(MetisService), 'posts', 'get');
+        const postsSubject = new ReplaySubject<Post[]>(1);
+        metisPostsSpy.mockReturnValue(postsSubject.asObservable());
+
+        postsSubject.next([]);
+
+        component.ngOnInit();
+        tick();
+
+        expect(component.posts).toHaveLength(0);
```
Comment (bassner) [inline src/test/javascript/spec/component/plagiarism/plagiarism-case-instructor-detail-view.component.spec.ts:163]:
```suggestion
        expect(component.posts).toBeEmpty();
```

**Review by bassner — CHANGES_REQUESTED** [review]
I'm sorry for dropping a few last refactoring comments below :)
Tests will still be valid after changing this

File: src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts (hunk 2 above)
Comment (akesfeden) [reply src/main/webapp/app/course/plagiarism-cases/instructor-view/detail-view/plagiarism-case-instructor-detail-view.component.ts]: Makes sense, thanks 👍

**Review by bassner — APPROVED** [review]
Thanks, LGTM!
