### PR TITLE
`Lectures`: Fix lecture unit names not trimmed

### LINKED ISSUE #5839: `Lecture Units`: Titles don't get trimmed
### Describe the bug

When trying to delete a lecture unit, it sometimes happens that the delete button is not available, even though the name was copied correctly. Adding an additional space at the end or beginning then allows the deletion:
grafik
grafik

The name should get trimmed when saving the lecture to prevent this

### To Reproduce

1. Create a Lecture Unit with a space at the beginning / end
2. Try to delete the unit

### Expected behavior

Names should get trimmed, deletion should work.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tobias-lippert**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.
### Motivation and Context
Closes #5839 

### Description
Lecture unit names are now trimmed, whenever the name is set.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Course where you can create lectures and lecture units.

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to a course
4. Create a lecture
5. Create all kinds of lecture units with a name containing leading and/or trailing spaces.
6. Try to delete all lecture units again. Just type the name without any additional leading or trailing whitespace. Once the name is typed, the delete button should be enabled.
#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

File: src/test/java/de/tum/in/www1/artemis/lecture/TextUnitIntegrationTest.java [hunk 1]
```diff
@@ -69,6 +69,7 @@ void testAll_asStudent() throws Exception {
     void createTextUnit_asEditor_shouldCreateTextUnitUnit() throws Exception {
         var persistedTextUnit = request.postWithResponseBody("/api/lectures/" + this.lecture.getId() + "/text-units", textUnit, TextUnit.class, HttpStatus.CREATED);
         assertThat(persistedTextUnit.getId()).isNotNull();
+        assertThat(persistedTextUnit.getName()).isEqualTo(textUnit.getName().strip());
```
Comment (Strohgelaender) [inline src/test/java/de/tum/in/www1/artemis/lecture/TextUnitIntegrationTest.java:72]: We should assert actual values in the test cases instead of duplicating production logic.
```suggestion
        assertThat(persistedTextUnit.getName()).isEqualTo("LoremIpsum");
```

**Review by Strohgelaender — APPROVED** [review]
code looks good. thanks for the fix!

**Review by tunargs — APPROVED** [review]
Tested on ts1 and works as expected

**Review by LiaLism — APPROVED** [review]
Everything works as expected. Tested on ts1.

**Review by bensofficial — APPROVED** [review]

**Review by ge65cer — APPROVED** [review]

**Review by krusche — APPROVED** [review]
