### PR TITLE
`Programming exercises`: Improve consistency check

### LINKED ISSUE #6591: `Programming exercise`: Add consistency checks for auxiliary repositories
### Describe the bug

In production we had an issue where an exercise with auxiliary repositories was unable to be imported.
This was seemingly due to the fact that the auxiliary repository was incorrectly used:
- Aux repo was created
- Aux repo was deleted & recreated or renamed on BitBucket
- Aux repo was removed from the build plans
- Importing the exercise failed when trying to import the aux repo
    - The new aux repo was created
    - No code was pushed (likely because the original one does not exist anymore)
    - It was not possible to delete the exercise anymore

### To Reproduce

See above.

### Expected behavior

What should be done to prevent this from happenining again (by Stephan):
1. When pressing the “Check Consistency” Button in the programming exercise details page, we should check for issues in the aux repos as well and display those. Right now the consistency check passes, even if the referenced aux repo does not exist any more (it was probably never tested with aux repos)
2. Before actually importing an exercise, we should do the consistency check on the source exercise (I guess this is partly done implicitly during the input validation, however, reusing the consistency check logic might be better, because it would be easier to maintain this in the future). If the (improved) consistency check fails for the source exercise, Artemis will show the corresponding error message and do not even try to import the exercise (to avoid follow-up issues). One additional check before the import should be to validate if an exercise with the same name already exists in the course (including checks for VCS projects and CI projects), then we could ask the instructor to use a different name to avoid follow-up errors.
3. We could execute the consistency check automatically when navigating into the (instructor’s) programming exercise details page. Instructors won’t do that often, so this would not be a high performance impact, but the information that an exercise config is incorrect is really important
4. (Small side issue: The tooltip for aux repos in the exercise details view does not work properly, see repo list screenshot)

### Screenshots

Source exercise BitBucket:
grafik
Source exercise repo list:
grafik

Imported exercise:
grafik

### Which version of Artemis are you seeing the problem on?

6.1.7

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

_No response_

### Relevant log output

Seems to be some related Sentry events: [Search](https://sentry.ase.in.tum.de/organizations/artemis/issues/?query=is%3Aunresolved+NUMPROTEST22SPA2&referrer=issue-list&statsPeriod=14d)

### PR DESCRIPTION
**Pull request by Hialus**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

Closes #6591

### Description

- Added aux repos to consistency check
- Added consistency check before importing a PE
- Added consistency check call when instructor navigates to PE detail view
- Adjusted tests
- Added a new rule to the `.editorconfig` file regarding *-imports
- Improved an inefficient `findAll` call in the test cases

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming Exercise with aux repos

1. Log in to Artemis
2. Navigate to the exercise detail page
3. Go to the aux repo on BitBucket
4. Delete the aux repo on BitBucket
5. Reload the exercise detail page
6. You should see an alert that the exercise is inconsistent
7. Actually running the consistency check via the button shows that the aux repo is missing
8. Importing the exercise also gives an error

#### Exam Mode Testing

- Same as normal testing, but for exam exercises and import

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [consistency-check-result.model.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4897-4/artifact/shared/Coverage-Report-Client-Tests/app/entities/consistency-check-result.model.ts.html) | 100% | ✅ |
| [programming-exercise-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4897-4/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/programming-exercise-detail.component.ts.html) | 66.81% | ✅ (Was already this low before)|
| [programming-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4897-4/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/update/programming-exercise-update.component.ts.html) | 80.09% | ✅ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [ConsistencyCheckService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4897-4/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/ConsistencyCheckService.html) | 95% | ✅ |
| [ProgrammingExerciseExportImportResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4897-4/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/ProgrammingExerciseExportImportResource.html) | 95% | ✅ |

### Screenshots

grafik

grafik

grafik

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java [hunk 1]
```diff
@@ -41,17 +41,15 @@
...
 import de.tum.in.www1.artemis.service.exam.ExamAccessService;
 import de.tum.in.www1.artemis.service.feature.Feature;
 import de.tum.in.www1.artemis.service.feature.FeatureToggle;
 import de.tum.in.www1.artemis.service.programming.*;
 import de.tum.in.www1.artemis.web.rest.dto.RepositoryExportOptionsDTO;
-import de.tum.in.www1.artemis.web.rest.errors.AccessForbiddenException;
-import de.tum.in.www1.artemis.web.rest.errors.BadRequestAlertException;
-import de.tum.in.www1.artemis.web.rest.errors.EntityNotFoundException;
-import de.tum.in.www1.artemis.web.rest.errors.InternalServerErrorException;
+import de.tum.in.www1.artemis.web.rest.errors.*;
```
Comment (julian-christl) [inline src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java:52]: Code alert

File: src/main/webapp/i18n/de/consistencyCheck.json [hunk 2]
```diff
@@ -10,12 +10,15 @@
                 "VCS_PROJECT_MISSING": "Fehlendes VCS Projekt",
                 "TEMPLATE_REPO_MISSING": "Fehlendes Vorlagen-Repository",
                 "SOLUTION_REPO_MISSING": "Fehlendes Lösung-Repository",
+                "AUXILIARY_REPO_MISSING": "Fehlendes Hilfs-Repository",
                 "TEST_REPO_MISSING": "Fehlendes Test-Repository",
                 "TEMPLATE_BUILD_PLAN_MISSING": "Fehlender Build-Plan für die Vorlage",
-                "SOLUTION_BUILD_PLAN_MISSING": "Fehlender Build-Plan für die Lösung"
+                "SOLUTION_BUILD_PLAN_MISSING": "Fehlender Build-Plan für die Lösung",
+                "programmingExerciseImportFailed": "Importieren der Programmieraufgabe fehlgeschlagen. Quellaufgabe ist inkonsistent."
```
Comment (julian-christl) [inline src/main/webapp/i18n/de/consistencyCheck.json:17]: This sounds very abstract. Without the context of this PR I would not be sure what this means and how to solve the issue.

File: src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts
Comment (julian-christl) [inline src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts:1]: Do I see it correctly that we now check for consistency every time we open the detail page of a programming exercise?

Isn't that too much? Don't we already have a button that allows us to check this on demand? Do we actually want to monitor it that strictly?

File: src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java [hunk 3]
```diff
@@ -171,6 +172,12 @@ public ResponseEntity<ProgrammingExercise> importProgrammingExercise(@PathVariab
                 .findByIdWithEagerTestCasesStaticCodeAnalysisCategoriesHintsAndTemplateAndSolutionParticipationsAndAuxRepos(sourceExerciseId)
                 .orElseThrow(() -> new EntityNotFoundException("ProgrammingExercise", sourceExerciseId));
 
+        var consistencyErrors = consistencyCheckService.checkConsistencyOfProgrammingExercise(originalProgrammingExercise);
+        if (!consistencyErrors.isEmpty()) {
+            // TODO: send error message to client and handle it accordingly
```
Comment (julian-christl) [inline src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java:177]: Can this TODO be removed? You already handle it in the client, don't you?

File: src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts
Comment (Hialus) [reply src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts:1]: It is only checked if the instructor opens the page. Stephans thinks this is acceptable, as this does not happen that often. And the button is apparently not used often enough.

File: src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java (hunk 1 above)
Comment (Hialus) [reply src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java:52]: I think this is fine here. IntelliJ automatically does this, since we use a lot of classes from that package. So it would likely be a constant effort to not use * here.
In this file we also have * imports for some other packages.

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
Code looks good to me, but left one comment.
(I especially like the new test methods 😉)

File: src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java (hunk 1 above)
Comment (julian-christl) [reply src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java:52]: We might want to consider using the "Flag as Tolerated" functionality in Teamscale, then.
At least assuming that this will prevent it from being flagged in the future.

File: src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts
Comment (julian-christl) [reply src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts:1]: Alright. Let's monitor this.

File: src/main/webapp/app/exercises/programming/manage/update/programming-exercise-update.component.ts [hunk 4]
```diff
@@ -625,11 +625,19 @@ export class ProgrammingExerciseUpdateComponent implements OnInit {
...
-        const errorMessage = error.headers.get('X-artemisApp-alert')!;
+        let errorMessage;
+        let disableTranslation = true;
+        // Workaround for conflict error, since conflict errors do not have the 'X-artemisApp-alert' header
+        if (error.status === 409 && error.error && error.error['X-artemisApp-error'] === 'error.sourceExerciseInconsistent') {
+            errorMessage = 'artemisApp.consistencyCheck.error.programmingExerciseImportFailed';
+            disableTranslation = false;
+        } else {
+            errorMessage = error.headers.get('X-artemisApp-alert')!;
+        }
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/programming/manage/update/programming-exercise-update.component.ts:636]:
```suggestion
        let errorMessage = error.headers.get('X-artemisApp-alert')!;
        let disableTranslation = true;
        // Workaround for conflict error, since conflict errors do not have the 'X-artemisApp-alert' header
        if (error.status === 409 && error.error && error.error['X-artemisApp-error'] === 'error.sourceExerciseInconsistent') {
            errorMessage = 'artemisApp.consistencyCheck.error.programmingExerciseImportFailed';
            disableTranslation = false;
        }
```
Or the other way around. But currently, you handle assigning values in two different ways here.

File: src/main/webapp/i18n/en/consistencyCheck.json [hunk 5]
```diff
@@ -10,12 +10,15 @@
                 "VCS_PROJECT_MISSING": "Missing VCS project",
                 "TEMPLATE_REPO_MISSING": "Missing template repository",
                 "SOLUTION_REPO_MISSING": "Missing solution repository",
+                "AUXILIARY_REPO_MISSING": "Missing auxiliary repository",
                 "TEST_REPO_MISSING": "Missing test repository",
                 "TEMPLATE_BUILD_PLAN_MISSING": "Missing template build plan",
-                "SOLUTION_BUILD_PLAN_MISSING": "Missing solution build plan"
+                "SOLUTION_BUILD_PLAN_MISSING": "Missing solution build plan",
+                "programmingExerciseImportFailed": "Import of programming exercise failed, as the source exercise is inconsistent. Please run the consistency check on the source exercise for more details."
```
Comment (julian-christl) [inline src/main/webapp/i18n/en/consistencyCheck.json:17]:
```suggestion
                "programmingExerciseImportFailed": "Import of programming exercise failed, as the source exercise is inconsistent. Please see the consistency check on the source exercise for more details."
```
For consistency

File: src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseIntegrationTestService.java [hunk 6]
```diff
@@ -2166,4 +2169,25 @@ void test_redirectGetTemplateRepositoryFilesWithContent(BiFunction<ProgrammingEx
     private long getMaxProgrammingExerciseId() {
         return programmingExerciseRepository.findAll().stream().mapToLong(ProgrammingExercise::getId).max().orElse(1L);
     }
+
```
Comment (julian-christl) [inline src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseIntegrationTestService.java:2172]: Would it make sense to extract this? Unsure if a default method on the MockDelegate would make sense.

But you use the very same method in the other TestService. The only difference is the way you retrieve the project key in the last two statements: Here, using the URL service, in the other TestService using the getter of the Exercise.

File: src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java (hunk 1 above)
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java:52]: We once decided that * imports are used once 4+ classes of the same package are imported.

File: src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts
Comment (Strohgelaender) [reply src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts:1]: > And the button is apparently not used often enough and these issues are usually pretty severe.

100% agree with this, I did not even know for a long time what this button does, so an automatic check sounds suitable for me. But wouldn't it be better to do this on some kind of schedule? Then we could also send alerts to the instructors if there are problems (they might never open the detail page and then the problems still would be unnoticed)

File: src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java (hunk 1 above)
Comment (krusche) [reply src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java:52]: can we configure IntelliJ to follow this rule?

File: src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts [hunk 7]
```diff
@@ -374,6 +378,20 @@ export class ProgrammingExerciseDetailComponent implements OnInit, OnDestroy {
         modalRef.componentInstance.exercisesToCheck = Array.of(exercise);
     }
 
+    /**
+     * Executes a consistency check for this programming exercise and alerts the user if any inconsistencies are found
+     * This is only run if the user is at least an instructor in the course
+     */
+    checkAndAlertInconsistencies() {
+        if (this.programmingExercise.isAtLeastInstructor) {
```
[the remark this answers is not in the document]
Comment (krusche) [reply src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts:386]: editors should be able to see it. What I meant with my statement was that users* do not often visit the programming exercise details page and the typically 5 REST calls to external systems which verify the consistency are not too demanding. So please activate it for editors as well


* no matter if they are instructors or editors, but basically everyone who can visit the page

File: src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseIntegrationTestService.java (hunk 6 above)
Comment (krusche) [reply src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseIntegrationTestService.java:2172]: time-wise, it is definitely not a good idea to invoke "findAll()". If this is the last test, that gets executed, there will be thousands of exercises which all are loaded into Java consuming lots of wasted time and way too much memory.
We should forbid the use of findAll in all places (production code and test code) except there is a really really good reason and no other way to achieve the desired functionality. Please change this here to make @DominikRemo and @laadvo happy as well ;-)

File: src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (Hialus) [reply src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts:386]: Currently, the entire consistency check feature is only available to instructors. I'll change it to allow editors as well.

File: src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseIntegrationTestService.java (hunk 6 above)
Comment (Hialus) [reply src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseIntegrationTestService.java:2174]: - Replaced the findAll call with a more efficient solution
- Regarding the `setupMocksForConsistencyChecksOnImport`: I already looked into removing this code duplication, but don't see a good way to do it. Putting it as a default method in `MockDelegate` isn't a great solution IMO: It would be the only default method in there and would be highly specific. Every other method in `MockDelegate` is more general and tailored to mock a single action of the VCS/CI. Also, you would have to pass a service as a parameter, which I've not seen being done anywhere else in Artemis. I think the best solution would ultimately be to split up this file into multiple smaller test classes. It currently is massive (>2000 LOC) and not tailored to test the importing of programming exercises (which caused me some headaches). This would then also remove the code duplication, as you could simply put all import-related test cases in the same class.

File: src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java (hunk 1 above)
Comment (Hialus) [reply src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingExerciseExportImportResource.java:52]: Yes we can by adding this to the `.editorconfig` file:
```
[*.{java,kt}]
ij_java_class_count_to_use_import_on_demand = 4
```

**Review by julian-christl — DISMISSED** [review]
Code approved

**Review by jakubriegel — APPROVED** [review]
Code is fine 👍🏻 

Tested on ts2 (GitLab), everything works

File: src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseIntegrationTestService.java [hunk 8]
```diff
@@ -2164,6 +2169,27 @@ void test_redirectGetTemplateRepositoryFilesWithContent(BiFunction<ProgrammingEx
     }
 
     private long getMaxProgrammingExerciseId() {
-        return programmingExerciseRepository.findAll().stream().mapToLong(ProgrammingExercise::getId).max().orElse(1L);
+        return programmingExerciseRepository.findAll(PageRequest.of(0, 1, Sort.by(Sort.Direction.DESC, "id"))).stream().mapToLong(ProgrammingExercise::getId).max().orElse(1L);
```
Comment (MichaelOwenDyer) [inline src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseIntegrationTestService.java:2172]: If the query results are already sorted then the largest ID will be first in the stream, right?
```suggestion
        return programmingExerciseRepository.findAll(PageRequest.of(0, 1, Sort.by(Sort.Direction.DESC, "id"))).stream().limit(1).findFirst().map(ProgrammingExercise::getId).orElse(1L);
```
This is still not as good as having a dedicated query to pull the largest ID, but perhaps that is being avoided for a good reason, I don't know.

**Review by MichaelOwenDyer — DISMISSED** [review]
Looks good to me

File: src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts
Comment (krusche) [reply src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts:1]: let's monitor how often such issues occur, normally they do not occur too often. In case this is still a problem, we could implement a scheduled consistency check in the future that only checks programming exercises in active courses (incl. test courses) which are released or due in the future. It could be executed every night. This way, we would not check too many programming exercises

**Review by krusche — APPROVED** [review]
Changes look good 👍
