### PR TITLE
`Development`: Add client support for programming exercise feedback suggestions

### LINKED ISSUE #6367: `Programming exercises`, `Assessment`: Unnecessary empty space below tutor comments
### Describe the bug

There is quite a bit of empty space below inline code editor comments. The actual amount of space seems to differ based on some browser/font settings per user.

### To Reproduce

1. Assess a programming exercise submission and add inline comments.

### Expected behavior

There is less empty space below inline comments.

### Screenshots

The actual amount of empty lines seems to be minimum one, but up to three depending on the system font settings. The space without line number could be reduced/removed.

Screenshot 2023-03-21 at 15-25-36 Programming Exercises
rect3148

### Which version of Artemis are you seeing the problem on?

6.1.1

### What browsers are you seeing the problem on?

Microsoft Edge, Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #7033: `Programming exercises`: Inline feedback sticks to top of online editor
### Describe the bug

Sometimes inline feedbacks get stuck to the top of the online editor.

### To Reproduce

In a programming exercise with manual assessment:

1. As tutor/instructor assess a submission and add various inline feedbacks.
2. When switching back to files where you added annotations before or when scrolling around within a file, sometimes some of the inline feedback items get stuck to the top of the editor as shown in the screenshot.

It might take a few minutes of adding feedbacks, changing files, and scrolling to reproduce the bug.

### Expected behavior

The feedbacks are not sticky but are shown at the correct location.

### Screenshots

Two inline feedbacks overlapping and stuck to the top of the editor box even when scrolling:

scroll_bug

### Which version of Artemis are you seeing the problem on?

6.3.8

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #7094: `Programming exercises`: Add Athena Feedback Suggestions
> Feature Template Spec Version 0.1

Quick links:
- **Feature proposal** (this document): #7094 
- Client: #7099
- Server: #7136
- Client + Server merged: #7138

## Context
We have revived feedback suggestions by Athena to text exercises (#6861). We want to extend this to programming exercises as well.

### Problem  

Athena can generate feedback suggestions for programming exercises, but Artemis cannot interact with Athena and show them.

### Motivation 

Athena could already help a lot of tutors save time by intelligently suggesting feedback for text exercises with the [Athena-CoFee](https://github.com/ls1intum/Athena-CoFee) system. We want to explore new ways to achieve the same for programming exercises. We will attempt this with the [ThemisML](https://github.com/ls1intum/Themis-ML) system and [a module](https://github.com/ls1intum/Athena/tree/develop/module_programming_llm) connected to the APIs for GPT3.5 and GPT4.

---
### Existing (Problematic) Solution / System 

There are no feedback suggestions available for programming exercises.

### Proposed System 

We show feedback suggestions for programming exercises and offer to accept or reject them. Because it would be annoying to click around in files to find all suggestions, the default will be to NOT accept a feedback suggestion. Still, you will receive a warning if you missed a suggestion and neither accepted nor rejected it.

### Requirements 

1. FR: **Provide Feedback Suggestions** Athena can deliver feedback suggestions to the LMS when a tutor starts grading a submission. Feedback suggestions are generated based on the capabilities of the selected assessment module and analysis parameters.
2. FR: **Review Suggestions** Once Athena has finished processing all incoming data and can provide feedback suggestions, Artemis can display a UI for tutors to view these feedback suggestions for programming exercises. The UI should be accessible only to authorized tutors who are grading the exercise.
3. FR: **Accept Feedback Suggestions** When a tutor is content with a given feedback suggestion, they can accept it from within the LMS.
4. FR: **Reject Feedback Suggestions** When a tutor does not want to apply a feedback suggestion, they can reject it from within the LMS.

1. NFR: **Usability: Feedback Accessibility** Tutors should be able to effortlessly view and interpret the feedback suggestions provided by Athena.
2. NFR: **Performance: Immediate Grading** Tutors should be able to start grading a submission immediately, even if Athena has not yet provided feedback suggestions. In this case, suggestions from Athena should load asynchronously, allowing grading to proceed without delay.
3. NFR: **Security: Data Leakage Prevention** Confidential data, such as student submissions or feedback, should not be leaked outside Artemis and Athena. Appropriate data protection measures must be in place.

---
### Analysis Object Model 

*Tutor*s will be able to get *Feedback Suggestion*s for *Assessment*s on *Submission*s in *Programming Exercises*:
screenshot-2023-08-24_001822

### Dynamic Behavior 

MA_Activity-Diagram-problem-only

---
### Subsystem Decomposition

Here are the full changes made from the text + programming suggestions integration with Athena:

**Server**:
MA_Subsystem-Decomposition-Component-Diagram-artemis-server

**Client**:
MA_Subsystem-Decomposition-Component-Diagram-web-interface

New endpoints:
- `api/athena/exercises/{exerciseId}/solution-repository`: Returns the solution repository of the exercise as a ZIP file for Athena to download and process for suggestions
- `api/athena/exercises/{exerciseId}/template-repository`: Returns the template repository of the exercise as a ZIP file for Athena to download and process for suggestions
- `api/athena/exercises/{exerciseId}/tests-repository`: Returns the tests repository of the exercise as a ZIP file for Athena to download and process for suggestions
- `api/athena/exercises/{exerciseId}/submissions/{submissionId}/repository`: Returns the submission repository as a ZIP file for Athena to download and process for suggestions

### Persistent Data Management

- Already approved: Mark feedback suggestions coming from Athena in the DB by prefixing their `text` with `FeedbackSuggestion:`
- Distinguish between feedback suggestions that are accepted as-is and modified ones: The prefix is either `FeedbackSuggestion:accepted:` or `FeedbackSuggestion:adapted:`
- Already approved: Add a new column `feedback_suggestions_enabled` to the `exercises` table to mark exercises where automatic feedback suggestions from Athena are enabled. When the migration happens, this is `true` for all text exercises with `assessment_type = SEMI_AUTOMATIC`.
- Choose the Athena module based on a Spring config entry for the corresponding exercise type
- Store submissions, assessments, and feedback as before.

### Access Control / Security Aspects 

Only tutors will be able to view feedback suggestions. The `feedback-suggestions` endpoint will be only available to users with the role TA or higher.

All new endpoints returning repositories have to be authenticated using the shared Athena secret. They should only work for exercises where feedback suggestions are enabled.

All access control systems set in #6861 stay as they are.

### Change Checklist
- [X] Change `Athena<*>Service`-s from #6861 to accept general exercises, submissions, and feedback instead of "only" text exercise content (e.g., `TextSubmission` objects)
- [X] Let the `/feedback-suggestions` endpoint from #6861 return instances of the `de.tum.in.www1.artemis.service.dto.athena.TextFeedbackDTO` (renamed to `FeedbackDTO` to be more general). The client will interpret the indices from the feedback reference instead of the server converting it to `TextBlockRefs`.
- [X] Extend the client-side `AthenaService` to allow programming exercises by changing the return type of `getFeedbackSuggestions`.
- [X] Extend the client-side `Feedback` model with a `Feedback.isFeedbackSuggestion` helper method to show them inline.
- [X] Extend the client-side `CodeEditorTutorAssessmentContainerComponent` to load and show feedback suggestions.
- [X] Add a boolean `feedbackSuggestions` for exercises to determine whether feedback suggestions are enabled for them
- [X] Add the endpoints for repositories and authenticate them
- [x] Schedule Athena for more/all exercise types
- [x] Add a checkmark for enabling feedback suggestions in exercise settings
  - [x] Programming exercises (new)
  - [x] Text exercises (change in logic)
  - [x] Only show the option on Athena-enabled servers
- [x] Add a setting for the choice of the Athena module
- [x] Add multiple tests
  - [x] server
  - [x] client

---
## UI / UX 

- A tutor starts a new assessment of a manually graded programming exercise. Artemis chooses a submission for them, using Athena.
- The tutor gets the submission. They can immediately start grading. Feedback suggestions are displayed in the UI as soon as they are available. Suggestions can be accepted or rejected by clicking a button on the feedback cards showing the suggestions. The feedback suggestion cards are visually distinguishable from normal feedback in that they have slightly transparent text and a purple background. This indicates they are "only" suggestions and are not applied by default.
- All files that include feedback suggestions are marked with a light bulb in the file tree.
- The tutor is done and submits the assessment. If no feedback suggestions are neither accepted or rejected, Artemis shows a popup warning the tutor about this. If the tutor is okay with this, the assessment is submitted. Otherwise, grading continues with the same submission.

Feedback suggestions are only loaded for submissions without an existing assessment, i.e., the "Save" button was never pressed. The accept/reject state for the feedback suggestions is temporary initially: If a TA reloads or cancels the assessment, they get the feedback suggestions again. This has two advantages:
1. When TAs change, the feedback suggestions are kept
2. More importantly, feedback suggestions don't need to be stored in Artemis before they are actually accepted

The downsides of this behavior are negligible because usually, a TA will assess a whole submission in a single go and not go back anyway.

### Feedback Suggestions in the programming assessment editor
full

Suggestions are clearly marked as such; it is also clear that the feedback is not automatically given without the TA's consent.

### Feedback Suggestion on hover
hover

The slight text transparency goes away.

### Unreferenced feedback suggestion
general

They follow a similar visual style.

### Unreferenced feedback suggestion on hover
general-hover

### Accepted feedback suggestion
accepted

Accepted feedback suggestions look like normal feedback, with an additional "Accepted Suggestion" badge only visible to tutors.

### Accepted unreferenced feedback suggestion
general-accepted

### Tooltips
screenshot-2023-08-27_001847

screenshot-2023-08-27_001848

### LINKED ISSUE #7102: `Programming exercises`: Cancelling feedback can go back too many steps
### Describe the bug

When you cancel feedback in the programming exercise assessment editor, you always get feedback from when you first created it. When you save twice, the "too old" feedback is loaded.

### To Reproduce

1. Go to the manual programming assessment editor.
2. Add a feedback. Save.
3. Edit the feedback. Save again.
4. Edit the feedback again. Cancel.
5. You see the first feedback from step 2, not the one from step 3.

### Expected behavior

The feedback is fully stored when pressing `Save`. When cancelling, I go back to the last saved state.

### Screenshots

https://github.com/ls1intum/Artemis/assets/9006596/076dc41a-ddbb-4d34-aba1-8083759fdcdb

### Which version of Artemis are you seeing the problem on?

6.4.1

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by pal03377**
> **Note**
> The hardcoded example feedback suggestions will need to be removed before merging.

Quick links:
- Feature proposal: #7094 
- **Client** (this PR): #7099
- Server: #7136
- Client + Server merged: #7138

#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [X] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [X] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [X] I translated all newly inserted strings into English and German.

### Motivation and Context

See #7094. We want to implement programming feedback suggestions on the client. Also, this PR refactors some parts of the code editor assessment area, making it more robust.

### Description

- This PR implements the client side of #7094 (feature proposal).
- It also fixes #7102
- Because of refactoring, it _might_ fix #7033 as a byproduct (inline feedback sometimes "escapes" editor).
- It resolves #6367: I slightly adjusted the spacing below the feedback cards.

### Steps for Testing

Prerequisites:
- 1 TA
- 1 Programming Exercise with manual assessment enabled and with submissions to assess. **The package name has to be `de.athena` and include `BubbleSort.java` because otherwise, the hardcoded example feedback suggestion will point nowhere!**

1. Log in to Artemis
2. Go into the exercise dashboard and start the assessment
3. Play around with the feedback in the editor:
  - Create lots of inline feedback
  - Create general feedback
  - Switch between files rapidly
  - Save, Cancel, Delete feedback
  - Rename files
  - Collapse folders
4. Test referenced feedback suggestions: You will see hardcoded referenced feedback suggestions in `BubbleSort.java` and `MergeSort.java`. Accept or discard them. You can get it back by not saving the whole assessment and refreshing the page. It is expected that discarded feedback re-appears this way. Try editing it as well. Check that the feedback suggestion badge always appropriately represents the state of the suggestion. Also, switch around in files again.
5. Test unreferenced feedback suggestions the same way. There is one unreferenced feedback suggestion at the bottom.
6. Save the assessment. Refresh and inspect the feedback on the page. Edit it again.
7. Look at the feedback from the perspective of a student.
8. Check that the feedback suggestions don't influence the overall score until they are accepted.
9. Collapse the `src/de/athena` folder. The feedback suggestions badge should sum up the badges of all files and show up next to the collapsed folder.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| assessment-detail.component.ts | not found (deleted) |  |
| [athena.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/assessment/athena.service.ts.html) |  | Currently incorrect because of testing data, should be close to 100% |
| assessment-correction-round-badge.component.ts | not found (renamed) |  |
| [unreferenced-feedback-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/assessment/unreferenced-feedback-detail/unreferenced-feedback-detail.component.ts.html) | 100% | ✅ |
| [feedback.model.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/entities/feedback.model.ts.html) | 96.69% | ✅  |
| [code-editor-tutor-assessment-container.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts.html) | 86.19% | ✅ up from ~85% |
| [code-editor-tutor-assessment-inline-feedback-suggestion.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/assess/code-editor-tutor-assessment-inline-feedback-suggestion.component.ts.html) | 100% |  |
| [code-editor-tutor-assessment-inline-feedback.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/assess/code-editor-tutor-assessment-inline-feedback.component.ts.html) | 98.11% | ✅  |
| [code-editor-ace.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts.html) | 84.27% | ✅ up from ~81% |
| [code-editor-container.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/shared/code-editor/container/code-editor-container.component.ts.html) | 86.36% | ✅ up from ~85% |
| [code-editor-file-browser-badge.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-badge.component.ts.html) | 100% | |
| [code-editor-file-browser-file.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-file.component.ts.html) | 100% | ✅ |
| [code-editor-file-browser.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser.component.ts.html) | 86.03% | ✅ up from ~85% |
| [code-editor.model.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/shared/code-editor/model/code-editor.model.ts.html) | 100% | ✅ |
| [feedback-suggestion-badge.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/feedback/feedback-suggestion-badge/feedback-suggestion-badge.component.ts.html) | 100% | |
| [unreferenced-feedback.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/unreferenced-feedback/unreferenced-feedback.component.ts.html) | 96.55% | ✅ |
| [textblock-feedback-editor.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5341/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/text/assess/textblock-feedback-editor/textblock-feedback-editor.component.ts.html) | 92.98% | ✅  |

### Screenshots

screenshot-2023-08-28_001852
screenshot-2023-08-28_001853
screenshot-2023-08-28_001854
screenshot-2023-08-28_001855
screenshot-2023-08-28_001856
screenshot-2023-08-28_001858

Student view: No feedback suggestion badges:

screenshot-2023-08-28_001859

### CODE REVIEW

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts [hunk 1]
```diff
@@ -108,10 +117,7 @@ export class CodeEditorAceComponent implements AfterViewInit, OnChanges, OnDestr
     annotationsArray: Array<Annotation> = [];
     annotationChange: Subscription;
     fileSession: FileSession = {};
-    // Inline feedback variables
-    fileFeedbacks: Feedback[];
-    fileFeedbackPerLine: { [line: number]: Feedback } = {};
-    linesWithNewFeedback: number[] = []; // lines with new feedback, which is not yet saved, but must already be displayed to be editable
+    newFeedbackLines: number[] = []; // new feedback, which is not yet saved, but must already be displayed to be editable
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:120]: Note for code reviewers: The file feedback is now mostly dynamically computed, which doesn't impact performance and is much more robust.

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts [hunk 2]
```diff
@@ -178,38 +181,39 @@ export class CodeEditorAceComponent implements AfterViewInit, OnChanges, OnDestr
...
         if (changes.commitState && changes.commitState.currentValue === CommitState.CONFLICT) {
             this.editor.setReadOnly(true);
         } else if (changes.commitState && changes.commitState.previousValue === CommitState.CONFLICT && changes.commitState.currentValue !== CommitState.CONFLICT) {
             this.editor.setReadOnly(false);
         }
+        if (changes.feedback || changes.feedbackSuggestions) {
+            // on changes to these props
+            if (this.editorSession) {
+                // initEditor should already be called, otherwise there is no need to init this anyways
+                this.updateLineWidgets();
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:196]: Note for code reviewers: This makes the editor line widgets more robust against changes from "outside"

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts [hunk 3]
```diff
@@ -178,38 +181,39 @@ export class CodeEditorAceComponent implements AfterViewInit, OnChanges, OnDestr
...
 
     /**
-     * Setup the ace editor after a file change occurred.
-     * Makes sure previous settings are restored and the correct language service is used.
+     * Set up the ace editor after a file change occurred or the file finished loading.
+     * Makes sure potential previous settings are restored and the correct language service is used.
      **/
-    initEditorAfterFileChange() {
-        // Setup editorSession for inline feedback using lineWidgets
+    initEditor() {
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:205]: Note for code reviewers: The old name did not make sense: The function is also called initially, not only on file change.

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts [hunk 4]
```diff
@@ -178,38 +181,39 @@ export class CodeEditorAceComponent implements AfterViewInit, OnChanges, OnDestr
...
             this.editorSession.widgetManager.attach(this.editor.getEditor());
         }
-        // Remove previous lineWidgets
-        if (this.editorSession.lineWidgets) {
-            this.editorSession.lineWidgets.forEach((widget: any) => {
-                if (widget) {
-                    this.editorSession.widgetManager.removeLineWidget(widget);
-                }
-            });
-        }
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:210]: Note for code reviewers: This is now done in `updateLineWidgets`

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts [hunk 5]
```diff
@@ -459,18 +449,7 @@ export class CodeEditorAceComponent implements AfterViewInit, OnChanges, OnDestr
...
     /**
-     * Displays the inline feedback of a line of code using lineWidgets. We first go through all feedbacks of the selected file
-     * and create a lineWidget for each feedback.
-     */
-    displayFeedbacks() {
-        this.fileFeedbacks.forEach((feedback) => {
-            const line: number = +feedback.reference!.split('line:')[1];
-            this.addLineWidgetWithFeedback(line);
-        });
-    }
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:470]: Note for code reviewers: Handled by `updateLineWidgets` now

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts [hunk 6]
```diff
@@ -536,7 +548,7 @@ export class CodeEditorAceComponent implements AfterViewInit, OnChanges, OnDestr
      * @param line Line of code which has inline feedback (lineWidget)
      */
     adjustLineWidgetHeight(line: number) {
-        const widget = this.editorSession.lineWidgets.find((w: any) => w?.el === this.getInlineFeedbackNode(line));
+        const widget = this.editorSession.lineWidgets[line];
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:551]: Note for code reviewers: Refactoring only

File: src/main/webapp/app/exercises/programming/shared/code-editor/container/code-editor-container.component.ts [hunk 7]
```diff
@@ -202,10 +236,6 @@ export class CodeEditorContainerComponent implements ComponentCanDeactivate {
         this.onFileChanged.emit();
     }
 
-    updateFeedback(feedbacks: Feedback[]) {
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/code-editor/container/code-editor-container.component.ts:205]: Note for code reviewers: We now call `onUpdateFeedback.emit` directly

File: src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-badge.component.html [hunk 8]
```diff
@@ -0,0 +1,4 @@
+<span class="badge" [class.on-colored-background]="onColoredBackground" [ngbTooltip]="tooltip">
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-badge.component.html:1]: Note for code reviewers: That's the badge on the right:
screenshot-2023-08-28_001851

File: src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-file.component.html [hunk 9]
```diff
@@ -19,12 +19,14 @@
             (keyup.esc)="clearRenamingNode($event)"
             class="list-group-item__input"
     /></span>
+    <!-- File badges -->
+    <jhi-file-browser-badge *ngFor="let badge of badges" [badge]="badge" [onColoredBackground]="item.checked || hasError || hasChanges"></jhi-file-browser-badge>
     <!-- File level actions -->
-    <span class="file-icons" [ngClass]="item.checked ? 'text-white' : 'primary'">
-        <button [disabled]="disableActions" (click)="setRenamingNode($event)" class="btn btn-small">
+    <span class="file-icons" [ngClass]="item.checked ? 'text-white' : 'primary'" *ngIf="!disableActions">
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-file.component.html:25]: Note for code reviewers: We now hide the file actions completely if they are not available: A tutor doesn't need to see a rename button they can't press anyway.

File: src/main/webapp/app/exercises/shared/unreferenced-feedback/unreferenced-feedback.component.html [hunk 10]
```diff
@@ -3,25 +3,31 @@
         <button id="add-unreferenced-feedback" class="btn btn-success mt-4" (click)="addUnreferencedFeedback()" [disabled]="readOnly">
             {{ 'artemisApp.fileUploadAssessment.addFeedback' | artemisTranslate }}
         </button>
-        <ng-container *ngIf="!busy">
```
Comment (pal03377) [inline src/main/webapp/app/exercises/shared/unreferenced-feedback/unreferenced-feedback.component.html:6]: Note for code reviewers: The `busy` property was never set to `true`, so I removed this.

Comment (pal03377) [reply src/main/webapp/app/exercises/shared/unreferenced-feedback/unreferenced-feedback.component.html:6]: Only the part with `<div *ngFor="let suggestion of feedbackSuggestions" class="col-12 col-lg-6 col-xl-6">` (line 22+) is new.

File: src/main/webapp/app/exercises/text/assess/textblock-feedback-editor/textblock-feedback-editor.component.ts [hunk 11]
```diff
@@ -49,9 +49,8 @@ export class TextblockFeedbackEditorComponent implements AfterViewInit {
     faEdit = faEdit;
     faQuestionCircle = faQuestionCircle;
     faExclamationTriangle = faExclamationTriangle;
-    faRobot = faRobot;
+    faLightbulb = faLightbulb;
     faExclamation = faExclamation;
-    faBalanceScaleRight = faBalanceScaleRight;
```
Comment (pal03377) [inline src/main/webapp/app/exercises/text/assess/textblock-feedback-editor/textblock-feedback-editor.component.ts:54]: Note for code reviewers: This was just unused

**Review by pal03377 — COMMENTED** [review]
I added a few notes for code reviewers to make it easier to understand changes.

**Review by terlan98 — CHANGES_REQUESTED** [review]
Tested on TS5. Good job overall 👍 , but it still needs some improvements.

Some issues I found:
- Suggested feedbacks disappear when I accept, edit them and save the assessment:
  sad_bug
- The popup that shows a summary of all feedbacks when the user clicks on ' x%, y of z passed, P points (preliminary)' does not include accepted suggested feedbacks.
- Accepting/Discarding suggestions decrements the badge count, but it resets back to its original value when the assessment is saved and the page is refreshed. 
- I was assessing a submission and added several inline and general feedbacks (suggested and non-suggested). I saved the assessment and went back to the assessment dashboard. Then, I could not continue assessing the same [submission](https://artemis-test5.artemis.cit.tum.de/course-management/4/programming-exercises/118/submissions/337/assessment?correction-round=0). The console showed this error:
  Screenshot 2023-08-28 at 20 51 25

I've also noted a few minor suggestions for the UI:
- I think the Accept and Discard buttons should have the same size as the Cancel, Delete, and Save buttons that appear on manual referenced feedbacks. 
- I love the new purple color for feedback suggestions. However, it seems more prominent on the dark mode than light mode. I'd make the light-mode version a bit more saturated. 
  - We can also later apply this purple color for suggested feedback in text, modeling, and other exercise types. This would improve visual consistency and the user would immediately recognize suggested feedback regardless of the exercise type.

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts [hunk 12]
```diff
@@ -154,6 +157,15 @@ export class CodeEditorAceComponent implements AfterViewInit, OnChanges, OnDestr
...
         }
+        if (!this.resizeObserver) {
+            // When the editor is resized in width, the inline feedback text could wrap. This would cause its height to change and we need to adapt it:
+            this.resizeObserver = new ResizeObserver(() => {
+                if (!this.editorSession) return; // not yet initialized, nothing to do
+                // Adjust height of all feedback line widgets
+                this.updateLineWidgets();
+            });
+            this.resizeObserver.observe(this.editor.elementRef.nativeElement);
+        }
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:168]: This is the second part of the fix for #6367

**Review by FelixTJDietrich — COMMENTED** [review]
Started reviewing but need to go to bed now 😅will review more in the following days.

File: src/main/webapp/app/entities/feedback.model.ts [hunk 13]
```diff
@@ -19,8 +19,19 @@ export enum FeedbackType {
...
+    ACCEPTED = 'ACCEPTED', // Suggestion is accepted
+    ADAPTED = 'ADAPTED', // Suggestion is accepted and then modified by the TA
+}
+
+// Prefixes for the feedback text to identify the feedback type more specifically without having to change the database schema:
 export const STATIC_CODE_ANALYSIS_FEEDBACK_IDENTIFIER = 'SCAFeedbackIdentifier:';
 export const SUBMISSION_POLICY_FEEDBACK_IDENTIFIER = 'SubPolFeedbackIdentifier:';
+export const FEEDBACK_SUGGESTION_IDENTIFIER = 'FeedbackSuggestion:';
+export const FEEDBACK_SUGGESTION_ACCEPTED_IDENTIFIER = 'FeedbackSuggestion:accepted:';
+export const FEEDBACK_SUGGESTION_ADAPTED_IDENTIFIER = 'FeedbackSuggestion:adapted:';
```
[the remark this answers is not in the document]
Comment (pal03377) [reply src/main/webapp/app/entities/feedback.model.ts:34]: I would do this in another PR that handles the server side to keep this one smaller 👍

File: src/main/webapp/app/entities/feedback.model.ts [hunk 14]
```diff
@@ -88,21 +96,46 @@ export class Feedback implements BaseEntity {
...
         }
-        return that.type === FeedbackType.AUTOMATIC && that.text.includes(SUBMISSION_POLICY_FEEDBACK_IDENTIFIER, 0);
+        return that.type === FeedbackType.AUTOMATIC && that.text.startsWith(SUBMISSION_POLICY_FEEDBACK_IDENTIFIER);
+    }
+
+    public static isFeedbackSuggestion(that: Feedback): boolean {
+        if (!that.text) {
+            return false;
+        }
+        return that.text.startsWith(FEEDBACK_SUGGESTION_IDENTIFIER);
```
[the remark this answers is not in the document]
Comment (pal03377) [reply src/main/webapp/app/entities/feedback.model.ts:120]: I'm changing them to always be `FeedbackType.MANUAL` because a lot of the code assumes that all `AUTOMATIC` / `AUTOMATIC_ADAPTED` feedback are automatically generated test cases, which does not make sense. We can detect feedback suggestions from the `FeedbackSuggestion:` prefix on the `text` anyway, so I think it makes sense to use `type = `FeedbackType.MANUAL`. I think using `AUTOMATIC_ADAPTED` would theoretically work, but would probably also introduce more confusion because normal suggestions would not be `AUTOMATIC`.

File: src/main/webapp/app/entities/feedback.model.ts [hunk 15]
```diff
@@ -114,6 +147,36 @@ export class Feedback implements BaseEntity {
...
+     * Get the referenced line for referenced programming feedbacks, or undefined.
+     * Typical reference format for programming feedback: `file:src/com/example/package/MyClass.java_line:13`.
+     * Example output in this case: 13
+     */
+    public static getReferenceLine(feedback: Feedback): number | undefined {
+        if (!feedback?.reference?.startsWith('file:')) {
+            // No programming feedback
+            return undefined;
+        }
+        const line = parseInt(feedback.reference.split('_line:')[1]);
```
[the remark this answers is not in the document]
Comment (pal03377) [reply src/main/webapp/app/entities/feedback.model.ts:173]: We are handling unreferenced feedback 🤔  `getReferenceLine` should never be called for unreferenced feedback. Even if it is, the first line of this function (`if (!feedback?.reference?.startsWith('file:')) {` would be true, and `getReferenceLine` would return `undefined`. Where do you see the potential for an error?

**Comment by pal03377** [comment]
Thanks @terlan98! I considered all your feedback 🎉

**Review by terlan98 — APPROVED** [review]
Re-tested on TS5. Thanks for addressing my comments 👍

File: src/main/webapp/app/entities/feedback.model.ts (hunk 14 above)
[the remark this answers is not in the document]
Comment (FelixTJDietrich) [reply src/main/webapp/app/entities/feedback.model.ts:120]: Hmm, I think we have to think about overall feedback suggestions. I feel this is inconsistent and confusing compared to text exercises and potentially future supported exercise types. In text exercises suggestions from Athena are `AUTOMATIC` and when changed `AUTOMATIC_ADAPTED`. I think this generally makes sense. 

Are you suggesting that generally we should use `MANUAL` and `MANUAL_UNREFERENCED` for all exercise types where Athena is suggesting feedback and use a prefix for the `text`? Alternatively, we can also think about renaming `AUTOMATIC_ADAPTED` to `SUGGESTION_ADAPTED` and add a new feedback type called `SUGGESTION`.

But idk, I'm also fine with the idea where we are generally using the `text` field for all Athena feedback and its state 🤔

File: src/main/webapp/app/entities/feedback.model.ts (hunk 15 above)
[the remark this answers is not in the document]
Comment (FelixTJDietrich) [reply src/main/webapp/app/entities/feedback.model.ts:173]: I mean in my module I'm referencing a filename: `src/com/example/package/MyClass.java` without line start and line end 😬 I guess for right now you'd be returning `null` for the reference field from Athena instead of `file:src/com/example/package/MyClass.java`. I guess it does not make much sense to have unreferenced feedback in Artemis that references a file 🤔

File: src/main/webapp/app/entities/feedback.model.ts [hunk 16]
```diff
@@ -88,21 +96,46 @@ export class Feedback implements BaseEntity {
         if (!feedback.text) {
             return true;
         }
-        return !feedback.text.includes(STATIC_CODE_ANALYSIS_FEEDBACK_IDENTIFIER, 0) && !feedback.text.includes(SUBMISSION_POLICY_FEEDBACK_IDENTIFIER, 0);
+        return !feedback.text.startsWith(STATIC_CODE_ANALYSIS_FEEDBACK_IDENTIFIER) && !feedback.text.startsWith(SUBMISSION_POLICY_FEEDBACK_IDENTIFIER);
```
[the remark this answers is not in the document]
Comment (FelixTJDietrich) [reply src/main/webapp/app/entities/feedback.model.ts:99]: Okay, I see. Let's discuss this in the other thread

**Review by b-fein — CHANGES_REQUESTED** [review]
Inline comments for files that contain `_` in the path no longer work.
E.g. for an inline feedback `{ ..., "reference": "file:src/game_of_life/Shell.java_line:3", ...}` the comment is feedback object is successfully created after clicking the save button the inline feedback box, but then immediately disappears.

I assume the splitting behaviour on `_` used to separate the file and line changed and now results in invalid file references.

File: src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-inline-feedback-suggestion.component.ts [hunk 17]
```diff
@@ -0,0 +1,38 @@
...
+    @Output()
+    onDiscardSuggestion = new EventEmitter<Feedback>();
+
+    // Expose functions to the template
+    readonly roundScoreSpecifiedByCourseSettings = roundValueSpecifiedByCourseSettings;
+    readonly buildFeedbackTextForReview = buildFeedbackTextForReview;
+
+    // Icons
+    faCheck = faCheck;
+    faTrash = faTrash;
```
[the remark this answers is not in the document]
Comment (pal03377) [reply src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-inline-feedback-suggestion.component.ts:31]: I looked through the codebase and decided against this: >90% of all our components prefer the shorter version, and I would keep this for consistency. If we want to change the convention here, we should do it in a separate PR.

File: src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts [hunk 18]
```diff
@@ -262,6 +271,22 @@ export class CodeEditorTutorAssessmentContainerComponent implements OnInit, OnDe
         }
     }
 
+    /**
+     * Load the feedback suggestions for the current submission from Athena.
+     */
+    private async loadFeedbackSuggestions(): Promise<void> {
+        this.feedbackSuggestions = (await this.athenaService.getFeedbackSuggestionsForProgramming(this.exerciseId, this.submission!.id!).toPromise()) ?? [];
```
[the remark this answers is not in the document]
Comment (pal03377) [reply src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts]: Thanks! [I changed it.](https://github.com/ls1intum/Artemis/pull/7099/commits/62e1223b1bc0080ffbd134a5061630a15fc47358)

**Comment by pal03377** [comment]
> Bugfix: Make feedback work for file names containing underscore

Great catch! I [fixed it](https://github.com/ls1intum/Artemis/pull/7099/commits/5245472b6d829db3a2da46cc44e88edbdf1f2653) and [also added tests so this does not happen in the future](https://github.com/ls1intum/Artemis/pull/7099/commits/800605e6853c32c70852bbe687699d6772dfd4f7).

File: src/main/webapp/app/entities/feedback.model.ts (hunk 14 above)
[the remark this answers is not in the document]
Comment (pal03377) [reply src/main/webapp/app/entities/feedback.model.ts:123]: Yes, I am suggesting to use `MANUAL`/`MANUAL_UNREFERENCED` + the `text` prefix 👍 

Otherwise, we either cannot distinguish suggestions from non-suggestions for programming exercises or we have to be inconsistent.

I am against renaming the feedback types because we should have to add a DB migration for millions of feedback that changes the enum value for the existing feedbacks.

File: src/main/webapp/app/entities/feedback.model.ts (hunk 15 above)
[the remark this answers is not in the document]
Comment (pal03377) [reply src/main/webapp/app/entities/feedback.model.ts]: Ok! I suggest we keep the code as-is in both your module and Artemis and add a compatibility filter within Artemis as a follow-up PR.

This could detect unreferenced file feedback and change it to "pure" unreferenced feedback where the `text` starts with `(file name):`. So when the module suggests `{reference: "src/com/example/package/MyClass.java", detailText: "Hello world"}`, it would be converted to `{reference: undefined, detailText: "src/com/example/package/MyClass.java: Hello world"}`

What do you think?

File: src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts [hunk 19]
```diff
@@ -262,6 +271,22 @@ export class CodeEditorTutorAssessmentContainerComponent implements OnInit, OnDe
...
     }
 
+    /**
+     * Load the feedback suggestions for the current submission from Athena.
+     */
+    private async loadFeedbackSuggestions(): Promise<void> {
+        this.feedbackSuggestions = (await firstValueFrom(this.athenaService.getFeedbackSuggestionsForProgramming(this.exerciseId, this.submission!.id!))) ?? [];
+        // Don't show feedback suggestions that have the same description and reference - probably it is coming from an earlier suggestion anyway
+        this.feedbackSuggestions = this.feedbackSuggestions.filter((suggestion) => {
+            for (const feedback of [...this.referencedFeedback, ...this.unreferencedFeedback]) {
```
Comment (b-fein) [inline src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts:281]:
```suggestion
            for (const feedback of allFeedback) {
```
The list remains the same for all calls of the lambda in `filter()`. Can it be moved outside the `filter()`?
I assume the current spread will iterate and construct the list anew for every item in the outer `filter` loop over `this.feedbackSuggestions`?

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts [hunk 20]
```diff
@@ -108,26 +117,25 @@ export class CodeEditorAceComponent implements AfterViewInit, OnChanges, OnDestr
...
     /**
-     * Get all line numbers in the current editor session that have inline feedback or new feedback (which is only shown temporarily)
+     * Filter feedback: Only referenced to current file
      */
-    get linesWithInlineFeedbackShown(): number[] {
-        const lines = this.linesWithNewFeedback.concat(Object.keys(this.fileFeedbackPerLine).map((line) => parseInt(line)));
-        lines.sort((a, b) => a - b);
-        return lines;
+    filterFeedbackForFile(feedbacks: Feedback[]): Feedback[] {
+        if (!this.selectedFile) return [];
```
Comment (b-fein) [inline src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:137]:
```suggestion
        if (!this.selectedFile) {
            return [];
        }
```
style nitpick
(I would have assumed prettier would also enforce braces for blocks similar to how Spotless does it for the server code.)

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts [hunk 21]
```diff
@@ -178,38 +193,35 @@ export class CodeEditorAceComponent implements AfterViewInit, OnChanges, OnDestr
...
         } else if (changes.commitState && changes.commitState.previousValue === CommitState.CONFLICT && changes.commitState.currentValue !== CommitState.CONFLICT) {
             this.editor.setReadOnly(false);
         }
+        if (changes.feedbacks || changes.feedbackSuggestions) {
+            // on changes to these props
+            if (this.editorSession) {
+                // initEditor should already be called, otherwise there is no need to init this anyways
+                await this.updateLineWidgets();
+            }
+        }
```
Comment (b-fein) [inline src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:210]:
```suggestion
        if ((changes.feedbacks || changes.feedbackSuggestions) && this.editorSession) {
            // initEditor should already be called, otherwise there is no need to init this anyways
            await this.updateLineWidgets();
        }
```
nitpick: one nesting depth could be avoided

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts [hunk 22]
```diff
@@ -492,42 +488,70 @@ export class CodeEditorAceComponent implements AfterViewInit, OnChanges, OnDestr
...
-                    lineWidget.el.querySelector('textarea')?.focus();
-                }
-            } else {
-                this.editorSession.widgetManager.addLineWidget(lineWidget);
-                lineWidget.el.querySelector('textarea')?.focus();
-            }
+        // Wait for one render cycle for all DOM updates to be done
+        await new Promise((resolve) => setTimeout(resolve, 0));
+        // Remove all existing line widgets
+        const linesWithWidgets = this.editorSession.lineWidgets?.map((l: any) => l?.row).filter((row: number | undefined) => row != null) ?? [];
```
Comment (b-fein) [inline src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:543]: `row: number | undefined` but then checking for `null`?

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts [hunk 23]
```diff
@@ -583,14 +604,35 @@ export class CodeEditorAceComponent implements AfterViewInit, OnChanges, OnDestr
...
+     * Accept a feedback suggestion: Make it "real" feedback and remove the suggestion card
+     */
+    async acceptSuggestion(feedback: Feedback) {
+        this.feedbackSuggestions = this.feedbackSuggestions.filter((f) => f !== feedback); // Remove the suggestion card
+        this.removeLineWidget(Feedback.getReferenceLine(feedback)!);
+        // We need to change the feedback type to "manual" because non-manual feedback is never editable in the editor
+        // and will be filtered out in all kinds of places
+        feedback.type = FeedbackType.MANUAL;
+        // Change the prefix "FeedbackSuggestion:" to "FeedbackSuggestion:accepted:"
+        feedback.text = (feedback.text || FEEDBACK_SUGGESTION_IDENTIFIER).replace(FEEDBACK_SUGGESTION_IDENTIFIER, FEEDBACK_SUGGESTION_ACCEPTED_IDENTIFIER);
```
Comment (b-fein) [inline src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:622]:
```suggestion
        feedback.text = (feedback.text ?? FEEDBACK_SUGGESTION_IDENTIFIER).replace(FEEDBACK_SUGGESTION_IDENTIFIER, FEEDBACK_SUGGESTION_ACCEPTED_IDENTIFIER);
```

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts [hunk 24]
```diff
@@ -617,4 +659,6 @@ export class CodeEditorAceComponent implements AfterViewInit, OnChanges, OnDestr
     updateTabSize(event: number) {
         this.tabSize = event;
     }
+
+    protected readonly Feedback = Feedback;
```
Comment (b-fein) [inline src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:663]: What is this for? Why is it at the very end of the class instead of near the top with other attributes?

File: src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser.component.ts [hunk 25]
```diff
@@ -593,4 +586,25 @@ export class CodeEditorFileBrowserComponent implements OnInit, OnChanges, AfterV
...
+    getFolderBadges(folder: TreeviewItem<string>): FileBadge[] {
+        if (!folder.collapsed) {
+            return []; // Only show folder badges on collapsed folders
+        }
+        const folderBadgesMap: Map<FileBadgeType, number> = new Map(); // Use a Map to preserve order
+        for (const [fileName, fileBadges] of Object.entries(this.fileBadges)) {
+            if (fileName.startsWith(folder.value)) {
+                // file is in folder
+                for (const fileBadge of fileBadges) {
+                    const folderBadgeCount = folderBadgesMap.get(fileBadge.type) || 0;
```
Comment (b-fein) [inline src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser.component.ts:603]:
```suggestion
                    const folderBadgeCount = folderBadgesMap.get(fileBadge.type) ?? 0;
```

File: src/main/webapp/app/exercises/shared/unreferenced-feedback/unreferenced-feedback.component.ts [hunk 26]
```diff
@@ -94,12 +104,34 @@ export class UnreferencedFeedbackComponent {
...
+    /**
+     * Accept a feedback suggestion: Make it "real" feedback and remove the suggestion card
+     */
+    acceptSuggestion(feedback: Feedback) {
+        this.feedbackSuggestions = this.feedbackSuggestions.filter((f) => f !== feedback); // Remove the suggestion card
+        // We need to change the feedback type to "manual" because non-manual feedback is never editable in the editor
+        // and will be filtered out in all kinds of places
+        feedback.type = FeedbackType.MANUAL_UNREFERENCED;
+        // Change the prefix "FeedbackSuggestion:" to "FeedbackSuggestion:accepted:"
+        feedback.text = (feedback.text || FEEDBACK_SUGGESTION_IDENTIFIER).replace(FEEDBACK_SUGGESTION_IDENTIFIER, FEEDBACK_SUGGESTION_ACCEPTED_IDENTIFIER);
```
Comment (b-fein) [inline src/main/webapp/app/exercises/shared/unreferenced-feedback/unreferenced-feedback.component.ts:116]:
```suggestion
        feedback.text = (feedback.text ?? FEEDBACK_SUGGESTION_IDENTIFIER).replace(FEEDBACK_SUGGESTION_IDENTIFIER, FEEDBACK_SUGGESTION_ACCEPTED_IDENTIFIER);
```

File: src/test/javascript/spec/component/exercises/programming/assess/code-editor-tutor-assessment-inline-feedback-suggestion.component.spec.ts [hunk 27]
```diff
@@ -0,0 +1,49 @@
...
+        component.course = new Course();
+        component.onAcceptSuggestion = new EventEmitter();
+        component.onDiscardSuggestion = new EventEmitter();
+        fixture.detectChanges();
+    });
+
+    it('should create', () => {
+        expect(component).toBeTruthy();
+    });
+
```
Comment (b-fein) [inline src/test/javascript/spec/component/exercises/programming/assess/code-editor-tutor-assessment-inline-feedback-suggestion.component.spec.ts:35]:
```suggestion
```
I don‘t think a test like this is necessary. All the other tests would fail anyway if the component could not be initialised.

File: src/test/javascript/spec/component/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-badge.component.spec.ts [hunk 28]
```diff
@@ -0,0 +1,54 @@
...
+        fixture = TestBed.createComponent(CodeEditorFileBrowserBadgeComponent);
+        component = fixture.componentInstance;
+        component.badge = new FileBadge(FileBadgeType.FEEDBACK_SUGGESTION, 3);
+        fixture.detectChanges();
+    });
+
+    it('should create', () => {
+        expect(component).toBeTruthy();
+    });
+
```
Comment (b-fein) [inline src/test/javascript/spec/component/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-badge.component.spec.ts:33]:
```suggestion
```
as above

File: src/test/javascript/spec/component/exercises/shared/feedback/feedback-suggestion-badge.component.spec.ts [hunk 29]
```diff
@@ -0,0 +1,74 @@
...
+        component = fixture.componentInstance;
+        component.feedback = new Feedback();
+        component.feedback.text = 'Test Feedback';
+        fixture.detectChanges();
+    });
+
+    it('should create', () => {
+        expect(component).toBeTruthy();
+    });
+
```
Comment (b-fein) [inline src/test/javascript/spec/component/exercises/shared/feedback/feedback-suggestion-badge.component.spec.ts:39]:
```suggestion
```

**Review by b-fein — APPROVED** [review]
Tested again:
Inline feedbacks in files where the path contains underscores work again. The other functionality related to inline feedback also works. :+1:
I could not reproduce either of the issues described in #6367 and #7033, so both seem to indeed be fixed. Thank you!

Code review:
Very nice improvements to the code editor component with the refactorings.
Besides that I left a few only small suggestions and/or questions.

File: src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts (hunk 19 above)
Comment (pal03377) [reply src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts:281]: You are right! I changed it.

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts (hunk 22 above)
Comment (pal03377) [reply src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:543]: It's a habit I developed to avoid issues with `null` vs. `undefined`: When you check `x == null` with only two equals signs in JS (or, like here, the opposite `!= null`), it is true for both `null` and `undefined` - so you don't have to worry about that.

However, as this violates our client style guides and it's a bit confusing, I changed it to `undefined` :+1:

File: src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts (hunk 24 above)
Comment (pal03377) [reply src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts:663]: It allows the HTML code (the template) to access the `Feedback` class. I've moved it to the top and added a comment (also in similar places).

**Review by b-fein — APPROVED** [review]
Re-review: Looks good!
All previous suggestions have been implemented and questions explained.

**Review by chrisknedl — COMMENTED** [review]
I only have a little formatting nitpick. Otherwise code looks good as far as I can tell, but I don't feel confident enough in my Angular knowledge to approve such a big PR.

File: src/main/webapp/app/assessment/unreferenced-feedback-detail/unreferenced-feedback-detail.component.ts [hunk 30]
```diff
@@ -0,0 +1,69 @@
...
+                FEEDBACK_SUGGESTION_ACCEPTED_IDENTIFIER,
+                FEEDBACK_SUGGESTION_ADAPTED_IDENTIFIER,
+            );
+        }
+        this.onFeedbackChange.emit(this.feedback);
+    }
+    /**
+     * Emits the deletion of an assessment
+     */
+    public delete() {
```
[the remark this answers is not in the document]
Comment (chrisknedl) [reply src/main/webapp/app/assessment/unreferenced-feedback-detail/unreferenced-feedback-detail.component.ts]: Seems to be on different lines now, it's been a while since I found this when I started reviewing.

[the remark this answers is not in the document]
Comment (pal03377) [reply src/main/webapp/app/assessment/unreferenced-feedback-detail/unreferenced-feedback-detail.component.ts]: Added the additional space 👍

File: src/main/webapp/app/entities/feedback.model.ts (hunk 15 above)
[the remark this answers is not in the document]
Comment (FelixTJDietrich) [reply src/main/webapp/app/entities/feedback.model.ts]: Sounds good, will anyways have to see if my programming module is any good 🤔

**Review by b-fein — DISMISSED** [review]
Re-approve after merge.

**Review by jakubriegel — APPROVED** [review]
Works on ts5

**Review by MarkusPaulsen — APPROVED** [review]
Works on TS5

**Review by MaximilianAnzinger — APPROVED** [review]

**Review by Kroko-fant — APPROVED** [review]
worked on test server 5 in the testing session

**Review by nityanandaz — DISMISSED** [review]
Manual test on TS5

Transition from suggested to accepted/adapted works

File: src/main/webapp/i18n/de/assessment.json [hunk 31]
```diff
@@ -9,7 +9,16 @@
             "feedbackHint": "Dieses Feedback ist mit einer Bewertungsanweisung verbunden. Du kannst zusätzliches Feedback für dieses Abgabeelement geben. Der/Die Studierende sieht das kombinierte Feedback während der Überprüfung.",
             "feedbackCommentPlaceholder": "Du kannst hier ein Feedback abgeben...",
             "additionalFeedbackCommentPlaceholder": "Du kannst hier zusätzliches Feedback abgeben...",
-            "automaticGenerated": "Automatisch erstelltes Feedback",
+            "suggestion": {
+                "suggested": "Feedback-Vorschlag (nicht akzeptiert)",
```
Comment (MarkusPaulsen) [inline src/main/webapp/i18n/de/assessment.json:13]: I think between "not applied" and "nicht akzeptiert" there is some significant difference.

File: src/main/webapp/content/scss/themes/_default-variables.scss [hunk 32]
```diff
@@ -504,6 +506,11 @@ $apollon-gray: $gray-200;
 $apollon-gray-variant: $gray-700;
 $apollon-grid: rgba(36, 39, 36, 0.1);
 
+// Feedback Suggestions (Athena)
+$feedback-suggestions-primary: rgb(181, 78, 254, 1);
+$feedback-suggestions-background: lighten($feedback-suggestions-primary, 24%);
```
Comment (MarkusPaulsen) [inline src/main/webapp/content/scss/themes/_default-variables.scss:511]: Is there a reason, why $feedback-suggestions-background is darkened in dark-mode by 50% but lightened tin light-mode by just 24%?

File: src/main/webapp/app/entities/feedback.model.ts [hunk 33]
```diff
@@ -114,6 +150,40 @@ export class Feedback implements BaseEntity {
...
+        return feedback.reference.substring(this.programmingReferencePrefix.length, indexOfLine); // Split after "_line:"
+    }
+
+    /**
+     * Get the referenced line for referenced programming feedbacks, or undefined.
+     * Typical reference format for programming feedback: `file:src/com/example/package/MyClass.java_line:13`.
+     * Example output in this case: 13
+     */
+    public static getReferenceLine(feedback: Feedback): number | undefined {
+        if (!feedback?.reference?.startsWith(this.programmingReferencePrefix)) {
```
Comment (MarkusPaulsen) [inline src/main/webapp/app/entities/feedback.model.ts:174]: Why does feedback needs a present-check here, but not in getReferenceFilePath?

File: src/main/webapp/app/entities/feedback.model.ts [hunk 34]
```diff
@@ -114,6 +150,40 @@ export class Feedback implements BaseEntity {
...
+            // Find "file:" prefix
+            // No programming feedback
+            return undefined;
+        }
+        const indexOfLine = feedback.reference?.lastIndexOf(this.programmingReferenceLineSeparator); // Split before "_line:"
+        const line = parseInt(feedback.reference?.substring(indexOfLine + this.programmingReferenceLineSeparator.length));
```
Comment (MarkusPaulsen) [inline src/main/webapp/app/entities/feedback.model.ts:180]: Why does `reference` needs a present-check here, but not in getReferenceFilePath?

File: src/main/webapp/app/exercises/programming/shared/code-editor/model/code-editor.model.ts [hunk 35]
```diff
@@ -103,3 +103,20 @@ export enum GitConflictState {
     CHECKOUT_CONFLICT = 'CHECKOUT_CONFLICT',
     OK = 'OK',
 }
+
+/**
+ * Enumeration defining the icon in a file badge.
+ */
+export enum FileBadgeType {
+    FEEDBACK_SUGGESTION = 'FEEDBACK_SUGGESTION',
```
Comment (MarkusPaulsen) [inline src/main/webapp/app/exercises/programming/shared/code-editor/model/code-editor.model.ts:111]: Why do we have an enum with just a single value?

File: src/main/webapp/i18n/de/assessment.json (hunk 31 above)
Comment (pal03377) [reply src/main/webapp/i18n/de/assessment.json:13]: Good catch! I chose to use "not accepted" in the English version.

File: src/main/webapp/content/scss/themes/_default-variables.scss (hunk 32 above)
Comment (pal03377) [reply src/main/webapp/content/scss/themes/_default-variables.scss:511]: Only because it looked better :) I tried using the same percentage, but the saturation of one of the two colors was never right.

File: src/main/webapp/app/entities/feedback.model.ts (hunk 33 above)
Comment (pal03377) [reply src/main/webapp/app/entities/feedback.model.ts:174]: It doesn't need it, I just accidentally added it 👍

File: src/main/webapp/app/entities/feedback.model.ts (hunk 34 above)
Comment (pal03377) [reply src/main/webapp/app/entities/feedback.model.ts:180]: It doesn't need it: The `if` check before would always `return undefined` before that. I've removed the check.

File: src/main/webapp/app/exercises/programming/shared/code-editor/model/code-editor.model.ts (hunk 35 above)
Comment (pal03377) [reply src/main/webapp/app/exercises/programming/shared/code-editor/model/code-editor.model.ts:111]: I added this enum to make it really easy later to other types of badges to the assessment code editor file tree. This way, we will be able to easily extend the badges introduced in this PR to also show badges on files that generally include any feedback, which I believe would be a nice addition in the future.

File: src/test/javascript/spec/component/code-editor/code-editor-ace.component.spec.ts [hunk 36]
```diff
@@ -48,21 +51,17 @@ describe('CodeEditorAceComponent', () => {
...
+                // Mock the ResizeObserver, which is not available in the test environment
+                global.ResizeObserver = jest.fn().mockImplementation((...args) => new MockResizeObserver(args));
             });
     });
 
     afterEach(() => {
         jest.restoreAllMocks();
     });
 
-    it('should know the lines in which inline feedback is shown', () => {
```
[the remark this answers is not in the document]
Comment (pal03377) [reply src/test/javascript/spec/component/code-editor/code-editor-ace.component.spec.ts:58]: It was testing internal behavior. Whenever feedback changed, we previously updated the arrays that are tested here. This is not needed anymore because we now directly calculate this with a simple function (`filterFeedbackForFile`) that is indirectly tested through the other parts of the component.

File: src/main/webapp/content/scss/themes/_default-variables.scss (hunk 32 above)
Comment (pal03377) [reply src/main/webapp/content/scss/themes/_default-variables.scss:511]: For reference, this is how the colors currently look:
screenshot-2023-09-15_001977
screenshot-2023-09-15_001978

**Review by b-fein — APPROVED** [review]

**Review by terlan98 — APPROVED** [review]
Re-tested on TS1. Works as expected 👍

**Review by MarkusPaulsen — APPROVED** [review]
Works on TS2 + Code looks good

**Review by MaximilianAnzinger — APPROVED** [review]
Tested on TS4

**Review by rriyaldhi — DISMISSED** [review]
Tested on TS4 and works as expected.

**Review by tobias-lippert — DISMISSED** [review]
Everything worked.
nice coloring of the feedback items.

**Review by rstief — DISMISSED** [review]
Tested on TS4.
Code LGTM (given the dummy code gets removed 😉 )

File: src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts [hunk 37]
```diff
@@ -262,6 +271,23 @@ export class CodeEditorTutorAssessmentContainerComponent implements OnInit, OnDe
...
+        const allFeedback = [...this.referencedFeedback, ...this.unreferencedFeedback]; // pre-compute to not have to do this in the loop
+        // Don't show feedback suggestions that have the same description and reference - probably it is coming from an earlier suggestion anyway
+        this.feedbackSuggestions = this.feedbackSuggestions.filter((suggestion) => {
+            for (const feedback of allFeedback) {
+                if (feedback.detailText === suggestion.detailText && feedback.reference === suggestion.reference) {
+                    return false; // exclude this suggestion
+                }
+            }
+            return true; // include this suggestion
+        });
```
Comment (bassner) [inline src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts:288]: We could leverage some of the array functions here. What do you think?

```suggestion
        this.feedbackSuggestions = this.feedbackSuggestions.filter((suggestion) =>
            allFeedback.every((feedback) =>
                feedback.detailText !== suggestion.detailText || feedback.reference !== suggestion.reference
            )
        );
```

File: src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-inline-feedback-suggestion.component.html [hunk 38]
```diff
@@ -0,0 +1,28 @@
+<div class="alert p-1 mb-1 border rounded" [style.max-width]="'780px'">
```
Comment (bassner) [inline src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-inline-feedback-suggestion.component.html:1]: Let's avoid inline styles and move it to scss instead

**Review by bassner — CHANGES_REQUESTED** [review]
Hey, did a quick code review. Retesting should not be necessary for these changes

File: src/main/webapp/app/assessment/unreferenced-feedback-detail/unreferenced-feedback-detail.component.html [hunk 39]
```diff
@@ -0,0 +1,92 @@
+<div (drop)="updateFeedbackOnDrop($event)" (dragover)="$event.preventDefault()" class="card mb-3" [class.is-suggestion]="isSuggestion" id="unreferenced-feedback-detail">
```
[the remark this answers is not in the document]
Comment (pal03377) [reply src/main/webapp/app/assessment/unreferenced-feedback-detail/unreferenced-feedback-detail.component.html]: I just renamed this file: [assessment-detail.component.html](https://github.com/ls1intum/Artemis/blob/07d0111e87d0ad48c19bb20c24ed7b70462967ae/src/main/webapp/app/assessment/assessment-detail/assessment-detail.component.html). However, I fixed it now regardless.

File: src/main/webapp/app/assessment/unreferenced-feedback-detail/unreferenced-feedback-detail.component.html [hunk 40]
```diff
@@ -0,0 +1,92 @@
...
+                [(ngModel)]="feedback.credits"
+                (ngModelChange)="emitChanges()"
+                [readOnly]="feedback.gradingInstruction || readOnly"
+                [disabled]="readOnly"
+                [required]="!feedback.gradingInstruction"
+            />
+        </div>
+        <div class="form-group row">
+            <div class="col-4 assessment-label">
+                <label class="pe-0" style="float: left" jhiTranslate="artemisApp.assessment.detail.feedback"></label>
```
[the remark this answers is not in the document]
Comment (pal03377) [reply src/main/webapp/app/assessment/unreferenced-feedback-detail/unreferenced-feedback-detail.component.html]: I just renamed this file: [assessment-detail.component.html](https://github.com/ls1intum/Artemis/blob/07d0111e87d0ad48c19bb20c24ed7b70462967ae/src/main/webapp/app/assessment/assessment-detail/assessment-detail.component.html). However, I fixed it now regardless.

File: src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts (hunk 37 above)
Comment (pal03377) [reply src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts]: Nice suggestion! I added the change.

File: src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-inline-feedback-suggestion.component.html (hunk 38 above)
Comment (pal03377) [reply src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-inline-feedback-suggestion.component.html]: I just renamed this file: [assessment-detail.component.html](https://github.com/ls1intum/Artemis/blob/07d0111e87d0ad48c19bb20c24ed7b70462967ae/src/main/webapp/app/assessment/assessment-detail/assessment-detail.component.html). However, I fixed it now regardless.

File: src/main/webapp/app/assessment/unreferenced-feedback-detail/unreferenced-feedback-detail.component.html [hunk 41]
```diff
@@ -0,0 +1,92 @@
...
+                >{{ 'artemisApp.exampleSubmission.feedback.' + feedback.correctionStatus! | artemisTranslate }}
+            </span>
+            <span *ngIf="feedback.correctionStatus !== 'CORRECT'" class="text-danger"
+                >{{ 'artemisApp.exampleSubmission.feedback.' + feedback.correctionStatus! | artemisTranslate }}
+            </span>
+
+            <!-- :warning: emoji was rendered as a black-white glyph, hence the solution with the fa-icon -->
+            <fa-layers *ngIf="feedback.correctionStatus !== 'CORRECT'">
+                <fa-icon class="text-warning" [icon]="faExclamationTriangle"></fa-icon>
+                <fa-icon [icon]="faExclamation" size="2x" [styles]="{ width: '16px', 'margin-top': '-6px' }" [classes]="['text-dark']" transform="shrink-10"></fa-icon>
```
[the remark this answers is not in the document]
Comment (pal03377) [reply src/main/webapp/app/assessment/unreferenced-feedback-detail/unreferenced-feedback-detail.component.html]: I just renamed this file: [assessment-detail.component.html](https://github.com/ls1intum/Artemis/blob/07d0111e87d0ad48c19bb20c24ed7b70462967ae/src/main/webapp/app/assessment/assessment-detail/assessment-detail.component.html). However, I fixed it now regardless.
