### PR TITLE
`Assessment`: Fix an issue where grading criteria are not applied correctly on drag and drop

### LINKED ISSUE #9979: `Assessment`: Cannot drag and drop structured assessment criteria under certain circumstances
### Describe the bug

The scenario is as follows:
I as an assessor am currently assessing a student submission. 
The exercise has structured assessment criteria, and I would like to drag and drop them into the Feedback section at the bottom of the assessment page. 
The first one works just fine. I then add some text into this feedback item, but the next time that I try to drag and drop another assessment criterion into the feedback section, it doesn't show up. If I repeat the dragging and dropping immediately after, it does show up.

### To Reproduce

1. Create a programming exercise with a due date a few minutes in the future, and select manual assessment (by clicking on the automatic assessment item in the timeline). Also add an assessment criterion on the bottom of the creation page.
2. In the online editor, create an assignment repository and submit once.
3. Wait until the due date passed and start the assessment of the submission.
4. See the bug description for the steps to reproduce the issue.

### Expected behavior

Dragging and dropping of the assessment criterions should always work the first time. It shouldn't matter if the instructor entered some text before that.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

7.7.5

### What browsers are you seeing the problem on?

Chrome, Safari

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by chrisknedl**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added a test related to the feature while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

Closes #9979.

### Description

The current issue actually stems from another bugfix that solved a problem where a drag and drop of the assessment criteria caused duplicates (#8908). The problem was that, due to event bubbling, the drop event was triggered twice when a new grading criteria was dropped on an existing unreferenced feedback item, namely in the `unreferenced-feedback.component.html` and `unreferenced-feedback-detail.component.html` files. The solution is to call `event.stopPropagation()` on the sub-component to make sure that only the intended event handler is executed.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exercise with manual assessment, due date in the future and at least one grading instruction/criterion

1. Log in to Artemis
2. Participate in the exercise, wait until the due date passed
3. Start assessing your participation
4. Make sure that the bugs described in #8908 and #9979 can't be replicated anymore

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved event handling for feedback updates to prevent unintended event propagation.
	- Enhanced feedback validation to ensure accurate assessment creation.

- **Refactor**
	- Streamlined feedback management logic by removing unnecessary tracking variables.
	- Introduced dedicated feedback validation method.

- **Tests**
	- Updated test suite for unreferenced feedback component.
	- Added new stub component for more precise testing.
	- Improved test case scenarios for feedback interactions.

### CODE REVIEW

**Comment by chrisknedl** [comment]
Third time's the charm. If github-actions decides one more time that the `assessment` label does not belong here, then I'll give up.

**Review by vinceclifford — APPROVED** [review]
Tested on TS1, works as expected.

**Review by vinceclifford — COMMENTED** [review]
Tested on TS5 an not on TS1

File: src/test/javascript/spec/helpers/stubs/unreferenced-feedback-detail-stub.component.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
+import { Component, EventEmitter, Input, InputSignal, Output, input } from '@angular/core';
+import { Feedback } from '../../../../../main/webapp/app/entities/feedback.model';
+
+@Component({
+    selector: 'jhi-unreferenced-feedback-detail',
+    template: '<div (drop)="updateFeedbackOnDrop($event)"></div>',
+})
+export class UnreferencedFeedbackDetailStubComponent {
+    @Input() public feedback: Feedback;
+    resultId: InputSignal<number> = input.required<number>();
```
Comment (b-fein) [inline src/test/javascript/spec/helpers/stubs/unreferenced-feedback-detail-stub.component.ts:10]: Should all inputs and outputs use this newer syntax?

**Review by HawKhiem — DISMISSED** [review]
Tested on TS5. Works as described

**Review by ole-ve — APPROVED** [review]
code is more reasonable now, thanks 👍

File: src/test/javascript/spec/helpers/stubs/unreferenced-feedback-detail-stub.component.ts (hunk 1 above)
Comment (chrisknedl) [reply src/test/javascript/spec/helpers/stubs/unreferenced-feedback-detail-stub.component.ts:10]: In this case, we really only need the input and output fields because the fixture wouldn't work otherwise. So I just copied the fields from the actual component. I don't think that it's a problem here for this stub.

**Review by kevinfischer4 — DISMISSED** [review]
Tested on TS1, works as expected. The bugs are not occuring.

**Review by b-fein — APPROVED** [review]
Code :+1:

**Comment by chrisknedl** [comment]
The conflict was due to the removal of the `: boolean` type annotation in `feedbackDetailChanges: boolean = false;`. The PR can stay on ready to merge.

**Review by ole-ve — APPROVED** [review]
re-approve code

**Review by b-fein — APPROVED** [review]

**Review by sawys777 — APPROVED** [review]
Tested on TS1, everything works as expected

**Review by SimonEntholzer — APPROVED** [review]
Code

**Review by b-fein — APPROVED** [review]

**Review by SindiBuklaji — APPROVED** [review]
Tested on TS2 and it works as excepted.

**Review by ole-ve — APPROVED** [review]
re-approve code after integrating angular 19 changes

**Review by krusche — APPROVED** [review]
