### PR TITLE
`Assessment`: Escape the participant name in the csv format of the scores export to avoid issues with commas

### LINKED ISSUE #4767: CSV Export "Export Results" broken
### Describe the bug

The functionality "Export Results" in the "Scores" view of programming exercises produces incorrect results. Some student names contain a comma which is interpreted as an additional column in the exported CSV file.

### To Reproduce

Try to export a programming exercise with a participant who has a comma in its name.

### Expected behavior

Quoted strings in CSV files.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).

### Motivation and Context
Closes #4767

### Description
Quotes are added around the student/team name.
The other fields (login name, score, points, repository-URL) never contain commas. Therefore, putting quotes around them is not necessary.

### Steps for Testing

Prerequisites:
- 1 Instructor
- Some exercise with student submissions

1. Go to the Scores page of the exercise.
2. Click on the Export Scores button in the top-right corner.
3. The name of the student/the team name should be inside `"`s. You might have to open the file in a text editor instead of LibreOffice/Excel as they probably remove the quotes automatically.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
unchanged

### Screenshots
n/a

### CODE REVIEW

File: src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores-export-button.component.ts [hunk 1]
```diff
@@ -126,7 +126,7 @@ export class ExerciseScoresExportButtonComponent {
         const { participantName, participantIdentifier } = participation;
         const score = roundValueSpecifiedByCourseSettings(result.score, getCourseFromExercise(exercise));
 
-        const columns = [participantName, participantIdentifier, score, resultWithPoints.totalPoints];
+        const columns = [`"${participantName}"`, participantIdentifier, score, resultWithPoints.totalPoints];
```
Comment (akesfeden) [inline src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores-export-button.component.ts:129]: I am not sure if the name can legally contain `"` characters, but as a precaution maybe it may make sense to escape `"` characters by replacing them with `""` to handle this potential case too.

**Review by akesfeden — APPROVED** [review]
Tested on TS3, works as expected. Code looks good too, I have a potential suggestion.

**Review by Bofan-Zhu — APPROVED** [review]
Tested on ts2. Everything looks as expected. 👍

**Review by Hialus — COMMENTED** [review]
The code generally looks good.
However, in my opinion this is more a quick and dirty fix.
We should replace the current creation of the CSV file either in this PR on in a future PR with the usage of Papa Parse.
Papa Parse is the usual way we read and write CSV files in Artemis, as it is a proper CSV parser that would have automatically handled an edge case like this.

**Review by dveljacic — APPROVED** [review]
Tested on TS2. The names are being surrounded with `"`, as it can be seen in the attached screenshot. ✅ 

csv

**Review by baranimo7 — APPROVED** [review]
Tested on ts2. Names were in ""

**Review by MertAksehirlioglu — APPROVED** [review]
Tested on TS2, works as expected.

**Comment by b-fein** [comment]
> However, in my opinion this is more a quick and dirty fix. We should replace the current creation of the CSV file either in this PR on in a future PR with the usage of Papa Parse. Papa Parse is the usual way we read and write CSV files in Artemis, as it is a proper CSV parser that would have automatically handled an edge case like this.

@Hialus I definitely agree.
I won’t have time neither this nor next week to refactor it further, but would be happy to do it afterwards. I think just merging the quick fix until then such that the right now actually occurring issue in the production system can be fixed would be acceptable in that case.

@akesfeden The further refactoring would then also handle the potential further issue of `"` in the student/team name.

**Comment by Hialus** [comment]
> @Hialus I definitely agree.
I won’t have time neither this nor next week to refactor it further, but would be happy to do it afterwards. I think just merging the quick fix until then such that the right now actually occurring issue in the production system can be fixed would be acceptable in that case.

Sounds good 👍🏻

**Review by Hialus — APPROVED** [review]
