### PR TITLE
`Adaptive learning`: Disable calling course competency server endpoint when atlas is disabled

### LINKED ISSUE #10377: API Calls Result in 404 and 504 Errors + Missing Learning Path Option
## Description
Some API calls return `404` or `504` errors in the browser console. When using the Brave browser, I frequently encounter `504` errors related to the Sentry API.

In **Chrome and Brave**, opening a programming exercise results in the following error:

ERROR NullInjectorError: R3InjectorError(Standalone[i])[t -> t -> t]:
  NullInjectorError: No provider for t!
    at co.get (core.mjs:1656:21)

Additionally, the learning path feature is missing from the course settings. When I try to force-load the path, a button appears to enable it, but clicking it results in an API error.

Docker Log: 
WARN 1 --- [Artemis] [at-handler-3416] o.z.problem.spring.common.AdviceTraits: Not Found: No static resource api/courses/3/learning-paths/enable.

Console Log:
PUT https://artemis.ise-i.ostfalia.de/api/courses/3/learning-paths/enable 404 (Not Found)

Another `404` error occurs for:

Docker Log:
WARN 1 --- [Artemis] [at-handler-2014] o.z.problem.spring.common.AdviceTraits: Not Found: No static resource api/science-settings.

## Expected Behavior
- API calls should not fail with `404` or `504` errors.
- The learning path feature should be available in the course settings as expected.

## Additional Information
- **Version 7.9.1 (Dev Instance):** The learning path option is available in the course settings.
- **Version 7.10.2:** The learning path option is missing.

Please let me know if you need any additional logs or steps to reproduce the issue.

Maybe this are two Bugs, but i dont know where one starts and the other ends.
And i hope its not a Network problem on our side, but i can't find any problems here. 

### To Reproduce

Sentry API:
1. Open a Course,Exercise or other Tabs.

404 Error:
1. Open a Course in Management View
2. Add  "/learning-path-management" to Course because the Learning Path Icon is not there.
3. Click on enable Learning Path.

### Expected behavior

No Errors

### Screenshots

Image
Image
Image
Image
Image
Image
Image
Image

### Which version of Artemis are you seeing the problem on?

7.10.2

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

Brave and Chrome

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by ole-ve**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style..

### Motivation and Context
Fixes #10377.

### Description
When the atlas profile was disabled, there were some left occurrences of calls to atlas resources.

### Steps for Testing
`Note`: Needs to be tested locally
1. Repeat for all exercise types:
2. Open the exercise update view (i.e. edit or create). Make sure that no error toaster notification is shown
3. For every lecture unit type:
4. Open the lecture unit update view and make sure that no error toaster notification shown
5. As an admin go to Server Administration > Standardized Competencies should not throw an error
6. (Unrelated to previous steps): Reload the page and see that no requests are sent to the "science-settings" endpoint in the dev network tab

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
  - Enhanced the competency selection experience to dynamically load course-related information for users with specific profile attributes, ensuring that relevant competency options are presented when a valid course identifier is detected.

### CODE REVIEW

File: src/main/webapp/app/shared/competency-selection/competency-selection.component.ts [hunk 1]
```diff
@@ -66,6 +69,16 @@ export class CompetencySelectionComponent implements OnInit, ControlValueAccesso
     // halfway between medium and high
 
     ngOnInit(): void {
+        // it's an explicit design decision to don't clutter every component that uses this component with the need to check if the atlas profile is enabled
+        this.profileService.getProfileInfo().subscribe((profileInfo) => {
+            const atlasEnabled = profileInfo.activeProfiles.includes(PROFILE_ATLAS);
+            if (atlasEnabled === true) {
```
Comment (MaximilianAnzinger) [inline src/main/webapp/app/shared/competency-selection/competency-selection.component.ts:75]:
```suggestion
            if (atlasEnabled) {
```
If I'm not wrong `atlasEnabled` is never undefined. So I aggree with the usually stupid rabbit, that this is a little nicer.

**Review by MaximilianAnzinger — CHANGES_REQUESTED** [review]

**Review by MaximilianAnzinger — CHANGES_REQUESTED** [review]
Could you please also include the administration of standardized competencies in this PR?

**Comment by ole-ve** [comment]
@MaximilianAnzinger all links to reach the admin standardized competency page are hidden, see [here](https://github.com/ls1intum/Artemis/blob/93eba08f0530257383bf23c00d3a258b9a2b4e52/src/main/webapp/app/shared/layouts/navbar/navbar.component.html#L295).

So the user couldn't reach this page if atlas was disabled.

File: src/main/webapp/app/shared/competency-selection/competency-selection.component.ts [hunk 2]
```diff
@@ -66,6 +69,16 @@ export class CompetencySelectionComponent implements OnInit, ControlValueAccesso
     // halfway between medium and high
 
     ngOnInit(): void {
+        // it's an explicit design decision to not clutter every component that uses this component with the need to check if the atlas profile is enabled
+        this.profileService.getProfileInfo().subscribe((profileInfo) => {
```
Comment (isabellagessl) [inline src/main/webapp/app/shared/competency-selection/competency-selection.component.ts:73]: I think you should unsubscribe from this in an ngOnDestroy, right?

**Review by isabellagessl — APPROVED** [review]
Requested changes were implemented. Code lgtm

**Review by coolchock — APPROVED** [review]
tested locally, no toaster errors were shown 👍

**Review by MaximilianAnzinger — APPROVED** [review]

**Comment by ole-ve** [comment]
unrelated server tests, this PR is client-only

**Review by BBesrour — APPROVED** [review]
tested locally, lgtm

**Review by tobias-lippert — APPROVED** [review]
Tested locally. Error didn't appear.

**Review by krusche — APPROVED** [review]
