### PR TITLE
`Communication`: Hide channel-name input field if messaging is disabled

### LINKED ISSUE #6957: Automatically generated channel name can contain invalid characters
### Describe the bug

I experienced it while creating an exam but should be reproducible with lectures and exercises as well.
Give the entity a name containing periods/hashtags any other invalid character. 
See that the channel name contains the invalid character as well.
Try to save the entity. 
Saving fails because of an invalid channel name.

### To Reproduce

see above.

### Expected behavior

invalid characters should be replaced with - 

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.3.5

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by lennart-keller**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Resolves #6957 

### Description

The input field for the channel name is only shown if messaging is enabled in the course. However, a channel is created for each lecture/exercise/exam even if messaging is disabled.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course
- A lecture, exercises, and an exam that do not have a channel 

1. Disable messaging in the course
2. Create a lecture with a long title that also contains special characters
3. Creation of the lecture should be possible
4. Import the just created lecture
5. Import another lecture that does not have a channel
6. Confirm that you can visit a lecture page and write messages (which are posts internally and visible on the communication tab)
7. Activate messaging in the course
8. Confirm that 3 lecture channels exist on the messages tab under browse channels
9. Confirm that the channel-name input field is visible, when editing a lecture
10. Confirm that you can visit a lecture page and write messages that become visible on the messages tab
11. Repeat 1-9 for each exercise type and exams

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [exam-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Client-Tests/app/exam/manage/exams/exam-update.component.ts.html) | 95.86% | ✅ |
| [file-upload-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/file-upload/manage/file-upload-exercise-update.component.ts.html) | 84.37% | ✅ |
| [modeling-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/modeling/manage/modeling-exercise-update.component.ts.html) | 86.36% | ✅ |
| [programming-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/update/programming-exercise-update.component.ts.html) | 79.9% | ✅ |
| [programming-exercise-information.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/update/update-components/programming-exercise-information.component.ts.html) | 100% | ✅ |
| [quiz-exercise-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/quiz/manage/quiz-exercise-detail.component.ts.html) | 88.19% | ✅ |
| [exercise-title-channel-name.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/exercise-title-channel-name/exercise-title-channel-name.component.ts.html) | 100% | ✅ |
| [text-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/text/manage/text-exercise/text-exercise-update.component.ts.html) | 86% | ✅ |
| [lecture-title-channel-name.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Client-Tests/app/lecture/lecture-title-channel-name.component.ts.html) | 100% | ✅ |
| [title-channel-name.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/form/title-channel-name/title-channel-name.component.ts.html) | 100% | ✅ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [FileUploadExerciseImportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/FileUploadExerciseImportService.html) | 100% | ✅ |
| [ModelingExerciseImportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/ModelingExerciseImportService.html) | 96% | ✅ |
| [QuizExerciseImportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/QuizExerciseImportService.html) | 88% | ✅ |
| [TextExerciseImportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/TextExerciseImportService.html) | 100% | ✅ |
| [ExamImportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.exam/ExamImportService.html) | 99% | ✅ |
| [ChannelService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.metis.conversation/ChannelService.html) | 91% | ✅ |
| [ProgrammingExerciseImportBasicService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.programming/ProgrammingExerciseImportBasicService.html) | 100% | ✅ |
| [ProgrammingExerciseService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.programming/ProgrammingExerciseService.html) | 93% | ✅ |
| [ExamResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/ExamResource.html) | 97% | ✅ |
| [FileUploadExerciseResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/FileUploadExerciseResource.html) | 100% | ✅ |
| [LectureResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/LectureResource.html) | 97% | ✅ |
| [ModelingExerciseResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/ModelingExerciseResource.html) | 98% | ✅ |
| [QuizExerciseResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/QuizExerciseResource.html) | 93% | ✅ |
| [TextExerciseResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5331/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/TextExerciseResource.html) | 99% | ✅ |

### Screenshots

If messaging is disabled, the channel-name input field is no longer shown:
after

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java [hunk 1]
```diff
@@ -451,6 +448,12 @@ private Channel updateChannelName(Channel channel, String newChannelName) {
         }
     }
 
+    /**
+     * Creates a channel object with some default properties
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java:452]: just a suggestion: directly specify in the javadoc that it is a public channel but not an announcement channel and the channel ist not archived instead of writing "some default properties"  which requires me to read the code to understand what is actually set.

File: src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java [hunk 2]
```diff
@@ -468,4 +471,21 @@ private static Channel createDefaultChannel(@NotNull String channelName) {
     private boolean allowDuplicateChannelName(Channel channel) {
         return channel.getExercise() != null || channel.getLecture() != null || channel.getExam() != null;
     }
+
+    /**
+     * Generates the channel name based on the associated lecture/exercise/exam title and a corresponding prefix.
+     * It replaces alternating/consecutive occurrences of spaces and hyphens and limits length of the name to 30 characters.
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java:477]: I would add that it only allows letters, digits and hyphens and replaces all other characters with hyhens.

File: src/main/java/de/tum/in/www1/artemis/web/rest/LectureResource.java [hunk 3]
```diff
@@ -247,8 +247,7 @@ public ResponseEntity<Lecture> importLecture(@PathVariable long sourceLectureId,
 
         final var savedLecture = lectureImportService.importLecture(sourceLecture, destinationCourse);
 
-        String channelName = generateChannelNameFromTitle(savedLecture.getTitle());
-        Channel createdChannel = channelService.createLectureChannel(savedLecture, channelName);
+        Channel createdChannel = channelService.createLectureChannel(savedLecture, null);
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/web/rest/LectureResource.java:250]: personal preference: passing optionals instead of null but feel free to ignore as I don't think we have an official guideline for that.

File: src/main/webapp/app/shared/form/title-channel-name/title-channel-name.component.ts [hunk 4]
```diff
@@ -43,10 +41,9 @@ export class TitleChannelNameComponent implements OnInit {
         this.formatChannelName(this.channelNamePrefix + this.title);
     }
 
-    formatChannelName(newName: string) {
-        if (!this.hideChannelName) {
-            this.channelName = newName.toLowerCase().slice(0, 30).replaceAll(' ', '-');
-            this.channelNameChange.emit(this.channelName);
-        }
+    formatChannelName(newName: string, allowDuplicateDashes = false) {
```
Comment (tobias-lippert) [inline src/main/webapp/app/shared/form/title-channel-name/title-channel-name.component.ts:44]: when do we want to allow duplicate dashes? What's a use case for this?

**Review by tobias-lippert — DISMISSED** [review]
Code looks good, I just have some (optional) suggestions concerning javadoc.

File: src/main/java/de/tum/in/www1/artemis/web/rest/LectureResource.java (hunk 3 above)
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/web/rest/LectureResource.java:250]: I agree, this would also improve the code in the method:
`channelName.orElse(generateChannelNameFromTitle("exercise-", exercise.getTitle())`

File: src/main/webapp/app/exam/manage/exams/exam-update.component.ts [hunk 5]
```diff
@@ -330,4 +330,6 @@ export class ExamUpdateComponent implements OnInit {
         this.exam.examUsers = undefined;
         this.exam.studentExams = undefined;
     }
+
+    protected readonly isMessagingEnabled = isMessagingEnabled;
```
Comment (Strohgelaender) [inline src/main/webapp/app/exam/manage/exams/exam-update.component.ts:334]: we usually have these on the top of the file, you already have `readonly FeatureToggle = FeatureToggle;` in this file.

File: src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java [hunk 6]
```diff
@@ -330,10 +330,7 @@ public void unarchiveChannel(Long channelId) {
      * @return the created channel
      */
     public Channel createLectureChannel(Lecture lecture, String channelName) {
-        if (!lecture.getCourse().getCourseInformationSharingConfiguration().isMessagingEnabled()) {
-            return null;
-        }
-        Channel channelToCreate = createDefaultChannel(channelName);
+        Channel channelToCreate = createDefaultChannel(channelName != null ? channelName : generateChannelNameFromTitle("lecture-", lecture.getTitle()));
```
Comment (simon-hng) [inline src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java:333]: you could use nullish coalescing here
```suggestion
        Channel channelToCreate = createDefaultChannel(channelName ?? generateChannelNameFromTitle("lecture-", lecture.getTitle()));
```

File: src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java [hunk 7]
```diff
@@ -348,10 +345,10 @@ public Channel createLectureChannel(Lecture lecture, String channelName) {
      * @return the created channel
      */
     public Channel createExerciseChannel(Exercise exercise, String channelName) {
-        if (!exercise.isCourseExercise() || !exercise.getCourseViaExerciseGroupOrCourseMember().getCourseInformationSharingConfiguration().isMessagingEnabled()) {
+        if (!exercise.isCourseExercise()) {
             return null;
         }
-        Channel channelToCreate = createDefaultChannel(channelName);
+        Channel channelToCreate = createDefaultChannel(channelName != null ? channelName : generateChannelNameFromTitle("exercise-", exercise.getTitle()));
```
Comment (simon-hng) [inline src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java:351]:
```suggestion
        Channel channelToCreate = createDefaultChannel(channelName ?? generateChannelNameFromTitle("exercise-", exercise.getTitle()));
```

File: src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java [hunk 8]
```diff
@@ -468,4 +471,21 @@ private static Channel createDefaultChannel(@NotNull String channelName) {
...
+    /**
+     * Generates the channel name based on the associated lecture/exercise/exam title and a corresponding prefix.
+     * It replaces alternating/consecutive occurrences of spaces and hyphens and limits length of the name to 30 characters.
+     *
+     * @param title prefix for the channel
+     * @param title title of the lecture/exercise/exam to derive the channel name from
+     * @return the generated channel name
+     */
+    private static String generateChannelNameFromTitle(@NotNull String prefix, String title) {
+        String channelName = prefix + (title != null ? title : "");
```
Comment (simon-hng) [inline src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java:484]:
```suggestion
        String channelName = prefix + (title ?? "");
```

File: src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java [hunk 9]
```diff
@@ -468,4 +471,21 @@ private static Channel createDefaultChannel(@NotNull String channelName) {
...
+        channelName = channelName.toLowerCase().replaceAll("[^a-z0-9]+", "-");
```
Comment (simon-hng) [inline src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java:485]: Adding comments before regexes explaining them would be nice

File: src/main/java/de/tum/in/www1/artemis/web/rest/LectureResource.java (hunk 3 above)
Comment (simon-hng) [reply src/main/java/de/tum/in/www1/artemis/web/rest/LectureResource.java:250]: I agree. I hate nulls

**Review by simon-hng — COMMENTED** [review]
Left some suggestions for more readable code. Looks good overall to me

File: src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java (hunk 6 above)
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java:333]: This is java code, so no ;(. See my suggestion with optionals above.

File: src/main/java/de/tum/in/www1/artemis/web/rest/LectureResource.java (hunk 3 above)
Comment (b-fein) [reply src/main/java/de/tum/in/www1/artemis/web/rest/LectureResource.java:250]: Alternative: Provide an overload in `ChannelService`
```java
public Channel createLectureChannel(Lecture lecture) {
     String channelName = generateChannelNameFromTitle("lecture-", lecture.getTitle());
     return createLectureChannel(lecture, channelName);
}
```

That way neither `null` nor `Optional`s needed.

File: src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java (hunk 6 above)
Comment (lennart-keller) [reply src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java:333]: The `??` operator doesn't exist in Java. I am using optionals now

File: src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java (hunk 7 above)
Comment (lennart-keller) [reply src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java:351]: Using optionals

File: src/main/webapp/app/shared/form/title-channel-name/title-channel-name.component.ts (hunk 4 above)
Comment (lennart-keller) [reply src/main/webapp/app/shared/form/title-channel-name/title-channel-name.component.ts:44]: This is the case, if the user manually enters a channel name. We could restrict it further, but there is no technical reason for it, so I wouldn't do it. We also do not restrict it for standard channels.

File: src/main/java/de/tum/in/www1/artemis/web/rest/LectureResource.java (hunk 3 above)
Comment (lennart-keller) [reply src/main/java/de/tum/in/www1/artemis/web/rest/LectureResource.java]: I call `createLectureChannel ` in multiple places and I cannot guarantee that the second input is not null. Instead of using overloads I would rather provide an optional here in the function argument.

**Review by basak-akan — APPROVED** [review]
Tested in testing session worked well

**Review by RY997 — APPROVED** [review]
Tested in testing session, worked well

File: src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java [hunk 10]
```diff
@@ -468,4 +472,24 @@ private static Channel createDefaultChannel(@NotNull String channelName) {
...
+     * consecutive hyphens, e.g. "Example(%)name" becomes "example-name".
+     *
+     * @param prefix prefix for the channel
+     * @param title  title of the lecture/exercise/exam to derive the channel name from
+     * @return the generated channel name
+     */
+    private static String generateChannelNameFromTitle(@NotNull String prefix, Optional<String> title) {
+        String channelName = prefix + title.orElse("");
+        // [^a-z0-9]+ matches all occurrences of single or consecutive characters that are no digits and letters
+        channelName = channelName.toLowerCase().replaceAll("[^a-z0-9]+", "-");
```
Comment (Strohgelaender) [inline src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java:489]: if I remember that correctly, we also need to replace multiple `-` instances here with a single `-` since we wanted to avoid repeating them in autogenerated names, right?

File: src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java [hunk 11]
```diff
@@ -347,11 +341,11 @@ public Channel createLectureChannel(Lecture lecture, String channelName) {
      * @param channelName the name of the channel
      * @return the created channel
      */
-    public Channel createExerciseChannel(Exercise exercise, String channelName) {
-        if (!exercise.isCourseExercise() || !exercise.getCourseViaExerciseGroupOrCourseMember().getCourseInformationSharingConfiguration().isMessagingEnabled()) {
+    public Channel createExerciseChannel(Exercise exercise, Optional<String> channelName) {
+        if (!exercise.isCourseExercise()) {
```
[the remark this answers is not in the document]
Comment (lennart-keller) [reply src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java:345]: Yes, I am sure. We want to create the channel in the background even if messaging is disabled.

File: src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java (hunk 10 above)
Comment (lennart-keller) [reply src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java:489]: Yes, and this is covered by the current regex as well, since it replaces everything that is not a digit or a number. Hence something like `---` would also be replaced with `-`.

**Review by MaximilianAnzinger — APPROVED** [review]
Code lgtm
