### PR TITLE
`Communication`: Fix an issue for answers in unnamed group chats

### LINKED ISSUE #10423: Internal server error when sending thread answer in unnamed group
### Describe the bug

In a group chat with not explicit name set, when sending an answer post in a thread, an internal server error occurred.

### To Reproduce

1. Go to a group chat with no name (or create a new group chat)
2. Create a base post
3. Reply to that post in a thread
4. Notice the "Internal Server error"

### Expected behavior

No error should occur

### Screenshots

https://github.com/user-attachments/assets/29156cac-b30e-4ab2-afc3-067dabb4787c

### Which version of Artemis are you seeing the problem on?

8.0.0 - current develop branch

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by FelberMartin**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

### Motivation and Context

There has been an internal server error for creating answer posts in a group chat without a name.

This PR closes #10423 

### Description

Similar to the creation of a new base post, we use the `conversationService.loadConversationWithParticipantsIfGroupChat()` function to get the participants for a group chat (the participants are needed to construct the conversation title for the notifications.

### Steps for Testing

Prerequisites:
- 1 Student

1. Go to a group chat with no name (or create a new group chat)
2. Create a base post
3. Reply to that post in a thread
4. Notice there is no "Internal Server error"

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **Refactor**
  - Streamlined the messaging process to enhance group conversation handling.
  - Improved the retrieval of conversation details, ensuring participants are accurately loaded while reducing redundant dependencies.

### CODE REVIEW

File: src/main/java/de/tum/cit/aet/artemis/communication/service/AnswerMessageService.java [hunk 1]
```diff
@@ -93,8 +89,9 @@ public AnswerPost createAnswerMessage(Long courseId, AnswerPost answerMessage) {
             throw new BadRequestAlertException("A new answer post cannot already have an ID", METIS_ANSWER_POST_ENTITY_NAME, "idexists");
         }
 
-        Conversation conversation = conversationService.isMemberOrCreateForCourseWideElseThrow(answerMessage.getPost().getConversation().getId(), author, Optional.empty())
-                .orElse(conversationRepository.findByIdElseThrow(answerMessage.getPost().getConversation().getId()));
+        var conversationId = answerMessage.getPost().getConversation().getId();
+        var conversation = conversationService.isMemberOrCreateForCourseWideElseThrow(conversationId, author, Optional.empty())
```
Comment (MaximilianAnzinger) [inline src/main/java/de/tum/cit/aet/artemis/communication/service/AnswerMessageService.java:93]: Optional: Maybe add a comment to explain why this differentiation is necessary. If I would come back here after a while this would not be immediately clear to me.

**Review by MaximilianAnzinger — APPROVED** [review]
Thank you for considering my feedback 👍 Code LGTM

**Review by anian03 — APPROVED** [review]
Tested on TS2, sending replies in unnamed groups works without an internal server error now 👍

**Review by coolchock — APPROVED** [review]
code

**Review by SimonKaran13 — APPROVED** [review]
Tested on TS1, when writing an answer to a message in a group chat no error occurrs.

https://github.com/user-attachments/assets/a608c2ff-9222-413f-864e-4c40a9186a4e

**Review by julian-wls — APPROVED** [review]
Tested on TS3, works as expected!

**Review by krusche — APPROVED** [review]
