### PR TITLE
`Programming exercises`: Fix LTI Moodle programming exercise participation for current and new Artemis users

### LINKED ISSUE #5745: LTI: New Users are not Created in GitLab
### Describe the bug

I was trying out the new LTI integration #5558 in a GitLab/Jenkins setup. When starting a programming exercise, there is an internal server error that the user does not exist in GitLab yet.

### To Reproduce

1. Start an exercise as a LTI user.
2. Notice the error.

### Expected behavior

The new LTI user is created in GitLab, too, so that they can start programming exercises.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

_No response_

### Relevant log output

```shell
Oct 18 09:31:56 artemis conmon[804382]: de.tum.in.www1.artemis.service.connectors.gitlab.GitLabException: The user was not created in GitLab and has to be manually added.
Oct 18 09:31:56 artemis conmon[804382]:         at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.configureRepository(GitLabService.java:90)
Oct 18 09:31:56 artemis conmon[804382]:         at de.tum.in.www1.artemis.service.ParticipationService.configureRepository(ParticipationService.java:390)
Oct 18 09:31:56 artemis conmon[804382]:         at de.tum.in.www1.artemis.service.ParticipationService.startProgrammingExercise(ParticipationService.java:200)
Oct 18 09:31:56 artemis conmon[804382]:         at de.tum.in.www1.artemis.service.ParticipationService.startExerciseWithInitializationDate(ParticipationService.java:134)
Oct 18 09:31:56 artemis conmon[804382]:         at de.tum.in.www1.artemis.service.ParticipationService.startExercise(ParticipationService.java:100)
Oct 18 09:31:56 artemis conmon[804382]:         at de.tum.in.www1.artemis.web.rest.ParticipationResource.startParticipation(ParticipationResource.java:184)
```

### PR DESCRIPTION
**Pull request by basak-akan**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

This pull request aims to fix issues between Artemis and Moodle Lti configuration and programming exercise participation.
1. Lti endpoints not working: After moving some LTI endpoints (with #6165), Artemis Lti capabilities became unreachable from Moodle.
2. Grading issues for current Artemis users: Students using Artemis can participate in programming exercises, but their grades don't show up in Moodle.
3. Errors for new users: New students who sign up through Moodle get an error when they try to participate in programming exercises.

### Description

- Corrected the paths for the moved Lti endpoints, and ensured that they are now fully operational within Moodle.
- The `ltiNewResultService` synchronization method call is added in `processNewProgrammingSubmission` for programming exercise results in Artemis to be reflected within Moodle's grading system.
- To fix the internal server error encountered by new users, optional VCS and optional CI user creation steps are added to the Lti new user generation process. (Also fixes #5745)

### Steps for Testing
Please test this PR with TS1, TS2, or TS5. I already pre-configured programming exercises for easy testing.

Prerequisites:
- Depending on the test server you are using:
  - Use "Programming Exercise for TS1" if testing on TS1.
  - Use "Programming Exercise for TS2" if testing on TS2.
  - Use "Programming Exercise for TS5" if testing on TS5.
- For Existing Artemis Users:
  - Moodle Login Credentials:
     | Test Server  | Username                   | Password                                                                           |
     | :------------ |    :--------                   |          :------------------------------------------------------ |
     | TS5/TS1      | test_user_1                  | same as artemis_test_user_1 from artemis test accounts |
     | TS2             |  artemis_test_user_1    | same as artemis_test_user_1 from artemis test accounts |
  
- For Non-Artemis User Tests:
  - The following users can be used (Note: These users will be deleted after this PR is merged): 
  - Moodle Login Credentials
       | Username                 | Password                 |
       |    :--------                 |                     :------- |
       | moodle_test_user_1 | moodle_test_user_1 |
       | moodle_test_user_2 | moodle_test_user_2 |
       | moodle_test_user_3 | moodle_test_user_3 |
       | moodle_test_user_4 | moodle_test_user_4 |
       | moodle_test_user_5 | moodle_test_user_5 |

Non-Artemis User Testing Steps:
1. Navigate to Moodle: https://moodle.ase.in.tum.de/
2. Login using one of the non-Artemis user credentials provided above.
3. Select the "Lti Testing Course".
4. Choose the exercise corresponding to your test server.
5. Confirm that you can view the Artemis page within the Moodle frame.
6. Check the automatically generated password. 
7.  Copy the generated password, mark the checkbox, and confirm.
8. Ensure you are logged into Artemis.
9. Initiate the programming exercise participation.
10. Submit your solution.
11. Navigate to the Moodle grades page: https://moodle.ase.in.tum.de/course/view.php?id=6
12. Confirm that your submission results are visible.

Artemis User Testing Steps:
1. Navigate to Moodle: https://moodle.ase.in.tum.de/
2. Log in using the test user credentials.
3. Select the "Lti Testing Course".
4. Choose the exercise corresponding to your test server.
5. Confirm that you can view the Artemis page within the Moodle frame.
6. Through the Moodle frame, log in to Artemis using the same credentials.
7. Ensure you are logged into Artemis.
8. Initiate the programming exercise participation.
9. Submit your solution.
10. Navigate to the Moodle grades page: https://moodle.ase.in.tum.de/course/view.php?id=6
11. Confirm that your submission results are visible.

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [course-lti-configuration.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5259/latest/artifact/shared/Coverage-Report-Client-Tests/app/course/manage/course-lti-configuration/course-lti-configuration.component.ts.html) | 100% | ✅ |
| [lti13-exercise-launch.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5259/latest/artifact/shared/Coverage-Report-Client-Tests/app/lti/lti13-exercise-launch.component.ts.html) | 100% | ✅ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [LtiService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5259/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.connectors.lti/LtiService.html) | 98% | ✅ ❌ |
| [PublicProgrammingSubmissionResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5259/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.open/PublicProgrammingSubmissionResource.html) | 96% | ✅ ❌ |

### Screenshots

Results are reflected for existing Artemis users:
image

Non-Artemis Users are generated:
image

### CODE REVIEW

**Review by MaximilianAnzinger — DISMISSED** [review]
For now, this PR looks good. Tested on/with ts2. We experienced an issue that should be handled in a follow-up PR. 👍

**Review by lennart-keller — APPROVED** [review]
Tested in testing session

**Review by Strohgelaender — APPROVED** [review]
code lgtm

**Review by lennart-keller — DISMISSED** [review]
Code lgtm

**Review by laurenzfb — DISMISSED** [review]
Testing session

**Review by milljoniaer — DISMISSED** [review]
tested in testing session

**Review by Kroko-fant — DISMISSED** [review]
tested in testing session

**Review by krusche — CHANGES_REQUESTED** [review]
@basak-akan I don't understand why Artemis would report a new result over LTI when a programming submission is received on Artemis. For me, this sounds incorrect.
Instead, I would assume that Artemis reports a result over LIT when a new result is received in `processNewProgrammingExerciseResult` in `PublicResultResource` 

As far as I can see, this is already done in `notifyUserAboutNewResult` in `ProgrammingMessagingService`.

Could you please double check this?

**Comment by basak-akan** [comment]
> @basak-akan I don't understand why Artemis would report a new result over LTI when a programming submission is received on Artemis. For me, this sounds incorrect. Instead, I would assume that Artemis reports a result over LIT when a new result is received in `processNewProgrammingExerciseResult` in `PublicResultResource`
> 
> As far as I can see, this is already done in `notifyUserAboutNewResult` in `ProgrammingMessagingService`.
> 
> Could you please double check this?

@krusche Thank you for pointing that out. I misunderstood the situation initially. After reverting the unrelated changes and reviewing the process again, I can confirm that Artemis report a result over LTI in the manner you described. I am sorry for the confusion!

**Review by lennart-keller — APPROVED** [review]
Reapprove code after reverting unrelated changes

**Review by laurenzfb — APPROVED** [review]
Tested on TS1 with existing Artemis account and moodle account. Both worked as described

**Review by milljoniaer — APPROVED** [review]
tested in testing session on ts2 and works as expected

**Review by julian-christl — APPROVED** [review]
Code changes look good, thanks for the fix!

File: src/main/java/de/tum/in/www1/artemis/service/connectors/lti/LtiService.java [hunk 1]
```diff
@@ -112,11 +123,18 @@ private Authentication createNewUserFromLaunchRequest(String email, String usern
             final User newUser;
             final var groups = new HashSet<String>();
             groups.add(LTI_GROUP_NAME);
-            newUser = userCreationService.createUser(username, null, groups, firstName, lastName, email, null, null, Constants.DEFAULT_LANGUAGE, true);
+
+            var password = RandomUtil.generatePassword();
```
Comment (Kroko-fant) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/lti/LtiService.java:127]: I wouldn't use var here

File: src/test/java/de/tum/in/www1/artemis/LtiIntegrationTest.java [hunk 2]
```diff
@@ -170,6 +173,23 @@ private void addJiraMocks(String email, String existingUser) throws Exception {
...
+        bitbucketRequestMockProvider.enableMockingOfRequests();
+
+        String username = "prefix_";
+        Matcher matcher = Pattern.compile("lis_person_sourcedid=([^&#]+)").matcher(requestBody);
+        if (matcher.find() && !matcher.group(1).isEmpty()) {
+            username += matcher.group(1);
+        }
+        else {
+            matcher = Pattern.compile("ext_user_username=([^&#]+)").matcher(requestBody);
+            if (matcher.find()) {
```
Comment (Kroko-fant) [inline src/test/java/de/tum/in/www1/artemis/LtiIntegrationTest.java:186]: is it possible that matcher.find() returns false? and if thats the case what would happen to username?

**Review by Kroko-fant — COMMENTED** [review]
Code looks good to me apart from two small things

**Review by dearjasmina — APPROVED** [review]
code LGTM

File: src/main/java/de/tum/in/www1/artemis/service/connectors/lti/LtiService.java (hunk 1 above)
Comment (basak-akan) [reply src/main/java/de/tum/in/www1/artemis/service/connectors/lti/LtiService.java:127]: I used var because it's shorter and clearer in this case. But I get that it might be confusing. Why do you think I shouldn't use var here?

File: src/test/java/de/tum/in/www1/artemis/LtiIntegrationTest.java (hunk 2 above)
Comment (basak-akan) [reply src/test/java/de/tum/in/www1/artemis/LtiIntegrationTest.java:186]: This method is a helper that takes certain input parameters. We know that in a standard request, the username field is send with lis_person_sourcedid for edX, for moodle with ext_user_username. In this scenario it is not the case that match.find() would be false.

File: src/main/java/de/tum/in/www1/artemis/service/connectors/lti/LtiService.java (hunk 1 above)
Comment (julian-christl) [reply src/main/java/de/tum/in/www1/artemis/service/connectors/lti/LtiService.java:127]: For readability reasons (and according to our guidelines as far as I remember) `var` should be used to significantly shorten variable types. `String` is not a long type, though.
