### PR TITLE
`Atlas`: Grey out user interface elements when the service is disabled

### LINKED ISSUE #10377: API Calls Result in 404 and 504 Errors + Missing Learning Path Option
## Description
Some API calls return `404` or `504` errors in the browser console. When using the Brave browser, I frequently encounter `504` errors related to the Sentry API.

In **Chrome and Brave**, opening a programming exercise results in the following error:

ERROR NullInjectorError: R3InjectorError(Standalone[i])[t -> t -> t]:
  NullInjectorError: No provider for t!
    at co.get (core.mjs:1656:21)

Additionally, the learning path feature is missing from the course settings. When I try to force-load the path, a button appears to enable it, but clicking it results in an API error.

Docker Log: 
WARN 1 --- [Artemis] [at-handler-3416] o.z.problem.spring.common.AdviceTraits: Not Found: No static resource api/courses/3/learning-paths/enable.

Console Log:
PUT https://artemis.ise-i.ostfalia.de/api/courses/3/learning-paths/enable 404 (Not Found)

Another `404` error occurs for:

Docker Log:
WARN 1 --- [Artemis] [at-handler-2014] o.z.problem.spring.common.AdviceTraits: Not Found: No static resource api/science-settings.

## Expected Behavior
- API calls should not fail with `404` or `504` errors.
- The learning path feature should be available in the course settings as expected.

## Additional Information
- **Version 7.9.1 (Dev Instance):** The learning path option is available in the course settings.
- **Version 7.10.2:** The learning path option is missing.

Please let me know if you need any additional logs or steps to reproduce the issue.

Maybe this are two Bugs, but i dont know where one starts and the other ends.
And i hope its not a Network problem on our side, but i can't find any problems here. 

### To Reproduce

Sentry API:
1. Open a Course,Exercise or other Tabs.

404 Error:
1. Open a Course in Management View
2. Add  "/learning-path-management" to Course because the Learning Path Icon is not there.
3. Click on enable Learning Path.

### Expected behavior

No Errors

### Screenshots

Image
Image
Image
Image
Image
Image
Image
Image

### Which version of Artemis are you seeing the problem on?

7.10.2

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

Brave and Chrome

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by ole-ve**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
Closes #10377. When the atlas profile is not enabled, the respective UI components are just now shown. This caused confusion because it was there before.

### Description
Instead of just not rendering the respective components, these changes wrap the respective UI components into a new component. This new component greys out the underlying text (i.e. opacitiy) and shows a respective tooltip. In addition, pointer events are disabled to the wrapped UI components.

### Steps for Testing
`Note`: These changes need to be tested locally as you need to disable the atlas profile.

1. Remove the `atlas`-profile from your respective Spring run configuration.
2. Start the server and the client (if your server is already running, also restart the client as the information of the active profiles is cached in the client)
3. Go to course management of one course
4. See that the "Competency"- and "Learning Path"-tab are present, but greyed out. When hovering over these, you see a tooltip. Make sure you cannot click on those and no pointer-cursor is disabled.
5. Go to course edit. Ensure same behavior for checkbox "Learning Paths Enabled"

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| feature-overlay.component.ts | 100% | ✅              |

### Screenshots
Screenshot 2025-02-22 at 20 03 48

## Summary by CodeRabbit

- **New Features**
  - Introduced a feature overlay mechanism to streamline how feature availability is indicated. Elements across several sections—such as course management, dashboards, and navigation—now use this overlay to show when a feature is disabled while still relying on user permission checks.
  - Added a German and English message for users indicating when a feature is not activated, guiding them to consult their administrator or documentation.

- **Bug Fixes**
  - Simplified conditional rendering logic for various management links, ensuring they are displayed based solely on user permissions while maintaining feature toggle functionality.

- **Tests**
  - Added comprehensive tests to ensure that the feature overlay behaves correctly under both enabled and disabled states.

### CODE REVIEW

**Comment by cremertim** [comment]
Changes look reasonable for me. Is this also intended for other features like the FAQs or the learning paths?

File: src/main/webapp/app/shared/components/feature-overlay/feature-overlay.component.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
+import { Component, input } from '@angular/core';
+import { NgbTooltip } from '@ng-bootstrap/ng-bootstrap';
+
+@Component({
+    selector: 'jhi-feature-overlay',
+    template: `
+        <div
+            ngbTooltip="{{ enabled() ? null : 'This feature is not enabled. Ask your Artemis administrator or consult the documentation for more information.' }}"
```
Comment (MaximilianAnzinger) [inline src/main/webapp/app/shared/components/feature-overlay/feature-overlay.component.ts:8]: Please remember to add translations.

**Review by MaximilianAnzinger — CHANGES_REQUESTED** [review]

**Review by MaximilianAnzinger — DISMISSED** [review]

**Review by isabellagessl — APPROVED** [review]
Tested locally, works as expected. code looks good to me so I approve :)

**Review by coolchock — CHANGES_REQUESTED** [review]
tested locally, `Competencies` and `Learning Paths` are greyed out, but translations keys aren't correct. Your keys are missing the part `artemisApp`.
image

File: src/main/webapp/app/shared/components/feature-overlay/feature-overlay.component.ts [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+    template: `
+        <div ngbTooltip="{{ enabled() ? null : ('artemisApp.featureToggles.title' | artemisTranslate) }}" placement="left">
+            <div [class.disabled]="!enabled()">
+                <ng-content></ng-content>
+            </div>
+        </div>
+    `,
+    styles: [
+        `
+            .disabled {
```
Comment (MaximilianAnzinger) [inline src/main/webapp/app/shared/components/feature-overlay/feature-overlay.component.ts:16]: rather than custom style it would be nice to use Bootstrap. `pe-none` and `opacity-50` should do the same if I'm not mistaken.

**Review by MaximilianAnzinger — CHANGES_REQUESTED** [review]

**Comment by ole-ve** [comment]
Failing server tests are flaky and totally unrelated to these changes

**Review by MaximilianAnzinger — APPROVED** [review]

**Review by isabellagessl — DISMISSED** [review]
Code lgtm

**Review by coolchock — DISMISSED** [review]
thanks for fixing the translations 👍

**Review by BBesrour — DISMISSED** [review]
code

**Review by chrisknedl — DISMISSED** [review]
Tested locally, works as expected 👍

**Review by tobias-lippert — APPROVED** [review]
Tested in testing session. Works as expected.

**Comment by ole-ve** [comment]
note: had 2 code reviews and 2 tests before minimal change in translation.

**Review by krusche — APPROVED** [review]
