### PR TITLE
Fix Usage of Undefined Exam Exercise Dates

### LINKED ISSUE #3821: Tests don't get collected after due date
### Describe the bug

When setting tests and exercise to run after due date, the test results don't get displayed correctly.

### To Reproduce

1. Create and submit a programming exercise with tests (exam to be sure)
2. Set the tests in the grading section to "After due date"
3. Set "Run Tests after Due Date" to a due date in the past
4. Run all tests
5. The result should only show "Build Successful, no tests executed" for the participation

### Expected behavior

Instead of showing the generic response "Build Successful, no tests executed", the actual test results should be displayed.

### Screenshots

Example with the wrong response on top and the correct response at the bottom

### What browsers are you seeing the problem on?

Chrome

### Additional context

Please make sure that it's also possible to have the visibility of the test "After due date" even if "Run Tests after Due Date" is unset.
At the moment it's unclear whether this is actually still possible or not.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by MaisiKoleni**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context
Fix #3821 and related issues. The problem is, that we use the `Exercise` object's dates in some places that need to handle both exam and course exercises and the dates (release, due, assessment due) are undefined (`null` in Java) for exam exercises.

### Description
- *Temporary: added assertions to methods in `Exercise` that must not be used for exam exercises.*
- Fix multiple issues where the presence of exam dates was assumed, but exam exercises have no dates.
- Make the WebSocket respect exam exercise results.
- Add many tests for special exam exercise checks.

#### TODO
- [x] Investigate all failing tests
- [x] Look for more date related problems - future work ??
- [x] ~Redefine and combine some methods in exercise, esp. `isVisibleToStudents` and `isReleased`~
- [x] ~Adjust `validateDates` to make sure, the dates are not defined for exam exercises?~

### Steps for Testing
- Check that #3821 cannot be reproduced.
  
  With an exercise with (almost) all test cases marked after due date:
  image
  Now all test cases are shown, independent of the set build after due date.

- You should also check that you can still work in the code editor on programming exercises and get your results when the build is done *without page reload* (meaning that you still get notified by the server).

### Test Coverage
- **WebsocketMessagingService**
  image
- **ExamDateService**
  image
- **QuizSubmissionResource**
  image

### CODE REVIEW

**Comment by MaisiKoleni** [comment]
See failing test in https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS2362-JAVATEST-2 for more hints where code is using problematic information. This is not a complete list, very likely.

**Comment by MaisiKoleni** [comment]
See commit message for risks that need to be checked.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseGradingService.java [hunk 1]
```diff
@@ -315,7 +317,14 @@ public void logReEvaluate(User user, ProgrammingExercise exercise, Course course
      * @return testCases, but the ones based on the described visibility criterion removed.
      */
     private Set<ProgrammingExerciseTestCase> filterTestCasesForCurrentDate(ProgrammingExercise exercise, Set<ProgrammingExerciseTestCase> testCases) {
-        boolean isBeforeDueDate = exercise.isBeforeDueDate();
+        boolean isBeforeDueDate;
+        if (exercise.isExamExercise()) {
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseGradingService.java:321]: I suggest to move the whole new code to the `examDateService` so that it can be used in more places

File: src/main/java/de/tum/in/www1/artemis/domain/Exercise.java [hunk 2]
```diff
@@ -507,6 +508,7 @@ public void setExerciseHints(Set<ExerciseHint> exerciseHints) {
     // jhipster-needle-entity-add-getters-setters - JHipster will add getters and setters here, do not remove
 
     public Boolean isEnded() {
+        assert isDateUsageAllowed() : "due date is not defined for exam exercises";
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/domain/Exercise.java:511]: I am not a big fan of such assertions. We won't see the assertion errors on production as they are hidden in the log. I think it would be better to directly send error messages to Sentry

File: src/main/java/de/tum/in/www1/artemis/domain/Exercise.java [hunk 3]
```diff
@@ -1048,11 +1053,16 @@ private boolean isValidAssessmentDueDate(ZonedDateTime releaseDate, ZonedDateTim
...
         if (previousDate == null || laterDate == null) {
             return true;
         }
         return previousDate.isBefore(laterDate);
     }
 
+    private boolean isDateUsageAllowed() {
+        // We want to allow serialization to JSON for exam exercises
+        return !isExamExercise()
+                || StackWalker.getInstance().walk(stackFrames -> stackFrames.anyMatch(frame -> frame.getClassName().contains("com.fasterxml.jackson.databind.ser")));
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/domain/Exercise.java:1066]: this also does not look like a good solution. What happens if the class name or serialization framework changes in the future? We would not notice the issue... I think we should avoid this in production code.

I would prefer a different solution, e.g. as part of tests or as part of a service that determines if the use of those dates is allowed

File: src/main/java/de/tum/in/www1/artemis/domain/Exercise.java (hunk 2 above)
Comment (krusche) [reply src/main/java/de/tum/in/www1/artemis/domain/Exercise.java:511]: One improvement would be to add JavaDoc that explicitly says if the method can be used in a specific case.
Another one would be to give an approximation in case of exam exercises. They typically include the exercise group and exam. In case those related objects are available, we could use the end date of the exam or the start of the exam to give an answer to this method.

In the JavaDoc, we could strongly advice to use the examDateService instead

**Comment by MaisiKoleni** [comment]
I added the assertion mainly for investigation purposes, I will remove it once all problems are found and resolved.

**Review by FuchsDominik — APPROVED** [review]
I tested the issue for exam exercises and the tests were executed after the due date and also correctly shown to the student. "Build Successful, no tests executed" was only shown during the exam, after it, the actual number of passed results can be seen

**Review by MDK5 — APPROVED** [review]
Tested in testing session, worked for  normal exercises

**Review by rs-maker — APPROVED** [review]
Code looks good too.

**Review by julian-christl — APPROVED** [review]
CR done, looks good, no complaints

**Review by jpbernius — APPROVED** [review]
