### PR TITLE
`Programming exercises`: Export and import embedded files in problem statement

### LINKED ISSUE #6535: Images not exported for Programming Exercises
### Describe the bug

When exporting a programming exercise, the images are not exported. If the exercise is then imported on the same system it has been exported from, the images are there, because the image URLs are the same. For a different system, the images can't be displayed, as they are not present on that system.

### To Reproduce

1. Go to the details page of a programming exercise with images in its description
2. Click on `Download Exercise` 
3. Import exercise on another system (e.g. local setup) by navigating to the exercise section of a course and clicking `Import Programming Exercise`
4. There should be no images in the description of the imported exercise

### Expected behavior

The export should also include images, so that they can be automatically transferred between systems.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.1.5

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tobias-lippert**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

Closes  #6535

### Description
Until now files embedded into the problem statement are not part of the export. This is not a problem as long as the export and import happens on the same instance. Once one imports a programming exercise on a different instance, the embedded files and hence parts of the problem statements are missing.
This PR adds the embedded files to the export and considers them when importing a programming exercise from a file

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3.  Create a programming exercise with a  problem statement that contains one or more embedded files (e.g. jpg files)
4. Export the exercise (Download exercise button)
5. Use another test server to import the exercise from file (make sure to deploy this branch first)
6. After the import the files should be shown in the problem statement (during the import they cannot be shown as they do not yet exist on the server)

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
-  Another instance as the one used for the export (make sure to deploy this branch there)

1. Log in to Artemis
2. Import the programming exercise from file you previously exported into an exercise group
3. After the import the files should be shown in the problem statement (during the import they cannot be shown as they do not yet exist on the server)

#### Performance Review
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) | Coment |
|------------|--------------:|-----------------------------:|----------------:|
| ProgrammingExerciseImportFromFileService.java | 96% | ✅ |
| ProgrammingExerciseExportService | 86% | ✅ | my changes are fully covered |
|ZipFileService.java| 96%| ✅ |
|programming-exercise-problem.component.ts| 100%| ✅ |
|programming-exercise-update-wizard-problem.component.ts|100% |✅|

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java [hunk 1]
```diff
@@ -156,8 +163,34 @@ public Path exportProgrammingExerciseInstructorMaterial(ProgrammingExercise exer
...
+        Matcher matcher = Pattern.compile(EMBEDDED_FILE_REGEX).matcher(exercise.getProblemStatement());
+        while (matcher.find()) {
+            embeddedFiles.add(matcher.group());
+        }
+        log.info("Found embedded files:{} ", embeddedFiles);
+        for (String embeddedFile : embeddedFiles) {
+            String filePath = embeddedFile.substring(embeddedFile.indexOf("(") + 1, embeddedFile.indexOf(")"));
+            String fileName = filePath.replace(API_MARKDOWN_FILE_PATH, "");
+            Path imageFilePath = Path.of(FilePathService.getMarkdownFilePath(), fileName);
+            Path imageExportPath = Path.of(exportDir.toString(), fileName);
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:184]:
```suggestion
            Path imageExportPath = exportDir.resolve(fileName);
```

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java [hunk 2]
```diff
@@ -85,11 +83,29 @@ public ProgrammingExercise importProgrammingExerciseFromFile(ProgrammingExercise
...
     }
 
+    /**
+     * copy embedded files from the extracted zip file to the markdown folder, so they can be used in the problem statement
+     **/
+    private void copyEmbeddedFiles(Path importExerciseDir) throws IOException {
+        // the conversion to a string is needed because otherwise the file extension is not included
+        Predicate<Path> embeddedFile = file -> file.getFileName().toString().endsWith(".jpg") || file.getFileName().toString().endsWith(".jpeg")
+                || file.getFileName().toString().endsWith(".png") || file.getFileName().toString().endsWith(".gif") || file.getFileName().toString().endsWith(".svg")
+                || file.getFileName().toString().endsWith(".pdf");
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java:100]: This could be a separate private method instead of a predicate.

Additionally, saving `file.getFileName().toString()` to a variable once would save a lot of duplication.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java [hunk 3]
```diff
@@ -156,8 +163,34 @@ public Path exportProgrammingExerciseInstructorMaterial(ProgrammingExercise exer
...
+     * @param pathsToBeZipped the paths that should be included in the zip file
+     */
+
+    private void copyEmbeddedFiles(ProgrammingExercise exercise, Path exportDir, List<Path> pathsToBeZipped) throws IOException {
+        List<String> embeddedFiles = new ArrayList<>();
+        Matcher matcher = Pattern.compile(EMBEDDED_FILE_REGEX).matcher(exercise.getProblemStatement());
+        while (matcher.find()) {
+            embeddedFiles.add(matcher.group());
+        }
+        log.info("Found embedded files:{} ", embeddedFiles);
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:179]:
```suggestion
        log.debug("Found embedded files:{} ", embeddedFiles);
```

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java [hunk 4]
```diff
@@ -85,11 +83,29 @@ public ProgrammingExercise importProgrammingExerciseFromFile(ProgrammingExercise
...
+        copyEmbeddedFiles(exerciseFilePath.toAbsolutePath().getParent().resolve(FileNameUtils.getBaseName(exerciseFilePath.toString())));
         importRepositoriesFromFile(importedProgrammingExercise, importExerciseDir, oldShortName);
         importedProgrammingExercise.setCourse(course);
+        fileService.scheduleForDirectoryDeletion(importExerciseDir, 5);
         return importedProgrammingExercise;
     }
 
+    /**
+     * copy embedded files from the extracted zip file to the markdown folder, so they can be used in the problem statement
+     **/
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java:95]: Not in the usual Javadoc format.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java [hunk 5]
```diff
@@ -85,6 +88,10 @@ public class ProgrammingExerciseExportService {
 
     public static final String EXPORTED_EXERCISE_PROBLEM_STATEMENT_FILE_PREFIX = "Problem-Statement";
 
+    private static final String EMBEDDED_FILE_REGEX = "!\\[.*\\.(jpg|jpeg|png|svg|gif|pdf)] *\\(.*\\)";
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:91]: I don’t think this matches images properly:

- The part in `[]` is the `alt="…"` attribute of the `` HTML tag. That can by an arbitrary image description written by the instructor.
- The `(…)` is the actual image link. That can even be a full http-URL for externally hosted images. Those cannot be copied. I think we probably only care about anything that matches `/api/files/markdown/.*` here regardless of the file extension. We can probably safely assume that only allowed files could have been uploaded in the first place.
   - That same assumption then also can be made for the import.
   - That shouldn’t be a security risk, as the export/import/edit of exercises is only done by editors/instructors/admins which have to be trusted anyway to provide safe Git repository template files etc.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java [hunk 6]
```diff
@@ -85,11 +83,29 @@ public ProgrammingExercise importProgrammingExerciseFromFile(ProgrammingExercise
         if (Boolean.TRUE.equals(programmingExerciseForImport.isStaticCodeAnalysisEnabled())) {
             staticCodeAnalysisService.createDefaultCategories(importedProgrammingExercise);
         }
+        copyEmbeddedFiles(exerciseFilePath.toAbsolutePath().getParent().resolve(FileNameUtils.getBaseName(exerciseFilePath.toString())));
         importRepositoriesFromFile(importedProgrammingExercise, importExerciseDir, oldShortName);
         importedProgrammingExercise.setCourse(course);
+        fileService.scheduleForDirectoryDeletion(importExerciseDir, 5);
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java:89]: Five minutes until deletion may be a bit short in case the instructor directly changes dates, … of the exercise during the import before saving the new exercise for the first time.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java [hunk 7]
```diff
@@ -85,11 +83,29 @@ public ProgrammingExercise importProgrammingExerciseFromFile(ProgrammingExercise
...
 
+    /**
+     * copy embedded files from the extracted zip file to the markdown folder, so they can be used in the problem statement
+     **/
+    private void copyEmbeddedFiles(Path importExerciseDir) throws IOException {
+        // the conversion to a string is needed because otherwise the file extension is not included
+        Predicate<Path> embeddedFile = file -> file.getFileName().toString().endsWith(".jpg") || file.getFileName().toString().endsWith(".jpeg")
+                || file.getFileName().toString().endsWith(".png") || file.getFileName().toString().endsWith(".gif") || file.getFileName().toString().endsWith(".svg")
+                || file.getFileName().toString().endsWith(".pdf");
+        try (var embeddedFiles = Files.list(importExerciseDir).filter(embeddedFile)) {
```
Comment (b-fein) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java:101]: In the export you place all images in a subdirectory `"programming-exercise-material"`. Could you only walk over that directory and copy its content without additional filter?

**Review by b-fein — CHANGES_REQUESTED** [review]
Thanks for implementing a first iteration to solve the issue so quickly.
Though, I think the logic that decides which files are exported currently does not work reliably. I added inline comments with more details in the export service.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java (hunk 7 above)
Comment (tobias-lippert) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java:101]: This is the subdirectory that is used for all the export material, it contains more than the images. (exercise details json file, problem statement markdown file, zipped repository), but I think I could place it in an additional subdirectory and hence get rid of the filter

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java (hunk 6 above)
Comment (tobias-lippert) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java:89]: If this endpoint is called the instructor has already clicked the import button and the exercise has been generated, so I think 5 minutes are fine.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java (hunk 5 above)
Comment (tobias-lippert) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:91]: Ok, so if I understand this correctly, we only care about the content in the rounded brackets.
For the export we can safely assume this because all other files are blocked anyway when someone tries to upload them. So the export doesn't contain any invalid files. Hence, the import would only contain invalid, potentially malicious files if someone actively modifies the export which is possible for sure but the same applies to the other files you mentioned.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java [hunk 8]
```diff
@@ -156,19 +168,54 @@ public Path exportProgrammingExerciseInstructorMaterial(ProgrammingExercise exer
...
-     * Export instructor repositories and optionally students' repositories in a zip file.
+     * In case the problem statement contains embedded files, they need to be part of the zip, so they can be imported again.
      *
+     * @param exercise        the programming exercise that is exported
+     * @param outputDir       the directory where the content of the export is stored
+     * @param pathsToBeZipped the paths that should be included in the zip file
+     */
+
+    private void copyEmbeddedFiles(ProgrammingExercise exercise, Path outputDir, List<Path> pathsToBeZipped) throws IOException {
+        List<String> embeddedFiles = new ArrayList<>();
```
Comment (JohannesStoehr) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:179]: This should be a set in case there is the same file in the problem statement twice

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java [hunk 9]
```diff
@@ -156,19 +168,54 @@ public Path exportProgrammingExerciseInstructorMaterial(ProgrammingExercise exer
...
      * @param exercise              the programming exercise
      * @param includingStudentRepos flag for including the students repos as well
      * @param outputDir             the path to a directory that will be used to store the zipped programming exercise.
+     * @param workingDir            the path to a directory that will be used to store the cloned repositories.
      * @param exportErrors          List of failures that occurred during the export
      * @param reportData            List of all exercises and their statistics
      * @return the path to the zip file
      */
-    public Path exportProgrammingExerciseRepositories(ProgrammingExercise exercise, Boolean includingStudentRepos, Path outputDir, List<String> exportErrors,
+    public Path exportProgrammingExerciseRepositories(ProgrammingExercise exercise, Boolean includingStudentRepos, Path workingDir, Path outputDir, List<String> exportErrors,
```
Comment (JohannesStoehr) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:218]: Why can't we use the output directory for working as well?

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java [hunk 10]
```diff
@@ -85,11 +82,32 @@ public ProgrammingExercise importProgrammingExerciseFromFile(ProgrammingExercise
...
+     **/
+    private void copyEmbeddedFiles(Path importExerciseDir) throws IOException {
+        Path embeddedFilesDir = importExerciseDir.resolve("files");
+
+        if (!Files.exists(embeddedFilesDir)) {
+            return;
+        }
+        try (var embeddedFiles = Files.list(embeddedFilesDir)) {
+            for (var file : embeddedFiles.toList()) {
+                var targetPath = Path.of(FilePathService.getMarkdownFilePath(), file.getFileName().toString());
```
Comment (JohannesStoehr) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java:105]: Does this overwrite any other file with the same name that is already stored in Artemis?

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java (hunk 9 above)
Comment (tobias-lippert) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:218]: because we zip all the content in the directory,  If we do not distinguish the directory the cloned repos are part of the final zip file

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java (hunk 10 above)
Comment (tobias-lippert) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportFromFileService.java:105]: No, it does nothing if it is the same file or fails if the file already exists.
It's very unlikely that this file already exists and the method fails because the file name contains the current timestamp and a random UUID, so I thought this behavior is acceptable as long as it doesn't overwrite existing files.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java (hunk 9 above)
Comment (JohannesStoehr) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:218]: But couldn't we simply use two subfolders in the directory that is provided to us?
This would keep the parameter list shorter

**Review by chrisknedl — COMMENTED** [review]
Had a look at the code. Also nice pictures 👍

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java [hunk 11]
```diff
@@ -156,19 +168,54 @@ public Path exportProgrammingExerciseInstructorMaterial(ProgrammingExercise exer
...
+        }
+        for (String embeddedFile : embeddedFiles) {
+            String filePath = embeddedFile.substring(embeddedFile.indexOf("(") + 1, embeddedFile.indexOf(")"));
+            String fileName = filePath.replace(API_MARKDOWN_FILE_PATH, "");
+            Path imageFilePath = Path.of(FilePathService.getMarkdownFilePath(), fileName);
+            Path imageExportPath = embeddedFilesDir.resolve(fileName);
+            Files.copy(imageFilePath, imageExportPath);
+        }
+
+    }
```
[the remark this answers is not in the document]
Comment (chrisknedl) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:202]: `embeddedFilesDir` is the culprit.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java (hunk 9 above)
Comment (tobias-lippert) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:218]: no, because the content of the zip is all content recursively, so even if it's a subdirectory it's included.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java (hunk 11 above)
[the remark this answers is not in the document]
Comment (tobias-lippert) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java]: fixed by always initializing the path before the if statement instead of a null check

**Review by chrisknedl — DISMISSED** [review]
Suggestions implemented -> approve

**Review by pal03377 — CHANGES_REQUESTED** [review]
tested in testing session on ts1, apparently pdf files are not exported yet

**Review by JohannesStoehr — DISMISSED** [review]
Newest code changes look good and address my last comment 👍

**Review by terlan98 — COMMENTED** [review]
Tested on TS1 (export) and TS3 (import). The exercise was successfully imported with an embedded pdf file (both as a standalone exercise and exam). I got the following error for the latter, despite a successful import:
Screenshot 2023-05-10 at 10 08 46

**Review by terlan98 — APPROVED** [review]
Retested on TS1(export) and TS3(import). The implementation now works for both standalone exercises and exam exercises as expected. 👍

**Review by b-fein — APPROVED** [review]
Code re-:+1:

**Review by pellumbbaboci — DISMISSED** [review]
Tested during testing session and works as expected for programming course exercise with PNG file.

**Review by frederik-kt — DISMISSED** [review]
Tested exporting an exam exercise on TS1 and importing it again for an exam on TS3. Worked as expected except for a small issue with brackets in the file name that caused the export to fail.

**Review by lennart-keller — DISMISSED** [review]
Tested during testing session and works as expected for pdf, jpg and png files.

**Review by frederik-kt — APPROVED** [review]
Latest changes look good. Re-tested exporting and importing an exam exercise locally by deleting the files after exporting the exercise. Importing from the zip file worked well and the embedded files were there.

**Review by terlan98 — APPROVED** [review]
Still works

**Review by laadvo — APPROVED** [review]
Re-tested on ts1 and ts3, exporting and importing of programming exercises with embedded files works, now even if there are parentheses in the file name.

**Review by b-fein — APPROVED** [review]
code changes since last review look good

**Comment by chbachm** [comment]
Would it be possible to export also images reference by inline html  ?
As scaling of images is difficult/impossible with the markdown reference ![...]{...} there might be some  tags in problem statements, as the latter do support the specification of image sizes. We did that infrequently by drag and dropping an image to get the markdown reference to the (renamed) uploaded file and transerferd the link then to  .

**Comment by tobias-lippert** [comment]
@chbachm  I think this should be feasible as one would only need to extend the current regex or introduce another regex to extract those. Since this PR is already ready to merge, I would address this in a follow-up unless it's really urgent.

**Comment by chbachm** [comment]
> I think this should be feasible as one would only need to extend the current regex or introduce another regex to extract those. Since this PR is already ready to merge, I would address this in a follow-up unless it's really urgent.

Another PR for that is perfectly ok for me.

> Could you maybe give me an example how such a tag would like with the file name?

You could replace
```text
![x_schematic.png](/api/files/markdown/Markdown_2023-05-16T09-19-43-656_9ec9f67f.png)
```
by
```text
<figure>
  <img src="/api/files/markdown/Markdown_2023-05-16T09-19-43-656_9ec9f67f.png" height="150"/>
  <figcaption>Bild 1: Schematische Darstellung einer Turingmaschine</figcaption>
</figure>
```
as there you can set the display height of the image, for example.

However, the clean solution would be to be able to provide a display size directly in the markdown construction, however, I found no working solution for that. Or am I wrong and there is some working syntax for that to work in Artemis?

@tobias-lippert Thanks for looking into that.

**Comment by tobias-lippert** [comment]
@chbachm I quickly looked into the implementation of the markdown editor and it seems that this limitation comes from the underlying ace editor that we use (at least I couldn't find any places where our logic should influence this). So I think for now the only feasible solution would be indeed to additionally extract files that are embedded as you described.

**Comment by chbachm** [comment]
A quick and **dirty** hack is probably to insert an html/xml comment such that that the image export parser notices the image to export. It also has the advantage, one can see the original file name of the image.

```text
<figure>
  <!--![x_schematic.png](/api/files/markdown/Markdown_2023-05-16T09-19-43-656_9ec9f67f.png)-->
  <img src="/api/files/markdown/Markdown_2023-05-16T09-19-43-656_9ec9f67f.png" height="150"/>
</figure>
```
However, the need to fallback to html for image sizing is ugly in itself :)

OT: As far as I can see, the Artemis upload folder for images is never cleaned automatically and, thus, grows with old pictures/versions like a garbage dump forever.

**Comment by krusche** [comment]
You can specify image dimensions in Markdown, see http://demo.showdownjs.com/ (scroll down to image dimensions)

We link this documentation in the Markdown Editor, however this might not be obvious.
image

(We implemented the help like in the Github markdown editor)

Should we change the (?) to some kind of help or syntax button? Would this make it easier to understand the syntax?

Example for an image with dimensions

``

**Comment by chbachm** [comment]
Nobody in our group did not know the syntax for image sizing, so I tried some from other Markdown systems, which did not work. I did not "see" the ?-button, maybe as I did not expect one (maybe as there is no context sensivite help consitently/generally at all "controls"/"contexts"/pages).
Nevertheless, this is good news. Now, I will replace all  tags. Further I think that there should be no export for images (only) in HTML <figure> references for clean code and, thus, Tobias should imho not create (new) pull request for that.
@krusche Thanks for the hint, it seems that I was blind for that.
