### PR TITLE
`General`: Fix an issue in the course overview and an edge case in programming exercise solution participations

### LINKED ISSUE #6556: `Programming exercises`: NullPointerException when handling VCS URL of the solution participation
### Describe the bug

There is a `NullPointerException` when handling the VCS URL of the solution participation in some cases.

This happens, e.g. when checking out the solution repository in the online editor or when a new result is received from the CI system. Therefore, the exercise is broken since no results for the solution can be persisted.

**Update**: Maybe some caching issue? The exercise seems to fix itself and then break again intermittently.

### To Reproduce

Not sure if this happens for all newly created exercises.

1. Create a new programming exercise.
2. Artemis throws an internal server error (see logs below) whenever a new result from the CI system is received.
   - The error only occurs for the solution repository, for the base/template one the results are received.

### Expected behavior

The VCS URL is present so that no NullPointerException is thrown.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.1.5

### What browsers are you seeing the problem on?

Firefox

### Additional context

Gitlab/Jenkins/PostgreSQL setup

Importing the exercise into another course fixes the issue.

- in `AbstractVersionControlService::getOrRetrieveBranchOfExercise` `ProgrammingExercise::getVcsTemplateRepositoryUrl` is called which at that point must already return `null` since there are no other read operations on the URL between that and the crash
- `ProgrammingExercise::getVcsTemplateRepositoryUrl` has multiple paths which can return `null`
  - probably because the `templateParticipation` is not loaded/initialized? 

### Relevant log output

```shell
May 09 09:45:09 artemis artemis[2497859]: java.lang.NullPointerException: Cannot invoke "de.tum.in.www1.artemis.domain.VcsRepositoryUrl.getURI()" because "repositoryUrl" is null
May 09 09:45:09 artemis artemis[2497859]:         at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.getPathIDFromRepositoryURL(GitLabService.java:172)
May 09 09:45:09 artemis artemis[2497859]:         at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.getDefaultBranchOfRepository(GitLabService.java:161)
May 09 09:45:09 artemis artemis[2497859]:         at de.tum.in.www1.artemis.service.connectors.vcs.AbstractVersionControlService.getOrRetrieveBranchOfExercise(AbstractVersionControlService.java:166)
May 09 09:45:09 artemis artemis[2497859]:         at de.tum.in.www1.artemis.web.rest.repository.RepositoryProgrammingExerciseParticipationResource.getOrRetrieveBranchOfDomainObject(RepositoryProgrammingExerciseParticipationResource.jav>
May 09 09:45:09 artemis artemis[2497859]:         at de.tum.in.www1.artemis.web.rest.repository.RepositoryResource.getStatus(RepositoryResource.java:299)
May 09 09:45:09 artemis artemis[2497859]:         at de.tum.in.www1.artemis.web.rest.repository.RepositoryProgrammingExerciseParticipationResource.getStatus(RepositoryProgrammingExerciseParticipationResource.java:333)
May 09 09:45:09 artemis artemis[2497859]:         at de.tum.in.www1.artemis.web.rest.repository.RepositoryProgrammingExerciseParticipationResource$$FastClassBySpringCGLIB$$9ebf5bf.invoke(<generated>)
```

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Fix latest sentry issues:
* [Course overview](https://sentry.ase.in.tum.de/organizations/artemis/issues/31675/?environment=prod&query=is%3Aunresolved&referrer=issue-stream)
    * Also caused the [unknown translations](https://sentry.ase.in.tum.de/organizations/artemis/issues/31560/?environment=prod&query=is%3Aunresolved&referrer=issue-stream)
* [Exercise issue](https://sentry.ase.in.tum.de/organizations/artemis/issues/31591/?environment=prod&query=is%3Aunresolved&referrer=issue-stream)
    * Also reported here: Fixes #6556

### Description

Quiz exercises can have a submission without a participation due to their scheduling. This is handled in the code, where it tried to add the new participation to an unchangeable list.
The other issue was that when a new result for the solution was produced it was possible that the default branch is not yet stored in Artemis, causing the null pointer.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise
- 1 Quiz Exercise

1. Log in to Artemis
2. Create the exercise and commit a second time to its solution, the new result should be shown
3. Participate as a student in the quiz and reload the exercise overview during the conduction of the quiz. Check that there are no errors and you correctly see your running participation.

#### Performance Review
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| ExerciseService.java | 97% | ✅                           |
| AbstractVersionControlService.java | 95% | ✅              |

### CODE REVIEW

**Review by pal03377 — COMMENTED** [review]
see @tobias-lippert comment

File: src/main/java/de/tum/in/www1/artemis/service/connectors/vcs/AbstractVersionControlService.java [hunk 1]
```diff
@@ -163,6 +164,9 @@ public String getOrRetrieveBranchOfStudentParticipation(ProgrammingExerciseStude
     @Override
     public String getOrRetrieveBranchOfExercise(ProgrammingExercise programmingExercise) {
         if (programmingExercise.getBranch() == null) {
+            if (!Hibernate.isInitialized(programmingExercise.getTemplateParticipation())) {
+                programmingExercise = programmingExerciseRepository.findWithTemplateAndSolutionParticipationByIdElseThrow(programmingExercise.getId());
```
Comment (julian-christl) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/vcs/AbstractVersionControlService.java:168]: How about, instead of reloading the whole exercise, we only update the section that we tested for?
=> Retrieve the template participation of the exercise and set it, if it's needed further down.

File: src/main/java/de/tum/in/www1/artemis/service/connectors/vcs/AbstractVersionControlService.java [hunk 2]
```diff
@@ -163,6 +164,9 @@ public String getOrRetrieveBranchOfStudentParticipation(ProgrammingExerciseStude
     @Override
     public String getOrRetrieveBranchOfExercise(ProgrammingExercise programmingExercise) {
         if (programmingExercise.getBranch() == null) {
```
Comment (julian-christl) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/vcs/AbstractVersionControlService.java:166]: To reduce the nesting, we could invert this conditional return `branch`in the section below.

Comment (julian-christl) [reply src/main/java/de/tum/in/www1/artemis/service/connectors/vcs/AbstractVersionControlService.java:171]: I see your point

**Review by julian-christl — APPROVED** [review]
Code looks good

**Review by tobias-lippert — APPROVED** [review]
Retested on ts2.

**Review by eceeeren — APPROVED** [review]
Tested on TS3, works as expected.
