### PR TITLE
`Communication`: Fix automatic scroll for latest message

### LINKED ISSUE #9003: `Communication`: Automatic scroll to latest message in chat not functioning correctly
### Describe the bug

In the chat history, similar to Discord, when a user scrolls to the top of the chat and then sends a new message, the automatic scroll should take him to the latest message. However, instead of scrolling to the latest message, it scrolls to the second-to-last message.

### To Reproduce

1. Go to Course Management page
2. Click on Communications button of a course
3. Find a chat history that fills the related window, or write new messages until the screen is full.
4. Scroll to the top of the chat history and write a new message
5. Notice that it scrolls to the second-to-last message, user cannot see his latest message automatically

### Expected behavior

The automatic scroll should bring the user to the latest message after a new message is sent.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

7.4.2

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] This is a small issue that I tested locally.
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

In the chat history, similar to Discord, when a user scrolls to a position where the latest messages are not visible and then sends a new message, the automatic scroll should take the user to the latest message. However, it was scrolling to the second-to-last message instead of the latest one, causing the latest message to not be visible without additional scrolling.
Closes #9003 

### Description

This issue has been fixed by using `setTimeout` to ensure the automatic scroll happens after the new message is rendered. Now, it correctly scrolls to the latest message, making it immediately visible.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Go to Course Management page
3. Click on Communications button of a course
4. Find a chat history that fills the related window, or write new messages until the screen is full.
5. Scroll to the top of the chat history and write a new message
6. Notice that it scrolls to the latest massage, not to the second-to-last message

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved scroll behavior in message conversations to ensure the scroll operation happens after new messages are rendered, enhancing the user experience when new messages arrive.

### CODE REVIEW

**Review by sarpsahinalp — APPROVED** [review]
Code lgtm

File: src/main/webapp/app/overview/course-conversations/layout/conversation-messages/conversation-messages.component.ts [hunk 1]
```diff
@@ -223,7 +223,9 @@ export class ConversationMessagesComponent implements OnInit, AfterViewInit, OnD
     };
 
     scrollToBottomOfMessages() {
-        this.content.nativeElement.scrollTop = this.content.nativeElement.scrollHeight;
+        setTimeout(() => {
```
Comment (JohannesStoehr) [inline src/main/webapp/app/overview/course-conversations/layout/conversation-messages/conversation-messages.component.ts:226]: Can you add a comment here why the timeout is necessary? Otherwise future devs might be confused about the timeout

**Review by egekurt123 — APPROVED** [review]
Tested on TS5, works as expected

**Review by JohannesStoehr — APPROVED** [review]
Thanks for the comment. Code looks good to me

**Review by SimonEntholzer — APPROVED** [review]
Tested on Ts5, works as described :+1:

**Review by PaRangger — APPROVED** [review]
Tested on TS5 👍🏼
