### PR TITLE
[Enhancements] Example solution export button should be visible only 'apollon' profile has been activated

### LINKED ISSUE #3997: Modeling Exercise Export Example Solution Broken
### Describe the bug

When using the export example solution functionality for modeling exercises this does not work.

### To Reproduce

1. Login as editor / instructor
2. Create a modeling exercise with an example solution
3. Open the exercise view of the created modeling exercise
4. Export the example solution
5. See that an error is displayed

### Expected behavior

The example solution should be exported, probably as JSON file that can be imported in Apollon.

### Screenshots

Error message displayed in the UI:
image

Screencast:
ExportModelingExampleSolutionBroken

### What browsers are you seeing the problem on?

Chrome

### Relevant log output
```
Request URL: https://artemistest.ase.in.tum.de/api/apollon-convert/pdf
Request Method: POST
Status Code: 405 
```

### PR DESCRIPTION
**Pull request by imstreetspirit**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Fixes #3997 .

In the issue description, it's sated that export button is not working anymore. This situation was reported while running on the TS1.  Export button needs "apollon" profile in server configuration in order to work in properly. TS1 and TS3 have missing configuration. It was not a bug. However, when "apollon" profile is not active, we may not show users the export button to avoid this situation. This PR aims to cover improvement for export button. 

### Description

Now we are checking active profile information in modeling-exercise-detail.component. And only if "apollon" is activated, export button is visible in modeling exercise detail page.
and I added LocalStorageService, SessionStorageService in corresponding test-suite, because it complained about that.

### Steps for Testing

Prerequisites:
- 1 Instructor / 1 Editor
- 1 Modeling Exercise
- Check the functionality in two test servers (TS2 and TS3)

TS3 (apollon profile IS NOT active)
1. Log in to Artemis
2. Navigate to Course Management
3. Create one modeling exercise save changes
4.  you SHOULD NOT see export button in exercise detail page

TS2 (apollon profile IS active)
1. Log in to Artemis
2. Navigate to Course Management
3. Create one modeling exercise save changes
4.  you SHOULD see export button in exercise detail page

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

nothing

### Screenshots

Example Submission Export button in Modeling Exercise Detail Page

### CODE REVIEW

**Review by willergeorg — APPROVED** [review]
Tested on both servers. Button is available and not like expected.

**Review by MerlinMehmed — APPROVED** [review]
Great job! Tested on both servers as well and works as expected. Code changes also look good.

File: src/main/webapp/app/exercises/modeling/manage/modeling-exercise-detail.component.ts [hunk 1]
```diff
@@ -54,6 +57,12 @@ export class ModelingExerciseDetailComponent implements OnInit, OnDestroy {
             this.load(params['exerciseId']);
         });
         this.registerChangeInModelingExercises();
+        // Checks if the current environment includes "apollon" profile
+        this.profileService.getProfileInfo().subscribe((profileInfo) => {
+            if (profileInfo && profileInfo.activeProfiles.includes('apollon')) {
+                this.isApollonProfileActive = true;
+            }
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/modeling/manage/modeling-exercise-detail.component.ts:64]: Would it make sense to simplify this to a one-liner like `this.isApollonProfileActive = !!(profileInfo && ...);`?
Or does it make this section less readable? What do you think?

File: src/test/javascript/spec/component/modeling-exercise/modeling-exercise-detail.component.spec.ts [hunk 2]
```diff
@@ -47,7 +50,12 @@ describe('ModelingExercise Management Detail Component', () => {
         TestBed.configureTestingModule({
             imports: [ArtemisTestModule],
             declarations: [ModelingExerciseDetailComponent, MockComponent(NonProgrammingExerciseDetailCommonActionsComponent)],
-            providers: [{ provide: ActivatedRoute, useValue: route }, MockProvider(TranslateService)],
+            providers: [
+                { provide: LocalStorageService, useClass: MockSyncStorage },
+                { provide: SessionStorageService, useClass: MockSyncStorage },
+                { provide: TranslateService, useClass: MockTranslateService },
+                { provide: ActivatedRoute, useValue: route },
```
Comment (julian-christl) [inline src/test/javascript/spec/component/modeling-exercise/modeling-exercise-detail.component.spec.ts:57]: Would it make sense to mock the ProfileService here as well?

**Review by julian-christl — COMMENTED** [review]
Just two (improvement) suggestions:

File: src/main/webapp/app/exercises/modeling/manage/modeling-exercise-detail.component.ts (hunk 1 above)
Comment (imstreetspirit) [reply src/main/webapp/app/exercises/modeling/manage/modeling-exercise-detail.component.ts:64]: I think that it doesn't matter much

File: src/test/javascript/spec/component/modeling-exercise/modeling-exercise-detail.component.spec.ts (hunk 2 above)
Comment (imstreetspirit) [reply src/test/javascript/spec/component/modeling-exercise/modeling-exercise-detail.component.spec.ts:57]: I thought it at first. since test-suit is initialized successfully, I do not think it is necessary. Also, ngOnInit is invoked in the test case, if it is needed it should complain about that

**Review by julian-christl — APPROVED** [review]
Code looks good
