### PR TITLE
`Programming exercises`: Make export more robust

### LINKED ISSUE #6935: Download of Exercise does not work
### Describe the bug

If I click on Download Exercise for a Programming Task, I get an internal Server Error in Browser Logs.

### To Reproduce

1. Go to a programming task (course mgmt)
2. Click on Download Exercise
3. See error in the log of the browser

### Expected behavior

Download options shall be shown

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.3.3

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

```shell
ERROR 
Object { headers: {…}, status: 500, statusText: "Internal Server Error", url: "https://artemis.praktomat.cs.kit.edu/api/programming-exercises/172/export-instructor-exercise", ok: false, name: "HttpErrorResponse", message: "Http failure response for https://artemis.praktomat.cs.kit.edu/api/programming-exercises/172/export-instructor-exercise: 500 Internal Server Error", error: Blob }
​
error: Blob { size: 273, type: "application/problem+json", … }
​
headers: Object { normalizedNames: Map(0), lazyUpdate: null, lazyInit: lazyInit() }
​
message: "Http failure response for https://artemis.praktomat.cs.kit.edu/api/programming-exercises/172/export-instructor-exercise: 500 Internal Server Error"
​
name: "HttpErrorResponse"
​
ok: false
​
status: 500
​
statusText: "Internal Server Error"
​
url: "https://artemis.praktomat.cs.kit.edu/api/programming-exercises/172/export-instructor-exercise"
​
<prototype>: Object { … }
core.mjs:10183:22

```
```

### PR DESCRIPTION
**Pull request by tobias-lippert**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types locally.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types locally with the Atlassian Suite
- [x] I tested **all** changes and their related features with **all** corresponding user types locally with Jenkins and Gitlab.

### Motivation and Context
Closes #6935 
Up until now, the export failed if the problem statement was null. Unfortunately, it even failed silently.
Instead one should be able to export the programming exercise even if the problem statement is null.
### Description

- only include problem statement if is not null
- export no longer fails if the embedded files cannot be copied
-  client now shows an alert if the export fails.
-  We cannot show a specific exception message from the server because the response type is a blob, see https://github.com/angular/angular/issues/19148

### Steps for Testing

Best tested locally, as you ideally need access to the database.
Prerequisites:
- 1 Instructor
- 1 Programming exercise

1. Set the problem statement to null in the database
2. Try to export the exercise which should be successful
3. Check that the export contains everything as for another programming exercise for which the problem statement is not null except the problem statement markdown file.
4. include some files in the problem statement and save the PE
5. delete the files on the file system.
6. Export the PE 
7. Export should contain everything but the embedded files.
8. Try to generate a PE for which the export could fail and see if you get an alert on the client if it fails.

#### Performance Review
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [programming-exercise-instructor-exercise-download.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5229/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/shared/actions/programming-exercise-instructor-exercise-download.component.ts.html) | 100% | ✅|
#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [ProgrammingExerciseExportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5229/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.programming/ProgrammingExerciseExportService.html) | 85% | ✅ |
| [ProgrammingExerciseExportImportResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5229/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/ProgrammingExerciseExportImportResource.html) | 95% | ✅|

### Screenshots

image

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java [hunk 1]
```diff
@@ -123,13 +132,21 @@ public Path exportProgrammingExerciseInstructorMaterial(ProgrammingExercise exer
...
+            String cleanProblemStatementFileName = FileService.removeIllegalCharacters(problemStatementFileName);
+            var problemStatementExportPath = Path.of(exportDir.toString(), cleanProblemStatementFileName);
+            pathsToBeZipped.add(fileService.writeStringToFile(exercise.getProblemStatement(), problemStatementExportPath));
+            try {
+                copyEmbeddedFiles(exercise, exportDir, pathsToBeZipped);
+            }
+            catch (IOException e) {
+                exportErrors.add("Failed to copy embedded files: " + e.getMessage());
+                log.warn("Could not copy embedded files for exercise with id {}", exercise.getId());
+            }
```
Comment (Strohgelaender) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:148]: Maybe move this into its own method?

File: src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseTestService.java [hunk 2]
```diff
@@ -1342,6 +1364,15 @@ java.io.File exportProgrammingExerciseInstructorMaterial(HttpStatus expectedStat
         return request.getFile(url, expectedStatus, new LinkedMultiValueMap<>());
     }
 
+    private void generateProgrammingExerciseWithProblemStatementNullForExport() {
+        exercise.setProblemStatement(null);
+        exercise = programmingExerciseRepository.save(exercise);
+        exercise = programmingExerciseRepository.save(exercise);
```
Comment (Strohgelaender) [inline src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseTestService.java:1370]:
```suggestion
```

**Review by Strohgelaender — APPROVED** [review]
code lgtm

**Review by Strohgelaender — DISMISSED** [review]

**Review by pal03377 — CHANGES_REQUESTED** [review]
Tested locally. When the `repos-download` folder is missing in the repo root, it is not created and I only get an Internal server error without a stack trace currently :/

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java [hunk 3]
```diff
@@ -181,7 +181,14 @@ private void copyEmbeddedFiles(ProgrammingExercise exercise, Path outputDir, Lis
         Path embeddedFilesDir = outputDir.resolve("files");
         if (!embeddedFiles.isEmpty()) {
             if (!Files.exists(embeddedFilesDir)) {
-                Files.createDirectory(embeddedFilesDir);
+                try {
+                    Files.createDirectory(embeddedFilesDir);
+                }
+                catch (IOException e) {
+                    exportErrors.add("Could not create directory for embedded files: " + e.getMessage());
+                    log.warn("Could not create directory for embedded files. Won't include embedded files: " + e.getMessage());
```
Comment (JohannesStoehr) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:189]: Should this be an error instead of a warning?

File: src/main/webapp/app/exercises/programming/manage/services/programming-exercise.service.ts [hunk 4]
```diff
@@ -24,6 +24,7 @@ import { BuildLogStatisticsDTO } from 'app/exercises/programming/manage/build-lo
 import { SortService } from 'app/shared/service/sort.service';
 import { Result } from 'app/entities/result.model';
 import { Participation } from 'app/entities/participation/participation.model';
+import { onError } from 'app/shared/util/global.utils';
```
Comment (JohannesStoehr) [inline src/main/webapp/app/exercises/programming/manage/services/programming-exercise.service.ts:27]: Unused

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java (hunk 3 above)
Comment (tobias-lippert) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:189]: Since this won't lead to an export failure, I wouldn't log it as an error but I'm not sure if we have specific guidelines, when we should which log level.

**Review by jakubriegel — DISMISSED** [review]
Re-tested locally. Works as described 👍🏻

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java (hunk 3 above)
Comment (MaximilianAnzinger) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java:189]: A warning should be fine. We do this also for Exam exports if I'm not mistaken.

**Review by MaximilianAnzinger — APPROVED** [review]
Code LGTM 👍

**Review by JohannesStoehr — DISMISSED** [review]
Approve Code

**Review by pal03377 — APPROVED** [review]
Re-tested locally. Everything works now & I couldn't break it 🎉 
Even changing file permissions doesn't seem to break the export.
Food for thought: It might be nice to have some kind of indication that files were skipped in the export (not found / accessible) to see that something went wrong there. This PR already improves the procedure quite a bit, though!

**Review by jakubriegel — APPROVED** [review]

**Review by pal03377 — DISMISSED** [review]
Re-approve after only a client test was added

**Review by JohannesStoehr — APPROVED** [review]
New tests also looks good to me

**Review by jakubriegel — APPROVED** [review]

**Review by MaximilianAnzinger — APPROVED** [review]
New test LGTM 👍

**Review by pal03377 — APPROVED** [review]
