### PR TITLE
`Development`: Refactor course dashboard filtering

### LINKED ISSUE #9086: `Programing exercises`: Student does not see the results from the latest submission in the overview
### Describe the bug

The overview of a Programming exercise sometimes does not show the results from the latest submission. Instead it shows the result of a previous submission.

### To Reproduce

1. Create a Programming exercise
2. Make some submissions with different results (e.g. with / without warning or different percentage of passed tests)
3. Go to the list of exercises of your course
4. The results on the overview is not from the latest submission (This does not appear always, see Additional context)

### Expected behavior

The overview on the left-hand side always shows the results for the latest submission.

### Screenshots

The overview on the left-hand side shows here a warning symbol, but the latest submission has no warning. But as you can see all previous submissions have a warning. It looks like the 
Status screenshot

### Which version of Artemis are you seeing the problem on?

7.4.3 (and also older version)

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

The visual impact of the bug, which the screenshot shows, appears on our productive Artemis server and was noticed by one student. The reproduction in a test environment was not successful yet, but an error in the log seems to indicate what is the problem behind it. 
An `Query did not return a unique result` error occurs which indicates that there is not deterministic which result is selected here. The problem appears with PostgreSQL, maybe this problem is also related to some difference between MySQL and PostgreSQL.

### Relevant log output
<details>

<summary>full log entry with stracktrace</summary>

```
2024-07-13T18:47:38.557+02:00 ERROR 34844 --- [Artemis] [taskScheduler-3] .w.a.s.s.ParticipantScoreScheduleService : Exception while processing participant score for exercise 7 and participant 3 for participant scores:

org.springframework.dao.IncorrectResultSizeDataAccessException: Query did not return a unique result: 2 results were returned
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:301)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:244)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:335)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:160)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
	at jdk.proxy2/jdk.proxy2.$Proxy305.findByExercise_IdAndUser_Id(Unknown Source)
	at de.tum.in.www1.artemis.service.scheduled.ParticipantScoreScheduleService.executeTask(ParticipantScoreScheduleService.java:283)
	at de.tum.in.www1.artemis.service.scheduled.ParticipantScoreScheduleService.lambda$scheduleTask$5(ParticipantScoreScheduleService.java:234)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.hibernate.NonUniqueResultException: Query did not return a unique result: 2 results were returned
	at org.hibernate.query.spi.AbstractSelectionQuery.uniqueElement(AbstractSelectionQuery.java:586)
	at org.hibernate.query.spi.AbstractSelectionQuery.getSingleResult(AbstractSelectionQuery.java:570)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:418)
	at jdk.proxy2/jdk.proxy2.$Proxy466.getSingleResult(Unknown Source)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:223)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:92)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:152)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:140)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:170)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:158)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:392)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
	... 16 common frames omitted

``` 
</details>

### PR DESCRIPTION
**Pull request by chrisknedl**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

There is a bug related to the data that is shown on the course dashboard (#9086). The related pieces of code were so convoluted that a fix without refactoring would have been very difficult to understand for reviewers, and would have further decreased the code's readability and maintainability.

Fixes #9086.

### Description

Most importantly, the code assumed that for a singular student, multiple participations are possible for the same exercise, which is not true. Therefore, the ordering based on the initialization state has been removed, and the corresponding logic has been reduced to the relevant parts. Since only rated exercises are relevant for the course dashboard, practice programming exercise submissions are not considered any more.

The logic for submission filtering should not be included in the exercise entities, so it has been moved from the exercise entities to a new `SubmissionFilterService`, where instead of polymorphism, a case distinction is used to determine the relevant filter logic for the type of exercise.

The relevant result for the course dashboard is now always connected to its original submission. Previously, it was theoretically possible to return a result as part of a submission to which it previously did not belong. 
### Steps for Testing

Prerequisites:
- 1 Instructor
- Best to have a course with different types of exercises and submissions/results.

#### For the linked issue
1. Create a Programming exercise with online code editor and manual assessment. Set the due date one day in the future, and the assessment due date 2 days in the future.
2. Create an assignment repository, submit once immediately.
3. Make some changes so that some of the tests pass, e.g. by creating and implementing the SortStrategy interface. Submit again.
4. Change the exercise due date to two minutes in the future and wait for it to pass.
5. Start assessing the submission. Add some feedback that slightly changes the score, and submit the assessment.
6. View the dashboard again, the score on the left should be the score of the latest automatic assessment.
7. Change the assessment due date to two minutes in the future and wait for it to pass. The dashboard should now show the score from the manual assessment.

#### General
 View the scores and statistics section in the course dashboard. The values should be the same on this branch as they are on develop. The statistics page should also show the same statistics.

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Performance Review

- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| Result.java | 95% | ✅ |
| ResultService.java | 88% | ✅ |
| ResultResource.java | 91% | ✅ |
| CourseService.java | 92% | ✅ |
| Exercise.java | 93% | ✅ |
| ExerciseDateService.java | 100% | ✅ |
| ExerciseService.java | 97% | ✅ |
| ParticipationFilterService.java | 100% | ✅ |
| SubmissionFilterService.java | 96% | ✅ |
| ProgrammingExercise.java | 88% | ✅ |
| QuizExercise.java | 90% | ✅ |

## Summary by CodeRabbit

- **New Features**
	- Improved assessment status displays, ensuring users see when an assessment is complete.
	- Enhanced filtering for participations and submissions, resulting in more accurate and consistent exercise results on dashboards.
- **Refactor**
	- Streamlined exercise and result processing by consolidating redundant logic and updating service interfaces.
	- Simplified methods to boost reliability and performance across various exercise types.
- **Documentation**
	- Updated user-facing documentation for clearer guidance on exercise display and assessment behavior.

## Summary by CodeRabbit

- **New Features**
  - Introduced a method to check assessment completion status.
  - Enhanced filtering for submissions and participations to improve the accuracy of assessment status.

- **Refactor**
  - Streamlined result and exercise workflows by removing obsolete methods and updating API signatures.
  - Integrated dedicated services to separate filtering logic for cleaner processing.

- **Documentation**
  - Upgraded comments and guidance for state indicators and submission types for improved clarity.

- **Tests**
  - Adjusted and expanded test scenarios, including updated user setups and new coverage for filtering services.

### CODE REVIEW

File: src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationFilterService.java [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+        }
+        else {
+            return Set.of(findStudentParticipationForNonProgrammingExercises(participationsInExercise));
+        }
+    }
+
+    /**
+     * Filters the student participation for display in the student dashboard.
+     *
+     * @param participation the participation that contains the exercise and should be filtered
```
Comment (b-fein) [inline src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationFilterService.java:65]:
```suggestion
     * Filters the student participation for display in the student dashboard.
     *
     * <p>Ensures that sensitive information (e.g. the assessing tutor) is removed. Additionally, this only keeps the latest submission and its most recent visible result. For example, in case the exercise uses a manual assessment and the assessment publication date has not yet passed, only the last automatic result is kept since the newer one should not yet be visible to the student.
     *
     * @param participation the participation that contains the exercise and should be filtered
```
I think the Javadoc here would benefit a bit from explaining what is retained and what is removed as part of the participation in the filtering step.

(Checkstyle/Spotless will probably complain about the line length when using the suggestion directly. The comment describes what I understood from the implementation, feel free to remove/add/adapt as you deem fit for stuff that is inaccurate.)

File: src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationFilterService.java [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+        Optional<Submission> optionalSubmission = submissionFilterService.getLatestSubmissionWithResult(participation.getSubmissions(), false);
+
+        Set<Result> results = Set.of();
+
+        if (optionalSubmission.isPresent()) {
+            var submission = optionalSubmission.get();
+            var latestResult = submission.getLatestResult();
+            if (latestResult != null) {
+                results = Set.of(latestResult);
+                latestResult.setParticipation(null);
```
Comment (b-fein) [inline src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationFilterService.java:78]:
```suggestion
                // avoid circular reference when converting to JSON later
                latestResult.setParticipation(null);
```
(?)

File: src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationFilterService.java [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+                // filter sensitive information about the assessor if the current user is a student
```
Comment (b-fein) [inline src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationFilterService.java:79]:
```suggestion

```
personal preference: I think the variable and method names are clear enough here to explain what happens without the comment.

File: src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationFilterService.java [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+            }
+            submission.setResults(new ArrayList<>(results));
+        }
+
+        // add submission to participation or set it to null
+        participation.setSubmissions(optionalSubmission.map(Set::of).orElse(null));
+        participation.setResults(results);
+        if (optionalSubmission.isPresent()) {
+            optionalSubmission.get().setResults(new ArrayList<>(results));
+        }
```
Comment (b-fein) [inline src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationFilterService.java:92]:
```suggestion
        optionalSubmission.ifPresent(submission -> submission.setResults(new ArrayList<>(results)));
```
nitpick/preference to avoid branching

File: src/main/java/de/tum/cit/aet/artemis/exercise/service/SubmissionFilterService.java [hunk 5]
```diff
@@ -0,0 +1,138 @@
...
+@Service
+@Profile(PROFILE_CORE)
+public class SubmissionFilterService {
+
+    /**
+     * Filters a set of submissions from a participation and determines the latest submission with a valid result, based
+     * on the type of the exercise. This method is used to get data for the course dashboard, in which case the
+     * assessment due date matters, but also to get the latest results for each participation with points for each
+     * grading criterion, where the assessment due date can be ignored, because the corresponding endpoint is only
+     * visible for instructors.
```
Comment (b-fein) [inline src/main/java/de/tum/cit/aet/artemis/exercise/service/SubmissionFilterService.java:35]:
```suggestion
     * Filters a set of submissions from a participation and determines the latest submission with a valid result, based
     * on the type of the exercise.
     *
     * <p>This method can be used for example to get data for the course dashboard, in which case the
     * assessment due date matters, but also to get the latest results for each participation with points for each
     * grading criterion, where the assessment due date can be ignored, because the corresponding endpoint is only
     * visible for instructors.
```
nitpick: more used as examples when the `ignoreAssessmentDueDate` matters, rather than a definitive list ‘you can only used this method for those two exact things’.

File: src/main/java/de/tum/cit/aet/artemis/exercise/service/SubmissionFilterService.java [hunk 6]
```diff
@@ -0,0 +1,138 @@
...
+            case FileUploadSubmission fileUploadSubmission -> isFileUploadSubmissionRelevantForCourseDashboard(fileUploadSubmission, ignoreAssessmentDueDate);
+            case QuizSubmission quizSubmission -> isQuizSubmissionRelevantForCourseDashboard(quizSubmission);
+            default -> throw new IllegalArgumentException("Unsupported submission type: " + submission.getClass());
+        };
+    }
+
+    private boolean isProgrammingSubmissionRelevantForCourseDashboard(ProgrammingSubmission programmingSubmission, boolean ignoreAssessmentDueDate) {
+        var latestResult = programmingSubmission.getLatestResult();
+        var participation = (StudentParticipation) programmingSubmission.getParticipation();
+        var exercise = participation.getExercise();
```
Comment (b-fein) [inline src/main/java/de/tum/cit/aet/artemis/exercise/service/SubmissionFilterService.java:68]:
```suggestion
        Result latestResult = programmingSubmission.getLatestResult();
        StudentParticipation participation = (StudentParticipation) programmingSubmission.getParticipation();
        Exercise exercise = participation.getExercise();
```
* Artemis guidelines, if I remember correctly: only use `var` for complex types.
* Can we be sure this is a `StudentParticipation` here? The `public` entrypoint takes in an arbitrary `Set<Submission>`, some of which might be for the template or the solution.

File: src/main/java/de/tum/cit/aet/artemis/exercise/service/SubmissionFilterService.java [hunk 7]
```diff
@@ -0,0 +1,138 @@
...
+        }
+        // a manual result may only be shared if its assessment is complete and the assessment due date has passed
+        boolean isAssessmentPeriodOverOrIgnored = ignoreAssessmentDueDate || ExerciseDateService.isAfterAssessmentDueDate(exercise);
+        if (isAssessmentPeriodOverOrIgnored && latestResult.isAssessmentComplete()) {
+            return true;
+        }
+        /*
+         * The last submission of manually graded programming exercises can contain multiple results:
+         * -> The first result is automatic, because that is the code that the student submitted and is evaluated by the automatic tests.
+         * -> All following results are semi-automatic (and therefore manual), created by a tutor during assessment.
```
Comment (b-fein) [inline src/main/java/de/tum/cit/aet/artemis/exercise/service/SubmissionFilterService.java:92]: Not true: The tests might have run multiple times for the same commit, e.g. in case the instructor triggers the build again, or if the tests are run again after the due date. Then we have multiple automatic results.

**Review by b-fein — CHANGES_REQUESTED** [review]
Code looks a lot cleaner than before and now is finally understandable. Nice job!

However, I still left a few (minor) suggestions. Only one of them actually affects the logic, the others are mostly about re-using existing methods or improving the documentation.

File: src/main/java/de/tum/cit/aet/artemis/exercise/domain/InitializationState.java [hunk 8]
```diff
@@ -1,6 +1,7 @@
 package de.tum.cit.aet.artemis.exercise.domain;
 
 /**
+ * ToDo: Add javadoc for the remaining states, and explain the states better
```
[the remark this answers is not in the document]
Comment (chrisknedl) [reply src/main/java/de/tum/cit/aet/artemis/exercise/domain/InitializationState.java:4]: Note for someone else in the future. I do not know how this actually works (or is intended to work).

File: src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationFilterService.java (hunk 2 above)
Comment (chrisknedl) [reply src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationFilterService.java:83]: I guess

File: src/main/java/de/tum/cit/aet/artemis/exercise/service/SubmissionFilterService.java (hunk 6 above)
Comment (chrisknedl) [reply src/main/java/de/tum/cit/aet/artemis/exercise/service/SubmissionFilterService.java:69]: Good point. The method still works with the generic `Participation` type, so I just removed the cast just now.

File: src/main/java/de/tum/cit/aet/artemis/exercise/service/SubmissionFilterService.java (hunk 7 above)
Comment (chrisknedl) [reply src/main/java/de/tum/cit/aet/artemis/exercise/service/SubmissionFilterService.java:97]: I agree, did not think of this. So we basically want to take the latest automatic result that is available in the list of results.

**Review by b-fein — DISMISSED** [review]
Code looks good now. 👍

File: src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationFilterService.java [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+     * @param participationsAcrossAllExercises all participations of the student in all exercises of the course
+     * @param exercise                         the exercise for which we want the participations
+     * @return the participations in the exercise
+     */
+    public Set<StudentParticipation> findStudentParticipationsInExercise(Set<StudentParticipation> participationsAcrossAllExercises, Exercise exercise) {
+        // only consider participations in the given exercise
+        if (participationsAcrossAllExercises == null || participationsAcrossAllExercises.isEmpty()) {
+            return Set.of();
+        }
+        var participationsInExercise = participationsAcrossAllExercises.stream().filter(p -> p.getExercise() != null && p.getExercise().equals(exercise))
```
Comment (dfuchss) [inline src/main/java/de/tum/cit/aet/artemis/exercise/service/ParticipationFilterService.java:47]: Neat pick:

You could use Objects.equals() here :)

**Review by dfuchss — COMMENTED** [review]
Code looks fine to me. What I want to test asap is an Exam with two grading rounds. In the worst case You could have 4 gradings (Automatic, Manual Round 1, Manual Round 2, And complaint) . I guess that might be the most complex combination, we might get ;)

**Review by b-fein — APPROVED** [review]

**Review by BBesrour — APPROVED** [review]
tested on TS6, lgtm

**Review by ole-ve — APPROVED** [review]
tested on TS6, worked fine

**Review by tobias-lippert — DISMISSED** [review]
Tested on ts6. Everything works as expected

**Review by dfuchss — DISMISSED** [review]
Code

**Review by b-fein — DISMISSED** [review]
Code re-approve.

Looks like the ‘conflict’ was only due to a renamed test class. No actual conflicting changes.

Keeping the ‘ready to merge’ label should be fine even though GitHub technically removed the approvals.

**Review by dfuchss — APPROVED** [review]

File: src/main/java/de/tum/cit/aet/artemis/exercise/domain/InitializationState.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (krusche) [reply src/main/java/de/tum/cit/aet/artemis/exercise/domain/InitializationState.java:4]: I don't think that we should add TODOs for JavaDoc. You can simply ask ChatGPT to explain the code. Please address this in this PR

File: src/main/java/de/tum/cit/aet/artemis/exercise/domain/SubmissionType.java [hunk 10]
```diff
@@ -1,6 +1,7 @@
 package de.tum.cit.aet.artemis.exercise.domain;
 
 /**
+ * ToDo: Add javadoc for the other cases
```
[the remark this answers is not in the document]
Comment (krusche) [reply src/main/java/de/tum/cit/aet/artemis/exercise/domain/SubmissionType.java:4]: I don't think that we should add TODOs for JavaDoc. You can simply ask ChatGPT to explain the code. Please address this in this PR

**Review by krusche — CHANGES_REQUESTED** [review]
The refactoring generally looks good. I kindly ask you to fix the 2 additional TODOs in the code before we merge this PR.

**Review by b-fein — APPROVED** [review]

**Review by krusche — APPROVED** [review]
