### PR TITLE
`Assessment`: Fix an issue where the progress bar for tutors shows NaN%

### LINKED ISSUE #10252: `Exam-Mode`: "Assess all submissions" shows NaN%
### Describe the bug

Artemis shows "NaN" when there are 0/0 corrections in a correction round of an exam.

### To Reproduce

1. Go to https://artemis.in.tum.de/course-management/{course-id}/exams/{exam-id} (<-- exam-id might be some kind of other id)
3. Scroll down to "Assess all submissions"
4. See "NaN%"

### Expected behavior

It should show 0%

### Screenshots

Image

### Which version of Artemis are you seeing the problem on?

7.9.1

### What browsers are you seeing the problem on?

Safari

### Additional context

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by ShuaiweiYu**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

Closes #10252

### Steps for Testing

1. Go to [https://artemis.in.tum.de/course-management/{course-id}/exams/{exam-id}](https://artemis.in.tum.de/course-management/%7Bcourse-id%7D/exams/%7Bexam-id%7D) (<-- exam-id might be some kind of other id)
2. Scroll down to "Assess all submissions"
3. See "0/0 (0%)"

### Test Coverage
unchanged

## Summary by CodeRabbit

- **Bug Fixes**
  - Updated the progress bar display so that when progress data is not compute-able, it now correctly shows a zero value instead of an unexpected result. This improvement ensures a more reliable and consistent visual feedback for users.

### CODE REVIEW

**Review by paoxin — DISMISSED** [review]
LGTM, but should you also consider when only the denominator is 0?

**Comment by ShuaiweiYu** [comment]
> LGTM, but should you also consider when only the denominator is 0?

Yeah, this is more or less a philosophical question: do we want to replace every NaN with zero or not?

File: src/main/webapp/app/shared/dashboards/tutor-participation-graph/progress-bar/progress-bar.component.ts [hunk 1]
```diff
@@ -35,7 +35,11 @@ export class ProgressBarComponent implements OnChanges, OnDestroy {
 
     ngOnChanges(changes: SimpleChanges) {
         if (changes.percentage) {
-            this.percentage = round(this.percentage);
+            if (isNaN(this.percentage) && this.numerator === 0 && this.denominator === 0) {
```
Comment (florian-glombik) [inline src/main/webapp/app/shared/dashboards/tutor-participation-graph/progress-bar/progress-bar.component.ts:38]: Why are we checking for the `numerator` here aswell? 

I think the suggestion would be more robust 
```suggestion
            if (isNaN(this.percentage) && this.denominator === 0) {
```

**Review by florian-glombik — CHANGES_REQUESTED** [review]

File: src/main/webapp/app/shared/dashboards/tutor-participation-graph/progress-bar/progress-bar.component.ts (hunk 1 above)
Comment (ShuaiweiYu) [reply src/main/webapp/app/shared/dashboards/tutor-participation-graph/progress-bar/progress-bar.component.ts:38]: Yes, however, I'm wondering whether you will consider 100/0 also as 0% or as 100%? Because in my eyes, 100 out of 0 seems to be 100%.

Comment (florian-glombik) [reply src/main/webapp/app/shared/dashboards/tutor-participation-graph/progress-bar/progress-bar.component.ts:38]: 100/0 is NaN anyways, isn't it?

Comment (florian-glombik) [reply src/main/webapp/app/shared/dashboards/tutor-participation-graph/progress-bar/progress-bar.component.ts:38]: Okay, I do now understand where you come from 0/0 appears to be NaN and 100/0 appears to be Infinity in typescript.

I would then suggest something like 
```
const isNaN = this.numerator === 0 && this.denominator === 0;
if (isNaN(this.percentage || isNaN) {
}
```
So the code tells the reader what shall actually happen (at least to me it is not clear from `this.numerator === 0 && this.denominator === 0` that this is a NaN case and 100/0 is infinity)

I think it would also be good to extract the `if` together with the `else` to a `getUpdatedPercentage` method

The best solution would be to use signals instead and make `percentage` a computed signal, but I would say this is out of scope for the bugfix

Comment (florian-glombik) [reply src/main/webapp/app/shared/dashboards/tutor-participation-graph/progress-bar/progress-bar.component.ts:38]: I am also wondering why we need the NaN check twice 😅

Comment (florian-glombik) [reply src/main/webapp/app/shared/dashboards/tutor-participation-graph/progress-bar/progress-bar.component.ts:38]:
```
    ngOnChanges(changes: SimpleChanges) {
        if (changes.percentage) {
            this.percentage = this.getUpdatedPercentage();
            this.chooseProgressBarTextColor();
            this.calculateProgressBarClass();
        }
    }

    private getUpdatedPercentage() {
        const isNaN = this.numerator === 0 && this.denominator === 0;
        if (isNaN(this.percentage) || isNaN) {
            return 0;
        }

        return round(this.percentage);
    }
```

From my perspective this would be a cleaner solution

Comment (florian-glombik) [reply src/main/webapp/app/shared/dashboards/tutor-participation-graph/progress-bar/progress-bar.component.ts:38]: And we should refactor, if possible, this component so that percentage is not passed to it - then we will also only have one NaN check - but not the scope of this PR 👍

**Review by florian-glombik — APPROVED** [review]
Approve code, thanks for the adjustments!

**Review by tobikli — APPROVED** [review]
LGTM now :)

**Review by HawKhiem — APPROVED** [review]
Tested on TS1. Works as described, also code 👍

**Review by MaximilianAnzinger — APPROVED** [review]

**Review by krusche — APPROVED** [review]

**Review by krusche — APPROVED** [review]
