### PR TITLE
`Programming exercises`: Directly link feedback to its test case

### LINKED ISSUE #5959: `Programming Exercise`: Test names not shown to instructors in feedback dialogue
### Describe the bug

Not in all feedback views the test names are visible to the tutor/instructor. This makes checking the result difficult sometimes.

### To Reproduce

1. Go to the Participations view for an exercise.
2. Click on a number in the Submissions column to list all submissions for that student.
   - the URL should be something like `https://<artemis-url>/course-management/<course-id>/programming-exercises/<exercise-id>/participations/<participation-id>/submissions`
4. Click on a result. The feedback dialogue opens.
5. Notice that the test names are not shown.

### Expected behavior

The test names are shown to make it possible for the instructor to see which tests were successful/failed/not executed.

### Screenshots

Especially for not executed tests it is impossible to see which ones they are.

Screenshot 2022-12-13 at 11-53-16 Participation

### Which version of Artemis are you seeing the problem on?

5.12.6

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Strohgelaender**
# Contains migrations, only test this on TS5.

#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
The main goal of this PR is to eliminate the need to send test case names to the client, since these are usually considered internal information that should not be known to the students.
Fixes #5959.

### Description
Currently, the related test case gets detected by the feedbacks text attribute, which in this case is the name of the test. After this PR, the test case is directly linked using the new `testCase` attribute.

When editing a problem statement, editors are still able to use the test name and link the name to tasks like before. However, the problem statement send to the student only contains ids and no test names.

### Steps for Testing
Please ensure the following 
- While working as a student on a programming exercise, no test case names are set to the client in any related REST response. The student can view tasks and see the task's status.
- Editing a problem statement as an editor works like prior (using test case names)
- Importing the exercise works. Also exporting and importing the exercise into a file works.

#### Exam Mode Testing
verify that the exam mode did not break

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [feedback.model.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Client-Tests/app/entities/feedback.model.ts.html) | 96.59% | ✅  |
| [programming-exercise-instruction-analysis.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/instructions-editor/analysis/programming-exercise-instruction-analysis.service.ts.html) | 97.77% | ✅  |
| [programming-exercise-editable-instruction.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/instructions-editor/programming-exercise-editable-instruction.component.ts.html) | 78.76% | ✅  |
| [programming-exercise-plant-uml.extension.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-plant-uml.extension.ts.html) | 91.3% | ✅  |
| [programming-exercise-task.extension.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-task.extension.ts.html) | 97.82% | ✅  |
| [programming-exercise-instruction.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/shared/instructions-render/programming-exercise-instruction.component.ts.html) | 86.42% | ✅  |
| [programming-exercise-instruction.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/shared/instructions-render/service/programming-exercise-instruction.service.ts.html) | 93.93% | ✅  |
| [programming-exercise-instruction-task-status.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/shared/instructions-render/task/programming-exercise-instruction-task-status.component.ts.html) | 71.05% | ✅  |
| [feedback.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/feedback/feedback.service.ts.html) | 100% | ✅ |
| [programming-feedback-item.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/feedback/item/programming-feedback-item.service.ts.html) | 97.67% | ✅  |
| [result.utils.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/result/result.utils.ts.html) | 89.51% | ✅  |
| [orion-build-and-test.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/orion/orion-build-and-test.service.ts.html) | 100% | ✅ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [Feedback.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain/Feedback.html) | 97% -> 97% | ✅ |
| [ProgrammingExerciseTestCase.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain/ProgrammingExerciseTestCase.html) | 98% -> 98% | ✅|
| [AbstractContinuousIntegrationResultService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.connectors.ci/AbstractContinuousIntegrationResultService.html) | 100% ->100% | ✅ |
| [ProgrammingExerciseTaskService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.hestia/ProgrammingExerciseTaskService.html) | 86% -> 98% | ✅ |
| [ProgrammingExerciseExportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.programming/ProgrammingExerciseExportService.html) | 84% -> 84% | ✅ |
| [ProgrammingExerciseFeedbackCreationService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.programming/ProgrammingExerciseFeedbackCreationService.html) | 89% -> 94% | ✅ |
| ProgrammingExerciseFeedbackService.java | deleted |  |
| [ProgrammingExerciseImportBasicService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.programming/ProgrammingExerciseImportBasicService.html) | 97 -> 97% | ✅ |
| [ProgrammingExerciseImportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.programming/ProgrammingExerciseImportService.html) | 97 -> 97% | ✅ |
| [ProgrammingExerciseService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5261/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.programming/ProgrammingExerciseService.html) | 93% -> 93% | ✅ |

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 1]
```diff
@@ -172,7 +177,7 @@
         if (problemStatement == null || problemStatement.isEmpty()) {
             return tasks;
         }
-        var matcher = taskPatternForProblemStatementMarkdown.matcher(problemStatement);
+        var matcher = TASK_PATTERN.matcher(problemStatement);
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:180]: 🤔 I don't really see a ways to improve the regex, has someone else an idea?

**Comment by terlan98** [comment]
> @terlan98: Could this PR break some functionality of Themis?

Thanks for the heads-up. Yes, this will cause the test names to appear empty. 
@Strohgelaender, please ping me when this PR is ready for review and I'll adjust the Themis code accordingly 🙂

**Review by pal03377 — COMMENTED** [review]
First code passthrough. Most changes already are quite clean, well done! Still, here are some suggestions / questions / comments:

File: src/main/java/de/tum/in/www1/artemis/config/migration/entries/MigrationEntry20230810_150000.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+import de.tum.in.www1.artemis.service.hestia.ProgrammingExerciseTaskService;
+
+/**
+ * Migration for automatically updating all Programming exercise problem statements, removing their test names and replacing them by test ids.
+ */
+public class MigrationEntry20230810_150000 extends MigrationEntry {
+
+    private final transient ProgrammingExerciseRepository programmingExerciseRepository;
+
+    private final transient ProgrammingExerciseTaskService taskService;
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/config/migration/entries/MigrationEntry20230810_150000.java:18]: I don't think so, but @julian-christl made the `MigrationEntry` implement `Serializable` and this caused a warning locally. So I added the transistent modifier.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 3]
```diff
@@ -178,21 +208,32 @@ public List<Feedback> createFeedbackFromStaticCodeAnalysisReports(List<StaticCod
...
+     * @param activeTestCases all active test cases of the exercise.
+     *                            They are passed as a parameter to avoid redundant database calls when calling this method multiple times.
      * @return Feedback object for the test job
      */
-    public Feedback createFeedbackFromTestCase(String testName, List<String> testMessages, boolean successful, final ProgrammingLanguage programmingLanguage,
-            final ProjectType projectType) {
+    public Feedback createFeedbackFromTestCase(String testName, List<String> testMessages, boolean successful, final ProgrammingExercise exercise,
+            Set<ProgrammingExerciseTestCase> activeTestCases) {
         Feedback feedback = new Feedback();
-        feedback.setText(testName);
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:191]: yes, that's exactly the goal of this PR. See also the migration SQL.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 4]
```diff
@@ -208,4 +249,105 @@ else if (!testMessages.isEmpty()) {
...
+     * @param buildResult the build result with all the test cases.
+     * @param exercise    programming exercise.
+     * @return Returns true if the test cases have changed, false if they haven't.
+     */
+    public boolean generateTestCasesFromBuildResult(AbstractBuildResultNotificationDTO buildResult, ProgrammingExercise exercise) {
+        Set<ProgrammingExerciseTestCase> existingTestCases = testCaseRepository.findByExerciseId(exercise.getId());
+        // Do not generate test cases for static code analysis feedback
+        Set<ProgrammingExerciseTestCase> testCasesFromFeedbacks = getTestCasesFromBuildResult(buildResult, exercise);
+        // Get test cases that are not already in database - those will be added as new entries.
+        Set<ProgrammingExerciseTestCase> newTestCases = testCasesFromFeedbacks.stream().filter(testCase -> existingTestCases.stream().noneMatch(testCase::isSameTestCase))
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:281]: This is code that I just move inside this class, I did not touch it. I'll look at why this is the case.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 5]
```diff
@@ -208,4 +249,105 @@ else if (!testMessages.isEmpty()) {
...
+        Set<ProgrammingExerciseTestCase> testCasesToSave = new HashSet<>();
+        testCasesToSave.addAll(newTestCases);
+        testCasesToSave.addAll(testCasesWithUpdatedActivation);
+
+        setTestCaseType(testCasesToSave, exercise.getProgrammingLanguage());
+
+        // Ensure no duplicate TestCase is present: TestCases have to have a unique name per exercise.
+        // Just using the uniqueness property of the set is not enough, as the equals/hash functions
+        // consider more attributes of the TestCase rather than only the testName.
+        testCasesToSave.removeIf(candidate -> testCasesToSave.stream().filter(testCase -> testCase.getTestName().equalsIgnoreCase(candidate.getTestName())).count() > 1);
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:295]: A "new" one with the same name cannot appear, in this case the existing one gets changed to active.

File: src/test/javascript/spec/component/example-modeling/example-modeling-submission.component.spec.ts [hunk 6]
```diff
@@ -64,7 +64,7 @@ describe('Example Modeling Submission Component', () => {
         correctionStatus: 'CORRECT',
     } as Feedback;
     const mockFeedbackWithoutReference = { text: 'FeedbackWithoutReference', credits: 30, type: FeedbackType.MANUAL_UNREFERENCED } as Feedback;
-    const mockFeedbackInvalid = { text: 'FeedbackInvalid', referenceId: '4', reference: 'reference', correctionStatus: FeedbackCorrectionErrorType.INCORRECT_SCORE };
+    const mockFeedbackInvalid = { text: 'FeedbackInvalid', referenceId: '4', reference: 'reference', correctionStatus: FeedbackCorrectionErrorType.INCORRECT_SCORE } as Feedback;
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/test/javascript/spec/component/example-modeling/example-modeling-submission.component.spec.ts:67]: not needed, but this activates type checking (in case the feedback model gets changed in the future, you would get a compilation error here, without this this is just "some object" which can have any properties.

File: src/main/java/de/tum/in/www1/artemis/domain/Result.java [hunk 7]
```diff
@@ -475,14 +475,37 @@ public void filterSensitiveInformation() {
...
 
-        // TODO: this is not good code!
+        if (exercise instanceof ProgrammingExercise programmingExercise) {
+            filterTestCaseFeedback(programmingExercise);
+        }
+    }
+
+    private void filterTestCaseFeedback(ProgrammingExercise programmingExercise) {
         var testCaseFeedback = feedbacks.stream().filter(Feedback::isTestFeedback).toList();
+        if (!Boolean.TRUE.equals(programmingExercise.getShowTestNamesToStudents())) {
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/domain/Result.java:501]: the column is nullable in the database and all these getters just return the db-value without any conversions, so I'd like to keep that. We treat null as false, that's why I used `!true` here.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 8]
```diff
@@ -208,4 +249,105 @@ else if (!testMessages.isEmpty()) {
...
+     *
+     * @param buildResult from which to extract the test cases.
+     * @param exercise    the programming exercise for which the test cases should be extracted from the new result
+     */
+    public void extractTestCasesFromResult(AbstractBuildResultNotificationDTO buildResult, ProgrammingExercise exercise) {
+        boolean haveTestCasesChanged = generateTestCasesFromBuildResult(buildResult, exercise);
+        if (haveTestCasesChanged) {
+            // Notify the client about the updated testCases
+            Set<ProgrammingExerciseTestCase> testCases = testCaseRepository.findByExerciseId(exercise.getId());
+            websocketMessagingService.sendMessage("/topic/programming-exercises/" + exercise.getId() + "/test-cases", testCases);
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:264]: I just moved this from the grading service. I changed to name to `extractTestCasesFromResultAndBroadcastUpdates` but I'd like to leave that part here to keep the calling method short and clean.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ExerciseHintService.java [hunk 9]
```diff
@@ -216,7 +216,7 @@ private boolean isTaskSuccessfulInSubmission(ProgrammingExerciseTask task, Submi
         var testCasesInTask = task.getTestCases();
         var feedbacks = result.getFeedbacks();
         // the feedback can either not exist (e.g. for skipped test cases), or the attribute positive may not be set
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ExerciseHintService.java:218]: 🤔 I not even sure if the logic is correct here. I think this comment wants to say that we only return true if all the mentioned tests were sucessfull, and it might be possible for a mentioned test to not exist in the student reslt. If this is the case, we must also return false.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ExerciseHintService.java [hunk 10]
```diff
@@ -216,7 +216,7 @@ private boolean isTaskSuccessfulInSubmission(ProgrammingExerciseTask task, Submi
...
-        return feedbacks.stream().filter(feedback -> feedback != null && testCasesInTask.stream().anyMatch(testCase -> Objects.equals(testCase.getTestName(), feedback.getText())))
+        return feedbacks.stream().filter(Objects::nonNull).filter(feedback -> testCasesInTask.stream().anyMatch(testCase -> Objects.equals(testCase, feedback.getTestCase())))
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ExerciseHintService.java:219]: This is correct.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 11]
```diff
@@ -191,6 +196,17 @@ private List<ProgrammingExerciseTask> extractTasks(ProgrammingExercise exercise)
...
 
+    /**
+     * Replaces a comma seperated list of test case names with their corresponding ids.
+     * If no matching test case exists (e.g. due to a typo) the test name get kept.
+     */
+    private String extractTestCaseIdsFromNames(String capturedTestCaseNames, Set<ProgrammingExerciseTestCase> testCases) {
+        var testCaseNames = extractTestCaseNames(capturedTestCaseNames);
+
+        return testCaseNames.stream().map(testName -> testCases.stream().filter(tc -> testName.equals(tc.getTestName())).findFirst().map(tc -> tc.getId().toString())
+                .map(id -> "<testid>" + id + "</testid>").orElse(testName)).collect(Collectors.joining(","));
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:207]: We should probably introduce some kind of escaping here.

File: src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseResultJenkinsIntegrationTest.java [hunk 12]
```diff
@@ -150,4 +150,14 @@ void shouldCreateResultOnCustomDefaultBranch() {
                 List.of(), List.of(commit), null);
         programmingExerciseResultTestService.shouldCreateResultOnCustomDefaultBranch(customDefaultBranch, notification);
     }
+
+    @Test
+    @WithMockUser(username = TEST_PREFIX + "student1", roles = "USER")
+    void shouldRemoveTestCaseNamesFromWebsocketNotification() throws Exception {
+        var exercise = programmingExerciseResultTestService.getProgrammingExercise();
+        var repoName = (exercise.getProjectKey() + "-" + TEST_PREFIX + "student1").toUpperCase();
+        var notification = ProgrammingExerciseFactory.generateTestResultDTO(exercise.getProjectKey() + " ┬╗ " + repoName + " #3", repoName, null, exercise.getProgrammingLanguage(),
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseResultJenkinsIntegrationTest.java:159]: Good question, I'm pretty sure I copied that somewhere. 👀

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 13]
```diff
@@ -208,4 +249,105 @@ else if (!testMessages.isEmpty()) {
...
+
+        Set<ProgrammingExerciseTestCase> testCasesToSave = new HashSet<>();
+        testCasesToSave.addAll(newTestCases);
+        testCasesToSave.addAll(testCasesWithUpdatedActivation);
+
+        setTestCaseType(testCasesToSave, exercise.getProgrammingLanguage());
+
+        // Ensure no duplicate TestCase is present: TestCases have to have a unique name per exercise.
+        // Just using the uniqueness property of the set is not enough, as the equals/hash functions
+        // consider more attributes of the TestCase rather than only the testName.
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:294]: True, "more" is not the correct wording here. It tests equality via id which allows multiple test cases with the same name, but we need to check for the name here. I adapted the comment.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ExerciseHintService.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ExerciseHintService.java]: I added more comments and improved the logic.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 14]
```diff
@@ -191,6 +196,17 @@ private List<ProgrammingExerciseTask> extractTasks(ProgrammingExercise exercise)
...
     }
 
+    /**
+     * Replaces a comma seperated list of test case names with their corresponding ids.
+     * If no matching test case exists (e.g. due to a typo) the test name get kept.
+     */
+    private String extractTestCaseIdsFromNames(String capturedTestCaseNames, Set<ProgrammingExerciseTestCase> testCases) {
+        var testCaseNames = extractTestCaseNames(capturedTestCaseNames);
+
+        return testCaseNames.stream().map(testName -> testCases.stream().filter(tc -> testName.equals(tc.getTestName())).findFirst().map(tc -> tc.getId().toString())
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:206]: > or at least being split into multiple lines.

That's not possible since Spotless reverts this change every time. I moved the map() call into its own method.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:281]: This is correct. In this code, we check if we need to create new test case objects. For any exercise, the test case name must be unique. This method tests of test name equality, making sure that no duplicated tests get created.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (julian-christl) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:180]: @Strohgelaender You could delete part of the pattern string and see if CodeQL is happy then. Then we'd know what part is the problem.

A non-greedy capture might wor, otherwise you could try
`\\[task]\\[(?<name>[^\\[\\]]+)]\\((?<tests>\w[\w_]*(?:,\s*[\w_]*)*)\\)`
It should be more precise. But again, first we need to know which part is the problem. Cut it out and if  CodeQL resolves this issue, that was it.

File: src/main/webapp/app/exercises/programming/shared/instructions-render/service/programming-exercise-instruction.service.ts [hunk 15]
```diff
@@ -15,67 +15,88 @@ export enum TestCaseState {
...
+                    notExecuted: feedback?.positive === undefined ? [...acc.notExecuted, testId] : acc.notExecuted,
                 };
             },
             { failed: [], successful: [], notExecuted: [] },
         );
     }
+
+    public convertTestListToIds(testList: string): number[] {
+        // If there are test names (preview case) map the test to its corresponding id. Else use the id directly provided in the text.
+        // split the names by "," only when there is not a closing bracket without a previous opening bracket
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/webapp/app/exercises/programming/shared/instructions-render/service/programming-exercise-instruction.service.ts:84]: not sure, I moved this from above and kept the regex.

File: src/main/resources/config/liquibase/changelog/20230810100000_changelog.xml [hunk 16]
```diff
@@ -0,0 +1,62 @@
...
+               , sp AS (SELECT exercise.id, exercise.solution_participation_id
+                        FROM exercise
+                        WHERE exercise.discriminator = 'P'
+                          AND exercise.solution_participation_id IS NOT NULL)
+               <!-- Maps every feedback to their exercise id -->
+               , fe AS (SELECT feedback.id, feedback.text, exercise.id AS exercise_id
+                        FROM feedback
+                          LEFT JOIN result ON feedback.result_id = result.id
+                          LEFT JOIN participation ON result.participation_id = participation.id
+                        , exercise
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/resources/config/liquibase/changelog/20230810100000_changelog.xml:32]: as you can see below, there are 3 options on how the exercise can get retrieved (paticipation.exericse is null for template and solution participations and they need to be handled separately), so a direct join is not possible.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ExerciseHintService.java [hunk 17]
```diff
@@ -215,9 +213,14 @@ private boolean isTaskSuccessfulInSubmission(ProgrammingExerciseTask task, Submi
         }
         var testCasesInTask = task.getTestCases();
         var feedbacks = result.getFeedbacks();
-        // the feedback can either not exist (e.g. for skipped test cases), or the attribute positive may not be set
-        return feedbacks.stream().filter(feedback -> feedback != null && testCasesInTask.stream().anyMatch(testCase -> Objects.equals(testCase.getTestName(), feedback.getText())))
-                .allMatch(feedback -> Boolean.TRUE.equals(feedback.isPositive()));
+        // a task is successful if feedback for all in the task linked tests exist and if these tests all passed.
+        var feedbackForTask = testCasesInTask.stream().map(testCase -> feedbacks.stream().filter(feedback -> testCase.equals(feedback.getTestCase())).findAny().orElse(null))
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ExerciseHintService.java:217]: Yes, each test case can only produce one (or zero) feedback object. So for each testcase, we look for the only feedback created by it, if this exists.

**Review by tobias-lippert — COMMENTED** [review]
Code looks good in general, I just added some questions and comments.

File: src/main/java/de/tum/in/www1/artemis/config/migration/MigrationEntry.java [hunk 18]
```diff
@@ -1,8 +1,6 @@
 package de.tum.in.www1.artemis.config.migration;
 
-import java.io.Serializable;
-
-public abstract class MigrationEntry implements Serializable {
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/config/migration/MigrationEntry.java:5]: See the discussion above. The class never gets serialized and this caused warnings / enforcing the use of `transistent`.

File: src/main/java/de/tum/in/www1/artemis/config/migration/entries/MigrationEntry20230810_150000.java [hunk 19]
```diff
@@ -0,0 +1,50 @@
...
+    private final ProgrammingExerciseTaskService taskService;
+
+    public MigrationEntry20230810_150000(ProgrammingExerciseRepository programmingExerciseRepository, ProgrammingExerciseTaskService taskService) {
+        this.programmingExerciseRepository = programmingExerciseRepository;
+        this.taskService = taskService;
+    }
+
+    @Override
+    public void execute() {
+        Pageable pageable = Pageable.ofSize(50);
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/config/migration/entries/MigrationEntry20230810_150000.java:27]: I don't think all programming exercises would fit into the memory on a production instance at the same time.

File: src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseGitlabJenkinsIntegrationTest.java [hunk 20]
```diff
@@ -415,6 +415,12 @@ void exportProgrammingExerciseInstructorMaterial_problemStatementNull() throws E
         programmingExerciseTestService.exportProgrammingExerciseInstructorMaterial_problemStatementNull_success();
     }
 
+    @Test
+    @WithMockUser(username = TEST_PREFIX + "instructor1", roles = "INSTRUCTOR")
+    void exportProgrammingExerciseInstructorMaterial_problemStatementShouldContainTestNames() throws Exception {
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseGitlabJenkinsIntegrationTest.java:420]: The instructor should be able to directly edit the received programming exercises, and while editing they should work directly with the names.

File: src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseIntegrationTestService.java [hunk 21]
```diff
@@ -179,10 +180,15 @@ class ProgrammingExerciseIntegrationTestService {
     // this will be a SpyBean because it was configured as SpyBean in the super class of the actual test class (see AbstractArtemisIntegrationTest)
     private VersionControlService versionControlService;
 
-    void setup(String userPrefix, MockDelegate mockDelegate, VersionControlService versionControlService) throws Exception {
+    // this will be a SpyBean because it was configured as SpyBean in the super class of the actual test class (see AbstractArtemisIntegrationTest)
+    private ContinuousIntegrationService continuousIntegrationService;
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseIntegrationTestService.java:184]: This is not a direct Test but a TestService. This class did not contain this field. I simply copied this comment, which is wrong.

File: src/test/java/de/tum/in/www1/artemis/domain/ResultTest.java [hunk 22]
```diff
@@ -11,29 +11,35 @@
...
+import de.tum.in.www1.artemis.course.CourseUtilService;
 import de.tum.in.www1.artemis.domain.enumeration.FeedbackType;
 import de.tum.in.www1.artemis.domain.enumeration.Visibility;
 import de.tum.in.www1.artemis.domain.participation.ProgrammingExerciseStudentParticipation;
 import de.tum.in.www1.artemis.domain.participation.StudentParticipation;
+import de.tum.in.www1.artemis.exercise.programmingexercise.ProgrammingExerciseUtilService;
 import de.tum.in.www1.artemis.repository.ResultRepository;
-import de.tum.in.www1.artemis.service.AssessmentService;
 
 class ResultTest extends AbstractSpringIntegrationBambooBitbucketJiraTest {
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/test/java/de/tum/in/www1/artemis/domain/ResultTest.java:22]: This should be a GitHub issue, I don't see something like this in the code.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 23]
```diff
@@ -184,13 +224,68 @@ private List<ProgrammingExerciseTask> extractTasks(ProgrammingExercise exercise)
             var testCaseNames = extractTestCaseNames(capturedTestCaseNames);
 
             for (String testName : testCaseNames) {
-                testCases.stream().filter(tc -> tc.getTestName().equals(testName)).findFirst().ifPresent(task.getTestCases()::add);
+                Optional<ProgrammingExerciseTestCase> foundTestCase;
+                if (testName.startsWith(TESTID_START)) {
+                    Long id = extractTestId(testName);
```
[the remark this answers is not in the document]
Comment (pal03377) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:229]: I would ignore this because it's an unsubstantial warning, and `id` is a pretty clear name for a variable name imo

**Review by pal03377 — COMMENTED** [review]
Code looks good! I only have a few optional notes:

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ExerciseHintService.java (hunk 17 above)
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ExerciseHintService.java:217]: I don't really see how since `anyMatch` returns just a boolean, but we need the test case to check its state.

File: src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-task.extension.ts [hunk 24]
```diff
@@ -12,11 +14,18 @@
 
 @Injectable({ providedIn: 'root' })
 export class ProgrammingExerciseTaskExtensionWrapper implements ArtemisShowdownExtensionWrapper {
+    // E.g. [task][Implement BubbleSort](testBubbleSort)
+    // const taskRegex = /\[task\]\[.*\]\(.*\)({.*})?/g;
+    private readonly taskRegex = /\[task]\[[^[\]]+]\((?:,?\s*[^()\s,]+(?:\([^()]*\))?)*\)/g;
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-task.extension.ts:18]: yes ;(

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 25]
```diff
@@ -178,21 +213,30 @@ public List<Feedback> createFeedbackFromStaticCodeAnalysisReports(List<StaticCod
...
+            Set<ProgrammingExerciseTestCase> activeTestCases) {
         Feedback feedback = new Feedback();
-        feedback.setText(testName);
+        var testCase = activeTestCases.stream().filter(test -> testName.equals(test.getTestName())).findAny();
+        if (testCase.isPresent()) {
+            feedback.setTestCase(testCase.get());
+        }
+        else {
+            // This feedback was created by a test which is not known to Artemis (not part of the solution result)
+            // Feedback like this does not get displayed to students. (see ProgrammingExerciseGradingService#filterAutomaticFeedbacksWithoutTestCase
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:233]:
```suggestion
            // Feedback like this does not get displayed to students, see ProgrammingExerciseGradingService#filterAutomaticFeedbacksWithoutTestCase.
```

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 26]
```diff
@@ -208,4 +252,111 @@ else if (!testMessages.isEmpty()) {
...
+        if (haveTestCasesChanged) {
+            // Notify the client about the updated testCases
+            Set<ProgrammingExerciseTestCase> testCases = testCaseRepository.findByExerciseId(exercise.getId());
+            websocketMessagingService.sendMessage("/topic/programming-exercises/" + exercise.getId() + "/test-cases", testCases);
+        }
+    }
+
+    /**
+     * From a list of build run feedback, extract all test cases. If an already stored test case is not found anymore in the build result, it will not be deleted, but set inactive.
+     * This way old test cases are not lost, some interfaces in the client might need this information to e.g. show warnings.
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:273]:
```suggestion
     * From a list of build run feedback, extract all test cases. If an already stored test case is not found anymore in the build result, it will not be deleted but set inactive.
     * This way old test cases are not lost, some interfaces in the client might need this information, e.g., to show warnings.
```

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 27]
```diff
@@ -208,4 +252,111 @@ else if (!testMessages.isEmpty()) {
...
+            // Either the test case was active and is not part of the feedback anymore OR was not active before and is now part of the feedback again.
+            return (matchingTestCase.isEmpty() && existing.isActive()) || (matchingTestCase.isPresent() && matchingTestCase.get().isActive() && !existing.isActive());
+        }).map(existing -> existing.clone().active(!existing.isActive())).collect(Collectors.toSet());
+    }
+
+    /**
+     * Sets the enum value test case type for every test case and saves to the database. Implicitly, all tests are of the same programming language.
+     * If the test cases belong to a non-JAVA programming exercise, the type is set to DEFAULT.
+     * If the test case belong to a JAVA programming exercise, the type is set to:
+     * STRUCTURAL: test case has been generated by the structure oracle, and it's name therefore follow a certain pattern.
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:328]:
```suggestion
     * STRUCTURAL: test case has been generated by the structure oracle, therefore its name follows a certain pattern.
```

File: src/main/webapp/app/exercises/programming/shared/instructions-render/service/programming-exercise-instruction.service.ts [hunk 28]
```diff
@@ -15,67 +16,91 @@ export enum TestCaseState {
...
+                    successful: feedback?.positive === true ? [...acc.successful, testId] : acc.successful,
+                    notExecuted: feedback?.positive === undefined ? [...acc.notExecuted, testId] : acc.notExecuted,
                 };
             },
             { failed: [], successful: [], notExecuted: [] },
         );
     }
+
+    public convertTestListToIds(testList: string, testCases: ProgrammingExerciseTestCase[] | undefined): number[] {
+        // If there are test names (e.g. during the markdown preview), map the test to its corresponding id using the given testCases array.
```
Comment (nityanandaz) [inline src/main/webapp/app/exercises/programming/shared/instructions-render/service/programming-exercise-instruction.service.ts:84]:
```suggestion
        // If there are test names, e.g., during the markdown preview, map the test to its corresponding id using the given testCases array.
```

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 29]
```diff
@@ -184,13 +224,79 @@ private List<ProgrammingExerciseTask> extractTasks(ProgrammingExercise exercise)
...
+                return Objects.requireNonNullElse(testName, testId);
+            }
+        }
+        return testId;
+    }
+
+    private Long extractTestId(String test) {
+        var matcher = TESTID_PATTERN.matcher(test);
+        if (!matcher.find()) {
+            // This not a test id but a name that got not replaced previously (e.g. due to a typo)
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:288]:
```suggestion
            // This not a test id but a name that got not replaced previously, e.g., due to a typo
```

**Review by nityanandaz — COMMENTED** [review]
Code looks good, added some grammar suggestions

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 30]
```diff
@@ -233,4 +342,117 @@ else if (currentChar == ')') {
...
+     * The problem statement of the passed exercise gets changed, but the result does not get saved.
+     * <p>
+     * Example:
+     * Input: [task][Implement BubbleSort](testBubbleSort, testClass[BubbleSort])
+     * Output: [task][Implement BubbleSort](<testid>15</testid>,<testid>18</testid>)
+     *
+     * @param exercise the exercise to replaces the test names in the problem statement
+     */
+    public void replaceTestNamesWithIds(ProgrammingExercise exercise) {
+        // Only replace active test cases (tests that actually exist in the repository).
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:357]: TIL that American English actually uses a comma after i.e. I don't think using 4 punctuation marks in 7 symbols looks good, so I'd prefer the brackets here.

**Review by terlan98 — COMMENTED** [review]
Tested on TS5. The problem statement does not contain the test case names anymore. The `text` field containing the test names is removed. Exporting/importing exercises also work 👍 

There's something I'm not sure about:
- I enabled the  'Show Test Names to Students' option when creating an exercise but I still can't see the test case names as a student.
  Screenshot 2023-09-01 at 11 02 41
  The test case names become available only after I press the submit button:
  Screenshot 2023-09-01 at 11 10 48
  Is this intended?

**Review by terlan98 — APPROVED** [review]
Thanks for the recent fix. Re-tested on TS5. Now works as expected 👍

**Review by RY997 — DISMISSED** [review]
Tested on ts5, worked as expected

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ExerciseHintService.java [hunk 31]
```diff
@@ -215,9 +213,14 @@ private boolean isTaskSuccessfulInSubmission(ProgrammingExerciseTask task, Submi
         }
         var testCasesInTask = task.getTestCases();
         var feedbacks = result.getFeedbacks();
-        // the feedback can either not exist (e.g. for skipped test cases), or the attribute positive may not be set
-        return feedbacks.stream().filter(feedback -> feedback != null && testCasesInTask.stream().anyMatch(testCase -> Objects.equals(testCase.getTestName(), feedback.getText())))
-                .allMatch(feedback -> Boolean.TRUE.equals(feedback.isPositive()));
+        // a task is successful if feedback for all in the task linked tests exist and if these tests all passed.
+        var feedbackForTask = testCasesInTask.stream().map(testCase -> feedbacks.stream().filter(feedback -> testCase.equals(feedback.getTestCase())).findAny())
```
Comment (pal03377) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ExerciseHintService.java:217]: IMO this is a bit hard to understand all at once, but since it didn't get worse compared to the previous version of this, I would be ok with it for this PR.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 32]
```diff
@@ -24,15 +26,52 @@ public class ProgrammingExerciseTaskService {
...
+     * The third and last section {@code tests} - within round brackets - captures zero, one or multiple test cases. Multiple test cases get separated by a comma and optional
+     * whitespace. Each test case contains a test name with or without round brackets. These round brackets may contain method parameters. Test names may contain any characters but
+     * round brackets, whitespace or commas. Method parameters only exclude round brackets. After round brackets a test case may contain additional characters excluding round
+     * brackets or commas.<br>
+     * Therefore, allowed test names are among others {@code testName}, {@code testName()}, {@code testName(1234, 12)}, {@code testName(testValue)[1]}, {@code Test Name}.<br>
+     * For multiple testcases it's {@code testName,otherTestName()} or {@code testName,     otherTestName()}.<br>
+     * <p>
+     * This is coupled to the value used in `ProgrammingExerciseTaskExtensionWrapper`, `ProgrammingExerciseInstructionAnalysisService`, and `TaskCommand` in the client
+     * If you change the regex, make sure to change it in all places!
```
Comment (pal03377) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:46]: Can you reference the other places?

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 33]
```diff
@@ -24,15 +26,52 @@ public class ProgrammingExerciseTaskService {
...
+     * The second section {@code name} - within square brackets - matches the task name, allowing any characters but square brackets.<br>
+     * The third and last section {@code tests} - within round brackets - captures zero, one or multiple test cases. Multiple test cases get separated by a comma and optional
+     * whitespace. Each test case contains a test name with or without round brackets. These round brackets may contain method parameters. Test names may contain any characters but
+     * round brackets, whitespace or commas. Method parameters only exclude round brackets. After round brackets a test case may contain additional characters excluding round
+     * brackets or commas.<br>
+     * Therefore, allowed test names are among others {@code testName}, {@code testName()}, {@code testName(1234, 12)}, {@code testName(testValue)[1]}, {@code Test Name}.<br>
+     * For multiple testcases it's {@code testName,otherTestName()} or {@code testName,     otherTestName()}.<br>
+     * <p>
+     * This is coupled to the value used in `ProgrammingExerciseTaskExtensionWrapper`, `ProgrammingExerciseInstructionAnalysisService`, and `TaskCommand` in the client
```
Comment (pal03377) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:45]: Very thought-through! 💪

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 34]
```diff
@@ -184,13 +223,79 @@ private List<ProgrammingExerciseTask> extractTasks(ProgrammingExercise exercise)
...
+                }
+                foundTestCase.ifPresent(task.getTestCases()::add);
             }
             tasks.add(task);
         }
         return tasks;
     }
 
+    /**
+     * Replaces a comma seperated list of test case names with their corresponding ids.
```
Comment (pal03377) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:242]:
```suggestion
     * Replaces a comma separated list of test case names with their corresponding ids.
```

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 35]
```diff
@@ -184,13 +223,79 @@ private List<ProgrammingExerciseTask> extractTasks(ProgrammingExercise exercise)
...
+        var testCaseNames = extractTestCaseNames(capturedTestCaseNames);
+
+        return testCaseNames.stream().map(testName -> convertTestNameToTestId(testName, testCases)).collect(Collectors.joining(","));
+    }
+
+    private String convertTestNameToTestId(String testName, Set<ProgrammingExerciseTestCase> testCases) {
+        for (ProgrammingExerciseTestCase testCase : testCases) {
+            if (testName.equals(testCase.getTestName())) {
+                String id = testCase.getId().toString();
+                return TESTID_START + id + TESTID_END;
```
Comment (pal03377) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:255]: Optional note: I would not expect a method called `convertTestNameToTestId` to also add `<testid>...</testid>` around the ID 🤔 Maybe rename the method or add it somewhere else? I would expect the test ID to be the content between the `<testid>` tags and not the full thing.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 36]
```diff
@@ -184,13 +223,79 @@ private List<ProgrammingExerciseTask> extractTasks(ProgrammingExercise exercise)
...
+        for (ProgrammingExerciseTestCase tc : testCases) {
+            if (tc.getId().equals(id)) {
+                String testName = tc.getTestName();
+                return Objects.requireNonNullElse(testName, testId);
+            }
+        }
+        return testId;
+    }
+
+    private Long extractTestId(String test) {
```
Comment (pal03377) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:284]: About the naming of test vs. testID: Here, you call a string like `<testid>123</testid>` simply `test` 🤔 

Also, can you Add an example of what this method does in a JavaDoc comment? Something like "example: <testid>123</testid> -> 123" suffices to understand the method much more quickly.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 37]
```diff
@@ -184,13 +223,79 @@ private List<ProgrammingExerciseTask> extractTasks(ProgrammingExercise exercise)
...
+        var matcher = TESTID_PATTERN.matcher(test);
+        if (!matcher.find()) {
+            // This not a test id but a name that got not replaced previously, e.g., due to a typo
```
Comment (pal03377) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:287]:
```suggestion
            // This not a test id but a name that did not get replaced previously, e.g., due to a typo
```
grammar nitpick

File: src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-task.extension.ts [hunk 38]
```diff
@@ -11,11 +13,25 @@ import { ShowdownExtension } from 'showdown';
...
+    /**
+     * Regular expression for finding tasks.
+     * A Task starts with the identifier `[task]` and the task name in square brackets.
+     * This gets followed by a list of test cases in parentheses.
+     * @example [task][Implement BubbleSort](testBubbleSort)
+     *
+     * The regular expression is used to find all tasks inside a problem statement and therefore uses the global flag.
+     *
+     * This is coupled to the value used in `ProgrammingExerciseTaskService` in the server.
+     * If you change the regex, make sure to change it in all places!
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-task.extension.ts:25]: Can you add a reference to the other places?

File: src/main/webapp/app/exercises/programming/shared/instructions-render/task/programming-exercise-instruction-task-status.component.ts [hunk 39]
```diff
@@ -17,19 +17,26 @@ export class ProgrammingExerciseInstructionTaskStatusComponent {
...
     @Input() taskName: string;
+
+    /**
+     * array of test ids
+     */
     @Input()
     get tests() {
-        return this.testsValue;
+        return this.testIds;
     }
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/instructions-render/task/programming-exercise-instruction-task-status.component.ts:27]: Why not call the prop `testIds` then? 🤔

**Review by pal03377 — COMMENTED** [review]
I did a code re-review and only found some minor things:

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java (hunk 32 above)
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:46]: What do you mean by this? They are directly mentioned above in the text.

File: src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-task.extension.ts (hunk 38 above)
Comment (pal03377) [reply src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-task.extension.ts:25]: Oh, I overlooked the line above 🤦

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java (hunk 32 above)
Comment (pal03377) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:46]: Sorry, I overlooked that this was the case

File: src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-task.extension.ts [hunk 40]
```diff
@@ -93,47 +113,46 @@ export class ProgrammingExerciseTaskExtensionWrapper implements ArtemisShowdownE
...
+                }
+                return problemStatement;
             },
         };
         return extension;
     }
+
+    private createTasks(problemStatement: string, tasks: RegExpMatchArray[]): string {
+        const testsForTask: TaskArray = tasks
+            .filter((testMatch) => testMatch?.length === 3)
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-task.extension.ts:129]: Where does the magic number 3 come from here? Maybe add a small comment (especially about when it will not be 3 - for some old test matches, I guess?)

**Review by pal03377 — APPROVED** [review]
All my change requests have been addressed and the code lgtm now 👍

File: src/main/java/de/tum/in/www1/artemis/domain/Result.java [hunk 41]
```diff
@@ -483,14 +483,43 @@ public void filterSensitiveInformation() {
...
+     * @param exercise        the exercise related to this result. Used to determine if test case names should be removed.
+     */
+    public void filterSensitiveFeedbacks(boolean isBeforeDueDate, Exercise exercise) {
         feedbacks.removeIf(Feedback::isInvisible);
 
         if (isBeforeDueDate) {
             feedbacks.removeIf(Feedback::isAfterDueDate);
         }
 
-        // TODO: this is not good code!
```
Comment (JohannesStoehr) [inline src/main/java/de/tum/in/www1/artemis/domain/Result.java:492]: Stephan specifically added this some time ago regarding the change of the test case count and so on. Is it ok to remove this TODO now?

**Review by pal03377 — DISMISSED** [review]
Code reapproval

**Comment by Strohgelaender** [comment]
To test in the next testing session:

- [ ] Import into other courses
- [ ] Export / import from file
- [ ] course archive
- [ ] data export
- [ ] complaints
- [ ] result export

**Review by milljoniaer — APPROVED** [review]
Tested in testing session on ts11

**Review by basak-akan — APPROVED** [review]
Tested in testing session on TS11, complaints and course archive worked as expected

**Review by laurenzfb — APPROVED** [review]
Tested exercise import to other course and export/import by file. works as expected

**Review by MaximilianAnzinger — DISMISSED** [review]
Tested on TS2

**Review by florian-glombik — DISMISSED** [review]
Tested on ts2 during testing session, the migration worked fine for the feedback.

Did not find issues with existing programming exercises and new exercises.
Also tested exam programming exercises, where the feedback was displayed properly (build failed, successful tests, failed tests, tests not displayed).

File: src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-plant-uml.extension.ts [hunk 42]
```diff
@@ -12,10 +13,14 @@ import { sanitize } from 'dompurify';
...
 export class ProgrammingExercisePlantUmlExtensionWrapper implements ArtemisShowdownExtensionWrapper {
     private latestResult?: Result;
+    private testCases?: ProgrammingExerciseTestCase[];
     private injectableElementsFoundSubject = new Subject<() => void>();
 
     // unique index, even if multiple plant uml diagrams are shown from different problem statements on the same page (in different tabs)
     private plantUmlIndex = 0;
+
+    // This regex is the same as in the server: ProgrammingExerciseTaskService.java
+    private readonly testsColorRegex = /testsColor\((\s*[^()\s]+(\([^()]*\))?)\)/g;
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-plant-uml.extension.ts:23]: Should be a constant instead of a field

File: src/main/webapp/app/exercises/programming/manage/instructions-editor/analysis/programming-exercise-instruction-analysis.service.ts [hunk 43]
```diff
@@ -13,7 +13,7 @@ import {
  */
 @Injectable()
 export class ProgrammingExerciseInstructionAnalysisService {
-    private readonly TEST_CASE_REGEX = /.*?\[.*]\((.*)\)/;
+    private readonly TEST_CASE_REGEX = /\[[^[\]]+]\(((?:[^(),]+(?:\([^()]*\)[^(),]*)?(?:,[^(),]+(?:\([^()]*\)[^(),]*)?)*)?)\)/;
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/programming/manage/instructions-editor/analysis/programming-exercise-instruction-analysis.service.ts:16]: Should be a constant instead of a field

File: src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-plant-uml.extension.ts [hunk 44]
```diff
@@ -92,11 +101,16 @@ export class ProgrammingExercisePlantUmlExtensionWrapper implements ArtemisShowd
...
+                        const tests = this.programmingExerciseInstructionService.convertTestListToIds(capture, this.testCases);
                         const { testCaseState } = this.programmingExerciseInstructionService.testStatusForTask(tests, this.latestResult);
-                        return testCaseState === TestCaseState.SUCCESS ? 'green' : testCaseState === TestCaseState.FAIL ? 'red' : 'grey';
+                        if (testCaseState === TestCaseState.SUCCESS) {
+                            return 'green';
+                        } else if (testCaseState === TestCaseState.FAIL) {
+                            return 'red';
+                        } else {
+                            return 'grey';
+                        }
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-plant-uml.extension.ts:113]: Consider unsing a switch-case
Feels smoother when working with enums. Just my personal opinion. Leave it if you don't agree.

File: src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-task.extension.ts [hunk 45]
```diff
@@ -11,11 +13,25 @@ import { ShowdownExtension } from 'showdown';
...
+     * A Task starts with the identifier `[task]` and the task name in square brackets.
+     * This gets followed by a list of test cases in parentheses.
+     * @example [task][Implement BubbleSort](testBubbleSort)
+     *
+     * The regular expression is used to find all tasks inside a problem statement and therefore uses the global flag.
+     *
+     * This is coupled to the value used in `ProgrammingExerciseTaskService` in the server.
+     * If you change the regex, make sure to change it in all places!
+     */
+    private readonly taskRegex = /\[task]\[([^[\]]+)]\(((?:[^(),]+(?:\([^()]*\)[^(),]*)?(?:,[^(),]+(?:\([^()]*\)[^(),]*)?)*)?)\)/g;
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-task.extension.ts:27]: Should be a constant instead of a field

File: src/main/webapp/app/exercises/programming/shared/instructions-render/service/programming-exercise-instruction.service.ts [hunk 46]
```diff
@@ -15,67 +16,91 @@ export enum TestCaseState {
...
+            .map((text) => text.trim())
+            .map((text) => {
+                // -1 to indicate a not found test
+                return this.convertProblemStatementTextToTestId(text, testCases) ?? -1;
+            });
+    }
+
+    public convertProblemStatementTextToTestId(test: string, testCases?: ProgrammingExerciseTestCase[]): number | undefined {
+        // If the text contains <testid> and </testid>, directly use the number inside
+        const match = RegExp('<testid>(\\d+)</testid>').exec(test);
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/programming/shared/instructions-render/service/programming-exercise-instruction.service.ts:98]: How about specifying this as a constant as well?

File: src/main/webapp/app/exercises/programming/shared/instructions-render/service/programming-exercise-instruction.service.ts [hunk 47]
```diff
@@ -15,67 +16,91 @@ export enum TestCaseState {
...
             { failed: [], successful: [], notExecuted: [] },
         );
     }
+
+    public convertTestListToIds(testList: string, testCases: ProgrammingExerciseTestCase[] | undefined): number[] {
+        // If there are test names, e.g., during the markdown preview, map the test to its corresponding id using the given testCases array.
+        // Otherwise, use the id directly provided within the <testid> section.
+        // split the tests by "," only when there is not a closing bracket without a previous opening bracket
+        return testList
+            .split(/,(?![^(]*?\))/)
```
Comment (julian-christl) [inline src/main/webapp/app/exercises/programming/shared/instructions-render/service/programming-exercise-instruction.service.ts:88]: How about specifying this as a constant as well?

File: src/test/java/de/tum/in/www1/artemis/hestia/ProgrammingExerciseTaskServiceTest.java [hunk 48]
```diff
@@ -247,15 +247,169 @@ void testParseTestCaseNames() {
...
-        final var actualTask = actualTasks.stream().findAny().orElseThrow().getId();
+        final var actualTask = actualTasks.iterator().next().getId();
         var actualTaskWithTestCases = programmingExerciseTaskRepository.findByIdWithTestCaseAndSolutionEntriesElseThrow(actualTask);
         assertThat(actualTaskWithTestCases.getTaskName()).isEqualTo("Task 1");
         var actualTestCaseNames = actualTaskWithTestCases.getTestCases().stream().map(ProgrammingExerciseTestCase::getTestName).toList();
         assertThat(actualTestCaseNames).containsExactlyInAnyOrder(testCaseNames);
     }
 
+    @Test
+    @WithMockUser(username = "instructor1", roles = "INSTRUCTOR")
```
Comment (julian-christl) [inline src/test/java/de/tum/in/www1/artemis/hestia/ProgrammingExerciseTaskServiceTest.java:258]: Why do we need this AuthMock here?

**Review by julian-christl — COMMENTED** [review]
Got some questions or concerns.
To be frank, I didn't check the tests as thoroughly as the production code, but generally, the test cases seem reasonable and nothing in particular stood out - apart from the one comment.

File: src/main/java/de/tum/in/www1/artemis/config/migration/MigrationRegistry.java [hunk 49]
```diff
@@ -26,11 +27,11 @@ public class MigrationRegistry {
...
 
     public MigrationRegistry(MigrationService migrationService) {
-        // Here we define the order of the ChangeEntries
         this.migrationService = migrationService;
-
+        // Here we define the order of the ChangeEntries
         this.migrationEntryMap.put(1, MigrationEntry20230808_203400.class);
-        this.migrationEntryMap.put(2, MigrationEntry20230920_181600.class);
+        this.migrationEntryMap.put(2, MigrationEntry20230810_150000.class);
+        this.migrationEntryMap.put(3, MigrationEntry20230920_181600.class);
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/config/migration/MigrationRegistry.java:34]: no, it must be sorted by time (there is a server test to ensure that).

File: src/main/java/de/tum/in/www1/artemis/config/migration/entries/MigrationEntry20230810_150000.java [hunk 50]
```diff
@@ -0,0 +1,86 @@
...
+
+    @Override
+    public void execute() {
+        long size = programmingExerciseRepository.count();
+        log.info("Migrating all {} programming exercises. This might take a while.", size);
+
+        ExecutorService executorService = Executors.newFixedThreadPool(THREADS);
+        Pageable pageable = Pageable.ofSize(BATCH_SIZE);
+
+        while (true) {
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/config/migration/entries/MigrationEntry20230810_150000.java:48]: You used an indexed loop in your migration, with such an approach this would be possible since you know how many pages you expect. I use the check for the last page in my code, and I only know information about the current page inside of the loop.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseService.java [hunk 51]
```diff
@@ -439,7 +439,10 @@ public ProgrammingExercise updateProgrammingExercise(ProgrammingExercise program
 
         channelService.updateExerciseChannel(programmingExerciseBeforeUpdate, updatedProgrammingExercise);
 
+        programmingExerciseTaskService.replaceTestNamesWithIds(updatedProgrammingExercise);
         ProgrammingExercise savedProgrammingExercise = programmingExerciseRepository.save(updatedProgrammingExercise);
+        // The returned value should use names since it gets send back to the client
+        programmingExerciseTaskService.replaceTestIdsWithNames(savedProgrammingExercise);
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseService.java:445]: No, I can just save the problem statement and set it again before sending the result to the client. 👍

File: src/main/webapp/app/exercises/programming/manage/instructions-editor/analysis/programming-exercise-instruction-analysis.service.ts [hunk 52]
```diff
@@ -98,12 +98,10 @@ export class ProgrammingExerciseInstructionAnalysisService {
      *
      * @param issueType for which to retrieve the fitting translation.
      */
-    private getTranslationByIssueType = (issueType: ProblemStatementIssue) => {
+    private getTranslationByIssueType = (issueType: ProblemStatementIssue): string => {
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/webapp/app/exercises/programming/manage/instructions-editor/analysis/programming-exercise-instruction-analysis.service.ts:101]: This """enum"" has only one possible value. If at any point a new value gets added, this method will throw a compilation error since then the missing default case will be a problem. That's exactly what I intended, force the developer to change this method in case a new issue type gets added.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 53]
```diff
@@ -24,15 +26,52 @@ public class ProgrammingExerciseTaskService {
...
+     * brackets or commas.<br>
+     * Therefore, allowed test names are among others {@code testName}, {@code testName()}, {@code testName(1234, 12)}, {@code testName(testValue)[1]}, {@code Test Name}.<br>
+     * For multiple testcases it's {@code testName,otherTestName()} or {@code testName,     otherTestName()}.<br>
+     * <p>
+     * This is coupled to the value used in `ProgrammingExerciseTaskExtensionWrapper`, `ProgrammingExerciseInstructionAnalysisService`, and `TaskCommand` in the client
      * If you change the regex, make sure to change it in all places!
      */
-    private final Pattern taskPatternForProblemStatementMarkdown = Pattern.compile("\\[task]\\[(?<name>[^\\[\\]]+)]\\((?<tests>.*)\\)");
+    private static final Pattern TASK_PATTERN = Pattern
+            .compile("\\[task]\\[(?<name>[^\\[\\]]+)]\\((?<tests>(?:[^(),]+(?:\\([^()]*\\)[^(),]*)?(?:,[^(),]+(?:\\([^()]*\\)[^(),]*)?)*)?)\\)");
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:49]: `[^(),]+` includes spaces, so the text is still corect (even if spaces are not explicitly looked for)

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 54]
```diff
@@ -233,4 +364,120 @@ else if (currentChar == ')') {
...
+        Matcher matcher = PLANTUML_PATTERN.matcher(problemStatement);
+
+        return matcher.replaceAll(matchResult -> {
+            // matchResult: Full UML diagramg (everything between @startuml and @enduml)
+            String diagram = matchResult.group();
+            Matcher tests = TESTSCOLOR_PATTERN.matcher(diagram);
+            return tests.replaceAll(testsMatchResult -> {
+                // testsMatchResult: one testscolor instance, e.g. testsColor(testAttributes[BubbleSort])
+                String fullMatch = testsMatchResult.group();
+                // group 1: test names, e.g testAttributes[BubbleSort]
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:448]: For UML currently only one test is allowed, I want to change that in the future.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 55]
```diff
@@ -208,4 +252,112 @@ else if (!testMessages.isEmpty()) {
...
+        // Ensure no duplicate TestCase is present: TestCases have to have a unique name per exercise.
+        // Just using the uniqueness property of the set is not enough, as the equals/hash functions
+        // compares test cases by their id.
+        testCasesToSave.removeIf(candidate -> testCasesToSave.stream().filter(testCase -> testCase.getTestName().equalsIgnoreCase(candidate.getTestName())).count() > 1);
+
+        if (!testCasesToSave.isEmpty()) {
+            testCaseRepository.saveAll(testCasesToSave);
+            programmingExerciseTaskService.updateTasksFromProblemStatement(exercise);
+            // Update the test cases in the problem statement.
+            // This handles the case if the problem statement already contains the name of test case
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:305]: no. The method above persists task changes (like a new name or different linked tests), but the call below updates the test names as described.

File: src/main/java/de/tum/in/www1/artemis/domain/Result.java [hunk 56]
```diff
@@ -485,27 +485,59 @@ public void filterSensitiveInformation() {
...
+     * @param exercise             used to check if students can see the test case names
      * @return the new filtered list
      */
-    public List<Feedback> createFilteredFeedbacks(boolean removeHiddenFeedback) {
-        return feedbacks.stream().filter(feedback -> !feedback.isInvisible()).filter(feedback -> !removeHiddenFeedback || !feedback.isAfterDueDate())
+    public List<Feedback> createFilteredFeedbacks(boolean removeHiddenFeedback, Exercise exercise) {
+        var filteredFeedback = feedbacks.stream().filter(feedback -> !feedback.isInvisible()).filter(feedback -> !removeHiddenFeedback || !feedback.isAfterDueDate())
                 .collect(Collectors.toCollection(ArrayList::new));
+
+        if (exercise instanceof ProgrammingExercise programmingExercise && !Boolean.TRUE.equals(programmingExercise.getShowTestNamesToStudents())) {
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/domain/Result.java:532]: this getter returns a Boolean but the underlying variable is a primitive type, can we change the getter and remove the Boolean.TRUE.equals

File: src/main/java/de/tum/in/www1/artemis/repository/ProgrammingSubmissionRepository.java [hunk 57]
```diff
@@ -64,7 +64,7 @@ public interface ProgrammingSubmissionRepository extends JpaRepository<Programmi
     @EntityGraph(type = LOAD, attributePaths = "results")
     Optional<ProgrammingSubmission> findWithEagerResultsById(Long submissionId);
 
-    @EntityGraph(type = LOAD, attributePaths = { "results", "results.feedbacks", "results.assessor" })
+    @EntityGraph(type = LOAD, attributePaths = { "results", "results.feedbacks", "results.feedbacks.testCase", "results.assessor" })
     Optional<ProgrammingSubmission> findWithEagerResultsFeedbacksAssessorById(long submissionId);
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/repository/ProgrammingSubmissionRepository.java:68]: shouldn't we rename the method to reflect that the test cases are also loaded?

File: src/main/java/de/tum/in/www1/artemis/repository/ResultRepository.java [hunk 58]
```diff
@@ -53,22 +54,27 @@ public interface ResultRepository extends JpaRepository<Result, Long> {
...
-                    and rr.participation.exercise.id = :exerciseId
-                    and rr.participation.student.id = r.participation.student.id)
-                and r.participation.exercise.id = :exerciseId
-                and r.participation.student.id IS NOT NULL
-            order by r.completionDate asc
+            SELECT DISTINCT r
+            FROM Result r
+                LEFT JOIN FETCH r.feedbacks f
+                LEFT JOIN FETCH f.testCase
+                LEFT JOIN FETCH f.testCase
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/repository/ResultRepository.java:61]: why do we fetch the test case twice?

File: src/main/java/de/tum/in/www1/artemis/repository/ResultRepository.java [hunk 59]
```diff
@@ -53,22 +54,27 @@ public interface ResultRepository extends JpaRepository<Result, Long> {
...
+            ORDER BY r.completionDate ASC
               """)
     List<Result> findLatestAutomaticResultsWithEagerFeedbacksForExercise(@Param("exerciseId") Long exerciseId);
 
-    @EntityGraph(type = LOAD, attributePaths = "feedbacks")
+    @EntityGraph(type = LOAD, attributePaths = { "feedbacks", "feedbacks.testCase" })
     Optional<Result> findFirstWithFeedbacksByParticipationIdOrderByCompletionDateDesc(Long participationId);
 
-    @EntityGraph(type = LOAD, attributePaths = { "submission", "feedbacks" })
+    @EntityGraph(type = LOAD, attributePaths = { "submission", "feedbacks", "feedbacks.testCase" })
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/repository/ResultRepository.java:77]: update the method name?

File: src/main/java/de/tum/in/www1/artemis/repository/ResultRepository.java [hunk 60]
```diff
@@ -53,22 +54,27 @@ public interface ResultRepository extends JpaRepository<Result, Long> {
...
+                )
+                AND r.participation.exercise.id = :exerciseId
+                AND r.participation.student.id IS NOT NULL
+            ORDER BY r.completionDate ASC
               """)
     List<Result> findLatestAutomaticResultsWithEagerFeedbacksForExercise(@Param("exerciseId") Long exerciseId);
 
-    @EntityGraph(type = LOAD, attributePaths = "feedbacks")
+    @EntityGraph(type = LOAD, attributePaths = { "feedbacks", "feedbacks.testCase" })
     Optional<Result> findFirstWithFeedbacksByParticipationIdOrderByCompletionDateDesc(Long participationId);
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/repository/ResultRepository.java:75]: update the methode name?

File: src/main/java/de/tum/in/www1/artemis/repository/SolutionProgrammingExerciseParticipationRepository.java [hunk 61]
```diff
@@ -30,7 +30,7 @@ default SolutionProgrammingExerciseParticipation findWithEagerResultsAndSubmissi
         return findWithEagerResultsAndSubmissionsByProgrammingExerciseId(exerciseId).orElseThrow(() -> new EntityNotFoundException("ProgrammingExerciseParticipation", exerciseId));
     }
 
-    @EntityGraph(type = LOAD, attributePaths = { "results", "results.feedbacks", "submissions" })
+    @EntityGraph(type = LOAD, attributePaths = { "results", "results.feedbacks", "results.feedbacks.testCase", "submissions" })
     Optional<SolutionProgrammingExerciseParticipation> findWithEagerResultsAndFeedbacksAndSubmissionsByProgrammingExerciseId(Long exerciseId);
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/repository/SolutionProgrammingExerciseParticipationRepository.java:34]: update the method name?

File: src/main/java/de/tum/in/www1/artemis/repository/StudentParticipationRepository.java [hunk 62]
```diff
@@ -158,20 +158,23 @@ Optional<StudentParticipation> findWithEagerLegalSubmissionsByExerciseIdAndStude
             LEFT JOIN FETCH p.submissions s
             LEFT JOIN FETCH s.results r
             LEFT JOIN FETCH r.assessor
-            LEFT JOIN FETCH r.feedbacks
-            WHERE p.exercise.id = :#{#exerciseId}
-            AND p.testRun = :#{#testRun}
+            LEFT JOIN FETCH r.feedbacks f
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/repository/StudentParticipationRepository.java:161]: usually the join fetches are indented compared to the where clause.

File: src/main/java/de/tum/in/www1/artemis/repository/StudentParticipationRepository.java [hunk 63]
```diff
@@ -158,20 +158,23 @@ Optional<StudentParticipation> findWithEagerLegalSubmissionsByExerciseIdAndStude
...
+            LEFT JOIN FETCH f.testCase
+            WHERE p.exercise.id = :exerciseId
+            AND p.testRun = :testRun
             """)
     List<StudentParticipation> findByExerciseIdAndTestRunWithEagerSubmissionsResultAssessorFeedbacks(@Param("exerciseId") Long exerciseId, @Param("testRun") boolean testRun);
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/repository/StudentParticipationRepository.java:166]: Does the order matter here?
If not, a set might be more efficient. If the order mattters we should probably enforce the order using order by

File: src/main/java/de/tum/in/www1/artemis/repository/StudentParticipationRepository.java [hunk 64]
```diff
@@ -158,20 +158,23 @@ Optional<StudentParticipation> findWithEagerLegalSubmissionsByExerciseIdAndStude
...
+            FROM StudentParticipation p
+                LEFT JOIN FETCH p.submissions s
+                LEFT JOIN FETCH s.results r
+                LEFT JOIN FETCH r.feedbacks f
+                LEFT JOIN FETCH f.testCase
+            WHERE p.exercise.id = :exerciseId
+                AND p.student.id = :studentId
+                AND p.testRun = :testRun
             """)
     Optional<StudentParticipation> findByExerciseIdAndStudentIdAndTestRunWithEagerSubmissionsResultsFeedbacks(@Param("exerciseId") Long exerciseId,
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/repository/StudentParticipationRepository.java:179]: update the method name?

File: src/main/java/de/tum/in/www1/artemis/repository/StudentParticipationRepository.java [hunk 65]
```diff
@@ -219,14 +222,16 @@ Set<StudentParticipation> findByExerciseIdAndTestRunWithEagerLegalSubmissionsAnd
...
+            SELECT DISTINCT p
+            FROM StudentParticipation p
+                LEFT JOIN FETCH p.results r
+                LEFT JOIN FETCH r.feedbacks f
+                LEFT JOIN FETCH f.testCase
+                LEFT JOIN FETCH r.submission s
+            WHERE p.exercise.id = :exerciseId
+                AND (r.id = (SELECT max(pr.id) FROM p.results pr
+                    LEFT JOIN pr.submission prs
+                    WHERE pr.assessmentType = 'AUTOMATIC' AND (prs.type <> 'ILLEGAL' OR prs.type IS NULL)))
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/repository/StudentParticipationRepository.java:234]: update the method name?

File: src/main/java/de/tum/in/www1/artemis/repository/StudentParticipationRepository.java [hunk 66]
```diff
@@ -241,26 +246,30 @@ default List<StudentParticipation> findByExerciseIdWithLatestAutomaticResultAndF
...
+                LEFT JOIN FETCH p.results r
+                LEFT JOIN FETCH r.feedbacks f
+                LEFT JOIN FETCH f.testCase
+                LEFT JOIN FETCH r.submission s
+            WHERE p.id = :participationId
+                AND (r.id = (SELECT max(pr.id) FROM p.results pr
+                    LEFT JOIN pr.submission prs
+                    WHERE pr.assessmentType = 'AUTOMATIC' AND (prs.type <> 'ILLEGAL' OR prs.type IS NULL)))
             """)
     Optional<StudentParticipation> findByIdWithLatestAutomaticResultAndFeedbacks(@Param("participationId") Long participationId);
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/repository/StudentParticipationRepository.java:260]: update the method name?

File: src/main/java/de/tum/in/www1/artemis/service/export/ProgrammingExerciseExportService.java [hunk 67]
```diff
@@ -141,14 +145,22 @@ private Path exportProgrammingExerciseMaterialWithStudentReposOptional(Programmi
...
         // Add problem statement as .md file
-        super.exportProblemStatementAndEmbeddedFilesAndExerciseDetails(exercise, exportErrors, exportDir.orElseThrow(), pathsToBeZipped);
+        exportProblemStatementAndEmbeddedFilesAndExerciseDetails(exercise, exportErrors, exportDir.orElseThrow(), pathsToBeZipped);
 
         return exportDir.orElseThrow();
     }
 
+    @Override
+    void exportProblemStatementAndEmbeddedFilesAndExerciseDetails(Exercise exercise, List<String> exportErrors, Path exportDir, List<Path> pathsToBeZipped) throws IOException {
+        if (exercise instanceof ProgrammingExercise programmingExercise) {
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/service/export/ProgrammingExerciseExportService.java:158]: shouldn't this if condition always be fulfilled?
but I think it's fine because otherwise one has to directly cast to a PE.
since you override the method, some javadoc would be nice.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 68]
```diff
@@ -15,9 +16,17 @@
...
+import de.tum.in.www1.artemis.repository.ProgrammingExerciseRepository;
+import de.tum.in.www1.artemis.repository.ProgrammingExerciseTestCaseRepository;
 import de.tum.in.www1.artemis.service.ProfileService;
+import de.tum.in.www1.artemis.service.WebsocketMessagingService;
+import de.tum.in.www1.artemis.service.dto.AbstractBuildResultNotificationDTO;
 import de.tum.in.www1.artemis.service.dto.StaticCodeAnalysisReportDTO;
+import de.tum.in.www1.artemis.service.hestia.ProgrammingExerciseTaskService;
 
 @Service
 public class ProgrammingExerciseFeedbackCreationService {
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:32]: some javadoc would be nice.

File: src/main/java/de/tum/in/www1/artemis/web/rest/dto/ResultDTO.java [hunk 69]
```diff
@@ -21,16 +22,27 @@ public record ResultDTO(Long id, ZonedDateTime completionDate, Boolean successfu
...
-            return new FeedbackDTO(feedback.getText(), feedback.getDetailText(), feedback.getHasLongFeedbackText(), feedback.getReference(), feedback.getCredits(),
-                    feedback.isPositive(), feedback.getType(), feedback.getVisibility());
+            return new FeedbackDTO(feedback.getId(), feedback.getText(), feedback.getDetailText(), feedback.getHasLongFeedbackText(), feedback.getReference(),
+                    feedback.getCredits(), feedback.isPositive(), feedback.getType(), feedback.getVisibility(), TestCaseDTO.of(feedback.getTestCase()));
 
         }
     }
 
+    @JsonInclude(JsonInclude.Include.NON_EMPTY)
+    public record TestCaseDTO(String testName, Long id) {
```
Comment (tobias-lippert) [inline src/main/java/de/tum/in/www1/artemis/web/rest/dto/ResultDTO.java:36]: to be consistent with the dto above, some javadoc would be nice.

**Review by tobias-lippert — COMMENTED** [review]
Code looks good, I just have a few questions.

File: src/main/java/de/tum/in/www1/artemis/service/export/ProgrammingExerciseExportService.java (hunk 67 above)
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/export/ProgrammingExerciseExportService.java:158]: Yes, it should always be fulfilled, but I wanted to avoid the unchecked cast.

File: src/main/java/de/tum/in/www1/artemis/config/migration/entries/MigrationEntry20230810_150000.java (hunk 50 above)
[the remark this answers is not in the document]
Comment (julian-christl) [reply src/main/java/de/tum/in/www1/artemis/config/migration/entries/MigrationEntry20230810_150000.java:48]: Whoopsie. Well ^^ 
It's the migration anyway, so not a big issue.

File: src/main/java/de/tum/in/www1/artemis/config/migration/MigrationRegistry.java (hunk 49 above)
[the remark this answers is not in the document]
Comment (julian-christl) [reply src/main/java/de/tum/in/www1/artemis/config/migration/MigrationRegistry.java:34]: Mhh. tbf I intended this to ensure a logical sorting. If one create the entry a long time ago, that obviously doesn't make much sense then. But as long as you don't rely on the other migration changes, I guess it doesn't really matter.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java (hunk 53 above)
[the remark this answers is not in the document]
Comment (julian-christl) [reply src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:49]: Ah, my bad. I didn't realise the negative matching and were just looking for \s. Thanks.

File: src/main/java/de/tum/in/www1/artemis/domain/Result.java (hunk 56 above)
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/domain/Result.java:532]: but the table column is nullable... I'll just keep that for now, maybe we can migrate a for of these Boolean-Attributes in a followup.

File: src/main/java/de/tum/in/www1/artemis/web/rest/dto/ResultDTO.java (hunk 69 above)
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/web/rest/dto/ResultDTO.java:36]: I don't have any javadoc for any of these inner classes and I also don't see any useful information to be included here.

File: src/main/webapp/app/exercises/programming/manage/instructions-editor/analysis/programming-exercise-instruction-analysis.service.ts (hunk 52 above)
[the remark this answers is not in the document]
Comment (julian-christl) [reply src/main/webapp/app/exercises/programming/manage/instructions-editor/analysis/programming-exercise-instruction-analysis.service.ts:101]: That makes sense. Could you add this under the return? Otherwise, in the future, a developer will just re-add it.

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 70]
```diff
@@ -208,4 +252,112 @@ else if (!testMessages.isEmpty()) {
...
+        return false;
+    }
+
+    private Set<ProgrammingExerciseTestCase> getTestCasesWithUpdatedActivation(Set<ProgrammingExerciseTestCase> existingTestCases,
+            Set<ProgrammingExerciseTestCase> testCasesFromFeedbacks) {
+        // We compare the new generated test cases from feedback with the existing test cases from the database
+        return existingTestCases.stream().filter(existing -> {
+            Optional<ProgrammingExerciseTestCase> matchingTestCase = testCasesFromFeedbacks.stream().filter(existing::isSameTestCase).findFirst();
+            // Either the test case was active and is not part of the feedback anymore OR was not active before and is now part of the feedback again.
+            return (matchingTestCase.isEmpty() && existing.isActive()) || (matchingTestCase.isPresent() && matchingTestCase.get().isActive() && !existing.isActive());
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java]: That case needs to be updated and also gets updated. Either a test is no longer present (active -> non active) or was inactive and is now again present in the build result.

[the remark this answers is not in the document]
Comment (julian-christl) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java]: So `matchingTestCase.isPresent() && !matchingTestCase.get().isActive()` will always resolve to false?

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 71]
```diff
@@ -208,4 +246,116 @@ else if (!testMessages.isEmpty()) {
...
+        return existingTestCases.stream().filter(existing -> {
+            Optional<ProgrammingExerciseTestCase> matchingTestCase = testCasesFromFeedbacks.stream().filter(existing::isSameTestCase).findFirst();
+            // Either the test case was active and is not part of the feedback anymore
+            boolean existingTestCaseRemoved = matchingTestCase.isEmpty() && existing.isActive();
+            // OR was not active before and is now part of the feedback again.
+            boolean inactiveTestReactivated = matchingTestCase.isPresent() && matchingTestCase.get().isActive() && !existing.isActive();
+            return existingTestCaseRemoved || inactiveTestReactivated;
+        }).map(existing -> existing.clone().active(!existing.isActive())).collect(Collectors.toSet());
+        // If an existing test gets reactivated, we reuse its grading settings (weight, visibility, etc.).
+        // The instructor should not need to enter these settings again.
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:324]: Spotless adds this indention then which does not look good imo: 
grafik

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java (hunk 70 above)
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java]: oh, I see where the confusion comes from. `matchingTestCase.get().isActive()` does not need to be checked, this will always be true when the test is part of the solution feedback.
grafik

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 72]
```diff
@@ -208,4 +252,112 @@ else if (!testMessages.isEmpty()) {
...
+    /**
+     * From a list of build run feedback, extract all test cases. If an already stored test case is not found anymore in the build result, it will not be deleted, but set inactive.
+     * This way old test cases are not lost, some interfaces in the client might need this information e.g. to show warnings.
+     * This also allows saving a grading configuration when testcases get temporaily removed, e.g. during an exam.
+     *
+     * @param buildResult the build result with all the test cases.
+     * @param exercise    programming exercise.
+     * @return Returns true if the test cases have changed, false if they haven't.
+     */
+    public boolean generateTestCasesFromBuildResult(AbstractBuildResultNotificationDTO buildResult, ProgrammingExercise exercise) {
```
[the remark this answers is not in the document]
Comment (Strohgelaender) [reply src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:277]: I just moved this method from one place to another. The best other name I can think of is `generateTestCasesFromBuildResultAndCheckIfTestsChanged` which imo does not sound good and is quite long.
Also its current usage is: `boolean haveTestCasesChanged = generateTestCasesFromBuildResult(buildResult, exercise);` I think that makes it quite clear.

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 73]
```diff
@@ -184,13 +223,49 @@ private List<ProgrammingExerciseTask> extractTasks(ProgrammingExercise exercise)
             var testCaseNames = extractTestCaseNames(capturedTestCaseNames);
 
             for (String testName : testCaseNames) {
```
Comment (julian-christl) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:225]: To solve the Teamscale warning which correctly points out the many indentations, how about extracting the for loop in a helper method that returns a `List<ProgrammingExerciseTestCase>` which you then can add with `tasks.getTestCases().addAll(...)`

**Review by julian-christl — COMMENTED** [review]
Changes look very good. Went through the codacy and teamscale issues and found one to solve.

**Review by julian-christl — APPROVED** [review]

**Review by tobias-lippert — APPROVED** [review]
Approve Code

**Review by terlan98 — APPROVED** [review]
Tested on TS5. Students do not get any test names in REST calls. The tasks and task status are shown correctly. Editing the problem statement works. Import/export functionality also works 👍

**Review by florian-glombik — DISMISSED** [review]
Tested on ts5 during testing session, did not find issues with the results display.

Tested within regular programming exercises and within an exam programming exercise.
The results were displayed / hidden properly during exams.

**Review by Kroko-fant — DISMISSED** [review]
Tested on ts5 looks good to me

**Review by laurenzfb — DISMISSED** [review]
Tested on TS5. Did not find any issues

**Review by simon-hng — APPROVED** [review]
Tested on TS5. LGTM

**Review by laurenzfb — DISMISSED** [review]
reapprove

**Review by julian-christl — DISMISSED** [review]
Reapprove code

**Review by terlan98 — APPROVED** [review]
Re-tested on TS5 and reapproved

**Review by simon-hng — APPROVED** [review]
Reapprove after merge conflicts

**Review by florian-glombik — DISMISSED** [review]
Re-tested on ts5, worked as described

- the _(automatic)_ feedback was displayer properly when participating in an existing programming exercise
   - the detailText was included but not the title of the test case
   - title of test cases were included if explicitly configured within the exercise
- tested importing a programming exercise within a course
- tested an exam with 1 programming exercise, submitting worked fine, the result was displayed according to the grading settings

**Comment by Strohgelaender** [comment]
Note: This PR is currently blocked by #7347 and #7335.

**Review by simon-hng — APPROVED** [review]
Tested again on TS5. Everything works as it did before. Test names are hidden in all rest calls

**Review by Hialus — CHANGES_REQUESTED** [review]
The recent changes in the migration file break TS5 if this PR is deployed. Since they are not trivial you'll either have to implement them differently, so that the required manual changes to the database are simple or provide me with the SQL statements to make the database work with these changes.

File: src/main/java/de/tum/in/www1/artemis/repository/ExerciseRepository.java [hunk 74]
```diff
@@ -494,12 +494,13 @@ default boolean toggleSecondCorrection(Exercise exercise) {
...
              FROM Course c
-                 LEFT JOIN  c.exercises e
+                 LEFT JOIN c.exercises e
                  LEFT JOIN FETCH e.studentParticipations p
                  LEFT JOIN p.team.students students
                  LEFT JOIN FETCH p.submissions s
                  LEFT JOIN FETCH s.results r
-                 LEFT JOIN FETCH r.feedbacks
+                 LEFT JOIN FETCH r.feedbacks f
+                 LEFT JOIN FETCH f.testCase
```
Comment (pal03377) [inline src/main/java/de/tum/in/www1/artemis/repository/ExerciseRepository.java:503]: The name of the method is outdates (missing `testCase`) with this change.

File: src/main/java/de/tum/in/www1/artemis/service/export/DataExportExerciseCreationService.java [hunk 75]
```diff
@@ -316,7 +316,11 @@ private void createResultsAndComplaintFiles(Submission submission, Path outputDi
                     if (feedback != null) {
                         resultScoreAndFeedbacks.append("- Feedback: ");
 
-                        // null if it's manual feedback
+                        // null if it's manual feedback or if the test name was filtered out above
+                        if (feedback.getTestCase() != null && feedback.getTestCase().getTestName() != null) {
+                            resultScoreAndFeedbacks.append(feedback.getTestCase().getTestName()).append("\t");
+                        }
+                        // e.g the file and line number for programming exercises
```
Comment (pal03377) [inline src/main/java/de/tum/in/www1/artemis/service/export/DataExportExerciseCreationService.java:323]: This comment describes an example of `feedback.getText()` content, right? That was not immediately clear to me. Can you add this information? Something like:
```suggestion
                        // feedback.getText() describes e.g the file and line number for programming exercises
```

File: src/main/java/de/tum/in/www1/artemis/service/export/ProgrammingExerciseExportService.java (hunk 67 above)
Comment (pal03377) [reply src/main/java/de/tum/in/www1/artemis/service/export/ProgrammingExerciseExportService.java:158]: Optional: Add a comment about what you explained here? Otherwise, this info gets lost a bit 🤔

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 76]
```diff
@@ -233,4 +312,193 @@ else if (currentChar == ')') {
...
+
+    /**
+     * Prepares a saved problem statement (with test ids) for editors.
+     * Replaces the test ids with test names.
+     * The problem statement of the passed exercise gets changed, but the result does not get saved.
+     *
+     * @param exercise The exercise where its problem statement is updated
+     */
+    public void replaceTestIdsWithNames(ProgrammingExercise exercise) {
+        // Also replace inactive test cases; don't send any testids (e.g. ids referring to previoulsy active test cases) to the editor.
```
Comment (pal03377) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:342]:
```suggestion
        // Also replace inactive test cases; don't send any testids (e.g. ids referring to previously active test cases) to the editor.
```

**Review by pal03377 — COMMENTED** [review]
I re-reviewed the code parts that changed since my last review.
Note that I don't have a full overview and it's quite complex, but everything I fully understood looks good 👍 

Note for manual testers: It might be interesting to also test to re-evaluate an exercise.

File: src/main/java/de/tum/in/www1/artemis/domain/Result.java [hunk 77]
```diff
@@ -485,27 +485,59 @@ public void filterSensitiveInformation() {
...
      */
     public void filterSensitiveFeedbacks(boolean removeHiddenFeedback) {
-        var filteredFeedback = createFilteredFeedbacks(removeHiddenFeedback);
+        filterSensitiveFeedbacks(removeHiddenFeedback, participation.getExercise());
+    }
+
+    /**
+     * Removes all feedback details that should not be passed to the student.
+     *
+     * @param removeHiddenFeedback if feedbacks marked with visibility 'after due date' should also be removed.
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/domain/Result.java:494]:
```suggestion
     * @param removeHiddenFeedback true if feedbacks marked with visibility 'after due date' should also be removed.
```

File: src/main/java/de/tum/in/www1/artemis/domain/Result.java [hunk 78]
```diff
@@ -485,27 +485,59 @@ public void filterSensitiveInformation() {
...
     }
 
     /**
      * Returns a new list that only contains feedback that should be passed to the student.
      * Does not change the feedbacks attribute of this entity.
+     * Also removes the test names from all feedback if it should not be shown to the student.
      *
      * @see ResultDTO
      *
      * @param removeHiddenFeedback if feedbacks marked with visibility 'after due date' should also be removed.
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/domain/Result.java:524]:
```suggestion
     * @param removeHiddenFeedback true if feedbacks marked with visibility 'after due date' should also be removed.
```

File: src/main/java/de/tum/in/www1/artemis/service/export/DataExportExerciseCreationService.java [hunk 79]
```diff
@@ -316,11 +316,16 @@ private void createResultsAndComplaintFiles(Submission submission, Path outputDi
                     if (feedback != null) {
                         resultScoreAndFeedbacks.append("- Feedback: ");
 
-                        // null if it's manual feedback
+                        // getTestCase() is null if it's manual feedback or if the test name was filtered out above
+                        if (feedback.getTestCase() != null && feedback.getTestCase().getTestName() != null) {
+                            resultScoreAndFeedbacks.append(feedback.getTestCase().getTestName()).append("\t");
+                        }
+                        // getText() contains e.g. the file and line number for programming exercises
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/export/DataExportExerciseCreationService.java:323]:
```suggestion
                        // getText() contains, e.g., the file and line number for programming exercises
```

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 80]
```diff
@@ -181,16 +220,53 @@ private List<ProgrammingExerciseTask> extractTasks(ProgrammingExercise exercise)
...
+            return testCases.stream().filter(tc -> tc.getId().equals(id)).findFirst();
+        }
+        else {
+            return testCases.stream().filter(tc -> tc.getTestName().equals(testName)).findFirst();
+        }
+    }
+
+    /**
+     * Finds the test case id wrapped into a <testid></testid> text.
+     * Returns null if the text does not reference a testid, but is e.g. a name instead.
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:244]:
```suggestion
     * Returns null if the text does not reference a testid, but is, e.g., a name instead.
```

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 81]
```diff
@@ -233,4 +312,193 @@ else if (currentChar == ')') {
...
+        var capturedTestIds = extractTestCaseNames(capturedTestCaseIds);
+
+        return capturedTestIds.stream().map(tc -> convertTestIdToTestName(tc, testCases)).collect(Collectors.joining(","));
+    }
+
+    private String convertTestIdToTestName(String testId, Set<ProgrammingExerciseTestCase> testCases) {
+        Long id = extractTestId(testId);
+
+        if (id == null) {
+            // no matching test case e.d. due to a typo, leave it as it is
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:357]:
```suggestion
            // no matching test case, e.g., due to a typo, leave it as it is
```

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 82]
```diff
@@ -233,4 +312,193 @@ else if (currentChar == ')') {
...
+     */
+    public void replaceTestNamesWithIds(ProgrammingExercise exercise) {
+        // Only replace active test cases (tests that actually exist in the repository).
+        // The other test cases will get replaced as soon as they get active.
+        replaceInProblemStatement(exercise, this::extractTestCaseIdReplacementsFromNames, true);
+    }
+
+    /**
+     * Replaces a comma separated list of test case names with their corresponding id replacement.
+     * If no matching test case exists (e.g. due to a typo), we keep the test name.
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:388]:
```suggestion
     * We keep the test name if no matching test case exists (e.g. due to a typo).
```

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 83]
```diff
@@ -233,4 +312,193 @@ else if (currentChar == ')') {
...
+        exercise.setProblemStatement(problemStatement);
+    }
+
+    /**
+     * Looks for all tasks in the given problem statement, and replaces its mentioned test cases using the given replacer method.
+     * Replacer methods are e.g. {@link ProgrammingExerciseTaskService#extractTestCaseIdReplacementsFromNames(String, Set)}
+     * or {@link ProgrammingExerciseTaskService#extractTestNamesFromTestIds(String, Set)}.
+     *
+     * @param problemStatement the problem statement to replace the tasks
+     * @param testCases        all test cases of the exercise, used to look up the new value to use
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:427]:
```suggestion
     * Looks for all tasks in the given problem statement and replaces its mentioned test cases using the given replacer method.
     * Replacer methods are, e.g., {@link ProgrammingExerciseTaskService#extractTestCaseIdReplacementsFromNames(String, Set)}
     * or {@link ProgrammingExerciseTaskService#extractTestNamesFromTestIds(String, Set)}.
     *
     * @param problemStatement the problem statement to replace the tasks
     * @param testCases        all test cases of the exercise used to look up the new value to use
```

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 84]
```diff
@@ -233,4 +312,193 @@ else if (currentChar == ')') {
...
+     * @param replacer         the replacer method that gets executed when a test case gets found
+     * @return the new problem statement
+     */
+    private String replaceTaskTests(String problemStatement, Set<ProgrammingExerciseTestCase> testCases, BiFunction<String, Set<ProgrammingExerciseTestCase>, String> replacer) {
+        Matcher matcher = TASK_PATTERN.matcher(problemStatement);
+
+        return matcher.replaceAll(matchResult -> {
+            // matchResult is fa full task, e.g. [task][Bubble Sort](testBubbleSort,testClass[BubbleSort])
+            String fullMatch = matchResult.group();
+            // group 1: task name, group 2: test names. e.g testBubbleSort,testClass[BubbleSort]
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:437]:
```suggestion
            // group 1: task name, group 2: test names. E.g., testBubbleSort,testClass[BubbleSort]
```

File: src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java [hunk 85]
```diff
@@ -233,4 +312,193 @@ else if (currentChar == ')') {
...
+            String testIds = replacer.apply(testNames, testCases);
+
+            // replace the names with their ids
+            return fullMatch.replace(testNames, testIds);
+        });
+    }
+
+    /**
+     * Looks for all test cases integrated into plantuml diagrams in the given problem statement, and replaces its test case using the given replacer method.
+     * Replacer methods are e.g. {@link ProgrammingExerciseTaskService#extractTestCaseIdReplacementsFromNames(String, Set)}
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/hestia/ProgrammingExerciseTaskService.java:450]:
```suggestion
     * Replacer methods are, e.g., {@link ProgrammingExerciseTaskService#extractTestCaseIdReplacementsFromNames(String, Set)}
```

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 86]
```diff
@@ -178,21 +210,30 @@ public List<Feedback> createFeedbackFromStaticCodeAnalysisReports(List<StaticCod
...
      * Create an automatic feedback object from a test job.
      *
-     * @param testName            the test case name.
-     * @param testMessages        a list of informational messages generated by the test job
-     * @param successful          if the test case was successful.
-     * @param programmingLanguage the programming language of the exercise.
-     * @param projectType         the project type of the exercise.
+     * @param testName        the test case name.
+     * @param testMessages    a list of informational messages generated by the test job
+     * @param successful      if the test case was successful.
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:215]:
```suggestion
     * @param successful      true if the test case was successful.
```

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 87]
```diff
@@ -178,21 +210,30 @@ public List<Feedback> createFeedbackFromStaticCodeAnalysisReports(List<StaticCod
...
+            Set<ProgrammingExerciseTestCase> activeTestCases) {
         Feedback feedback = new Feedback();
-        feedback.setText(testName);
+        var testCase = activeTestCases.stream().filter(test -> testName.equals(test.getTestName())).findAny();
+        if (testCase.isPresent()) {
+            feedback.setTestCase(testCase.get());
+        }
+        else {
+            // This feedback was created by a test which is not known to Artemis (not part of the solution result)
+            // Feedback like this does not get displayed to students. (see ProgrammingExerciseGradingService#filterAutomaticFeedbacksWithoutTestCase
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:230]:
```suggestion
            // Feedback like this does not get displayed to students, see ProgrammingExerciseGradingService#filterAutomaticFeedbacksWithoutTestCase.
```

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 88]
```diff
@@ -208,4 +249,116 @@ else if (!testMessages.isEmpty()) {
...
+            // Notify the client about the updated testCases
+            Set<ProgrammingExerciseTestCase> testCases = testCaseRepository.findByExerciseId(exercise.getId());
+            websocketMessagingService.sendMessage("/topic/programming-exercises/" + exercise.getId() + "/test-cases", testCases);
+        }
+    }
+
+    /**
+     * From a list of build run feedback, extract all test cases. If an already stored test case is not found anymore in the build result, it will not be deleted, but set inactive.
+     * This way old test cases are not lost, some interfaces in the client might need this information e.g. to show warnings.
+     * This also allows saving a grading configuration when testcases get temporaily removed, e.g. during an exam.
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:271]:
```suggestion
     * This way old test cases are not lost, some interfaces in the client might need this information, e.g., to show warnings.
     * This also allows saving a grading configuration when testcases get temporaily removed, e.g., during an exam.
```

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java [hunk 89]
```diff
@@ -208,4 +249,116 @@ else if (!testMessages.isEmpty()) {
...
+        }).map(existing -> existing.clone().active(!existing.isActive())).collect(Collectors.toSet());
+        // If an existing test gets reactivated, we reuse its grading settings (weight, visibility, etc.).
+        // The user should not need to enter these settings again.
+    }
+
+    /**
+     * Sets the enum value test case type for every test case and saves to the database. Implicitly, all tests are of the same programming language.
+     * If the test cases belong to a non-JAVA programming exercise, the type is set to DEFAULT.
+     * If the test case belong to a JAVA programming exercise, the type is set to:
+     * STRUCTURAL: test case has been generated by the structure oracle, therefore it's name follows a certain pattern.
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseFeedbackCreationService.java:331]:
```suggestion
     * STRUCTURAL: test case has been generated by the structure oracle, therefore its name follows a certain pattern.
```

File: src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseGradingService.java [hunk 90]
```diff
@@ -668,28 +652,28 @@ private void addFeedbackTestsNotExecuted(final Result result, final ProgrammingE
     }
 
     /**
-     * Only keeps automatic feedbacks that also are associated with a test case.
+     * Only keeps automatic feedbacks that also are associated with a relevant test case.
+     * Used to remove feedbacks that are e.g. related to test cases with visibility = never.
```
Comment (nityanandaz) [inline src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseGradingService.java:656]:
```suggestion
     * Used to remove feedbacks that are, e.g., related to test cases with visibility = never.
```

**Review by nityanandaz — COMMENTED** [review]
Code looks good; minor suggestions

**Review by pal03377 — APPROVED** [review]
My comments have been addressed and the most recent code changes lgtm 👍

File: src/main/resources/config/liquibase/changelog/20230810100000_changelog.xml [hunk 91]
```diff
@@ -0,0 +1,231 @@
...
+            WHERE feedback.id = fe.id
+                AND programming_exercise_test_case.test_name = feedback.text
+                AND programming_exercise_test_case.exercise_id = fe.exercise_id
+        </sql>
+
+    </changeSet>
+    <changeSet author="welscher" id="20230810100000-22">
+        <!-- Postgres -->
+        <preConditions onFail="CONTINUE">
+            <dbms type="postgres"/>
```
Comment (b-fein) [inline src/main/resources/config/liquibase/changelog/20230810100000_changelog.xml:55]:
```suggestion
            <dbms type="postgresql"/>
```
same for others below.

**Review by b-fein — CHANGES_REQUESTED** [review]
Liquibase Migrations are not executed in PostgreSQL setup.
`DBMS Precondition failed: expected postgres, got postgresql`

**Review by b-fein — APPROVED** [review]
Migration works now in systems using a PostgreSQL database.
Both existing and new programming exercises work after the migration was applied.
