### PR TITLE
`Iris`: Fix an issue on course management overview page for tutors and editors

### LINKED ISSUE #10738: Overview page not working for editors and tutors
### Describe the bug

I was testing #10714 and stumbled upon the bug. I logged in with test user 15 and test user 10 (editor and tutor, respectively), but couldn't access the overview page. 

Image
Image

This was the error message on the console

Image

### To Reproduce

1. Go to any course
2. Click on the Overview page as a tutor or editor
3. See error

### Expected behavior

As described in the PR itself, editor and tutor should also be able to access the Overview page

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

8.0.0

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

I used Brave. I also tested using Chrome but still the same error

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by tobias-lippert**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

Closes #10738 

### Description

The Iris settings REST call should only happen when the user is at least instructor as the resource only allows instructor access and it's unnecessary for tutors and editors.

### Steps for Testing

Prerequisites:
- 1 Tutor/Editor
- 1 TS with Iris enabled
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Open a course
4. Go to the overview page
5. Make sure that no error occurs when opening the page
6. Optional: Check the network tab that no 403 occurs.
7. As instructor do the same as above but check in the network tab that the REST call to `global-iris-settings` still happens

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved the initialization of IRIS chat settings to ensure they are only fetched when course data is available and the user has at least instructor permissions.

- **Tests**
  - Enhanced test coverage for conditional IRIS settings retrieval based on user roles and active profiles.
  - Refactored test setup for more dynamic and accurate simulation of route data and permissions.

### CODE REVIEW

File: src/main/webapp/app/core/course/manage/detail/course-detail.component.ts [hunk 1]
```diff
@@ -93,17 +93,19 @@ export class CourseDetailComponent implements OnInit, OnDestroy {
...
                 this.course = course;
                 this.messagingEnabled = !!this.course.courseInformationSharingConfiguration?.includes('MESSAGING');
                 this.communicationEnabled = !!this.course.courseInformationSharingConfiguration?.includes('COMMUNICATION');
                 this.fetchOrganizations(course.id);
+
+                if (this.irisEnabled && course.isAtLeastInstructor) {
+                    const irisSettings = await firstValueFrom(this.irisSettingsService.getGlobalSettings());
+                    // TODO: Outdated, as we now have a bunch more sub settings
+                    this.irisChatEnabled = irisSettings?.irisChatSettings?.enabled ?? false;
+                }
```
Comment (florian-glombik) [inline src/main/webapp/app/core/course/manage/detail/course-detail.component.ts:108]: Why are we doing this inside the subscription? Can't we do that outside of the subscription?

**Review by florian-glombik — CHANGES_REQUESTED** [review]

**Review by florian-glombik — APPROVED** [review]
Code

**Review by AjayvirS — APPROVED** [review]
Tested on TS5 and no error occurs as tutor and the globa-iris-settings call is successfully made as instructor

**Review by FelberMartin — APPROVED** [review]
Tested for both Tutor and instructor on TS5, no error or 403 appeared, and the global-iris-settings call was there for instructors

**Review by krusche — APPROVED** [review]
