### PR TITLE
Enhancement/programming exercise/dynamically build build plan links

### LINKED ISSUE #1184: Hardcoded Bamboo link always shown for build plans
### Describe the bug

In the client, we have a hardcoded URL link for the build plans of all participations. Since we now have Jenkins as an alternative, we need to generate this link dynamically, e.g. by passing some template URL in the /info endpoint.

#### To Reproduce

0. Use the Jenkins+GitLab Testserver
1. Go to the exercises overview for a course
2. Click on any build plan link for a programming exercise
3. You should get directed to the LS1 Bamboo

#### Expected behavior

You should get routed to the Jenkins instance

### PR DESCRIPTION
**Pull request by ungaralex**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Client: I added multiple integration tests (Jest) related to the features
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation and Context

Fixes #1184 

We currently have hardcode the links to the build plans of programming exercises in all components. This is far from optimal and especially problematic with the new Jenkins CI alternative.

### Description

I added a new directive `build-plan-link.directive.ts` that adds the appropriate attributes to its host component. The link gets created dynamically based on the value provided by the profile service, which in turn gets the link template from the call to the `/info` actuator endpoint.

### Steps for Testing

1. Log in to Artemis
2. Check the build plan links on the following pages
3. Programming exercise details
4. Course overvice
5. Exercise scores page
6. Exercise participation list

### CODE REVIEW

File: src/main/webapp/app/scores/exercise-scores.component.ts [hunk 1]
```diff
@@ -163,8 +168,18 @@ export class ExerciseScoresComponent implements OnInit, OnDestroy {
     }
 
     goToBuildPlan(result: Result) {
-        // TODO: get the continuous integration URL as a client constant during the management info call
-        window.open('https://bamboobruegge.in.tum.de/browse/' + (result.participation! as ProgrammingExerciseStudentParticipation).buildPlanId);
+        const planId = (result.participation! as ProgrammingExerciseStudentParticipation).buildPlanId;
+        const projectKey = (this.exercise as ProgrammingExercise).projectKey!;
+        this.profileService
```
Comment (krusche) [inline src/main/webapp/app/scores/exercise-scores.component.ts]: This looks really really complicated. Can we not achieve this in an easier way?

File: src/main/webapp/app/overview/exercise-details/course-exercise-details.component.ts [hunk 2]
```diff
@@ -283,7 +288,17 @@ export class CourseExerciseDetailsComponent implements OnInit, OnDestroy {
     }
 
     goToBuildPlan(participation: Participation) {
-        // TODO: get the continuous integration URL as a client constant during the management info call
-        window.open('https://bamboobruegge.in.tum.de/browse/' + (participation as ProgrammingExerciseStudentParticipation).buildPlanId);
+        const planId = (participation! as ProgrammingExerciseStudentParticipation).buildPlanId;
+        const projectKey = (this.exercise as ProgrammingExercise).projectKey!;
+        this.profileService
```
Comment (krusche) [inline src/main/webapp/app/overview/exercise-details/course-exercise-details.component.ts]: this is quite some duplicated code (see below)

File: src/main/webapp/app/scores/exercise-scores.component.ts (hunk 1 above)
Comment (ungaralex) [reply src/main/webapp/app/scores/exercise-scores.component.ts]: I moved the code to a new directive `build-plan-button.directive.ts`, so that the components only have to provide the projectKey and buildPlanId.

**Comment by ungaralex** [comment]
> Thanks for working on this. Please simplify the code needed for opening the link (it's too much duplicated code) and double check that the profile info call is only made once in the client.
> 
> Also search for https://bamboobruegge.in.tum.de in the code, we use the hard coded value more often.

- @krusche I couldn't find any more occurences of the hardcoded String, did I miss something?
- The `/info` call gets handled by the `ProfileService`, which only calls this once during initialization and then always returns the cached value.
