### PR TITLE
`Development`: Fix an issue with duplicated notification recipients in Bamboo

### LINKED ISSUE #7227: Programming Exercises: Result Generation for Existing Programming Exercises Is Broken
Since the maintenance work over night (update to 6.5.0, presumably), existing programming exercises variously generate incorrect and/or duplicate results. I'll try to describe the issue as best I can, but as I don't have reproduction, I would appreciate some pointers for investigating this issue further.

For a given programming exercise, here's what I've been able to observe:
- The build in the underlying CI system (Bamboo) completes successfully, and all JUnit test cases are recognized properly.
- In Artemis, the student sees two results. The first result properly contains the test results, while the second shows a "Build Failed"
  image
    - The first result always shows 0% when I've reproduced this (even though all tests passed), but students have sent screenshots with a score of e.g. 85%. The result contains the build log, and properly shows the test results:
      image
    - The second result shows the typical build failure message, but since the build succeeds, there is just some log information:
  image
- From the instructor view (e.g. for the template and sample solution), only the latest result, i.e. the build failure is shown.

### To Reproduce

None, unfortunately. Newly created exercises have no apparent issues.

### Expected Behaviour

A single result, properly showing passed/failed tests, the score, and no build failure message.

### Which version of Artemis are you seeing the problem on?

6.5.0

### What browsers are you seeing the problem on?

Firefox, not browser-specific

### Additional context

All this has been observed only in OCaml exercises. Note that we have modified the configuration of our exercises in Bamboo: the Docker image is a custom one. I can't think of any other modifications. Unfortunately, we have no existing exercises with an unmodified Bamboo configuration to check this issue against.

Additionally, our exercises use the "Sample Solution Checkout" feature, but I can't imagine that being the issue here.

From looking over recent commits, the most relevant I've seen is the one of #6682. That one seems to be live, despite being committed after 6.5.0, but I'm anyway not sure how that would cause this issue.

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [X] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [X] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).
- [X] I documented the Java code using JavaDoc style.

### Motivation and Context

In #6682 we replaced among others the old notification URL with the new one. I only deleted URLs that start with the current domain name to prevent deleting possible manual configurations. However, due to the domain name change at TUM we now have several duplicated notification configurations. This also fixes #7227.

### Description

I copied the previous Migration and deleted anything not related to the issue at hand. I did not do any additional cleanup as it's a pressing issue and only a migration.
I then removed the conditional on the domain name from the Bamboo migration service and made sure to only run the migration on Bamboo as we don't have the issue on other CI services.

The behaviour is basically:
- If we find the correct notification URL, we delete all other notification URLs
- If we don't find the correct notification URL, we delete all and add the correct one.

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/config/migration/entries/MigrationEntry20230920_181600.java [hunk 1]
```diff
@@ -0,0 +1,356 @@
...
+
+    private final CopyOnWriteArrayList<ProgrammingExerciseParticipation> errorList = new CopyOnWriteArrayList<>();
+
+    private static final List<String> MIGRATABLE_PROFILES = List.of("bamboo");
+
+    public MigrationEntry20230920_181600(ProgrammingExerciseRepository programmingExerciseRepository,
+            SolutionProgrammingExerciseParticipationRepository solutionProgrammingExerciseParticipationRepository,
+            TemplateProgrammingExerciseParticipationRepository templateProgrammingExerciseParticipationRepository,
+            ProgrammingExerciseStudentParticipationRepository programmingExerciseStudentParticipationRepository, AuxiliaryRepositoryRepository auxiliaryRepositoryRepository,
+            Optional<CIVCSMigrationService> ciMigrationService, Optional<VersionControlService> versionControlService, Environment environment) {
```
Comment (MaximilianAnzinger) [inline src/main/java/de/tum/in/www1/artemis/config/migration/entries/MigrationEntry20230920_181600.java:65]: unused: `versionControlService`

**Review by MaximilianAnzinger — CHANGES_REQUESTED** [review]

**Review by lennart-keller — COMMENTED** [review]
Besides the duplicated code in the migration (which is fine) and the requested changes, code lgtm.

**Comment by krusche** [comment]
Tested on TS1 with @maximiliansoelch and the fix works

**Review by krusche — APPROVED** [review]

**Review by maximiliansoelch — APPROVED** [review]
