### PR TITLE
Fix missing scheduling for manually assessed programming exercises

### LINKED ISSUE #1936: Manual assessed programming exercises retain write permissions after due date.
- [`ProgrammingExerciseScheduleService.java` Line 78ff](https://github.com/ls1intum/Artemis/blob/develop/src/main/java/de/tum/in/www1/artemis/service/scheduled/ProgrammingExerciseScheduleService.java#L78) and
- [`ProgrammingExerciseScheduleService.java` Line 101ff](https://github.com/ls1intum/Artemis/blob/develop/src/main/java/de/tum/in/www1/artemis/service/scheduled/ProgrammingExerciseScheduleService.java#L101)

cause (team) programming exercises with manual assement to be open for write access after the due date.
This causes things like this [[EIST 2020 Example]](https://artemis.ase.in.tum.de/#/course-management/48/exercises/1300/participations/362178/submissions) and confuses students (and is problematic for manual assessments).

_We should fix this ASAP._

### PR DESCRIPTION
**Pull request by MaisiKoleni**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I added multiple integration tests (Spring) related to the features
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context
Fix #1936 and refactor and fix some other problems that are mentioned in the TODOs.

### Description
- Rename `scheduleExerciseIfRequired` into `updateScheduling`
- Add database call for programming exercises with manual assessment and due date that lies in the future
- Schedule programming exercises with manual assessment on startup
- Schedule programming exercises with manual assessment when updated
- Fix `TODO: there is small logic error here. [...]`
- Break up code into smaller functions to improve level of abstraction consistency of the methods.
- Add comments to explain the intent behind what is scheduled how and what is not

### Steps for Testing
0. _Best would be to repeat that process with different exercise settings (automatic only, build after due date, manual review, exam)_
1. Create programming exercise
2. Participate (maybe change something)
3. Check that the repository gets locked properly (e.g. over BitBucket) and that tests are run, if that was selected. _(In case the exercise was automatic only, editing and submitting should still be possible)_

What is expected:
- `Run Tests once after Due Date` is set ---> repository should be locked after due date
- `Manual Review` is set ---> repository should be locked after due date
- `otherwise` ---> students can still make changes

### CODE REVIEW

**Comment by krusche** [comment]
Can you please make sure the fixed functionality is addressed in server integration tests?
(These tests should basically fail with the previous version where the manually assessed programming exercises have not fully been taken into account)

File: src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseRepository.java [hunk 1]
```diff
@@ -91,6 +91,15 @@
...
     List<ProgrammingExercise> findAllByBuildAndTestStudentSubmissionsAfterDueDateAfterDate(@Param("dateTime") ZonedDateTime dateTime);
 
+    /**
+     * Returns the programming exercises that have manual assessment enabled and a due date higher than the provided date.
+     *
+     * @param dateTime ZonedDateTime object.
+     * @return List<ProgrammingExercise> (can be empty)
+     */
+    @Query("select pe from ProgrammingExercise pe where pe.assessmentType <> 'AUTOMATIC' and pe.dueDate > :#{#dateTime}")
+    List<ProgrammingExercise> findAllByManualAssessmentAndDueDateAfterDate(@Param("dateTime") ZonedDateTime dateTime);
```
Comment (sleiss) [inline src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseRepository.java:101]: The method name states the we filter by manual assessment, but we filter by `<> 'AUTOMATIC'`. Is there a reason why don't filter by 'MANUAL'?

Comment (MaisiKoleni) [reply src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseRepository.java:101]: Because we use `SEMIAUTOMATIC` for that _currently_. I wanted to be safe here and return all exercises that involve some sort of manual assessment. As far as I can see, `MANUAL` is unused currently for the programming exercises.

File: src/main/java/de/tum/in/www1/artemis/service/scheduled/ProgrammingExerciseScheduleService.java [hunk 2]
```diff
@@ -89,25 +95,38 @@ public void scheduleRunningExercisesOnStartup() {
...
+            cancelAllScheduledTasks(exercise);
             return;
         }
-        // exam exercises are always scheduled, course exercises are only scheduled if buildAndTestStudentSubmissionsAfterDueDate is set and in the future
         scheduleExercise(exercise);
     }
 
+    private static boolean needsToBeScheduled(ProgrammingExercise exercise) {
+        // Exam exercises need to be scheduled
+        if (isExamExercise(exercise))
```
Comment (sleiss) [inline src/main/java/de/tum/in/www1/artemis/service/scheduled/ProgrammingExerciseScheduleService.java:114]: Could you please add brackets to this and the following if statement?

File: src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseRepository.java (hunk 1 above)
Comment (sleiss) [reply src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseRepository.java:101]: Thanks, seems reasonable.

File: src/main/java/de/tum/in/www1/artemis/service/scheduled/ProgrammingExerciseScheduleService.java (hunk 2 above)
Comment (MaisiKoleni) [reply src/main/java/de/tum/in/www1/artemis/service/scheduled/ProgrammingExerciseScheduleService.java]: Yes. Strange that the style tests passed then.

File: src/main/java/de/tum/in/www1/artemis/service/scheduled/ProgrammingExerciseScheduleService.java [hunk 3]
```diff
@@ -123,11 +144,24 @@ private void scheduleExercise(ProgrammingExercise exercise) {
     }
 
     private void scheduleCourseExercise(ProgrammingExercise exercise) {
-        // TODO: there is small logic error here. When build and run test date is after the due date, the lock operation might be executed even if it is not necessary.
-        scheduleService.scheduleTask(exercise, ExerciseLifecycle.DUE, lockAllStudentRepositories(exercise));
-        scheduleService.scheduleTask(exercise, ExerciseLifecycle.BUILD_AND_TEST_AFTER_DUE_DATE, buildAndTestRunnableForExercise(exercise));
-        log.debug("Scheduled build and test for student submissions after due date for Programming Exercise \"" + exercise.getTitle() + "\" (#" + exercise.getId() + ") for "
-                + exercise.getBuildAndTestStudentSubmissionsAfterDueDate() + ".");
+        // For exercises with buildAndTestAfterDueDate or manual assessment
+        if (exercise.getDueDate() != null && ZonedDateTime.now().isBefore(exercise.getDueDate())) {
```
Comment (kloessst) [inline src/main/java/de/tum/in/www1/artemis/service/scheduled/ProgrammingExerciseScheduleService.java:148]: I'm a bit confused, this if clause will lock all programming exercises with a due date in the future but the comment says "For exercises with buildAndTestAfterDueDate or manual assessment"

Comment (MaisiKoleni) [reply src/main/java/de/tum/in/www1/artemis/service/scheduled/ProgrammingExerciseScheduleService.java:148]: This is because `needsToBeScheduled` will only schedule those course exercises. I can improve the comment, though.

File: src/main/java/de/tum/in/www1/artemis/service/scheduled/ProgrammingExerciseScheduleService.java [hunk 4]
```diff
@@ -123,11 +144,24 @@ private void scheduleExercise(ProgrammingExercise exercise) {
     }
 
     private void scheduleCourseExercise(ProgrammingExercise exercise) {
-        // TODO: there is small logic error here. When build and run test date is after the due date, the lock operation might be executed even if it is not necessary.
-        scheduleService.scheduleTask(exercise, ExerciseLifecycle.DUE, lockAllStudentRepositories(exercise));
-        scheduleService.scheduleTask(exercise, ExerciseLifecycle.BUILD_AND_TEST_AFTER_DUE_DATE, buildAndTestRunnableForExercise(exercise));
-        log.debug("Scheduled build and test for student submissions after due date for Programming Exercise \"" + exercise.getTitle() + "\" (#" + exercise.getId() + ") for "
-                + exercise.getBuildAndTestStudentSubmissionsAfterDueDate() + ".");
+        // For exercises with buildAndTestAfterDueDate or manual assessment
```
Comment (MaisiKoleni) [inline src/main/java/de/tum/in/www1/artemis/service/scheduled/ProgrammingExerciseScheduleService.java:147]: @kloessst would that be better?
```suggestion
        // For any exercise that needsToBeScheduled (buildAndTestAfterDueDate and/or manual assessment)
```

Comment (kloessst) [reply src/main/java/de/tum/in/www1/artemis/service/scheduled/ProgrammingExerciseScheduleService.java:147]: That's good. Just wasn't clear for me.

File: src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseRepository.java [hunk 5]
```diff
@@ -91,6 +91,15 @@
     @Query("select pe from ProgrammingExercise pe where pe.buildAndTestStudentSubmissionsAfterDueDate > :#{#dateTime}")
     List<ProgrammingExercise> findAllByBuildAndTestStudentSubmissionsAfterDueDateAfterDate(@Param("dateTime") ZonedDateTime dateTime);
 
+    /**
+     * Returns the programming exercises that have manual assessment enabled and a due date higher than the provided date.
+     *
+     * @param dateTime ZonedDateTime object.
+     * @return List<ProgrammingExercise> (can be empty)
+     */
+    @Query("select pe from ProgrammingExercise pe where pe.assessmentType <> 'AUTOMATIC' and pe.dueDate > :#{#dateTime}")
```
Comment (stefanwaldhauser) [inline src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseRepository.java:100]: This Query will return nothing if `pe.dueDate` is null. Just to confirm @MaisiKoleni , that this is the intended behaviour?

Comment (MaisiKoleni) [reply src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseRepository.java:100]: Yes, programming exercises without due date don't have a due date higher that the passed due date and don't need to be scheduled.

**Comment by stefanwaldhauser** [comment]
Greenshot 2020-07-22 22 35 59
Nice work! Works fine! Tested it with @florian-glombik @fde312
