### PR TITLE
`Exam mode`: Only send student notifications when end time has changed

### LINKED ISSUE #7380: `Exam mode`: Misleading notification when updating exam details
### Describe the bug

When updating the Title of an exam a notification for updated working time is sent to the students.

### To Reproduce

1. Configure an exam 
2. Make sure the exam is visible to students _(exams have been prepared & exercise start aswell)_
3. Change the title of the exam
4. See that the registered students receive a message that the working time would have been updated

### Expected behavior

No notification should be sent

### Screenshots

image

### Which version of Artemis are you seeing the problem on?

6.6.0

### What browsers are you seeing the problem on?

Chrome

### PR DESCRIPTION
**Pull request by aplr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

This PR fixes a bug introduced in #7284. When saving, the code comparing the new and old end date uses `equals`, which always returns `false`. This concern [was already discussed](https://github.com/ls1intum/Artemis/pull/7284#discussion_r1342151543) about in the comments of the PR, however failed to address it properly, and the issue was not found in manual testing.

### Description

This PR now uses the comparator, comparing dates on seconds-precision.

#### Case 1: No date change - no notification

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam

1. Log in to Artemis
2. Navigate to Course Administration
3. Set the exam dates so the exam can be worked on by students
4. Go to exam edit
5. Save the exam, without changing the dates.
6. The students should *NOT* receive a notification

#### Case 2: Date change + notification

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam

1. Log in to Artemis
2. Navigate to Course Administration
3. Set the exam dates so the exam can be worked on by students
4. Go to exam edit
5. Change the end date of the exam
6. Save the exam, without changing the dates.
7. The students *SHOULD* receive a notification

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Comment by aplr** [comment]
TODO:

- [ ] Server: Test if notifications are sent when time was changed
- [ ] Server: Test if no notification is sent when time was not changed
- [ ] Client: E2E test if confirmation pops up when time was changed
- [ ] CLient: E2E test if confirmation does not pop up if no time was changed

**Comment by aplr** [comment]
> Please add a comment why equals cannot be used here.

There's already an explanation a few lines above. Imho, this is sufficient. Tell me if you think otherwise. https://github.com/ls1intum/Artemis/blob/45f33b2fbfbab6ddf9340d050370fb5848d2683f/src/main/java/de/tum/in/www1/artemis/web/rest/ExamResource.java#L222

**Comment by aplr** [comment]
Interesting thing: There _is_ a test for the case, that a exam title is updated, without updating the dates, and no notification should be sent. However, this test just does not work, as the update data is not sent from the frontend, but uses the server-side dates. These dates *of course* match (i.e. `oldDate.equals(newDate)` returns `true`) -> the notification is never sent.

However, if the data is coming from the frontend, the dates do not match w/ `equals`. We have to verify that in the tests.

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java [hunk 1]
```diff
@@ -57,9 +58,10 @@
 import de.tum.in.www1.artemis.web.rest.dto.*;
 import de.tum.in.www1.artemis.web.rest.errors.EntityNotFoundException;
 
+@TestInstance(TestInstance.Lifecycle.PER_CLASS)
```
Comment (aplr) [inline src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:61]: Note: Required by `@BeforeAll`. Implications: The class is not re-created for each test. Please raise your hand if this is not acceptable.

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java [hunk 2]
```diff
@@ -405,26 +453,76 @@ void testUpdateExam_asInstructor() throws Exception {
...
+    void testUpdateExam_failsWithExamIdMismatch() throws Exception {
         // Course id in the updated exam and in the REST resource url do not match -> bad request
-        exam = ExamFactory.generateExam(course1);
+        Exam exam = ExamFactory.generateExam(course1);
         exam.setId(1L);
         request.put("/api/courses/" + course2.getId() + "/exams", exam, HttpStatus.BAD_REQUEST);
+    }
+
+    @ParameterizedTest
+    @MethodSource("provideExamsWithInvalidDates")
```
Comment (aplr) [inline src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:478]: Note: Don't iterate within tests, rather use test data providers.

File: src/test/java/de/tum/in/www1/artemis/exam/ExamUtilService.java [hunk 3]
```diff
@@ -428,6 +428,7 @@ public Exam addExamWithModellingAndTextAndFileUploadAndQuizAndEmptyGroup(Course
 
     public StudentExam addStudentExam(Exam exam) {
         StudentExam studentExam = ExamFactory.generateStudentExam(exam);
+        studentExam.setWorkingTime(exam.getDuration());
```
Comment (aplr) [inline src/test/java/de/tum/in/www1/artemis/exam/ExamUtilService.java:431]: Note: Had to add this so the working time calculation does not throw a `null` pointer. Do you see any problematic implications?

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java [hunk 4]
```diff
@@ -57,9 +58,10 @@
 import de.tum.in.www1.artemis.web.rest.dto.*;
 import de.tum.in.www1.artemis.web.rest.errors.EntityNotFoundException;
 
+@TestInstance(TestInstance.Lifecycle.PER_CLASS)
 class ExamIntegrationTest extends AbstractSpringIntegrationBambooBitbucketJiraTest {
 
-    private static final String TEST_PREFIX = "examintegration";
+    private static final String TEST_PREFIX = "examint";
```
Comment (aplr) [inline src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:64]: Note: Had to shorten the test prefix because of #7391

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java
Comment (aplr) [inline src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:1]: Note: In general, I've ripped some tests apart and created individual tests. This way, it is clearer what is tested, failing cases can be pinned down more easily, and when refactoring, only single test cases have to be touched. Please tell me if you explicitly want these aggregated test cases in Artemis, and this was a design decision.

File: src/test/java/de/tum/in/www1/artemis/util/AbstractArtemisIntegrationTest.java [hunk 5]
```diff
@@ -100,6 +101,9 @@ public abstract class AbstractArtemisIntegrationTest implements MockDelegate {
     @SpyBean
     protected ExamAccessService examAccessService;
 
+    @SpyBean
+    protected ExamLiveEventsService examLiveEventsService;
```
Comment (Strohgelaender) [inline src/test/java/de/tum/in/www1/artemis/util/AbstractArtemisIntegrationTest.java:105]: I don't like this approach. Can you instead verify that the database contains no notifications for the specific exam id?

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java (hunk 1 above)
Comment (Strohgelaender) [reply src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:61]: I like this 👍 I tried to add this change for all tests in general (since creating users seems quite slow, especially on postgres) but this led to problems for some test cases. I think this would be quite a useful test improvement in the future.

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java [hunk 6]
```diff
@@ -296,29 +306,36 @@ void testSaveExamWithExerciseGroupWithExerciseToDatabase() {
 
     @Test
     @WithMockUser(username = TEST_PREFIX + "student1", roles = "USER")
-    void testAll_asStudent() throws Exception {
-        this.testAllPreAuthorize();
+    void testAll_asStudent_shouldNotBeAuthorized() throws Exception {
+        Course course = courseUtilService.addEmptyCourse();
+        Exam exam = examUtilService.addExam(course);
+
+        this.testAllPreAuthorize(course, exam);
```
Comment (Strohgelaender) [inline src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:313]: style, same below
```suggestion
        testAllPreAuthorize(course, exam);
```

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java [hunk 7]
```diff
@@ -328,71 +345,102 @@ void testCreateExam_checkCourseAccess_InstructorNotInCourse_forbidden() throws E
         request.post("/api/courses/" + course1.getId() + "/exams", exam, HttpStatus.FORBIDDEN);
     }
 
+    private List<Exam> provideExamsWithInvalidDates() {
```
Comment (Strohgelaender) [inline src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:348]: Can you move this method next to the test where it is used?

File: src/test/java/de/tum/in/www1/artemis/exam/ExamUtilService.java (hunk 3 above)
Comment (Strohgelaender) [reply src/test/java/de/tum/in/www1/artemis/exam/ExamUtilService.java:431]: 🤔 Are there other (production) cases where the working time could be null?

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java [hunk 8]
```diff
@@ -328,71 +345,102 @@ void testCreateExam_checkCourseAccess_InstructorNotInCourse_forbidden() throws E
...
+        examF.setVisibleDate(examF.getStartDate());
+        // Test for bad request, when exampleSolutionPublicationDate is before the visibleDate
+        Exam examG = ExamFactory.generateExam(course1);
+        examG.setExampleSolutionPublicationDate(examG.getVisibleDate().minusHours(1));
+        return List.of(examA, examB, examC, examD, examE, examF, examG);
+    }
+
     @Test
     @WithMockUser(username = TEST_PREFIX + "instructor1", roles = "INSTRUCTOR")
     void testCreateExam_asInstructor() throws Exception {
```
Comment (Strohgelaender) [inline src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:375]: This test name could be more specific.

**Review by Strohgelaender — COMMENTED** [review]
Looks good in general, thanks for taking the time to cleanup and improve the tests. Just a few small suggestions:

File: src/test/java/de/tum/in/www1/artemis/exam/ExamUtilService.java (hunk 3 above)
Comment (aplr) [reply src/test/java/de/tum/in/www1/artemis/exam/ExamUtilService.java:431]: Really no clue, but good point really. Guess this invariant is enforced by exam creation / update, so should not happen.

File: src/test/java/de/tum/in/www1/artemis/util/AbstractArtemisIntegrationTest.java (hunk 5 above)
Comment (aplr) [reply src/test/java/de/tum/in/www1/artemis/util/AbstractArtemisIntegrationTest.java:105]: Hmm interesting, that was a no-brainer actually, as we're also checking the instance messages by spying on the service. Is it too much white-box testing or what's your thoughts there? But yea, guess then it would be a full e2e right?

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java (hunk 1 above)
Comment (aplr) [reply src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:61]: Thanks :) Yea I was surprised to see such results. I've also tried to also create courses just once, however, some tests modify them, and influence other tests. Also, from what I saw, the impact is quite small (~2s reduction). Just went for the low-hanging fruit.

What we have to check, however, is the behaviour w/ parallel tests. I'll try to check with @laadvo & @DominikRemo regarding this, as I actually have no JUnit experience at all 😅

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java (hunk 8 above)
Comment (aplr) [reply src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:375]: Haha yea indeed :D

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java (hunk 1 above)
Comment (Strohgelaender) [reply src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:61]: I don't see an issue with parallel test execution here, since we also execute different test classes in parallel, not different Test cases within the same class.

File: src/test/java/de/tum/in/www1/artemis/util/AbstractArtemisIntegrationTest.java (hunk 5 above)
Comment (Strohgelaender) [reply src/test/java/de/tum/in/www1/artemis/util/AbstractArtemisIntegrationTest.java:105]: We use this approach for other webocket notifications, since their content is not saved and this is the only way of retrieving their content. But this is not the case for these type of messages.

My problem with that is that we don't tests "that no messages got created", but instead that messages got send using this specific method. I can think of multiple cases of wrong server behaviour, that would not be catched by your test.

- If we change this code to only create the database objects and instead use some worker thread to send out notifications in parallel, your test will always work. In fact, if the notification for some reason gets saved to the database but not send via websocket, the test will work but the student will still see this after reloading the page.
- If a future developer directly calls `websocketMessaginService.sendMessage()` your assertion also gets bypassed.

Similarly I also don't like the spy on the ExamAccessService. What if there is a bug inside of the called access check method? Instead there should be tests with users without permission that verify the returned status code.

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java [hunk 9]
```diff
@@ -405,26 +470,76 @@ void testUpdateExam_asInstructor() throws Exception {
...
         // Course id in the updated exam and in the REST resource url do not match -> bad request
-        exam = ExamFactory.generateExam(course1);
+        Exam exam = ExamFactory.generateExam(course1);
         exam.setId(1L);
         request.put("/api/courses/" + course2.getId() + "/exams", exam, HttpStatus.BAD_REQUEST);
+    }
+
+    @ParameterizedTest
+    @MethodSource("provideExamsWithInvalidDates")
+    @WithMockUser(username = TEST_PREFIX + "instructor1", roles = "INSTRUCTOR")
```
Comment (Strohgelaender) [inline src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:496]: Please move this test towards line 430 since it also used the same method source.

File: src/test/java/de/tum/in/www1/artemis/util/AbstractArtemisIntegrationTest.java (hunk 5 above)
Comment (aplr) [reply src/test/java/de/tum/in/www1/artemis/util/AbstractArtemisIntegrationTest.java]: Ok, yea for the first point one still might go through the spied-on method, so that won't be a issue, but yea, one really has to know what the function is doing, and I agree with you. We should either check the database (did that) and the websocket rather than spying on some in-between service. I went fro the DB now.

Comment (aplr) [reply src/test/java/de/tum/in/www1/artemis/util/AbstractArtemisIntegrationTest.java]: Regarding the `ExamAccessService` spy - I also really don't like that. Thats implementation detail, and should not be tested like that. The integration test should not care about *how* authorization is enforced, it should only test *that* it is enforced, and not care about the how.

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java (hunk 9 above)
Comment (aplr) [reply src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:500]: Hm really want to keep creates / updates together

Comment (aplr) [reply src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:500]: We should rather think about splitting this whole thing up as it's really huge. One good candidate would be a separate suspicious behaviour integration test class

File: src/main/java/de/tum/in/www1/artemis/repository/ExamLiveEventRepository.java [hunk 10]
```diff
@@ -32,11 +32,26 @@ public interface ExamLiveEventRepository extends JpaRepository<ExamLiveEvent, Lo
...
+    List<ExamLiveEvent> findAllByStudentExamId(@Param("studentExamId") Long studentExamId);
+
     /**
      * Delete all events for the given exam.
      *
      * @param examId the id of the exam
      */
-    @Transactional // delete
+    @Transactional
+    // delete
```
Comment (Strohgelaender) [inline src/main/java/de/tum/in/www1/artemis/repository/ExamLiveEventRepository.java:55]: The comment explains why `@Transactional` is used here, we want to use this annotation as few as possible.
```suggestion
    @Transactional // delete
```

Comment (aplr) [reply src/main/java/de/tum/in/www1/artemis/repository/ExamLiveEventRepository.java:55]: Guess that was the auto code formatter. Really have to tweak it, sth. is not right

**Review by Strohgelaender — APPROVED** [review]
code aproved.

Again, thanks for keeping the tests clean!

File: src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java (hunk 1 above)
Comment (DominikRemo) [reply src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:62]: I was also thinking about adding this for all tests in the JUnit properties file, but it does not work for all tests and I did not have enough time for more investigation.
Maybe we should open an Issue for this. There is performance improvements and maybe we could enable this for all classes and disable (set lifecycle for methods) in special cases.
I'll have a deeper look into it. For now, this works :)

Comment (aplr) [reply src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java:62]: Perfect. Yea, it's really a lot of work to untangle the tests, as they're currently treating the resources as non-shared, as they're re-created in `beforeEach`. What has to be done is essentially:
1) identifying tests which do modifications on shared, non-SUT objects (i.e. for ExamIntegration, exams would be "SUT-objects", while courses are non-SUT). In general, they're mostly just read, not modified.
2) create local versions of these modified objects
3) use these local versions in the tests, not the shared ones

However, there can be hidden dependencies between tests, which only show up when tests are run in a non-deterministic order. I.e. I had issues with one test modifying groups of the course, which caused other tests to fail because of access rights issues.

It's really a different way to write tests, and we have to check if it's worth the effort.

File: src/test/java/de/tum/in/www1/artemis/localvcci/LocalVCLocalCIIntegrationTest.java [hunk 11]
```diff
@@ -500,9 +500,10 @@ void testFetchPush_assignmentRepository_examMode() throws Exception {
         examRepository.save(exam);
 
         // Create StudentExam.
-        StudentExam studentExam = examUtilService.addStudentExam(exam);
-        studentExam.setUser(student1);
+
+        StudentExam studentExam = examUtilService.addStudentExamWithUser(exam, student1);
         studentExam.setExercises(List.of(programmingExercise));
+        studentExam.setWorkingTime(null);
```
Comment (aplr) [inline src/test/java/de/tum/in/www1/artemis/localvcci/LocalVCLocalCIIntegrationTest.java:506]: Sooo since I've added `setWorkingTime` in `ExamUtilService.addStudentExam`, this test failed deep inside some checks. Setting it back to `null` fixes the test, however, it somehow does not feel right. Sb. has an Idea?

**Comment by xHadie** [comment]
Notification are showing up
image

However found a small quirk:
When the user never visited the "start exam" page before and the end date of the exam changed, then it will take a couple of seconds for the notification to show up. This is a bit confusing and depending on how fast a student is with typing in their name could result in accidentally bypassing the notifications

**Comment by aplr** [comment]
@xHadie thanks for the feedback! Do you see this is a big issue if it's only affecting the "start exam" page? I guess the working time update notification is predominantly important during the exam, but correct me if I'm wrong :)

File: src/test/java/de/tum/in/www1/artemis/localvcci/LocalVCLocalCIIntegrationTest.java [hunk 12]
```diff
@@ -518,8 +519,8 @@ void testFetchPush_assignmentRepository_examMode() throws Exception {
         // Working time
         exam.setStartDate(ZonedDateTime.now().minusHours(1));
         examRepository.save(exam);
-        studentExam.setExam(exam);
-        studentExamRepository.save(studentExam);
+        // studentExam.setExam(exam);
+        // studentExamRepository.save(studentExam);
```
Comment (laadvo) [inline src/test/java/de/tum/in/www1/artemis/localvcci/LocalVCLocalCIIntegrationTest.java:523]: I think you should remove these lines, or is there a reason why they are still here?

File: src/test/java/de/tum/in/www1/artemis/localvcci/LocalVCLocalCIIntegrationTest.java (hunk 11 above)
Comment (laadvo) [reply src/test/java/de/tum/in/www1/artemis/localvcci/LocalVCLocalCIIntegrationTest.java:506]: I think this is because of the line `exam.setStartDate(ZonedDateTime.now().minusHours(1));` below. If you look into the helper method creating the exam, you can see that the working time is set to 3000 (seconds). So the working time is already over when it is tested that the student can fetch/push etc. If you align the start date and end date of the exam with the woking time this part should work.

I'm not sure if the working time has any effect after the due date has passed (last part of the test). It should be possible to avoid setting the working time to null.

**Review by laadvo — COMMENTED** [review]
I have some minor suggestions but otherwise the refactoring looks really good. Thanks!

File: src/test/java/de/tum/in/www1/artemis/localvcci/LocalVCLocalCIIntegrationTest.java (hunk 12 above)
Comment (aplr) [inline src/test/java/de/tum/in/www1/artemis/localvcci/LocalVCLocalCIIntegrationTest.java:523]:
```suggestion
```

**Review by RY997 — APPROVED** [review]
Code LGTM

**Comment by AntonGeTUM** [comment]
LGTM

**Review by jakubriegel — APPROVED** [review]
Works on ts1

**Review by lennart-keller — APPROVED** [review]
Tested in testing session

**Review by vinceclifford — APPROVED** [review]
Works as expected, tested on ts1
