### PR TITLE
`General`: Fix SAML2 Login

### LINKED ISSUE #5710: SAML2 Login Not Possible
### Describe the bug

The redirection to the SAML2 provider no longer works. Therefore, users cannot login.

### To Reproduce

Artemis with SAML2 enabled required.

1. Log out of Artemis.
2. Click the Login via SAML2/Shibboleth/… button on the right half of the login screen.
3. You are not redirected to the SAML2 provider, instead a blank page is shown.
4. The error as shown below is in the browser console log.

### Expected behaviour

The user is forwarded to the SAML2 provider for the authentication

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

### Additional context

* Artemis Version: 5.11.0
* Confirmed working on 5.10.2
* Using `curl` to query the `/saml2/authenticate` endpoint correctly returns the 302 redirect in 5.10.2, but the same call is intercepted in the newer version and returns a HTML ‘please activate Javascript’ response.

The redirection to the `/saml2/authenticate` page is initiated at https://github.com/ls1intum/Artemis/blob/723ddcc017006bf6c4874fa44c9cf1a8a078bf38/src/main/webapp/app/home/saml2-login/saml2-login.component.ts#L46

### Relevant log output

```shell
Error: NG04002: Cannot match any routes. URL Segment: 'saml2/authenticate'
```

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
Fixes #5710

### Description
This basically reverts #5604.

Interestingly, the Bamboo WAR artefact was broken with the mentioned PR. However, local builds in the regular source directory, local builds in clean environments, and WARs/Docker images produced by Github Actions continued to work at least until release 5.10.2 but were broken in the next release 5.11.0.

An additional investigation why the change continued to work in some environments is necessary so that the deprecated security configuration can be replaced. The newly introduced integration test that checks that the redirect works as intended also passes for the actually broken configuration.
Therefore, this PR is to be seen as an intermediary hotfix to allow us to continue upgrading our systems until the underlying cause is found.

I checked that the produced CI artefacts are now working again:
- Bamboo WAR with local Docker build
- Docker image as built in Github Actions

~~Additionally, the base image for Docker was updated, as the [`openjdk` image](https://hub.docker.com/_/openjdk) is deprecated. The last update for the [previous image](https://hub.docker.com/layers/library/openjdk/17-jdk-slim/images/sha256-779635c0c3d23cc8dbab2d8c1ee4cf2a9202e198dfc8f4c0b279824d9b8e0f22) has been released six months ago and therefore not received any security updates since.
The new `eclipse-temurin:17-jre` image is also smaller by avoiding to include the full JDK when not needed for running the application (531MB vs 720MB before).~~
Moved to a follow-up PR.

### Steps for Testing

Prerequisites:
- System with SAML2 set up
    - e.g., via https://github.com/kit-sdq/Artemis-SAML2-Test-Docker by setting `ARTEMIS_VERSION=pr-5721` in the `.env` file

1. Login via Shibboleth/SAML2.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
unchanged

### CODE REVIEW

**Review by dfuchss — CHANGES_REQUESTED** [review]
Tested with https://github.com/kit-sdq/Artemis-SAML2-Test-Docker/releases/tag/v5.10.2

There it does not resolve the issue :(

**Comment by b-fein** [comment]
Okay, I’ve now got some weird behaviour:
If I build the WAR and Docker image from this branch *locally* and deploy it, it works. When I use the Docker image built in GitHub Actions here from the same commit, it does not.

**Comment by b-fein** [comment]
Current develop branch when built locally works, too.

**Comment by dfuchss** [comment]
Have you tested what happens with a locally build docker image?

**Comment by dfuchss** [comment]
Have you tested what happens if you use the War from the release and build the docker image locally ?

**Comment by b-fein** [comment]
Good idea. Now I did with the WAR from https://github.com/ls1intum/Artemis/releases/tag/5.11.2: It’s broken, too.

**Comment by dfuchss** [comment]
Ok then I guess, we can assume that the broken jar (actions build) is the problem.

**Comment by dfuchss** [comment]
E.g., we could try to test whether the build (actions) works with temurin instead of Zulu

**Comment by b-fein** [comment]
I already tried that: https://github.com/ls1intum/Artemis/pull/5721/commits/63b77fcf22e81384c58d1776178e7b4644b3dd0a

**Comment by dfuchss** [comment]
We could also try to build Artemis within the docker image in a build stage. Then we would not directly rely on actions.

**Comment by b-fein** [comment]
I now made sure the CI run uses Temurin and the most recent Node/npm versions. The only difference between the WAR files is now some metadata like build time and the name of JS files.

Otherwise all class files are *identical* (verified by md5hash):

```
1605c1603
< fbbf87b93a8d3c2ae505d70b878c6d0b  WEB-INF/classes/git.properties
---
> 06ced52695f471d0652d050269cd60c2  WEB-INF/classes/git.properties
1610c1608
< a8406d996477822cd1d3e1297553bd45  WEB-INF/classes/META-INF/build-info.properties
---
> be739e9f46fffcbc915d27799bdf6b59  WEB-INF/classes/META-INF/build-info.properties
1726,1727c1724,1725
< f6162e709ee57faab74475e7a080ca03  WEB-INF/classes/static/1326.0cf362dff96b19f7.js
< e5bdf728d15ef86d00ff3cf6f2079010  WEB-INF/classes/static/1326.0cf362dff96b19f7.js.map
---
> c2de2b7cf08fc5237e1a633a4b83b50f  WEB-INF/classes/static/1326.4661e29918019082.js
> e1a9904e0883151ffe78c04864bc6d5e  WEB-INF/classes/static/1326.4661e29918019082.js.map
1779,1780c1777,1778
< dc5da9819ee415e2b974292047682743  WEB-INF/classes/static/4502.c917e89a7331bc14.js
< 5e6f66f7f1df8ea757846d1f8a3e9f18  WEB-INF/classes/static/4502.c917e89a7331bc14.js.map
---
> ba466ceb9874f7fcd1227fe7317695c4  WEB-INF/classes/static/4502.edeb8f96f49dabe7.js
> d5e74b1c2b588efc8f19153bbe801a9a  WEB-INF/classes/static/4502.edeb8f96f49dabe7.js.map
1918c1916
< bf955ba4968dc591ffc7b77370ec0b53  WEB-INF/classes/static/index.html
---
> 209aa3e23465e1386904337715dcc8bd  WEB-INF/classes/static/index.html
1989,1990c1987,1988
< f028c2c2f4605560ecd8f056060cb283  WEB-INF/classes/static/main.711ac3295180a8b5.js
< ac35e9632486e2213747222e32acb87d  WEB-INF/classes/static/main.711ac3295180a8b5.js.map
---
> 676695d54d79dcd1c283e07c25d81da4  WEB-INF/classes/static/main.a817fdb0b82d256f.js
> 14045c842217204964abd629decb6cd6  WEB-INF/classes/static/main.a817fdb0b82d256f.js.map
1992c1990
< 2f0e030e720cee3f61478e6e2bd8c6df  WEB-INF/classes/static/ngsw.json
---
> 2ad53ed249a670f379e4639a2bdb3868  WEB-INF/classes/static/ngsw.json
1997,1998c1995,1996
< 8e7e95860e7373aa198e29b30973ed01  WEB-INF/classes/static/runtime.cc3d9795627939f3.js
< 3aa8f9b385113e8003409c8c0675f642  WEB-INF/classes/static/runtime.cc3d9795627939f3.js.map
---
> 004d7c74a3bec34d24e2428b50194486  WEB-INF/classes/static/runtime.5bb1b4b09556582e.js
> 584d4324ca680c4f310c0383caf8c6b1  WEB-INF/classes/static/runtime.5bb1b4b09556582e.js.map
2006c2004
< c9f878275475ce8aaa067f59210755b6  WEB-INF/classes/stats.html
---
> a9d8c8b36a9f9e8224c1420674c00c43  WEB-INF/classes/stats.html
2385c2383
< 2cd3533ceb1a4676f11891cce2501a48  WEB-INF/classpath.idx
---
> c738f870515887ee27e036190c42f6ca  WEB-INF/classpath.idx
```

The differences in `WEB-INF/classes/static/ngsw.json` are only the different names for the `*.js` files. In `classpath.idx` the order is a bit different. In the js files I’ve looked into the only differences seem to be identifier names.

**Comment by dfuchss** [comment]
I'll check whether it works now asap :)

**Comment by b-fein** [comment]
Oh, I forgot that part in the comment above: It still doesn’t work for me.

**Comment by dfuchss** [comment]
@b-fein I've tested the following:

* Build via Docker eclipse-temurin:17 (linux amd64) -> Does not work
* Build on Windows 11 eclipse-temurin 17 -> works 

Did you created your working WAR on Windows as well?

**Comment by b-fein** [comment]
No, I’m using a Linux machine.

**Comment by dfuchss** [comment]
Ok, then I do not get what's different .. Have you also tried building your branch directly in docker (that's what I did and what didn't worked)

On windows I used "Temurin-17+35"
The docker contains "Temurin-17.0.4.1+1"

**Comment by dfuchss** [comment]
maybe we have a cached dependency ?

**Comment by b-fein** [comment]
I have now tried
- building the WAR locally inside a `eclipse-temurin:17` image with a completely fresh repo clone and no mounted directories. ⇒  **works**
- updating the base image from the deprecated `openjdk` (last update five months ago for the used version) to the same temurin image as above. ⇒  **works locally**, **broken when built in GitHub Actins**
- clearing the GitHub Actions cache and rebuilding ⇒  **still broken**

**Comment by dfuchss** [comment]
Interesting .. I've also build the branch with `eclipse-temurin:17` in docker .. that didn't work for me (as mentioned before) ->I'll test that again. (Did you build it as root or as another user?)

**Comment by krusche** [comment]
Did you try out the build that we use at TUM which comes from Bamboo?

**Comment by b-fein** [comment]
> Did you build it as root or as another user?

As a regular user on the host system.

---

> Did you try out the build that we use at TUM which comes from Bamboo?

The [WAR from the current `develop`](https://bamboo.ase.in.tum.de/browse/ARTEMIS-WEBAPP-JOB1-4841/artifact) combined with a local `docker build` with `src/main/docker/Dockerfile` is broken, too.

**Comment by dfuchss** [comment]
this is strange .. even with build container it does not work ..

**Comment by dfuchss** [comment]
@b-fein do you have an idea, why it does not build here: https://github.com/ls1intum/Artemis/actions/runs/3228188803/jobs/5283947520

File: src/main/docker/Dockerfile [hunk 1]
```diff
@@ -1,4 +1,11 @@
-FROM openjdk:17-jdk-slim-bullseye
+FROM eclipse-temurin:17 as builder
+WORKDIR /build
+COPY . .
+RUN chown -R 1000.1000 /build
```
Comment (b-fein) [inline src/main/docker/Dockerfile:4]:
```suggestion
RUN chown -R 1000:1000 /build
```
This is definitely an error. I also think npm tries to store the npm cache in `$HOME/.npm/`. I’m not sure how that is handled if user 1000 does not have a `$HOME`-dir.

**Comment by dfuchss** [comment]
@b-fein does this image work locally ?
The GH Docker image does not work for me

**Comment by b-fein** [comment]
New finding:
- [Artifact of Github release 5.10.2](https://github.com/ls1intum/Artemis/releases/tag/5.10.2) works
- [Bamboo artifact for the same commit](https://bamboo.ase.in.tum.de/browse/ARTEMIS-WEBAPP-4790/artifact) broken

⇒ The issue seems to have been present before release 5.10.2, it just did not occur in Github Actions.

**Review by dfuchss — DISMISSED** [review]
Tested on our test systems. Works as expected. Thanks a lot !

**Comment by dfuchss** [comment]
As follow-up we can think about changing the SecurityConfig similar to this https://github.com/kit-sdq/NewsList/blob/main/src/main/java/edu/kit/kastel/sdq/newslist/config/SecurityConfiguration.java But therefore, we might have to migrate some implementations.

File: src/main/docker/Dockerfile [hunk 2]
```diff
@@ -1,4 +1,4 @@
-FROM openjdk:17-jdk-slim-bullseye
+FROM eclipse-temurin:17-jre
```
Comment (4ludwig4) [inline src/main/docker/Dockerfile:1]: We should maybe streamline this over the whole Artemis project? (Thinking about the Github actions and my docker compose refactoring) Maybe in a seperate PR if there are problems to easier revert it? I can do this if desired.

In the bamboo tests (client-tests and server-tests) we are currently using the following docker image as base: https://github.com/ls1intum/docker-jdk-node-yarn which is based on `eclipse-temurin` itself therefore this change here seems really good!

Comment (b-fein) [reply src/main/docker/Dockerfile]: Sure, I reverted the change here and will open a separate PR for it.

**Review by dfuchss — APPROVED** [review]
Re-approve code lgtm

**Comment by 4ludwig4** [comment]
Manually tested this with a docker-compose setup including a SAML test server and a mail server with an empty Artemis DB.
It took a while to process everything but that's probably my computer, but I get the SAML account registered in Artemis, GitLab and Jenkins and get logged in. So it seems like the SAML login is working with these changes!

After logging out I guess I'm keeping some kind of session cookie as after clicking `SAML2 Login` I'm logged in as the user I wanted to sign out before. Not sure if this is a bug or a feature. If I delete all cookies, I can log in again as a different user.

After playing a bit around, I also noticed that if I try going back (browser back button) from the external SAML page I eventually get to the page `/accesdenied` and if I then click the Artemis logo I get to the Artemis Login page, but I instantly get redirected to the external SAML page. So I can't leave this cycle without entering correct data in the external SAML page or waiting for a bit. It could of course be that this is a problem with my configuration! Also, probably not an issue introduced with these changes?!

**Comment by dfuchss** [comment]
That should not be related to this issue. Maybe we should raise another to improve the workflow :)

**Comment by 4ludwig4** [comment]
> That should not be related to this issue. Maybe we should raise another to improve the workflow :)

As I'm not into the Spring Security Scheme I couldn't review the code and therefore just tested more thoroughly and already thought that this is not related but couldn't verify ;)

@b-fein I added an PR for the Java distro changes:
- #5739

**Comment by dfuchss** [comment]
It should just be the old code (same as before the mentioned PR)

File: src/test/java/de/tum/in/www1/artemis/authentication/UserSaml2IntegrationTest.java [hunk 3]
```diff
@@ -52,6 +52,13 @@ void clearAuthentication() {
         this.database.resetDatabase();
     }
 
+    @Test
+    void testAuthenticationRedirect() throws Exception {
+        request.postWithResponseBody("/api/saml2", Boolean.FALSE, UserJWTController.JWTToken.class, HttpStatus.UNAUTHORIZED);
+        final String redirectTarget = request.getRedirectTarget("/saml2/authenticate", HttpStatus.FOUND);
+        assertThat(redirectTarget).isEqualTo("http://localhost/login");
```
Comment (4ludwig4) [inline src/test/java/de/tum/in/www1/artemis/authentication/UserSaml2IntegrationTest.java:59]: Are tests always executed on `localhost`? Then this line is not an issue, otherwise it might be.

File: src/main/java/de/tum/in/www1/artemis/config/SecurityConfiguration.java [hunk 4]
```diff
@@ -115,7 +144,7 @@ protected SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
             .headers()
             .contentSecurityPolicy("script-src 'self' 'unsafe-inline' 'unsafe-eval'")
             // TODO: investigate exactly whether the following works in our setup or not
-            // .contentSecurityPolicy("default-src 'self'; connect-src: 'self' 'https://sentry.io' 'ws:' 'wss:'; frame-src * data:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src * data:; font-src 'self' data:")
+//            .contentSecurityPolicy("default-src 'self'; connect-src: 'self' 'https://sentry.io' 'ws:' 'wss:'; frame-src * data:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src * data:; font-src 'self' data:")
```
Comment (4ludwig4) [inline src/main/java/de/tum/in/www1/artemis/config/SecurityConfiguration.java:147]:
```suggestion
            // .contentSecurityPolicy("default-src 'self'; connect-src: 'self' 'https://sentry.io' 'ws:' 'wss:'; frame-src * data:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src * data:; font-src 'self' data:")
```
Prettier in the state it was before :D

**Review by 4ludwig4 — COMMENTED** [review]
Looks good to me, everything mentioned was reverted and tests were added.
I just have one question concerning the tests. Also, a small code style improvement which shouldn't be reverted I guess.

File: src/test/java/de/tum/in/www1/artemis/authentication/UserSaml2IntegrationTest.java (hunk 3 above)
Comment (b-fein) [reply src/test/java/de/tum/in/www1/artemis/authentication/UserSaml2IntegrationTest.java]: Replaced it with a `endsWith` check, that definitely shouldn’t break.

File: build.gradle [hunk 5]
```diff
@@ -345,6 +345,7 @@ tasks.withType(Test) {
                 def startItem = "|  ", endItem = "  |"
                 def repeatLength = startItem.length() + output.length() + endItem.length()
                 println("\n" + ("-" * repeatLength) + "\n" + startItem + output + endItem + "\n" + ("-" * repeatLength))
+                // @formatter:on
```
Comment (4ludwig4) [inline build.gradle:348]: One `@formatter:on` too much? Or why is this eclipse specific comment needed here?

Comment (b-fein) [reply build.gradle]: That is not needed. Probably an accidental paste. Removed again.

**Review by dfuchss — APPROVED** [review]
Re-approve

**Review by 4ludwig4 — APPROVED** [review]
