### PR TITLE
Bugfix/categories/adding category

### LINKED ISSUE #1333: Bugfixes for category selection
Currently, the category selection for exercises is error-prone and hard to use. 
Some improvement suggestions which should be easy to implement:
1) A category should also be added when leaving the focus (e.g. by clicking Tab) and not only when clicking on Enter
2) Existing categories in the same course should be suggested and the same color should be reused, otherwise it's confusing for students. One option would be that existing categories of the course (based on the same name) are shown with a checkbox, so they can be easily switched on or off. Another approach would be to use auto completion when the user starts typing.
3) Instead of "+ Tag", it should state "+ Category"
4) It's not obvious that users can change the color by clicking on the category. Also the color picker is not working correctly

image

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
### Checklist
- [x] I tested *all* changes and *all* related features with different users 
- [X] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

Closes #1333 

### Description

Set the necessary parameters to the ngx-chips to satisfy the requirements (automatic opening of autocomplete, tags added when blur etc)

### Steps for Testing

1. Log in to Artemis
2. Navigate to the exercise configuration page
3. Add some tags

### CODE REVIEW

**Comment by stefanwaldhauser** [comment]
Theres still an issue left that the input field does not stretch the whole page size. So to open to autocomplete dropdown the user has to click near the category input.

**Comment by tessaRuckstuhl** [comment]
Nice work there! 
Apart from Stephans mentioned issues everything worked just fine.
One minor suggestion might be to move the X  for deleting and the three dots for choosing the colors further appart (e.g. from left to right: the cross, then the text and finally the three dots) as I accidently deleted the tag wenn trying to change the color a few times.

**Comment by krusche** [comment]
@stefanwaldhauser what is the status here? Can you please solve the remaining issues so that we can merge this PR?

**Comment by stefanwaldhauser** [comment]
> @stefanwaldhauser what is the status here? Can you please solve the remaining issues so that we can merge this PR?

I will look into the remaining issues today (22.05.2020(.  I am not sure if I can fix all the things you mentioned as the whole thing depends on a third party package

**Comment by stefanwaldhauser** [comment]
> @stefanwaldhauser what is the status here? Can you please solve the remaining issues so that we can merge this PR?

@krusche I changed a little bit of the properties of ngxchips. I found no way to speed up the dropdown speed however. Maybe somebodt with more experience can take a look?

**Comment by madwau** [comment]
I was not able to reproduce the dropdown delay. I noticed an error appearing when deleting a category and then typing in a letter for which there is a suggestion. Doesn't seem to have any effect on functionality though.

OnPaste 20200525-131949

> One minor suggestion might be to move the X for deleting and the three dots for choosing the colors further appart (e.g. from left to right: the cross, then the text and finally the three dots) as I accidently deleted the tag wenn trying to change the color a few times.

@tessaRuckstuhl I agree that they are too close to each other. I only noticed later that you can click on the category text instead of on the dots to achieve the same result.

File: src/main/webapp/app/shared/category-selector/category-selector.component.ts [hunk 1]
```diff
@@ -44,7 +44,8 @@ export class CategorySelectorComponent implements OnChanges {
      */
     openColorSelector(event: MouseEvent, tagItem: ExerciseCategory) {
         this.selectedCategory = tagItem;
-        this.colorSelector.openColorSelector(event);
+        const height = 110;
```
Comment (madwau) [inline src/main/webapp/app/shared/category-selector/category-selector.component.ts:47]: Maybe place this value up higher in the component below the Input/Output props as a `readonly` property (e.g. as `colorSelectorHeight`) since it's more of a configuration value than a local variable of the method?

File: src/main/webapp/app/shared/category-selector/category-selector.scss [hunk 2]
```diff
@@ -26,3 +26,21 @@ jhi-category-selector {
...
+.category-name:hover + .tag-options {
+    transform: scale(1.5);
+    transform-origin: 50% 50%;
+}
+
+.tag-options {
+    position: absolute;
+    transition: all 0.2s ease-in-out;
+}
+.tag-options:hover {
```
Comment (madwau) [inline src/main/webapp/app/shared/category-selector/category-selector.scss:39]: Maybe combine with `.category-name:hover + .tag-options` to avoid the duplication?

```css
.category-name:hover + .tag-options,
.tag-options:hover {
    transform: scale(1.5);
    transform-origin: 50% 50%;
}

File: src/main/webapp/app/shared/category-selector/category-selector.component.ts (hunk 1 above)
Comment (stefanwaldhauser) [reply src/main/webapp/app/shared/category-selector/category-selector.component.ts]: Done in b388424253bcf5adf8d9abdbacf18b256655cd24

File: src/main/webapp/app/shared/category-selector/category-selector.scss (hunk 2 above)
Comment (stefanwaldhauser) [reply src/main/webapp/app/shared/category-selector/category-selector.scss:36]: Done in 835e24f4cd81348ec6efe86a3d67fac46a45e8c1

**Comment by stefanwaldhauser** [comment]
Fixed the problems that @tessaRuckstuhl had
