### PR TITLE
`Communication`: Fix an issue with editing messages

### LINKED ISSUE #10778: Editing a message in a channel sometimes leads to an error: "Bad Request"
### Describe the bug

When I try to edit a message in a group channel (that I have created as a tutor) I get a error 400 "bad request". After fully refreshing (Ctrl + F5 on Windows) I can save the edited message. (Please check the added logs)

### To Reproduce

1. Create a group channel 
2. Add users to it 
3. Send a message
4. Edit the message
5. Save the changes

### Expected behavior

I expect the changes to be able to be saved

### Screenshots

Image

### Which version of Artemis are you seeing the problem on?

8.0.4

### What browsers are you seeing the problem on?

Chrome

### Additional context

Please heck the log

### Relevant log output

```shell
Payload of the sent request:
e-pictures/14238/ProfilePicture_2024-10-14T19-54-57-884_4bf3dfb3.jpeg","name":"Liam Berger"},"authorRole":"TUTOR","creationDate":"2025-05-02T10:34:38.171Z","updatedDate":"2025-05-02T10:41:20.438Z","content":"**Hi Team,**\nReally excited to be working with you all on this project! To ensure a smooth start, here's a quick rundown of a few things:\n- **GitHub Access:** Please double-check everyone has access to our team repository. Let me know immediately if you're running into any issues – we need to get that sorted right away.\n- **Meeting Schedule:** Let's start by scheduling weekly meetings. This will give us a good rhythm initially to discuss progress and any roadblocks. We can always adjust the frequency later in the semester to better suit your needs – scaling back when things are running smoothly, or adding more if you find it helpful.\n- **Initial Project Discussion:** Our first meeting will be a good opportunity to discuss your initial project ideas and get a general direction approved before diving into implementation.\n- **Official Communication Channel:** This channel is our official hub for all project-related discussions and decisions. I'll be referencing things discussed here, so please keep everything contained within this space.\n- **Other Tools:** Feel free to use any other tools you find helpful (Discord, WhatsApp, etc.) – and don’t hesitate to add me if you think it would be useful!\n- **My Role:** My primary role is to support you. I’m here to help navigate challenges and offer guidance. Please don’t hesitate to reach out with questions – big or small! I really encourage you to drive the communication; I'm here as a resource, not a project manager.\n**Let me know what times next week work for our first meeting.**","isSaved":false,"hasForwardedMessages":false,"isConsecutive":false,"conversation":{"type":"channel","id":21987,"creator":{"id":14238,"name":"Liam Berger"},"creationDate":"2025-05-02T08:14:43.838Z","lastMessageDate":"2025-05-02T10:34:38.196Z","name":"stratton-oakmont","isPublic":false,"isAnnouncementChannel":false,"isArchived":false,"isCourseWide":false},"title":"","displayPriority":"NONE","resolved":false,"forwardedPosts":[],"forwardedAnswerPosts":[]}

Response of the 400 error:
{
    "type": "https://www.jhipster.tech/problem/problem-with-message",
    "title": "Bad Request",
    "status": 400,
    "detail": "JSON parse error: No _valueDeserializer assigned",
    "path": "/api/communication/courses/446/messages/27072",
    "message": "error.http.400"
}
```

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

Updating messages and replies as a tutor sometimes results in a bad request error. (Closes #10778)

### Description

`UpdatePostingDTO` has been added to use a minimal DTO and fix the valueDeserializer error.

### Steps for Testing

Prerequisites:
- 1 Tutor
- 1 Course with Communication enabled

1. Log in to Artemis.
2. Navigate to Communication section of a course.
3. Send a message to a private channel and reply to it.
4. Try editing both messages and verify that the update works as before (without any bad request error)

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
  - Introduced a streamlined update format for postings, improving how messages and answers are updated.

- **Refactor**
  - Updated message and answer update endpoints and services to use the new update format.
  - Modified client-side update methods to send only essential posting fields during updates.

### CODE REVIEW

File: src/main/java/de/tum/cit/aet/artemis/communication/dto/UpdatePostingDTO.java [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+import com.fasterxml.jackson.annotation.JsonInclude;
+
+/**
+ * DTO for updating a Posting with only the necessary fields.
+ */
+@JsonInclude(JsonInclude.Include.NON_EMPTY)
+@JsonIgnoreProperties(ignoreUnknown = true)
+public record UpdatePostingDTO(Long id, String content, String title, Boolean resolvesPost) {
+
+    public String getContent() {
```
Comment (krusche) [inline src/main/java/de/tum/cit/aet/artemis/communication/dto/UpdatePostingDTO.java:13]: please remove the getters, those are not needed

File: src/main/java/de/tum/cit/aet/artemis/communication/dto/UpdatePostingDTO.java [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
+import com.fasterxml.jackson.annotation.JsonInclude;
+
+/**
+ * DTO for updating a Posting with only the necessary fields.
+ */
+@JsonInclude(JsonInclude.Include.NON_EMPTY)
+@JsonIgnoreProperties(ignoreUnknown = true)
+public record UpdatePostingDTO(Long id, String content, String title, Boolean resolvesPost) {
```
Comment (krusche) [inline src/main/java/de/tum/cit/aet/artemis/communication/dto/UpdatePostingDTO.java:11]: please try to use long and boolean to avoid null values

**Review by HawKhiem — APPROVED** [review]
Tested on TS3. Works as expected

**Review by julian-wls — APPROVED** [review]
Tested on TS2, works fine. I also tested editing on the Android app to ensure it is compatible to these changes :+1:

**Review by krusche — APPROVED** [review]
Code changes look good 👍
