### PR TITLE
`General`: Save language choice

### LINKED ISSUE #5210: language isn't stored
### Describe the bug

If I switch the language to Deutsch, it isn't stored and I have the make this choice at each visit of Artemis.

### To Reproduce

1. Browse to your Artemis server.
2. Change the language to Deutsch
3. Sign in
4. Logout
5. Reload the page :arrow_right:  Page is in English again, also after I login again

### Expected behavior

Artemis remembers the language I had selected. At least after I Sign in.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

- browsers:
  - Firefox 101.0
  - Opera 87.0.4390.45
- OS: Linux Mint 20.3 64-bit
- Artemis 5.8.3

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Closes #5210

### Description

- Created a new API endpoint that lets the logged in user switch the language key in the database
- When a logged in user switches the language, this API endpoint will be called
- Whenever a user logs in, the value from the database will be set throughout the UI (including in the session storage)
- Upon visiting Artemis for the "first-time" (meaning session storage is clear and not logged in), Artemis will determine if english or german is the preferred language and set this value to the session storage.

### Steps for Testing

**Scenario 1:**

- The is no active Artemis session open (meaning no locale stored in your session storage). When you access Artemis the language will be the preferred language of your browser.

**Scenario 2:**

- The is no active Artemis session open (meaning no locale stored in your session storage). When you access Artemis the language will be the preferred language of your browser. You then change the language in the dropdown to a different language to the one of your browser. Artemis will be shown in that language while the session is open and your are NOT logged in.

**Scenario 3:** 
- You log into Artemis. Then **always** the language of your account will be chosen. When you select a language n the dropdown, this will **persist**. Meaning even after your session ends. This language selected will be chosen when you log into Artemis again.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Comment by bassner** [comment]
I guess there's just a misunderstanding in what the session storage does; Scenario 2 can't work if you use the session storage. Session storage is only for your current session and is wiped if you close the tab. If you want the setting to be persistent, use local storage instead.

Another scenario that could be confusing for users:
Prerequisites: System Language = EN, User Language in DB = EN
1. Be on login page
2. Change language to DE
3. Log in
The language is then changed back to EN although I explicitly changed it a second before.

**Comment by stefanwaldhauser** [comment]
> I guess there's just a misunderstanding in what the session storage does; Scenario 2 can't work if you use the session storage. Session storage is only for your current session and is wiped if you close the tab. If you want the setting to be persistent, use local storage instead. However, I do not recommend that as that could be an issue for machines that are used by multiple users with different language preferences
> 
> Another scenario that could be confusing for users: Prerequisites: System Language = EN, User Language in DB = EN
> 
> 1. Be on login page
> 2. Change language to DE
> 3. Log in
> 
> --> The language is then changed back to EN although I explicitly changed it a second before.

Hmm. 

> I guess there's just a misunderstanding in what the session storage does; Scenario 2 can't work if you use the session storage. Session storage is only for your current session and is wiped if you close the tab. If you want the setting to be persistent, use local storage instead. However, I do not recommend that as that could be an issue for machines that are used by multiple users with different language preferences
> 
> Another scenario that could be confusing for users: Prerequisites: System Language = EN, User Language in DB = EN
> 
> 1. Be on login page
> 2. Change language to DE
> 3. Log in
> 
> --> The language is then changed back to EN although I explicitly changed it a second before.

To be hosted I see this as expected behaviour. Just tested it on LinkedIn and it the exact same behaviour. No matter what language Artemis currently is in, I expect it to respect my language settings once I login.

**Comment by stefanwaldhauser** [comment]
> Tested on TS5. Scenario 1 and 3 work as you described it. However, Scenario 2 does not work in my test. Instead of reusing the last language set in the login form, it seems to still use the browser language (chrome in my case):
> 
>  2022-06-13.12-32-18.mp4 
> Could you recheck this again, please?

I made a mistake in describing scenario2. (See helpful comment by @bassner). It is not possible to do this when using session storage

**Review by TheTrueVester — DISMISSED** [review]
Tested on ts1. Everything worked as expected.

File: src/main/java/de/tum/in/www1/artemis/web/rest/AccountResource.java [hunk 1]
```diff
@@ -187,6 +187,22 @@ public void changePassword(@RequestBody PasswordChangeDTO passwordChangeDto) {
...
+     *
+     * @param languageKey languageKey to change to.
+     * @throws IllegalArgumentException {@code 400 (Bad Request)} if the language key is not 'en' or 'de'.
+     */
+    @PostMapping(path = "/account/change-language")
+    public void changeLanguageKey(@RequestBody String languageKey) {
+        User user = userRepository.getUser();
+        String langKey = languageKey.replaceAll("\"", "").toLowerCase().trim();
+        if (!"en".equals(langKey) && !"de".equals(langKey)) {
+            throw new BadRequestAlertException("Invalid language key", "Account", "invalidLanguageKey");
```
Comment (JohannesStoehr) [inline src/main/java/de/tum/in/www1/artemis/web/rest/AccountResource.java:201]: @throws IllegalArgumentException seams to be wrong, since you throw another exception.
Additionally, can you also include the invalid key in the error message of the exception?

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
Left one comment:

**Review by manuelmanso — APPROVED** [review]
Works as expected in TS2, code looks good too!

**Review by jbllhff — APPROVED** [review]
Tested on ts1, works fine!

**Review by SimonPaul02 — DISMISSED** [review]
Tested on TS2, works as expected

**Review by yuling-sun — APPROVED** [review]
Tested on TS2. Works as described.

File: src/main/java/de/tum/in/www1/artemis/web/rest/AccountResource.java (hunk 1 above)
Comment (ge65cer) [reply src/main/java/de/tum/in/www1/artemis/web/rest/AccountResource.java:201]: Jup, I also think this should be a `IllegalArgumentException`. The user will not see the alert anyway, if the client behaves correctly.

**Review by ge65cer — CHANGES_REQUESTED** [review]

**Review by babyygemperor — DISMISSED** [review]
Tested on ts2, works as described

**Review by ge65cer — DISMISSED** [review]
Approved after feedback was applied

**Review by Marvin-Vitcu — COMMENTED** [review]
Tested on ts1 with Chrome browser.
Task 1 and 3 work fine.
Task 2 doesn't work as intended: the language is not saved during a session. Artemis always uses the default language of the browser.

**Review by Santia-go — COMMENTED** [review]
Tested on TS1
The task 2 does not save the language
Other tasks working okay.

**Review by rhubinger — APPROVED** [review]
Tested on TS2. Task 2 isn't working, 1 and 3 are.

**Review by luisa-we — APPROVED** [review]
Tested on ts2, all scenarios work as expected

**Review by MetinLamby — COMMENTED** [review]
scenario 2 also does not work as expected (ts2). all others are fine

**Review by ge65cer — DISMISSED** [review]
Approve code.

**Review by Hialus — COMMENTED** [review]
Apart from the small issue the code looks good.

**Review by Dominik-Weinzierl — APPROVED** [review]
Looks good to me! Nice changes :+1:

**Review by Hialus — APPROVED** [review]
