### PR TITLE
`Programming exercises`: Trigger build on repository reset

### LINKED ISSUE #10347: `Programming exercises`: Build result is outdated after repository reset
### Describe the bug

I as a student have 57 different checkstyle errors in my code. I decide that I do not like my current solution and reset my repository. This does not re-trigger the tests, so even though I am now working with the clean template repository again, my latest result still shows the 57 checkstyle errors, which does not match the current state of my repo.

### To Reproduce

1. Have a programming exercise with some static code analysis errors.
2. Reset the repository.
3. The result still shows the test cases and SCA errors from before the reset.

### Expected behavior

I think the easiest solution in this case would probably be to simply trigger the tests after the reset. That way, the state of the template repo is shown, not the state from before the reset.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

7.9.1

### What browsers are you seeing the problem on?

Chrome, Safari

### Additional context

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by chrisknedl**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added an integration test (Spring) related to the feature (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context

Fixes #10347.

### Description

To keep the latest result up to date with the current repo state, the build and tests are triggered after a reset of the repo.

### Steps for Testing

(Please look at the test checkboxes below to see on which server should be tested on)

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Create a (java) programming exercise with online editor enabled
3. Go to the course and then the exercise in the course overview
4. Start the exercise and open the online code editor on the bottom right
5. Submit the assignment repo.
6. Create the SortStrategy interface in the same package as the other source files
7. Submit again, one test case should pass now
8. Go back one page in the browser, scroll to the bottom on the exercise in the course dashboard, and reset your repo
9. This should trigger a third build, and create a new submission where 0 test cases pass (see screenshot)

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1 (local-ci)
- [x] Test 2 (jenkins)

### Test Coverage

The two new lines are covered by the new test.
### Screenshots
image
This shows the result timeline after following the steps.

## Summary by CodeRabbit

- **New Features**
	- Enhanced repository reset functionality improves version control integration, ensuring reliable triggering of updated build processes.

- **Tests**
	- Added automated tests to confirm that resetting a repository correctly initiates subsequent actions, enhancing the overall user experience.
	- Introduced a new test to verify that a build is triggered upon repository reset.

### CODE REVIEW

**Review by SimonKaran13 — APPROVED** [review]
I tested on TS1 and the feature works as expected. Resetting the repo triggers a new build.

image

File: src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java [hunk 1]
```diff
@@ -314,6 +327,9 @@ public ResponseEntity<Void> resetRepository(@PathVariable Long participationId,
 
         programmingExerciseParticipationService.resetRepository(participation.getVcsRepositoryUri(), sourceURL);
 
+        var targetRepo = gitService.getOrCheckoutRepository(participation.getVcsRepositoryUri(), true);
+        localVCServletService.orElseThrow().processNewPush(null, targetRepo);
```
Comment (b-fein) [inline src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java:331]: I would consider this to be domain logic. Why is it part of the controller here instead of the `resetRepository` logic?

File: src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java [hunk 2]
```diff
@@ -97,12 +100,19 @@ public class ProgrammingExerciseParticipationResource {
 
     private final Optional<SharedQueueManagementService> sharedQueueManagementService;
 
+    private final ProfileService profileService;
```
Comment (b-fein) [inline src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java:103]: Is this used somewhere?

**Review by b-fein — CHANGES_REQUESTED** [review]

File: src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java (hunk 1 above)
Comment (MaximilianAnzinger) [reply src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java:331]: I agree. Although we have to consider if we want to trigger the build every time we reset the repo or if this should be a separate method to differentiate between `reset` and `reset & trigger`

File: src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java (hunk 2 above)
Comment (chrisknedl) [reply src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java:103]: Not anymore. Good catch.

File: src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java (hunk 1 above)
Comment (chrisknedl) [reply src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java:331]: The `resetRepository` method is actually only used once. I wouldn't make a separate method, but I could add a boolean flag to decide if it should also trigger a build.

Comment (b-fein) [reply src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java:331]: In that case I would not add a flag, but just document in the Javadoc that the reset operation also triggers a build. In case someone else needs it without the build in the future, they can separate it.

Comment (MaximilianAnzinger) [reply src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java]: Yep, this seems like the best solution.

Comment (chrisknedl) [reply src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java]: Will adapt it later 👍

**Review by b-fein — APPROVED** [review]
Code :+1:. I agree that the refactoring outlined in the discussion above and noted in the to-do comment it out-of-scope here.

**Review by dfuchss — APPROVED** [review]
Code

**Review by b-fein — DISMISSED** [review]
manual test Jenkins: works

**Review by tobias-lippert — DISMISSED** [review]
Tested on ts1 with localVC/localCI

File: src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java [hunk 3]
```diff
@@ -314,6 +324,13 @@ public ResponseEntity<Void> resetRepository(@PathVariable Long participationId,
 
         programmingExerciseParticipationService.resetRepository(participation.getVcsRepositoryUri(), sourceURL);
 
+        // ToDo: Circular dependencies currently make it impossible to put this into the ProgrammingExerciseParticipationService
+        // ToDo: Major refactoring would be required
+        if (localVCServletService.isPresent()) {
```
Comment (krusche) [inline src/main/java/de/tum/cit/aet/artemis/programming/web/ProgrammingExerciseParticipationResource.java:329]: I don't think this is the right approach. With LocalVC, there is no need to checkout the repository in this case. 
I also don't think we should expose `localVCServletService` like that. I agree that a larger refactoring would be needed to cleanup the underlying code.

For the particular case I am wondering, if it would not make more sense to use `ContinuousIntegrationTriggerService` and to invoke

`triggerBuild(ProgrammingExerciseParticipation participation)`

**Review by krusche — CHANGES_REQUESTED** [review]
Please look at my inline feedback, the current solution in the code is not a good idea

**Comment by krusche** [comment]
Please reopen this PR again when you have time to work on it.

**Review by HawKhiem — DISMISSED** [review]
Tested on TS5. Works as described

image

File: src/test/java/de/tum/cit/aet/artemis/programming/AbstractProgrammingIntegrationIndependentTest.java [hunk 4]
```diff
@@ -148,4 +150,8 @@ public abstract class AbstractProgrammingIntegrationIndependentTest extends Abst
     @Autowired
     protected UserUtilService userUtilService;
 
+    // Spy Beans
+    @MockitoSpyBean
```
Comment (b-fein) [inline src/test/java/de/tum/cit/aet/artemis/programming/AbstractProgrammingIntegrationIndependentTest.java:154]: The server tests fail.

If the regular start still works as expected, it is likely due to the mocking here. This might cause additional server restarts during testing.

**Review by b-fein — CHANGES_REQUESTED** [review]

File: src/test/java/de/tum/cit/aet/artemis/programming/AbstractProgrammingIntegrationIndependentTest.java (hunk 4 above)
Comment (theblobinthesky) [reply src/test/java/de/tum/cit/aet/artemis/programming/AbstractProgrammingIntegrationIndependentTest.java]: I think there might have only been tests for failure cases of the method `ProgrammingExercisesParticipationResource.resetRepository` before, because the success case of the method ends on 
`
        programmingExerciseParticipationService.resetRepository(participation.getVcsRepositoryUri(), sourceURL);
        continuousIntegrationTriggerService.triggerBuild(participation, true);
        return ResponseEntity.ok().build();
`.

I don't think you can really test that without mocking both `resetRepository` and `triggerBuild` bc. otherwise the tests crash. If you have any suggestions on how to test anything else about the method, I'm open to them. But for now I've removed the test, since it basically just checked whether the method returns OK HTTP 200 or not.

**Review by b-fein — APPROVED** [review]

**Review by HawKhiem — APPROVED** [review]
Tested again on TS3. Works as described

Screenshot 2025-05-14 080518
Screenshot 2025-05-14 080621
Screenshot 2025-05-14 080639

**Review by dfuchss — APPROVED** [review]
Code lgtm

**Review by krusche — APPROVED** [review]
