### PR TITLE
`Quiz exercises`: Fix minor issues when participating

### LINKED ISSUE #5149: TypeError in live quiz exercises
Error when navigating to `/courses/{id}/quiz-exercises/{id}/live`. Occurred almost 200 times with over 50 different users in the past weeks. Likely introduced in Artemis version 5.8.0. 

Sentry Issue: https://sentry.ase.in.tum.de/organizations/artemis/issues/22481 and https://sentry.ase.in.tum.de/organizations/artemis/issues/21981/

```
TypeError: undefined is not an object (evaluating 'this.selectedAnswerOptions.findIndex')
(45 additional frame(s) were not displayed)
...
  at next ([native code])
```

### LINKED ISSUE #5150: Do not use service worker if the browser does not support them
Sentry Issue: [ARTEMIS-KXB](https://sentry.ase.in.tum.de/organizations/artemis/issues/20828/?referrer=github_integration)

```
Error: Uncaught (in promise): Error: Service workers are disabled or not supported by this browser
checkForUpdate@https://artemis.ase.in.tum.de/main.418311382fc804c9.js:1:6147
checkForUpdates@https://artemis.ase.in.tum.de/main.418311382fc804c9.js:1:230688
g...
(6 additional frame(s) were not displayed)
...
  at onInvokeTask (webpack:/./node_modules/@angular/core/fesm2020/core.mjs:25621:33)
  at invokeTask (webpack:/./node_modules/zone.js/fesm2015/zone.js:406:31)
  at apply (webpack:/./node_modules/zone.js/fesm2015/zone.js:1278:17)
  at resolvePromise (webpack:/./node_modules/zone.js/fesm2015/zone.js:1165:17)
  at resolvePromise (webpack:/./node_modules/zone.js/fesm2015/zone.js:1211:31)
```

### PR DESCRIPTION
**Pull request by bottbenj**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Description
https://sentry.ase.in.tum.de/organizations/artemis/issues/22481/?project=2 / Closes #5149 
When using the refresh button to refresh to a started quiz things would be in an invalid state after loading the quiz exercise and before loading the quiz participation.

#### Steps for Testing
1. One synchronized Quiz that hasn't started and isn't scheduled
2. Go to the participation page reload it with F5 to break the websocket refresh (see #5024)
3. Start the quiz in another tab
4. use the refresh button in the quiz participation footer
5. See that no errors have occurred in the browser console

#### Manual Tests
- [x] Test 1
- [x] Test 2

### Description
https://sentry.ase.in.tum.de/organizations/artemis/issues/22534/?project=2
When a quiz participation times out without the student ever saving anything, the resulting submission has no submitted answers at all (not even empty ones)
Also the scoring explanation would have an unfilled placeholder for the achieved score.

#### Steps for Testing
1. One batched Quiz (can also happen in individual mode)
2. Add a batch
3. Join it
4. Start batch batch
5. End Now the quiz (or otherwise wait for it to expire without clicking any option or submitting as the student)
6. view the results as the student
7. check that no error happens in the browser console
8. check that the scoring explanation doesn't have an unfilled placeholder

#### Manual Tests
- [x] Test 1
- [x] Test 2

### Description
https://sentry.ase.in.tum.de/organizations/artemis/issues/21981/events/77b3d74488314fef8f49f7b7169e6172/?project=2
This is almost certainly just a user error when using a invalid password for joining batches. I made the error message more specific and also showed it to the user when joining fails.

#### Steps for Testing
1. One batched Quiz (can also happen in individual mode)
2. Fail to join in various ways (wrong/expired password, joined in anther tab, the other tab has already completed the submission)
3. Check the error message (as with submission errors it is not translated, as the error comes from the server)

#### Manual Tests
- [x] Test 1
- [x] Test 2

### Description
https://sentry.ase.in.tum.de/organizations/artemis/issues/20828/?project=2 / Closes #5150
When service workers are disabled update checks would cause an unhandled promise rejection.
When the service worker is disable trigger the update prompt based on the `Content-Version` response header.

#### Steps for Testing
1. It is unclear how exactly service workers get disabled, there does not seem to be an option in any browser to do so
2. At least in firefox unregistering the service worker seems to somewhat disable them for that domain (in chrome the service worker will just come back immediately)
3. In the firefox dev tools click > Application > Service Worker > Unregister to break the service worker
   image
4. Navigate artemis a bit / wait
5. check that there are no errors in the console

#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Not changed
https://sentry.ase.in.tum.de/organizations/artemis/issues/21981/?project=2
these issues are documented in the code https://github.com/ls1intum/Artemis/blob/4d0d4e5883f927252394e75bdd7533977b1ff216/src/main/java/de/tum/in/www1/artemis/web/rest/ParticipationResource.java#L519-L525
and fixing that is a significantly bigger job that deserves its own PR

#### Code Review
- [ ] Review 1
- [ ] Review 2

### CODE REVIEW

File: src/main/webapp/app/core/interceptor/artemis-version.interceptor.ts [hunk 1]
```diff
@@ -67,12 +67,18 @@ export class ArtemisVersionInterceptor implements HttpInterceptor {
...
      * @private
      */
-    private checkForUpdates() {
+    private checkForUpdates(hasUpdate: boolean) {
+        // don't spam errors when service workers are not available, instead rely on the Content-Version header of responses
+        const update = this.updates.isEnabled ? this.updates.checkForUpdate() : Promise.resolve(hasUpdate);
+
         // first update the service worker
-        this.updates.checkForUpdate().then((updateAvailable: boolean) => {
+        update.then((updateAvailable: boolean) => {
```
Comment (bassner) [inline src/main/webapp/app/core/interceptor/artemis-version.interceptor.ts:81]: I think we'd need to bypass ``this.updates.activateUpdate()`` as well in L95, right? That would trigger an error as well
So if the sw is not enabled, we should just reload the page instead of telling the sw to update

**Comment by SimonPaul02** [comment]
@yuling-sun and I had a question: What is meant with participation page? 
image
or 
image
or the page where you participate as a student? 
Also, we have not been able to find a refresh button in the **footer**
Thank you in advance for clarification!

**Review by SimonPaul02 — APPROVED** [review]
Tested everything except the Firefox part. Works as described👌

**Review by yuling-sun — APPROVED** [review]
Tested everything except for the Firefox part on TS1. I tried to test the last issue, too, but didn't understand the instructions and what to look out for.

**Review by babyygemperor — APPROVED** [review]
Tested everything on ts1 on firefox, works as described.

**Review by rhubinger — APPROVED** [review]
Tested on TS2. Everything works fine.

**Comment by bottbenj** [comment]
I updated the testing steps for the service worker bit to clarify what i meant, but it is not exactly clear to me when service workers are unavailable, just what the consequences of that are.

**Review by bassner — CHANGES_REQUESTED** [review]

**Review by nadinesamyy — APPROVED** [review]
looks good

**Review by max-bergmann — APPROVED** [review]
Tested on TS2. Looks good

**Review by nadinesamyy — APPROVED** [review]
tested on ts3, works as described

**Review by Santia-go — APPROVED** [review]
Tested on TS1
All working as expected.
