### PR TITLE
`Plagiarism checks`: Disable status buttons during confirm and deny action to avoid concurrency issues

### LINKED ISSUE #6529: `Plagiarism cases`: The cases in the instructor plagiarism view are not being updated.
### Describe the bug

When a tutor `confirm` a case, this case is shown in the `course management>course> Plagiarism cases` as a list. 
However, when a tutor deny the case, the list is not updated (remove the previous case). 

### To Reproduce

1. Run the plagiarism check of one exercise and confirm some cases. 
2. As an instructor check the list of cases 
3. As tutor, deny the previous confirmed cases 
4. Check if the list is updated. 
5. check if the columns are sorted correctly (see the screenshot)

### Expected behavior

Confirm or deny some cases, should update the list that the instructor have. 

### Screenshots

image

### Which version of Artemis are you seeing the problem on?

6.1.5

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jakubriegel**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

Fixes #6529 

### Description

Block both status button when REST call is performed or confirmation pop up is on.

### Steps for Testing

First reproduce the issue on `development`:
1. Create text exercises.
2. Submit two identical submissions for it.
3. Run plagiarism checks.
4. Open plagiarism results.
5. Open Network tab in dev tool and set network throttling to 3G.
6. Confirm the submission and see that buttons were enabled during the REST call.
7. Deny the submission and see that button was enabled during the REST call and pop up on.

Deploy this branch and do steps 4 and 5. Then set up throttling and verify that both buttons are always disabled during the REST call or pop up on.

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| plagiarism-header.component.ts | 100% | ✅                           |

### CODE REVIEW

**Review by undernagruzez — COMMENTED** [review]
Tested on ts2 and ts3. Was able to reproduce the abovementioned behavior on ts3 with develop deployed on it. The buttons stayed deactivated on ts2 during request processing.

**Review by SolizerCodes — APPROVED** [review]
Tested on ts1, works fine there.

**Review by rriyaldhi — DISMISSED** [review]
Code change looks good.

**Review by DominikRemo — DISMISSED** [review]
Code LGTM

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-header/plagiarism-header.component.ts [hunk 1]
```diff
@@ -39,13 +40,16 @@ export class PlagiarismHeaderComponent {
...
+            this.askForConfirmationOfDenying(() => this.updatePlagiarismStatus(PlagiarismStatus.DENIED));
         } else {
             this.updatePlagiarismStatus(PlagiarismStatus.DENIED);
         }
     }
 
-    private askForConfirmation(onConfirm: () => void) {
+    private askForConfirmationOfDenying(onConfirm: () => void) {
+        // change the status to dirty so that both buttons are disabled
+        this.plagiarismStatusDirty = true;
```
Comment (JohannesStoehr) [inline src/main/webapp/app/exercises/shared/plagiarism/plagiarism-header/plagiarism-header.component.ts:51]: Why is a denied plagiarism case considered 'dirty'?
Or is the name of the variable misleading?

**Review by FreshLlamanade — APPROVED** [review]
Code tested on ts3, works as advertised

**Review by SabrinaGlatz — DISMISSED** [review]
tested on ts1. Works as expected.

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-header/plagiarism-header.component.ts (hunk 1 above)
Comment (jakubriegel) [reply src/main/webapp/app/exercises/shared/plagiarism/plagiarism-header/plagiarism-header.component.ts:51]: The dirty flag is set here, so that both buttons are disabled when pop up is on

Comment (JohannesStoehr) [reply src/main/webapp/app/exercises/shared/plagiarism/plagiarism-header/plagiarism-header.component.ts:51]: I get that.
But this does not explain why it is considered `dirty`. If the name of the variable does not make sense in this context please change it to something like `disableConfirmDenyButton`

Comment (jakubriegel) [reply src/main/webapp/app/exercises/shared/plagiarism/plagiarism-header/plagiarism-header.component.ts]: Agree!
I did the change. I also added one missing flow on cancelling the pop up

**Review by DominikRemo — APPROVED** [review]
Reapprove Code

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-header/plagiarism-header.component.ts [hunk 2]
```diff
@@ -48,13 +48,13 @@ export class PlagiarismHeaderComponent {
 
     private askForConfirmationOfDenying(onConfirm: () => void) {
         // change the status to dirty so that both buttons are disabled
```
Comment (rriyaldhi) [inline src/main/webapp/app/exercises/shared/plagiarism/plagiarism-header/plagiarism-header.component.ts:50]: Since you remove the dirty word, I think this needs to be adjusted as well.

**Review by SabrinaGlatz — APPROVED** [review]
tested on ts1, works as expected

**Review by JohannesStoehr — APPROVED** [review]
Code looks good to me

**Review by krusche — APPROVED** [review]
