### PR TITLE
`Plagiarism check`: Fix display of escaped characters

### LINKED ISSUE #6120: `Plagiarism check`: Some characters are presented differently in the code comparison.
### Describe the bug

Some characters are presented differently in the code comparison view 

### To Reproduce

1. Go to course management.
2. Click on any programming exercise and submit two code like this: 
 `while (!isWon() && this.hero.isAlive())`
4. Verify in the plagiarism case view that for the first `&` character is being modify by `&amp;`

### Expected behavior

Should present the correct code. 

### Screenshots

Plagiarism check view: 
Screenshot 2023-01-20 at 18 42 04

Code view in the repo: 
Screenshot 2023-01-20 at 18 43 13

### Which version of Artemis are you seeing the problem on?

5.12.9

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.

### Motivation and Context
1) Closes #6120 
2) The Distribution chart gets displayed in reverse:
grafik

### Description
1) #5991 introduced escaping for the plagiarism view. However, this makes the resulting text longer, and the provided start and end indices of JPlag were no longer valid. In some cases, this leads to a highlighted text starting in between an escaped character as seen in the issue.

2) JPlag 4.1.0 fixed this bug and now returns the correct order. Our workaround code is no longer needed. See https://github.com/jplag/JPlag/pull/794

### Steps for Testing
1) This is a bit tricky to reproduce since you need a JPlag match stating directly after an `>` character. 

2) Run a new plagiarism check and see that the chart displays the results correctly.

### Test Coverage
unchanged

### CODE REVIEW

**Review by krusche — DISMISSED** [review]
Code changes look good 👍

**Review by simon-hng — DISMISSED** [review]
Code

**Review by krusche — DISMISSED** [review]
code looks good 👍

**Review by rriyaldhi — APPROVED** [review]
Tested on TS1 using this programming exercise: [https://artemis-test1.artemis.in.tum.de/course-management/40/programming-exercises/1917](https://artemis-test1.artemis.in.tum.de/course-management/40/programming-exercises/1917)

1. Similarity distribution is displayed as expected: [https://artemis-test1.artemis.in.tum.de/course-management/40/programming-exercises/1917/plagiarism](https://artemis-test1.artemis.in.tum.de/course-management/40/programming-exercises/1917/plagiarism)
image

2. Code is displayed as expected: [https://artemis-test1.artemis.in.tum.de/course-management/40/plagiarism-cases/84](https://artemis-test1.artemis.in.tum.de/course-management/40/plagiarism-cases/84)
image

**Review by stefanwaldhauser — APPROVED** [review]
LGTM!

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts [hunk 1]
```diff
@@ -201,47 +201,86 @@ export class TextSubmissionViewerComponent implements OnChanges {
...
             const idxLineTo = match.to.line - 1;
 
-            const idxColumnFrom = match.from.column - 1 + offsets[idxLineFrom];
+            const idxColumnFrom = match.from.column - 1;
+            const idxColumnTo = match.to.column + match.to.length - 1;
 
-            if (rows[idxLineFrom]) {
-                rows[idxLineFrom] = this.insertToken(rows[idxLineFrom], this.tokenStart, idxColumnFrom);
-                offsets[idxLineFrom] += this.tokenStart.length;
+            if (!rows[idxLineFrom]) {
```
Comment (bassner) [inline src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts:246]: In don't get this check somehow. So if the first line of the match is empty you skip the entire match. Why? Technically, a match could start in an empty line with ``column === 0``, can it?

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts [hunk 2]
```diff
@@ -201,47 +201,86 @@ export class TextSubmissionViewerComponent implements OnChanges {
...
             }
+            result += this.tokenStart;
 
-            const idxColumnTo = match.to.column + match.to.length - 1 + offsets[idxLineTo];
+            if (idxLineFrom === idxLineTo) {
+                result += escape(rows[idxLineFrom].slice(idxColumnFrom, idxColumnTo)) + this.tokenEnd;
+            } else {
+                result += escape(rows[idxLineFrom].slice(idxColumnFrom));
+                for (let j = idxLineFrom + 1; j < idxLineTo; j++) {
+                    if (rows[j]) {
```
Comment (bassner) [inline src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts:256]: What if the line is just empty (``''``)? Shouldn't we add it regardless? Or are you intentionally removing empty lines from the output?

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts [hunk 3]
```diff
@@ -201,47 +201,86 @@ export class TextSubmissionViewerComponent implements OnChanges {
...
+                        result += '\n' + escape(rows[j]);
+                    }
+                }
+                result += escape(rows[idxLineTo].slice(0, idxColumnTo)) + this.tokenEnd;
```
Comment (bassner) [inline src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts:260]: I think we'd need a line break here, similar to the lines above in the loop. Or am I wrong? 🤔 
```suggestion
                result += '\n' + escape(rows[idxLineTo].slice(0, idxColumnTo)) + this.tokenEnd;
```

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts [hunk 4]
```diff
@@ -201,47 +201,86 @@ export class TextSubmissionViewerComponent implements OnChanges {
...
-                offsets[idxLineTo] += this.tokenEnd.length;
+            // escape everything up until the next match (or the end of the string if there is no more match)
+            if (i === matches.length - 1) {
+                result += escape(rows[idxLineTo].slice(idxColumnTo));
+                for (let j = idxLineTo + 1; j < rows.length; j++) {
+                    if (rows[j]) {
+                        result += '\n' + escape(rows[j]);
+                    }
+                }
+            } else if (matches[i + 1].from.line === match.to.line) {
```
Comment (bassner) [inline src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts:271]: What if the next match is an invalid one (with ``from`` missing)? You check this in the beginning of the match loop, but you access it before the next match is checked by these safeguards here.
*If you change the code to filter out invalid matches above, ignore this comment*

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts [hunk 5]
```diff
@@ -201,47 +201,86 @@ export class TextSubmissionViewerComponent implements OnChanges {
         return this.matches.has(file);
     }
 
-    insertToken(text: string, token: string, position: number) {
-        // prevent negative values because slice does not handle them as we would wish
-        if (position < 0) {
-            position = 0;
+    insertMatchTokens(fileContent: string): string {
+        const matches = this.getMatchesForCurrentFile().sort((m1, m2) => {
+            if (!m1.from || !m1.to || !m2.from || !m2.to) {
```
Comment (bassner) [inline src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts:206]: What if we just filter the invalid matches instead of including them in the sort?
You skip them in the loop below anyways, so to avoid incidents we could just entirely ignore them.
We can still capture an exception for such cases in the filter function.

**Review by bassner — CHANGES_REQUESTED** [review]
Hey I have a few questions regarding ``insertMatchTokens`` :)

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts (hunk 2 above)
Comment (Strohgelaender) [reply src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts:256]: The previous code did such checks, so I just kept them everywhere. But I think you are right, they are not needed. The array is created by splitting a string, so undefined is not possible, and empty strings should be kept.

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts (hunk 5 above)
Comment (Strohgelaender) [reply src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts:206]: Great idea 👍

File: src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts (hunk 1 above)
Comment (Strohgelaender) [reply src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts:246]: This check was already in the code, I just inverted it here. But I agree, I don't see why this is needed.

**Review by bassner — APPROVED** [review]
Thanks for addressing my comments. The code looks good now ✅
