### PR TITLE
Avoid ArrayOutOfBoundsException when invalid Bitbucket URL is given. This fixes #92.

### LINKED ISSUE #92: ArrayIndexOutBoundsException when invalid Bitbucket URL is given.
When an invalid URL (with less then 3 slashes in the path), is given when creating a programming exercise, an ArrayIndexOutBoundsException occurs.

### PR DESCRIPTION
**Pull request by sleiss**

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/service/BitbucketService.java [hunk 1]
```diff
@@ -107,16 +107,24 @@ public URL getRepositoryWebUrl(Participation participation) {
 
     private String getProjectKeyFromUrl(URL repositoryUrl) {
         // https://ga42xab@repobruegge.in.tum.de/scm/EIST2016RME/RMEXERCISE-ga42xab.git
-        return repositoryUrl.getFile().split("/")[2];
+        String[] urlParts = repositoryUrl.getFile().split("/");
+        if (urlParts.length > 2) {
+            return urlParts[2];
+        }
+        return "";
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/service/BitbucketService.java]: what happens in the other code parts, in case we return "" here?
Of course we avoid an exception, but do we have any side effects when using an empty string? (sometimes an exception might be better)

File: src/main/java/de/tum/in/www1/artemis/service/BitbucketService.java [hunk 2]
```diff
@@ -107,16 +107,24 @@ public URL getRepositoryWebUrl(Participation participation) {
...
+        if (urlParts.length > 3) {
+            String repositorySlug = urlParts[3];
+            if (repositorySlug.endsWith(".git")) {
+                repositorySlug = repositorySlug.substring(0, repositorySlug.length() - 4);
+            }
+            return repositorySlug;
         }
-        return repositorySlug;
+        return "";
     }
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/service/BitbucketService.java]: what happens in the other code parts, in case we return "" here?
Of course we avoid an exception, but do we have any side effects when using an empty string? (sometimes an exception might be better)

File: src/main/java/de/tum/in/www1/artemis/service/BitbucketService.java (hunk 1 above)
Comment (sleiss) [reply src/main/java/de/tum/in/www1/artemis/service/BitbucketService.java]: In theory thats right, however I can only imagine of having an invalid URL when creating the exercise (here the repositoryUrlIsValid-method will return false because BitBucket cannot find the repository if either the project slug or repo name is empty). In any other case, we assume we have a correct URL (as we assume we only create correct URLs).

File: src/main/java/de/tum/in/www1/artemis/service/BitbucketService.java (hunk 2 above)
Comment (sleiss) [reply src/main/java/de/tum/in/www1/artemis/service/BitbucketService.java]: Same as above.

File: src/main/java/de/tum/in/www1/artemis/service/BitbucketService.java (hunk 1 above)
Comment (sleiss) [reply src/main/java/de/tum/in/www1/artemis/service/BitbucketService.java]: @krusche I just thought about it, an exception problably really is better. I will change it.
