### PR TITLE
[Enhancement] Handle manual results on trigger-all

### LINKED ISSUE #2213: ‘Trigger All’ with Manual Assessments present results in inconsistent database state
### Describe the bug
Clicking ‘Trigger All’ in the ‘Configure Grading’ view after manual assessments are created results in them being neither editable nor a tutor being able to create new ones for that student.
The previous manual feedback is still considered partially present by Artemis.

#### To Reproduce
1. Create a Programming Exercise with a manual assessment.
2. Submit a solution as a student.
3. Wait until after the due date and submit a manual assessment as a tutor.
4. Click ‘Trigger All’ in the ‘Configure Grading’ view.
5. The manual submission is no longer available, but no new one can be created for that student.

#### Expected behaviour
The warning when clicking ‘Trigger All’ mentions that all manual assessments will be overwritten by the new automatic feedback. That should enable a tutor to create a new manual assessment even if one existed beforehand.

In my opinion a good improvement over fully removing the manual assessments would be to put all existing ones back into draft mode, so that the existing feedback is not fully lost, but a manual interaction by the tutor to review them is still necessary.

#### Screenshots
The tutor view shows inconsistent behaviour after reproduction steps. The status at the top mentions an existing manual assessment, but it can no longer be changed.
Screenshot_20201015_220722

### Environment

<details><pre>
 - Version: 4.6.1
 - Setup with Jenkins+Gitlab
</pre></details>

### PR DESCRIPTION
**Pull request by schultek**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

Trigger-All currently does not handle manual results. 
Resolves #2213 

### Description

Whenever a new automatic result is generated and a manual or semi-automatic result exists, these two results are combined into a new semi-automatic result with:

- The automatic feedback from the automatic result
- The manual feedback from the manual result
- The assessor and state (draft / completed) from the manual result
- A new calculated score and scoreString

### Steps for Testing

1. Log in to Artemis
2. Create or use a programming exercise with manual review enabled.
3. Add one or two participations and manual assessments.
4. Change the grading config (test case weights, sca penalties) and press 'Trigger All'.
5. Wait for the build completion and check the results. 
   - They should consist of the unchanged manual feedback
   - combined with the updated automatic feedback
   - and have the correct score and score-string assigned.
 6. Check the results in all places they are shown: Course Details, Exercise Details, Code Editor, Scores Page (as Instructor)

### Test Coverage

 * ProgrammingExerciseGradingService: 95%

### Screenshots

No UI changes

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java [hunk 1]
```diff
@@ -106,6 +110,60 @@ public ProgrammingExerciseGradingService(ProgrammingExerciseTestCaseService test
...
+
+                    ProgrammingSubmission newSubmission = programmingSubmissionService.createSubmissionWithLastCommitHashForParticipation(participation, SubmissionType.MANUAL);
+                    Result newResult = programmingSubmissionService.setNewResult(newSubmission);
+                    newResult.setAssessor(manualResult.getAssessor());
+                    newResult.setAssessmentType(AssessmentType.SEMI_AUTOMATIC);
+                    newResult.setCompletionDate(manualResult.getCompletionDate());
+                    newResult.setHasFeedback(manualResult.getHasFeedback());
+                    newResult.setRated(manualResult.isRated());
+
+                    for (Feedback feedback : result.getFeedbacks()) {
```
Comment (fde312) [inline src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:130]: Maybe we can do it like we did it on `ProgrammingExerciseGradingService:462`

File: src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseStudentParticipationRepository.java [hunk 2]
```diff
@@ -27,7 +27,8 @@
     Optional<ProgrammingExerciseStudentParticipation> findByIdWithLatestResultAndFeedbacksAndRelatedSubmissions(@Param("participationId") Long participationId,
             @Param("dateTime") ZonedDateTime dateTime);
 
-    @Query("select p from ProgrammingExerciseStudentParticipation p left join fetch p.results pr left join fetch pr.feedbacks left join fetch pr.submission left join fetch pr.assessor where p.id = :participationId and (pr.assessmentType = 'MANUAL' or pr.assessmentType = 'SEMI_AUTOMATIC')")
+    @Query("select p from ProgrammingExerciseStudentParticipation p left join fetch p.results pr left join fetch pr.feedbacks left join fetch pr.submission left join fetch pr.assessor"
+            + " where p.id = :participationId and pr.id = (select max(prr.id) from p.results prr where prr.assessmentType = 'MANUAL' or prr.assessmentType = 'SEMI_AUTOMATIC')")
```
[the remark this answers is not in the document]
Comment (schultek) [reply src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseStudentParticipationRepository.java:31]: Well with this PR there can be multiple :)

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java (hunk 1 above)
Comment (schultek) [reply src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:130]: Yes. 👍

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java [hunk 3]
```diff
@@ -106,6 +110,60 @@ public ProgrammingExerciseGradingService(ProgrammingExerciseTestCaseService test
...
+                        .findStudentParticipationWithLatestManualResultsAndFeedbacksAndRelatedSubmissionsAndAssessor(participation.getId());
+                if (studentParticipation.isPresent() && studentParticipation.get().getResults().stream().findFirst().isPresent()) {
+
+                    Result manualResult = studentParticipation.get().getResults().stream().findFirst().get();
+
+                    ProgrammingSubmission newSubmission = programmingSubmissionService.createSubmissionWithLastCommitHashForParticipation(participation, SubmissionType.MANUAL);
+                    Result newResult = programmingSubmissionService.setNewResult(newSubmission);
+                    newResult.setAssessor(manualResult.getAssessor());
+                    newResult.setAssessmentType(AssessmentType.SEMI_AUTOMATIC);
+                    newResult.setCompletionDate(manualResult.getCompletionDate());
```
[the remark this answers is not in the document]
Comment (schultek) [reply src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:134]: We decided to keep the completion state as is, so that tutors does not need to go through all submissions again.

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java [hunk 4]
```diff
@@ -115,6 +119,47 @@ public ProgrammingExerciseGradingService(ProgrammingExerciseTestCaseService test
...
+                    newResult.setRated(manualResult.isRated());
+
+                    for (Feedback feedback : result.getFeedbacks()) {
+                        Feedback newFeedback = feedback.copyProgrammingAutomaticFeedbackForManualResult();
+                        newResult.addFeedback(newFeedback);
+                    }
+
+                    for (Feedback feedback : manualResult.getFeedbacks()) {
+                        if (feedback != null && feedback.getType() != FeedbackType.AUTOMATIC) {
+                            Feedback newFeedback = feedback.copyProgrammingAutomaticFeedbackForManualResult();
```
[the remark this answers is not in the document]
Comment (schultek) [reply src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java]: Done

**Review by airelawaleria — APPROVED** [review]
Tested in the testing session with @JohannesWeiss @simonzilker @EneaGore @marvinchimeka . Tested with different test cases (with/without bonus points, manual/without manual review), all worked fine

**Review by JohannesWeiss — DISMISSED** [review]
Tested in testing session and works as intended. Some numbers are rounded (11.77 in detail view, 11.8 in the overview), but correctly.

**Review by EneaGore — DISMISSED** [review]
Tested in testing session, all looks good.

**Review by marvinchimeka — DISMISSED** [review]
Tested in a testing session. Approve.

**Comment by simonzilker** [comment]
Approve!

**Review by simonzilker — DISMISSED** [review]
Tested in testing session. Approve!

**Review by JohannesStoehr — DISMISSED** [review]
Works as expected!

**Review by sebastiantpeter — APPROVED** [review]
Tested on ts1. The bug seems to be fixed.

**Review by SimonEntholzer — APPROVED** [review]
Looks good, all seemed to work during testing :+1:

**Review by nicolasruscher — DISMISSED** [review]
looks good!

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java [hunk 5]
```diff
@@ -115,6 +119,58 @@ public ProgrammingExerciseGradingService(ProgrammingExerciseTestCaseService test
...
+
+                    // copy all feedback from the automatic result
+                    for (Feedback feedback : result.getFeedbacks()) {
+                        Feedback newFeedback = feedback.copyFeedback();
+                        newResult.addFeedback(newFeedback);
+                    }
+
+                    // copy only the non-automatic feedback from the manual result
+                    for (Feedback feedback : manualResult.getFeedbacks()) {
+                        if (feedback != null && feedback.getType() != FeedbackType.AUTOMATIC) {
```
Comment (kloessst) [inline src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:151]: Can it actually happen, that `feedback == null` here?

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java [hunk 6]
```diff
@@ -115,6 +119,58 @@ public ProgrammingExerciseGradingService(ProgrammingExerciseTestCaseService test
...
+                        }
+                    }
+
+                    // recalculate the score and set the result string
+                    double maxScore = getMaxScoreRespectingZeroPointExercises(programmingExercise);
+                    double points = programmingAssessmentService.calculateTotalScore(newResult);
+                    newResult.setScore(points, maxScore);
+
+                    String resultString = result.getResultString() + ", " + newResult.createResultString(points, maxScore);
+                    newResult.setResultString(resultString);
```
Comment (kloessst) [inline src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:163]: We have similar statements in updateResultString(). We could factor this out into a new method to avoid code duplication.

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java [hunk 7]
```diff
@@ -115,6 +119,58 @@ public ProgrammingExerciseGradingService(ProgrammingExerciseTestCaseService test
                 // This method will return without triggering the build if the submission is not of type TEST.
                 triggerTemplateBuildIfTestCasesChanged(programmingExercise.getId(), result.getId());
             }
+
+            if (!isSolutionParticipation && !isTemplateParticipation) {
```
Comment (kloessst) [inline src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:123]: We could factor this block out into an own method to keep the top level grading method short and simpler.

**Review by kloessst — COMMENTED** [review]
Haven't tested yet, code looks fine! Just small remarks:

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java [hunk 8]
```diff
@@ -115,6 +119,58 @@ public ProgrammingExerciseGradingService(ProgrammingExerciseTestCaseService test
...
+
+                // check if a manual result exists, if so we want to clone and update this with the new updated test-case and sca feedback
+                Optional<ProgrammingExerciseStudentParticipation> studentParticipation = programmingExerciseParticipationService
+                        .findStudentParticipationWithLatestManualResultsAndFeedbacksAndRelatedSubmissionsAndAssessor(participation.getId());
+
+                if (studentParticipation.isPresent() && studentParticipation.get().getResults().stream().findFirst().isPresent()) {
+
+                    Result manualResult = studentParticipation.get().getResults().stream().findFirst().get();
```
Comment (MaisiKoleni) [inline src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:131]: I think we should use the latest result, not the first when iterating through a set. It is not impossible that a participation has two manual results (be it later because of the second correction). Could we use `findLatestResult()` here?

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java [hunk 9]
```diff
@@ -115,6 +119,58 @@ public ProgrammingExerciseGradingService(ProgrammingExerciseTestCaseService test
...
+
+                    // create a new manual result for the same submission as the automatic result
+                    Result newResult = programmingSubmissionService.saveNewEmptyResult(result.getSubmission());
+
+                    newResult.setAssessor(manualResult.getAssessor());
+                    newResult.setAssessmentType(AssessmentType.SEMI_AUTOMATIC);
+                    // this makes it the most recent result, but optionally keeps the draft state of an unfinished manual result
+                    newResult.setCompletionDate(manualResult.getCompletionDate() != null ? result.getCompletionDate().plusSeconds(1) : null);
```
Comment (MaisiKoleni) [inline src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:139]: Just a thought: I hope it is safe/tested here that the tutors will not see two unfinished results (and only the latest one is used and submitted).

File: src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseStudentParticipationRepository.java (hunk 2 above)
Comment (MaisiKoleni) [inline src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseStudentParticipationRepository.java:31]: Could we use better names instead of `pr` and `prr`? At least the last one does express what it is in my eyes, or is this to indicate that we have multiple results at this point? Would `prs` be better or worse?

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java (hunk 8 above)
Comment (MaisiKoleni) [reply src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:131]: The repository method here is
```
findStudentParticipationWithLatestManualResultsAndFeedbacksAndRelatedSubmissionsAndAssessor
```
but the one in the changes above is 
```
findByIdWithLatestManualResultAndFeedbacksAndRelatedSubmissionsAndAssessor
```
In particular, the first one mentions "Result***s***" and the latter only "Result". Is this something we need to worry about?

**Review by MaisiKoleni — CHANGES_REQUESTED** [review]
See inline comments, some things don't match from my point of view (f they do, we should document why).

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java (hunk 8 above)
Comment (schultek) [reply src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:131]: There is only ever one result returned from the repository method.

Comment (schultek) [reply src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:131]: I will rename this to singular.

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java (hunk 9 above)
Comment (schultek) [reply src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:139]: Yes only the latest one is then used for further manual assessments.

File: src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseStudentParticipationRepository.java (hunk 2 above)
Comment (schultek) [reply src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseStudentParticipationRepository.java:31]: This is also used at other places

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java (hunk 7 above)
Comment (schultek) [reply src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:123]: Done

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java (hunk 6 above)
Comment (schultek) [reply src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:163]: Done

File: src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java (hunk 5 above)
Comment (schultek) [reply src/main/java/de/tum/in/www1/artemis/service/ProgrammingExerciseGradingService.java:151]: I had that once when testing locally

**Review by MaisiKoleni — APPROVED** [review]
Code looks good to me.

**Review by JohannesWeiss — CHANGES_REQUESTED** [review]
Tested in testing session with @marvinchimeka, @simonzilker, @airelawaleria on ts2. After triggering the new  builds with the updated grading criteria the students could not see the manual feedback that was given before (contrary to the statement from the testing instructions). In the assessment dashboard still 3/3 submissions were shown as graded.

**Review by simonzilker — CHANGES_REQUESTED** [review]
What @JohannesWeiss said.

**Review by airelawaleria — CHANGES_REQUESTED** [review]
Same reasoning as @JohannesWeiss

**Review by marvinchimeka — CHANGES_REQUESTED** [review]
Agreeing with @JohannesWeiss's statement. tested on ts2

**Comment by schultek** [comment]
@JohannesWeiss Which course and exercise did you use?

**Comment by JohannesWeiss** [comment]
> @JohannesWeiss Which course and exercise did you use?
`Valeryia's Course > tetetetettee` on ts2

**Comment by schultek** [comment]
I cannot reproduce this. For me it works when re-triggering.

**Review by EneaGore — COMMENTED** [review]
Tested on ts1 and i can not repsroduce it either. To me it actually works exactly as described.

**Review by JohannesWeiss — APPROVED** [review]
Re-Tested it with @schultek, @airelawaleria, @simonzilker and @LudwigWeide on ts1 and it works now. There seemingly was some other reason hindering the correct behaviour, but it works as intended now.

**Review by marvinchimeka — APPROVED** [review]
tested it in testing session. Approve

**Review by simonzilker — APPROVED** [review]
Approve!

**Review by airelawaleria — APPROVED** [review]
Approve

**Review by LudwigWeide — APPROVED** [review]
tested it in testing session. Approve

**Review by krusche — APPROVED** [review]
