### PR TITLE
[Bugfix] Validation of Misleading Mappings for Short Answer Questions

### LINKED ISSUE #1711: Quiz, Short-Answer Question: question is marked as invalid when a answer option is correct for multiple fields
### Describe the bug

This bug appears during the creation of a quiz when adding new short-answer questions.
When adding an answer option that is correct in multiple fields, the quiz can't be saved, since the short-answer question is marked as invalid.

#### To Reproduce

1. Go to Course Management
2. Go to Exercises
3. Click on Create Quiz
4. Click on Add Short-Answer Question
5. add a title for the quiz and a title for the question
6. see that the template is still marked as invalid
_(7. let each answer only be valid for one field -> the question is valid)_

#### Expected behavior

It should be possible to save the quiz with an answer option for a short-answer question that is valid for multiple fields.

#### Screenshots

distributetQuizScheduling#1644-templateFor

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Google Chrome 83.0.4103.116
</pre></details>

### PR DESCRIPTION
**Pull request by fde312**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) locally.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Fixes #1711.

### Description

- Rewrote logic for misleading mappings
- Added tests

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create new Quiz Exercise with a Short Answer Question
4. Type in quiz and question title
5. Try out different mappings (solvable and unsolvable) and check if the validation is correct. You can orientate on the screenshots below, but please try out also different ones (you can also orientate on the test case in short-answer-question-util.service.spec.ts)

### Test Coverage

image

### Screenshots

1 to 1 mapping:
image

1 to 1 and n to 1 mappings:
image

n to m mappings:
image

Misleading mapping -> unsolvable question (if "is" is used for spot 1 then spot 2 cannot be solved correctly anymore):
image

### CODE REVIEW

**Review by airelawaleria — DISMISSED** [review]
validation worked correctly

**Review by JohannesWeiss — APPROVED** [review]
Worked for me on ts1 with the different mappings. The validation was often rather slow to update, though.

**Review by marvinchimeka — APPROVED** [review]
Tested on ts1. Worked with the 1 to 1,  1 to 1, n to 1 and n to m Mappings. For invalid mappings i get the invalid input error like it was intended. So no issues could be found

**Review by simonzilker — APPROVED** [review]
Looks good :)

File: src/main/webapp/app/exercises/quiz/manage/statistics/short-answer-question-statistic/short-answer-question-statistic.component.ts [hunk 1]
```diff
@@ -118,19 +118,4 @@ export class ShortAnswerQuestionStatisticComponent extends QuestionStatisticComp
...
         this.updateData();
     }
-
-    /**
-     * Get the solution that was mapped to the given spot in the sample solution
-     *
-     * @param spot {object} the spot that the solution should be mapped to
-     * @return the mapped solution or undefined if no solution has been mapped to this location
-     */
-    correctSolutionForSpot(spot: ShortAnswerSpot) {
```
Comment (FrankeLukas) [inline src/main/webapp/app/exercises/quiz/manage/statistics/short-answer-question-statistic/short-answer-question-statistic.component.ts:128]: This removes the only usage of `ShortAnswerSpot` which causes an "defined but never used" warning on line 11 now. (=> Remove the import.)

**Review by tiffca — APPROVED** [review]
Tested successfully

**Review by EneaGore — APPROVED** [review]
Looks good.

**Review by DenizShabani — DISMISSED** [review]
Looks good!

**Review by nicolasruscher — DISMISSED** [review]
Did not test it, but code looks good to me :)

File: src/main/webapp/app/exercises/quiz/manage/statistics/short-answer-question-statistic/short-answer-question-statistic.component.ts (hunk 1 above)
Comment (fde312) [reply src/main/webapp/app/exercises/quiz/manage/statistics/short-answer-question-statistic/short-answer-question-statistic.component.ts:128]: Done :)

File: src/test/javascript/spec/service/short-answer-question-util.service.spec.ts [hunk 2]
```diff
@@ -134,13 +134,79 @@ describe('ShortAnswerQuestionUtil', () => {
...
+        const mapping2 = new ShortAnswerMapping(spot2, solution2);
+        const mapping3 = new ShortAnswerMapping(spot3, solution3);
+
+        shortAnswerQuestion.correctMappings!.push(mapping2, mapping3);
+        let hasNoMisleadingMapping = service.validateNoMisleadingShortAnswerMapping(shortAnswerQuestion);
+        expect(hasNoMisleadingMapping).to.be.true;
+
+        const mapping4 = new ShortAnswerMapping(spot2, solution);
+        shortAnswerQuestion.correctMappings!.push(mapping4);
+        hasNoMisleadingMapping = service.validateNoMisleadingShortAnswerMapping(shortAnswerQuestion);
```
Comment (iozbeyli) [inline src/test/javascript/spec/service/short-answer-question-util.service.spec.ts:175]: This gets repeated a lot, I think it can be moved into a function.

Comment (fde312) [reply src/test/javascript/spec/service/short-answer-question-util.service.spec.ts]: Done :)

**Review by airelawaleria — APPROVED** [review]
tested one more time with different edge cases, workes as described :)

**Review by JohannesWeiss — APPROVED** [review]
Still works as intended.

**Review by marvinchimeka — APPROVED** [review]
Re-tested. Validation still works so Re-approve

**Review by DenizShabani — APPROVED** [review]

**Review by simonzilker — APPROVED** [review]

**Review by nicolasruscher — APPROVED** [review]
re-approve 👍

**Review by krusche — APPROVED** [review]
