### PR TITLE
`Assessment`: Fix access to duplicated submissions with same commit hash

### LINKED ISSUE #5430: getProgrammingSubmissionWithoutAssessment returns wrong submissionId
### Describe the bug

In some edge cases [getProgrammingSubmissionWithoutAssessment](https://github.com/ls1intum/Artemis/blob/1a0a647ffb7d70ade81bc4f2330e54a0163d904c/src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingSubmissionResource.java#L422)
Returns an invalid / wrong submissionId

image

I've created a "double" submission by (I assume) clicking multiple times on submit.
The mentioned endpoint returns 651 in its Lock Object. This is actually wrong.
It has to return specify 652.

In the submission overview the link is correctly generated:
image

Clicking on "Start new assessment" leads to the wrong submission
image

May be related to https://github.com/ls1intum/Artemis/issues/5145

### To Reproduce

See above

### Expected behavior

See above

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

Fix #5430 where duplicated programming submissions with the same commit hash were not consistently assessed correctly.

### Description

Submissions with the same commit hash now use their ID for sorting, since the submission date might not be accurate in such cases. This will now consistently use the same submission

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. See linked issue and try to reproduce it

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

File: src/main/java/de/tum/in/www1/artemis/domain/participation/Participation.java [hunk 1]
```diff
@@ -279,7 +279,7 @@ private <T extends Submission> Optional<T> findLatestSubmission(boolean includeI
         }
 
         return (Optional<T>) submissions.stream().max((s1, s2) -> {
-            if (s1.getSubmissionDate() == null || s2.getSubmissionDate() == null) {
+            if (s1.getSubmissionDate() == null || s2.getSubmissionDate() == null || s1.getSubmissionDate().equals(s2.getSubmissionDate())) {
```
Comment (dfuchss) [inline src/main/java/de/tum/in/www1/artemis/domain/participation/Participation.java:282]: This does not resolve the issue for me. I guess thats the case because the submission dates are not equal, but hashsums are.

```
mysql> select * from submission where id=656 or id=657;
+---------------+-----+----------+----------------------+-----------------+------------------------------------------+------------------+----------------------------+-----------+------+------------------+----------------------------------------+-------+----------+----------------------------+--------------------------------+------------+
| discriminator | id  | jhi_type | submitted            | score_in_points | commit_hash                              | participation_id | submission_date            | file_path | text | explanation_text | example_submission                     | model | language | build_failed               | build_artifact                 | quiz_batch |
+---------------+-----+----------+----------------------+-----------------+------------------------------------------+------------------+----------------------------+-----------+------+------------------+----------------------------------------+-------+----------+----------------------------+--------------------------------+------------+
| P             | 656 | MANUAL   | 0x01                 |            NULL | 9bca4d27a373bb47fa7fd4cbb3a22cfa61156049 |              285 | 2022-07-19 11:34:56.017944 | NULL      | NULL | NULL             | NULL                                   | NULL  | NULL     | 0x00                       | 0x00                           |       NULL |
| P             | 657 | MANUAL   | 0x01                 |            NULL | 9bca4d27a373bb47fa7fd4cbb3a22cfa61156049 |              285 | 2022-07-19 11:34:56.044334 | NULL      | NULL | NULL             | NULL                                   | NULL  | NULL     | 0x00                       | 0x00                           |       NULL |
+---------------+-----+----------+----------------------+-----------------+------------------------------------------+------------------+----------------------------+-----------+------+------------------+----------------------------------------+-------+----------+----------------------------+--------------------------------+------------+
```

**Review by dfuchss — CHANGES_REQUESTED** [review]

**Review by dfuchss — APPROVED** [review]
Tested on our test-system. It works :)

**Review by Dominik-Weinzierl — APPROVED** [review]
Looks good to me!

**Review by nairaarnez — APPROVED** [review]
Tested in TS1, couldn't reproduce the issue #5430. Clicking on "Start new assessment" led me to the right submission:+1:.

File: src/main/java/de/tum/in/www1/artemis/domain/Submission.java [hunk 2]
```diff
@@ -327,4 +327,14 @@ public void removeNotNeededResults(int correctionRound, Long resultId) {
     public Result getResultWithComplaint() {
         return results.stream().filter(result -> Boolean.TRUE.equals(result.hasComplaint())).findFirst().orElse(null);
     }
+
+    @Override
+    public int compareTo(Submission other) {
+        if (getSubmissionDate() == null || other.getSubmissionDate() == null) {
+            // this case should not happen, but in the rare case we can compare the ids
+            // newer ids are typically later
```
Comment (Strohgelaender) [inline src/main/java/de/tum/in/www1/artemis/domain/Submission.java:335]:
```suggestion
            // higher ids are typically later
```

File: src/test/java/de/tum/in/www1/artemis/domain/ExerciseTest.java [hunk 3]
```diff
@@ -203,29 +210,43 @@ void filterForCourseDashboard_submissionsWithRatedResultsOrder() {
...
+        submission1.commitHash("same");
+        submission2.commitHash("same");
+        submission3.commitHash("same");
+
+        submission1.setId(42L);
+        submission2.setId(21L);
+        submission3.setId(15L);
+
+        exerciseService.filterForCourseDashboard(exercise, filterForCourseDashboard_prepareParticipations(), "student", true);
+        assertThat(exercise.getStudentParticipations().iterator().next().getSubmissions()).isEqualTo(Set.of(submission1));
```
Comment (Strohgelaender) [inline src/test/java/de/tum/in/www1/artemis/domain/ExerciseTest.java:242]:
```suggestion
        assertThat(exercise.getStudentParticipations().iterator().next().getSubmissions()).containsExactly(submission1);
```
