### PR TITLE
Enhancement/improve score accuracy

### LINKED ISSUE #2969: Rounding Error in the Scoring System and CSV Export
### Describe the bug
Point seem to be reconstructed incorrectly from the achieved percentages for exercises.

Example: Exercise with 15 points, student scores 10 points.  The system reports 67%.  In the CSV export, the system use 67% out of 15 points max, which is 10.05 points.  This is then rounded to 10.1 points which is clearly wrong and can lead to accumulated errors.

#### To Reproduce
Create test exam, with one exercise and grade it such that it has a max of 15 points and score 10 points; or 15 max and 7 pt; or 15pt and 13pt.

#### Expected behavior
Correctly store the scored points and do not use the achieved percentage to reconstruct the scored points from it.

#### Screenshots
Screenshot:
image

### Environment
n/a

#### Additional context
n/a

#### Output in Web Console
n/a

### PR DESCRIPTION
**Pull request by krusche**
Fixes #2969 

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
Artemis stores `result.score` as integer between 0 and (typically) 100 %.
In case `result.score` would have been a floating value (e.g. 2/3 points = 66.666666%), Artemis immediately rounded it to 67%, loosing precision when calculating the points later on using `result.score * exercise.maxPoints`. This led to rounding errors as described in #2969

### Description
Change `result.score` to double and only round on the client:
* Round scores (e.g. 67 %) in the client (user interface and various csv export) to 0 decimal places
* Round points (e.g. 10.5 points) in the client (user interface and various csv export) to 1 decimal place based on the max points of the exercise: `round(result.score * exercise.maxPoints, 1)`

### Steps for Testing
1. Check existing and new results to all kinds of exercises (course and exam)
2. Create manual (text, modeling, file-upload, programming) and automatic results (programming, quiz)
3. Make sure the score (%) and points calculation is correct: score in % with 0 decimal places (except specific places with 1 decimal place), points with 1 decimal place
4. Check the csv exports (for courses and exams) if they are correct
5. Test explicitly the case mentioned in the issue #2969

### Screenshots
Now we...

... correctly format the result string:
grafik

... properly format additional and inline feedback:
grafik
grafik

... format the values for the course scores:
grafik

... and export formatted values for course and exercise scores:
grafik
grafik

### CODE REVIEW

**Review by stefanwaldhauser — APPROVED** [review]
Amazing work @krusche and @stefanwaldhauser. You are the best!

**Review by SimonEntholzer — DISMISSED** [review]
Good code changes, just tested on TS3, works nice :D :+1:

**Comment by iozbeyli** [comment]
On assessment dashboard, it looks like this

Screenshot_2021-03-07 Exercise Assessment Dashboard

**Comment by stefanwaldhauser** [comment]
> On assessment dashboard, it looks like this
> 
> Screenshot_2021-03-07 Exercise Assessment Dashboard

Good catch! Done in 4dbfb6ea473046ea564e778b5ba687f3cd46bc64

**Review by iozbeyli — APPROVED** [review]
Code looks good and couldn't see any more issues

**Review by FrankeLukas — COMMENTED** [review]
Some observations:
- We are inconsistent with the spacing around the percent sign, but that should probably be handled in a different PR
- The programming (edit: actually all exercise types?) exercise scores overview does still round to two decimal places:
grafik
- In the export the percentage is not rounded, is that intentional?
grafik

**Review by FrankeLukas — DISMISSED** [review]
Updated. Now we...

... correctly format the result string:
grafik

... properly format additional and inline feedback:
grafik
grafik

... format the values for the course scores:
grafik

... and export formatted values for course and exercise scores:
grafik
grafik

File: src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/dto/TestResultsDTO.java [hunk 1]
```diff
@@ -37,7 +37,7 @@ public static TestResultsDTO convert(Object someResult) {
         return new ObjectMapper().registerModule(new JavaTimeModule()).convertValue(someResult, TestResultsDTO.class);
     }
 
-    public int getSuccessful() {
+    public Integer getSuccessful() {
```
Comment (derLalla) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/dto/TestResultsDTO.java:40]: was this intentionally changed to `Integer`?

File: src/main/webapp/app/overview/course-score-calculation.service.ts [hunk 2]
```diff
@@ -51,7 +51,7 @@ export class CourseScoreCalculationService {
                         if (score == undefined) {
                             score = 0;
                         }
-                        pointsAchievedByStudentInCourse += score * this.SCORE_NORMALIZATION_VALUE * maxPointsReachableInExercise;
+                        pointsAchievedByStudentInCourse += round(score) * this.SCORE_NORMALIZATION_VALUE * maxPointsReachableInExercise;
```
Comment (derLalla) [inline src/main/webapp/app/overview/course-score-calculation.service.ts:54]: wouldn't it be better to round the whole statement? 

```suggestion
                        pointsAchievedByStudentInCourse += round(score * this.SCORE_NORMALIZATION_VALUE * maxPointsReachableInExercise);
```

**Review by derLalla — CHANGES_REQUESTED** [review]
the changes in the code look good. 
I have left two inline remarks, which I am not sure are correct.

File: src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingAssessmentIntegrationTest.java [hunk 3]
```diff
@@ -602,7 +594,8 @@ private void assessmentDueDatePassed() {
     private void overrideAssessment(HttpStatus httpStatus) throws Exception {
         var participation = programmingSubmission.getParticipation();
         var result = programmingSubmission.getLatestResult();
-        result.setScore(75L);
+        assert result != null;
```
Comment (FuchsDominik) [inline src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingAssessmentIntegrationTest.java:597]:
```suggestion
        assertThat(result).isNotNull();
```
Because we use this formulation in other parts in this Test class

**Review by FuchsDominik — CHANGES_REQUESTED** [review]
In a programmingExercise of mine, points are still getting rounded to 2 decimal numbers (test_user_8)
Screenshot 2021-03-08 at 12 30 59

Also found some minor code improvements, nothing crucial, though :)

**Comment by FrankeLukas** [comment]
> In a programmingExercise of mine, points are still getting rounded to 2 decimal numbers (test_user_8)

That is because the result strings are set in the database like this. Once a new assessment is generated it will display the correct values. I don't think there's much else we can do here?

File: src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/dto/TestResultsDTO.java (hunk 1 above)
Comment (krusche) [reply src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/dto/TestResultsDTO.java:40]: I guess it can stay as int

Comment (FrankeLukas) [reply src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/dto/TestResultsDTO.java:40]: We needed this so we can use `.doubleValue`. I changed that place to a `(double)` cast so we can use `int` here.

**Comment by FrankeLukas** [comment]
I addressed the comments in https://github.com/ls1intum/Artemis/pull/2976/commits/e255208de8b3d5d5e52d3bf744dee8804c57b266.

**Review by airelawaleria — DISMISSED** [review]
tested in the testing session. everything worked as expected

**Review by JohannesWeiss — DISMISSED** [review]
Tested in testing session on ts1, did not encounter issues with the scores.

**Review by simonzilker — DISMISSED** [review]
tested in testing session. Looks good :)

**Review by EneaGore — APPROVED** [review]
Lg on ts1

**Review by FuchsDominik — APPROVED** [review]
code looks good to me now :)

File: src/main/webapp/app/course/course-scores/course-scores.component.ts [hunk 4]
```diff
@@ -224,7 +227,7 @@ export class CourseScoresComponent implements OnInit, OnDestroy {
                         console.warn('found more than one result for student ' + student.user.login + ' and exercise ' + exercise.title);
                     }
 
-                    const pointsAchievedByStudentInExercise = (result.score! * relevantMaxPoints) / 100;
+                    const pointsAchievedByStudentInExercise = round((result.score! * relevantMaxPoints) / 100, 1);
```
Comment (MaisiKoleni) [inline src/main/webapp/app/course/course-scores/course-scores.component.ts:230]: Could we change the decimal places to two here? It seems that this would round quarter points to `.3` and quarter points are relatively common I would say.

File: src/main/webapp/app/course/course-scores/course-scores.component.ts [hunk 5]
```diff
@@ -224,7 +227,7 @@ export class CourseScoresComponent implements OnInit, OnDestroy {
...
                     student.overallPoints += pointsAchievedByStudentInExercise;
```
Comment (MaisiKoleni) [inline src/main/webapp/app/course/course-scores/course-scores.component.ts:231]: I think we should round the overall points as late as possible and add the most accurate score we can archive here. Otherwise, small errors like the quarter points add up again.

File: src/main/webapp/app/course/course-scores/course-scores.component.ts [hunk 6]
```diff
@@ -316,19 +319,19 @@ export class CourseScoresComponent implements OnInit, OnDestroy {
...
-                            rowData[title] = this.localeConversionService.toLocaleString(exercisePointValues[index]);
+                            rowData[title] = this.localeConversionService.toLocaleString(round(exercisePointValues[index], 1));
                         });
                         rowData[exerciseTypeName + ' ' + POINTS_KEY] = this.localeConversionService.toLocaleString(exercisePointsPerType);
                         rowData[exerciseTypeName + ' ' + SCORE_KEY] = this.localeConversionService.toLocalePercentageString(exerciseScoresPerType);
                     }
                 }
 
-                const overallScore = (student.overallPoints / this.maxNumberOfOverallPoints) * 100;
+                const overallScore = round((student.overallPoints / this.maxNumberOfOverallPoints) * 100);
```
Comment (MaisiKoleni) [inline src/main/webapp/app/course/course-scores/course-scores.component.ts:334]: I don't know if it would be beneficial to have at least one decimal place here like we currently have in the scores report.

File: src/main/webapp/app/course/course-scores/course-scores.component.ts [hunk 7]
```diff
@@ -382,7 +385,7 @@ export class CourseScoresComponent implements OnInit, OnDestroy {
                 }
             }
 
-            const averageOverallScore = (this.averageNumberOfOverallPoints / this.maxNumberOfOverallPoints) * 100;
+            const averageOverallScore = round((this.averageNumberOfOverallPoints / this.maxNumberOfOverallPoints) * 100);
```
Comment (MaisiKoleni) [inline src/main/webapp/app/course/course-scores/course-scores.component.ts:388]: I would add at least one decimal place here as well.

**Review by MaisiKoleni — CHANGES_REQUESTED** [review]
I think there are still rounding errors adding up, and quarter points could be problematic as well. I added some comments for the course scores, but it is quite likely that this also applies to the exam scores and the student course statistics.

File: src/main/webapp/app/course/course-scores/course-scores.component.ts (hunk 5 above)
Comment (stefanwaldhauser) [reply src/main/webapp/app/course/course-scores/course-scores.component.ts:231]: This decision was made with @krusche. If I understood it correctly, this is correct as we want to round on the individual exercise level.

File: src/main/webapp/app/course/course-scores/course-scores.component.ts (hunk 4 above)
Comment (stefanwaldhauser) [reply src/main/webapp/app/course/course-scores/course-scores.component.ts:230]: This decision was made with @krusche. If I understood it correctly, this is correct as we want to round on the individual exercise level. The decision was made to round to 1 decimal place here.

File: src/main/webapp/app/course/course-scores/course-scores.component.ts (hunk 6 above)
Comment (stefanwaldhauser) [reply src/main/webapp/app/course/course-scores/course-scores.component.ts]: Done in 86b66a17e3722f0f0c70d375ea39e9a39f681e37

File: src/main/webapp/app/course/course-scores/course-scores.component.ts (hunk 7 above)
Comment (stefanwaldhauser) [reply src/main/webapp/app/course/course-scores/course-scores.component.ts]: Done in 86b66a17e3722f0f0c70d375ea39e9a39f681e37

**Review by philgabr — COMMENTED** [review]
works well for model, text, quiz (also the csv exports)

I'd agree that 0.25 is quite common and therefore should be possible. Also when rounding, maybe it would be better to round in favor with the students, e.g. ((totalPoints+1) / maxPoints * 100)
image

File: src/main/webapp/app/course/course-scores/course-scores.component.ts (hunk 4 above)
Comment (krusche) [reply src/main/webapp/app/course/course-scores/course-scores.component.ts:230]: I'm not a big fan of quarter points, in particular if we then would get issues with half points. We previously had issues that rounding to 2 places led to cases in which we suddenly had 2,99 or 3,01 points instead of 3,0

I would suggest we investigate this further in a follow-up PR in which we also write a lot of tests to make sure the behavior is always correct

File: src/main/webapp/app/course/course-scores/course-scores.component.ts (hunk 5 above)
Comment (krusche) [reply src/main/webapp/app/course/course-scores/course-scores.component.ts:231]: The problem with rounding late is as follows:
If we show the student 5 times that he has 1,1 points in an exercise while he actually has 1,05 then rounding the sum would be quite problematic, because suddenly the student would have 5,25 -> 5,3 points even if the actual sum of 5 times 1,1 points would lead to 5,5 points. Of course we could round to more decimal places but then the same issue can occur.
So I would think the best solution is to decide on the exercise level how to round and then take the sum of all rounded values. This will not lead to confusion. Also I don't think we should be too critical to small rounding errors on the exercise level. They will only occur on programming exercises in the future and won't affect manually corrected exercises, except reviewers give weiter points

File: src/main/webapp/app/course/course-scores/course-scores.component.ts (hunk 4 above)
Comment (krusche) [reply src/main/webapp/app/course/course-scores/course-scores.component.ts:230]: By the way: you can prevent quarter points by simply doubling the number of overall points in an exercise / exam. Then you can simply give half points.

In the future, we could let the instructor decide what kind of precision (in terms of decimal places) is desired in the course / exam and use this for rounding in all places.

**Comment by stefanwaldhauser** [comment]
> works well for model, text, quiz (also the csv exports)
> 
> I'd agree that 0.25 is quite common and therefore should be possible. Also when rounding, maybe it would be better to round in favor with the students, e.g. ((totalPoints+1) / maxPoints * 100)
> image

Fixed this in a7bd88bada2888ca506130758a71578ee911681d. It will, however, only show up for new results as the bug was in the creation of the result string.

**Review by nicolasruscher — DISMISSED** [review]
code looks good to me!

**Review by SimonEntholzer — APPROVED** [review]
Re-approve

**Review by FrankeLukas — APPROVED** [review]
The display on the course scores pages no longer seems to reflect the output of the csv export. Everything else seems to work as intended (and code changes lgtm too).
