### PR TITLE
`Programming exercises`: Concatenate testsuite names with testcase names in LocalCI

### LINKED ISSUE #9688: LocalCI: Nested Testsuites are handled incorrectly
### Describe the bug

JUnit-XMLs support nested test suited. This is for example extensively used by the Haskell template.

Before, if there was a nested test suite like:
```xml
<testsuite name="Properties">
    <testsuite name="Checked by QuickCheck">
        <testcase name="Test A against sample solution"/>
    </testsuite>
</testsuite>
```
the resulting test name was `Properties.Checked by QuickCheck.Testing A against sample solution`. Currently it is only `Test A against sample solution`.

The old behaviour should be restored.

### To Reproduce

1. Create a new Haskell exercise.
2. The exercise description contains test cases like `Properties.Checked by QuickCheck.Testing A against sample solution`.

However, Artemis only receives test cases with the partial name after the last dot like `Testing A against sample solution`.

### Expected behavior

The full test name including the names of the test suites is retained. The original name as in the exercise template is returned as test case name to Artemis. This restores the old behaviour.

Keeping only the last section of the name and adapting the template is not the preferred solution:
- Two different exercise descriptions for setups using LocalCI and Jenkins would have to be defined.
- The old behaviour that concatenated the test suite + final test names with a `.` in between resulted in unique test cases. This can no longer be ensured when using only the last part. Tests in different test suites are allowed to have the same name.
- Existing exercises created in Bamboo, before 7.6.1, or in Jenkins setups may depend on the original behaviour.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

7.6.5

### What browsers are you seeing the problem on?

Firefox

### Additional context

The flattening of `Testsuite` objects has been implemented already in the Jenkins plugin:
https://github.com/ls1intum/jenkins-server-notification-plugin/blob/798ffccb8d55186e468ffedb552cf12f43e1855e/src/main/java/de/tum/in/www1/jenkins/notifications/model/Testsuite.java#L98

It can potentially be ported over to Artemis to work the same way when parsing results of LocalCI jobs.

---

Relevant previous PR: #9490

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by magaupp**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

The Jenkins parser concatenates the names of deeply nested `<testsuite>` elements to the `<testcase>` names to produce the final test result name, while leaving out the top-level `<testsuite>` name.
LocalCI currently only uses the `<testcase>` name.

### Description

The names of `<testsuite>` elements which are not top-level are concatenated like with the Jenkins parser.
Additionally, the case of multiple top-level `<testsuite>` elements in a `<testsuites>` root element is handled.
There the names of the top-level `<testsuite>` elements are included in the result.

Fixes #9688.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Create a programming exercise using the Haskell language template
2. Wait until the Solution build finishes
3. Click on the Solution result
4. The feedback should have names like `Properties.Checked by SmallCheck.Testing filtering in A`

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| TestResultXmlParser.java | 97% | ✅ |

## Summary by CodeRabbit

- **New Features**
	- Enhanced test result processing to support both single and multiple test suites, improving clarity in results.
	- Added new test methods to validate parsing of nested test suites and multiple test suites.

- **Bug Fixes**
	- Updated assertions in tests to reflect new naming conventions for test cases, ensuring accurate reporting.

- **Refactor**
	- Improved method names and parameters for better clarity and functionality in test result processing.

### CODE REVIEW

**Review by b-fein — APPROVED** [review]
Thanks for the quick fix. Code looks good.

I’ll test tomorrow and also adapt the Jenkins plugin to handle the `<testsuites>` case.

**Review by sachmii — APPROVED** [review]
Tested on TS2. 

Bildschirmfoto 2024-11-06 um 21 33 18

File: src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java [hunk 1]
```diff
@@ -33,31 +36,63 @@
...
+    private static void processTestSuiteWithNamePrefix(TestSuite testSuite, List<BuildResult.LocalCITestJobDTO> failedTests, List<BuildResult.LocalCITestJobDTO> successfulTests,
+            String namePrefix) {
         for (TestCase testCase : testSuite.testCases()) {
             if (testCase.isSkipped()) {
                 continue;
             }
             Failure failure = testCase.extractFailure();
             if (failure != null) {
-                failedTests.add(new BuildResult.LocalCITestJobDTO(testCase.name(), List.of(failure.extractMessage())));
+                failedTests.add(new BuildResult.LocalCITestJobDTO(namePrefix + testCase.name(), List.of(failure.extractMessage())));
```
[the remark this answers is not in the document]
Comment (magaupp) [reply src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java:81]: Adding null to a string will not cause a NullPointerException, but will add "null" to the string

**Review by HawKhiem — APPROVED** [review]
Tested on TS3. Works as described

image

**Review by flbrgit — DISMISSED** [review]
Tested on TS3, everything works as described, if the last three tests "Unit Tests.Testing selectAndReflect" are intentional. Then everything wokrs fine.
Screenshot 2024-11-07 153037

**Comment by Strohgelaender** [comment]
We just recently introduced that handling of nested test suites into Artemis, right? So there should not be a lot of exercises on production instanced that would be affected by this change, right?

Since the test case name is used as an identifier, a change in how they are read could break a lot of exercises, so I want to make sure that this only affects littes (to basically none) currently active exercises.

**Comment by b-fein** [comment]
@Strohgelaender PR #9490 introduced this recently. So only Haskell exercises created with or after Artemis version 7.6.1 might be affected.

**Review by kevinfischer4 — APPROVED** [review]
Tested on TS2, works as expected.
image

File: src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java [hunk 2]
```diff
@@ -33,31 +36,63 @@ public static void processTestResultFile(String testResultFileString, List<Build
         testResultFileString = testResultFileString.replaceAll(INVALID_XML_CHARS, "");
         TestSuite testSuite = mapper.readValue(testResultFileString, TestSuite.class);
 
-        // A toplevel <testsuites> element is parsed like a <testsuite>
-        processTestSuite(testSuite, failedTests, successfulTests);
+        // The toplevel element can be <testsuites> or <testsuite>
+        if (testResultFileString.contains("<testsuites")) {
```
Comment (Strohgelaender) [inline src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java:40]: Do we need to to the string for this check? Can't this be done on the parsed objects?

```suggestion
        if (testSuite.testSuites().size() > 0) {
```

Comment (magaupp) [reply src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java:40]: It's not that easy, I'm afraid. Both `<testsuites>` and `<testsuite>` can contain other testsuites. We need to distinct a `<testsuites>` root element from a `<testsuite>` root element because the name of the highest-level `<testsuite>` tag needs to be ignored. This means the name of a `<testsuite>` under the root `<testsuites>` is ignored, while the name of a `<testsuite>` under a root `<testsuite>` is kept because the root's name is ignored.

Comment (Strohgelaender) [reply src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java:40]: Could you have a boolean-parameter like `testsuitesFound` that gets passed through recursivly? This can be used to decided if the name should be appended, and the value gets changed one the level got round.

Comment (magaupp) [reply src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java:40]: I'm not sure what you mean. The impact of the `<testsuites>` element is only on its direct child `<testsuite>` elements. All deeper nested `<testsuite>`s should have their names prepended.

**Review by HanyangXu0508 — DISMISSED** [review]
Locally tested and worked as expectred.

File: src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java (hunk 2 above)
Comment (Strohgelaender) [reply src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java:40]: I'm also not sure if my understanding of what you want to accive is correct now (Btw, if this is a quite complicated logic we should test all these cases and further extend the current server tests)

From my interpretation the main difference if wheter when traversing the nested `testsuite` and `testsuites` we have hit a point where we found a `testsuites` element. Then, the name construction below should only use the local name. So we can just pass a boolean-Parameter that tells the level below if the top-level is such a element, and then create the name accordingly.

Well, since you wrote `hightest level` we would need anotother boolean to indicate if we already found one such element before. With that, we should have all information we neeed (what is me parent, and was that parent the first such element) to create a fitting name.

Again, this behaviour should be documented and tested. I can already see it breaking just becuase the next developer didi not even know about testsuites in testsuites.

Comment (magaupp) [reply src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java:40]: I think the confusion comes from the equal parsing of `<testsuites>` and `<testsuite>`. I can create a distinct record to make it clear that no further `<testsuites>` should occur.

Comment (magaupp) [reply src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java:40]: I also get that the documentation/naming is confusing. How can we improve this?

**Review by sawys777 — DISMISSED** [review]
TestingHaskell
Tested on TS1, everything worked as described.

**Review by Haoyuli2002 — COMMENTED** [review]
Tested on TS3 as User 17(Instructor). I created a new programming exercise and click the solution result. It shows exactly as expected. Everything is working fine so far.

**Comment by magaupp** [comment]
Jackson cannot inspect the root element name while parsing. That is why I used the "<testcases" string check.
I can replace Jackson with JAXB in a follow-up PR. JAXB allows selecting a class based on the root tag.

**Comment by magaupp** [comment]
I just got feedback, that we would rather keep Jackson parsing. I replaced the plain string check with a regex, which only checks the XML root tag.

File: src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java [hunk 3]
```diff
@@ -31,33 +36,74 @@ public class TestResultXmlParser {
...
+                for (TestSuite suite : testSuites.testSuites()) {
+                    processInnerTestSuite(suite, failedTests, successfulTests, "");
+                }
+            }
+        }
+        else {
+            TestSuite testSuite = mapper.readValue(testResultFileString, TestSuite.class);
+            processTopLevelTestSuite(failedTests, successfulTests, testSuite);
+        }
+    }
```
[the remark this answers is not in the document]
Comment (magaupp) [reply src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java]: We want to keep using Jackson.

The `has()` method of JsonNode looks at the names of the children, and not the name of the element itself.

**Review by raffifasaro — DISMISSED** [review]
Code

File: src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java [hunk 4]
```diff
@@ -20,8 +22,16 @@ public class TestResultXmlParser {
     // https://stackoverflow.com/a/4237934
     private static final String INVALID_XML_CHARS = "[^\t\r\n -\uD7FF\uE000-�\uD800\uDC00-\uDBFF\uDFFF]";
 
+    private static final Pattern XML_ROOT_TAG_IS_TESTSUITES = Pattern.compile("^(<\\?([^?]|\\?[^>])*\\?>|<!--(-?[^-])*-->|<!DOCTYPE[^>]>|\\s)*<testsuites(\\s|/?>)",
+            Pattern.DOTALL);
```
[the remark this answers is not in the document]
Comment (magaupp) [reply src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java:26]: 1. Jackson's tree model can't access the name of the root object.
2. We need to support potential XML declarations and comments before the root tag.

**Review by b-fein — DISMISSED** [review]
Code looks good.

I also tried a bit around with Jackson, but I could also not find a way to preserve the XML root element. So using the regex is probably the sensible approach without requiring another XML parsing library.

**Review by sachmii — APPROVED** [review]

**Review by sawys777 — APPROVED** [review]

**Review by Cathy0123456789 — APPROVED** [review]
Tested on TS3. Works as described.

**Review by chrisknedl — APPROVED** [review]
Code

**Review by krusche — DISMISSED** [review]
Please add more JavaDoc (also add this to private methods) and inline comments so the code is easier to understand. Also comment the regex pattern to make it easer to understand.

File: src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java [hunk 5]
```diff
@@ -20,8 +22,16 @@ public class TestResultXmlParser {
...
+
     /**
      * Parses the test result file and extracts failed and successful tests.
+     * The name of nested testsuite elements are prepended with dots to the testcase name.
+     * A singular top-level testsuite is not included in the name.
+     * If multiple top-level testsuite elements are present, their names will be included.
+     * Top-level testsuite elements refer to direct children of the root &lt;testsuites&gt; element or
+     * the root &lt;testsuite&gt; element itself.
```
Comment (krusche) [inline src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java:34]: please add an example here how the XML files can look like

File: src/test/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParserTest.java [hunk 6]
```diff
@@ -240,10 +240,77 @@ void testNestedTestsuite() throws IOException {
...
+                "Properties.Checked by QuickCheck.Testing C against sample solution",
+                "Unit Tests.Testing selectAndReflectA (0,0) []",
+                "Unit Tests.Testing selectAndReflectB (0,1) [(0,0)]",
+                "Unit Tests.Testing selectAndReflectC (0,1) [(-1,-1)]");
+        // @formatter:on
+        assertThat(failedTests).isEmpty();
+    }
+
+    @Test
+    void testMultipleTestsuite() throws IOException {
```
Comment (krusche) [inline src/test/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParserTest.java:263]: can you add a few more examples with different nesting structures?

Comment (magaupp) [reply src/test/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParserTest.java:263]: More tests added in https://github.com/ls1intum/Artemis/pull/9691/commits/cda222a86afc911b8f139ba888e92aed811adf3d

File: src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java [hunk 7]
```diff
@@ -20,8 +21,54 @@ public class TestResultXmlParser {
     // https://stackoverflow.com/a/4237934
     private static final String INVALID_XML_CHARS = "[^\t\r\n -\uD7FF\uE000-�\uD800\uDC00-\uDBFF\uDFFF]";
 
+    // The root element can be preceded by processing instructions (<? ... ?>), comments (<!-- ... -->),
+    // a doctype declaration (<!DOCTYPE ... >) and whitespace.
+    // Comments cannot contain the string "--".
+    private static final Pattern XML_ROOT_TAG_IS_TESTSUITES = Pattern.compile("^(<\\?([^?]|\\?[^>])*\\?>|<!--(-?[^-])*-->|<!DOCTYPE[^>]*>|\\s)*<testsuites(\\s|/?>)",
+            Pattern.DOTALL);
```
[the remark this answers is not in the document]
Comment (magaupp) [reply src/main/java/de/tum/cit/aet/artemis/buildagent/service/TestResultXmlParser.java:28]: I checked the regex for exponential backtracking. This is not possible here.

**Review by chrisknedl — APPROVED** [review]

**Review by sachmii — COMMENTED** [review]
Tested on TS4, I receive a build error for the template and solution somehow:

Bildschirmfoto 2024-12-02 um 17 26 30
Bildschirmfoto 2024-12-02 um 17 27 10

**Comment by magaupp** [comment]
Looks like `ghcr.io/uni-passau-artemis/artemis-haskell:v22.37.0` can't be pulled anymore in general. This is also the case outside of Artemis.

```docker pull ghcr.io/uni-passau-artemis/artemis-haskell:v22.37.0```
fails with
```manifest unknown```

@b-fein Any idea what's happening here?

**Comment by b-fein** [comment]
> @b-fein Any idea what's happening here?

No idea why GitHub forget the image. I triggered a rebuild. It should work again now.

**Review by HawKhiem — APPROVED** [review]
Tested on TS2 again. Works as described

image

**Review by ItsaaaMeMario — APPROVED** [review]
Tested on TS2, everything works as expected. 
Bildschirmfoto 2024-12-03 um 13 35 02

**Review by krusche — APPROVED** [review]
