### PR TITLE
`Programming exercises`: Prevent tree compression for single files within the online code editor

### LINKED ISSUE #6988: `Programming exercises`: Inconvenient to rename files in online editor
### Describe the bug

When there is only one file under a folder, click "edit" to rename the file, the text field will show the whole path of the file. Users need to delete the path string before the file name to rename the file successfully, otherwise will get the error.

### To Reproduce

1. Go to programming exercise editor
2. Create folder1/folder2/file.txt
3. Click "edit" and only change the name of file.txt

### Expected behavior

A better organized file structure in online editor: users can just input the new name they want like in IDE, don't need to do any other things.

### Screenshots

image
image

### Which version of Artemis are you seeing the problem on?

6.3.8

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by DominikRemo**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
Fixes #6988 
Exam mode SS 23 - Issues Students#14
"When you create a single file in a new folder, it becomes a single file with a strange path" ~ @pal03377 
"One small problem I still have is that you still cannot rename a single non-empty folder in the "normal" compressed view"  ~ @pal03377 

### Description
- Changes to the compressTree method now prevent files from being compressed. Compression is, from now on, only enabled for folders.
- When compression is enabled, but a folder is not part of a compressed path, the folder can still be renamed. This is done by checking if a tree view item value contains '/' which indicates that the path of the folder has been compressed.
- When a folder is compressed, the rename button is disabled. However, from now on, the tooltip is still being presented to the user.

### Steps for Testing

Prerequisites:
- 1 Programming Exercise with online code editor enabled

1. Participate in programming exercise with online code editor
2. Create a new folder
3. Create a new file within this folder (step 2) -> The file should not be compressed 
4. Create a new folder
5. Create a new folder within this folder (step 4) -> empty folders should be compressed by default
_Note: You can still click the icon marked in the picture below for accessing individual nested folders_
Bildschirmfoto 2023-07-24 um 10 31 33

Also check:
- It's possible to rename uncompressed folders
- A tooltip is displayed for the rename button on hover, even if it is disabled
- Try various different paths that might break the introduced changes

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Before: By default, it was not possible to create new files in a folder when there was only a single file in that folder.
Bildschirmfoto 2023-07-24 um 09 15 13

After: By default, files get not compressed and new files can be created within a new folder. Folders do still get compressed.
Bildschirmfoto 2023-07-24 um 10 20 50

After: Displays tooltip for disabled button on hover (explaining how to enable the button).
Bildschirmfoto 2023-07-24 um 15 20 36

After: Nested but uncompressed folders can be renamed.
Bildschirmfoto 2023-07-24 um 15 20 41

### CODE REVIEW

File: src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser.component.ts [hunk 1]
```diff
@@ -379,7 +379,7 @@ export class CodeEditorFileBrowserComponent implements OnInit, OnChanges, AfterV
      * @param node Tree node
      */
     compressTree(node: FileTreeItem): FileTreeItem {
-        if (node.children && node.children.length === 1 && node.children[0].children) {
+        if (node.children && node.children.length === 1 && this.repositoryFiles[node.children[0].value] === FileType.FOLDER) {
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser.component.ts:382]: Can you add a comment here about why the if condition looks like this now?

**Review by pal03377 — DISMISSED** [review]
Thanks you for this improvement! 🚀  This is definitely better now.

I tested it on TS4 and I reviewed the code.

One small problem I still have is that you still cannot rename a single non-empty folder in the "normal" compressed view:

screenshot-2023-07-24_001671

(the rename button is disabled)

However, this was not possible before this PR as well (in fact, it caused an error before) => This PR only improves things 🎉 => I think this is fine for now

**Review by pal03377 — APPROVED** [review]
Good comments, thanks! 👍

File: src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser.scss [hunk 2]
```diff
@@ -77,6 +77,8 @@ File browser tree
             }
             button {
                 padding: 0;
+                border: none;
+                pointer-events: auto;
```
Comment (pal03377) [inline src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser.scss:81]: Why is this necessary? When I remove this in the DevTools, everything seems to still be fine 🤔

**Review by pal03377 — APPROVED** [review]
Great additional fix for the renaming! 🚀 🚀 🚀  
Tested on TS4 & looked at code

File: src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser.scss (hunk 2 above)
Comment (DominikRemo) [reply src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser.scss:81]: When the button is disabled, there was a weird border that I did not like ^^"

Also, it did not show the tooltip on hover, that tells you why the button is disabled. _It's weird how we had a tooltip explaining why a button is disabled that was not being displayed when the button was disabled_ O.o 
With ```pointer-events: auto``` the tooltip can now be displayed, even if the rename button is disabled

**Review by laadvo — APPROVED** [review]
Tested on ts1, single files no longer get compressed, code also looks good to me :)

File: src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-folder.component.html [hunk 3]
```diff
@@ -21,11 +21,11 @@
         <button [disabled]="disableActions" (click)="setCreatingNodeInFolder($event, FileType.FOLDER)" class="btn btn-small">
             <fa-icon [icon]="faFolder" title="{{ 'artemisApp.editor.fileBrowser.createFolder' | artemisTranslate }}"></fa-icon>
         </button>
-        <button [disabled]="disableActions || (isCompressed && item.children && item.children.length)" (click)="setRenamingNode($event)" class="btn btn-small">
+        <button [disabled]="disableActions || (isCompressed && item.value.includes('/'))" (click)="setRenamingNode($event)" class="btn btn-small">
```
Comment (JohannesStoehr) [inline src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-folder.component.html:24]: Tested on ts1: I can not rename a compressed folder that does not contain any elements

File: src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-folder.component.html [hunk 4]
```diff
@@ -21,11 +21,11 @@
...
             <fa-icon
                 [icon]="faEdit"
                 title="{{
-                    (!disableActions && isCompressed && item.children && item.children.length
+                    (!disableActions && isCompressed && item.value.includes('/')
```
Comment (JohannesStoehr) [inline src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-folder.component.html:28]: This tooltip is not shown for me

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]

File: src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-folder.component.html (hunk 3 above)
Comment (DominikRemo) [reply src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-folder.component.html:24]: Hi, this is expected behaviour, since we do not (yet?) support renaming compressed folders.

I also tested it on develop. Although renaming compressed files is not disabled on develop, I get an error when I try to rename compressed folders: "File operation could not be executed. Please try again later."

Image showing error on develop when trying to rename compressed folders
Bildschirmfoto 2023-07-26 um 11 19 30

File: src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-folder.component.html (hunk 4 above)
Comment (DominikRemo) [reply src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-folder.component.html:28]: I can not reproduce this locally nor on ts1.
What browser are you using? Could you provide a screencast, please?

**Review by RY997 — APPROVED** [review]
Tested on ts3, worked well. Really great improvement!

**Review by MaximilianAnzinger — APPROVED** [review]
Code LGTM

File: src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-folder.component.html (hunk 4 above)
Comment (JohannesStoehr) [reply src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-folder.component.html:28]: Ah, you're using `title`instead of `ngbTooltip` which has apparently a longer delay until it is shown to the user and I did not wait that long

Comment (DominikRemo) [reply src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser-folder.component.html:28]: Ahh, ok, nice that it works :)
