### PR TITLE
[Exam] Show error in client if submitting exam failed. Update Exam Page if student failed to submit on time

### LINKED ISSUE #1941: Finishing after grace period doesn't show error
### Describe the bug
When you let the grace period run out and enter your name you are able to click on fnish. Doing so will result in a 403 call however no error is shown to the user.

#### To Reproduce
1. Participate in an exam
2. Wait for the grace period to pass
3. Check and Fill in your name
4. Click on finish
5. See that nothing happens (watch the 403 in the Dev-Tools)

#### Expected behavior
Either make the button non clickable even if you enter the name and check the checkbox (with an additional information please) or show an dedicated error message if the call returns a 403.

#### Additional information
Ciritical because it can cause confusion in the exam which we want to prevent. And it should be easily resolved.

### PR DESCRIPTION
**Pull request by anditurdiu**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
Fixes #1941

### Description
- [x] Handle the 403 error thrown if not within the defined exam end time
- [x] Lock the submit button to protect against spamming
- [x] Hide all exam page elements in case the student fails to hand in on time and the exam will not be graded. 

### Steps for Testing
1. Participate in an exam
2. Press hand in early
3. Go offline, and confirm
4. You should be reported that submitting failed and that you should try again. The button should be unlocked as soon as you receive the error message. 
5. Go online
6. Wait for the grace period to pass
7. The exam end interactions should disappear and you should be informed that your exam will not be graded. 

### Screenshots
image

### CODE REVIEW

File: src/main/webapp/app/exam/participate/exam-participation.component.ts [hunk 1]
```diff
@@ -266,10 +267,19 @@ export class ExamParticipationComponent implements OnInit, OnDestroy, ComponentC
...
+        this.handInPossible = false;
         if (this.autoSaveInterval) {
             window.clearInterval(this.autoSaveInterval);
         }
-        this.examParticipationService.submitStudentExam(this.courseId, this.examId, this.studentExam).subscribe((studentExam) => (this.studentExam = studentExam));
+        this.examParticipationService.submitStudentExam(this.courseId, this.examId, this.studentExam).subscribe(
+            (studentExam) => (this.studentExam = studentExam),
+            (error: Error) => {
+                this.alertService.error(error.message);
+                // Explicitly check whether the error was caused because the submission was not in-time, in this case, set hand in not possible
```
Comment (JonasPetry) [inline src/main/webapp/app/exam/participate/exam-participation.component.ts:279]:
```suggestion
                // Explicitly check whether the error was caused by the submission not being in-time, in this case, set hand in not possible
```

File: src/main/webapp/i18n/de/exam.json [hunk 2]
```diff
@@ -268,6 +268,7 @@
     },
     "studentExam": {
         "alreadySubmitted": "Du hast bereits abgegeben.",
-        "submissionNotInTime": "Du kannst nur zwischen Start und Ende der Klausur abgeben."
+        "submissionNotInTime": "Du hast die Klausur nicht rechtzeitig abgegeben. Sie wird nicht bewertet!",
+        "handInFailed": "Die Abgabe der Klausur ist fehlgeschlagen. Bitte versuchen Sie es erneut!"
```
Comment (JonasPetry) [inline src/main/webapp/i18n/de/exam.json:272]:
```suggestion
        "handInFailed": "Die Abgabe der Klausur ist fehlgeschlagen. Bitte versuche es erneut!"
```
