### PR TITLE
`General`: Improve passkey error handling

### LINKED ISSUE #12414: `General`: Error message on passkey login when no passkey is registered is confusing
### Describe the bug

We improved the error message recently to indicate when accounts are deactivated, but now this error message also mistakenly displays, when a user just has not registered a passkey yet.

### To Reproduce

1. Enable Passkeys
```
artemis:
  user-management:
    passkey:
      enabled: true
```
2. Make sure you have no registered any passkeys (you can verify that in your user settings passkey section)
3. Log Out
4. Try to log in with passkey, pressing the button
5. See the misleading error message, the account is not deactivated, simply no passkey is registered

### Expected behavior

The error message should say that no passkey was registered, or at least not be misleading.

### Screenshots

Image

Image

<details>
<summary>Higher resolution video</summary>

https://github.com/user-attachments/assets/95599954-a99f-4a62-92da-dd246013e5f3

</details>

### Which version of Artemis are you seeing the problem on?

9.0.0

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by florian-glombik**
### Summary
Improve passkey error handling by distinguishing between different authentication failure scenarios: unregistered passkey, deactivated account, and general authentication errors. Previously, all failures showed misleading error messages (e.g., "your account has been deactivated" when no passkey was registered).

Fixes https://github.com/ls1intum/Artemis/issues/12414

#### General
- [x] I tested **all** changes and their related features locally
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.tum.de/developer/guidelines/language).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.tum.de/developer/development-process#pr-naming-conventions).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.tum.de/developer/guidelines/performance) and prevented too many (unnecessary) and too complex database calls. - we added a database call, but it is not a complex one and should not have a big performance impact
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).

#### Client
- [x] I **strictly** followed the [client coding guidelines](https://docs.artemis.tum.de/developer/guidelines/client-development).
- [x] I added multiple integration tests (Vitest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.tum.de/developer/guidelines/client-tests).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
When a user without a registered passkey attempted to log in with a passkey, the error message incorrectly stated "your account has been deactivated." This was caused by the client mapping all HTTP 401 responses to the deactivated-account error, while the server returned 401 for all authentication failures regardless of the cause.

Fixes https://github.com/ls1intum/Artemis/issues/12414

### Description

**Server changes:**
- Add `NoPasskeyFoundException` extending `AuthenticationException` for unregistered passkey credential IDs
- In `ArtemisWebAuthnAuthenticationProvider`: check if the credential ID exists before attempting verification; log an error and throw `NoPasskeyFoundException` if not found
- In `ArtemisWebAuthnAuthenticationFilter`: map exceptions to distinct HTTP status codes:
  - `UserNotActivatedException` → 403 (account deactivated)
  - `NoPasskeyFoundException` → 404 (no matching passkey registered)
  - All other failures → 401 (general authentication error)

**Client changes:**
- Fix `webauthn.service.ts` error handling to correctly map HTTP status codes to error messages:
  - 403 → "Login with Passkey failed because your account has been deactivated."
  - 404 → "No passkey was found for Artemis. Please make sure you have registered a passkey in your account settings, or use a different login method."
  - Other → "Login with Passkey failed. Please reload the page and try again."
- Add new `noPasskeyFound` translation key (English and German)
- Update existing error messages for clarity

### Steps for Testing
Prerequisites:
- 1 User with a registered passkey
- 1 User without a registered passkey
- 1 Deactivated user with a registered passkey

1. **No passkey registered:** Log in as a user without a registered passkey and attempt to use "Login with Passkey". Verify the error message says no passkey was found and suggests registering one or using a different login method.
2. **Deactivated account:** Attempt passkey login with a deactivated user's passkey. Verify the error message says the account has been deactivated. ⚠️ (can only be tested on ts3, make sure to also activate the test user again after you're done with testing)
3. **Successful login:** Log in with a valid passkey and verify it still works correctly.

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Code Review
- [x] Code Review 1
#### Manual Tests
- [x] Test 1

### Test Coverage

**Warning:** Client tests failed. Coverage could not be fully measured. Please check the [workflow logs](https://github.com/ls1intum/Artemis/actions/runs/24886346655).

#### Server

| Class/File | Line Coverage | Lines |
|------------|-------------:|------:|
| ArtemisWebAuthnAuthenticationFilter.java | 100.00% | 31 |
| ArtemisWebAuthnAuthenticationProvider.java | 100.00% | 81 |
| NoPasskeyFoundException.java | 100.00% | 10 |

_Last updated: 2026-04-24 11:21:18 UTC_

### Screenshots
image

image

passkeyImprovedErrorMessages

<details>
<summary>Higher resolution video</summary>

https://github.com/user-attachments/assets/6f9c5d6d-3cc3-43c3-ade2-ebc2e67aabc5

</details>

## Summary by CodeRabbit

* **Bug Fixes**
  * Passkey authentication now returns specific HTTP statuses: deactivated account → 403 Forbidden; missing passkey → 404 Not Found; other failures → 401 Unauthorized. Login flow also suppresses error alerts when the user cancels the authenticator dialog.

* **Documentation**
  * Updated user-facing passkey error messages to distinguish deactivated accounts, missing passkeys, and generic failures.

* **Tests**
  * Updated and added tests to verify new status mappings, UI alerts, and user-cancellation behavior.

### CODE REVIEW

File: src/main/java/de/tum/cit/aet/artemis/core/security/passkey/ArtemisWebAuthnAuthenticationProvider.java [hunk 1]
```diff
@@ -69,6 +73,11 @@ public Authentication authenticate(Authentication authentication) throws Authent
         try {
             String credentialId = webAuthnRequest.getWebAuthnRequest().getPublicKey().getId();
 
+            if (this.passkeyCredentialsRepository.findByCredentialId(credentialId).isEmpty()) {
+                log.error("Passkey login attempt with unregistered credential id '{}'", credentialId);
```
Comment (Claudia-Anthropica) [inline src/main/java/de/tum/cit/aet/artemis/core/security/passkey/ArtemisWebAuthnAuthenticationProvider.java]: @florian-glombik [low] `log.error` feels too strong here — a user trying to log in with an unregistered passkey is expected behavior, not an application error. In production, ERROR-level logs typically trigger monitoring alerts and page oncall. `log.warn` would be more appropriate for this kind of "user did something invalid" scenario.

**Review by Claudia-Anthropica — DISMISSED** [review]
@florian-glombik Clean implementation — the new exception type, distinct HTTP status codes, and client-side error differentiation all make sense. Nice improvement to the user-facing error messages too. One small note inline about the log level.

File: src/main/java/de/tum/cit/aet/artemis/core/security/passkey/ArtemisWebAuthnAuthenticationProvider.java [hunk 2]
```diff
@@ -69,6 +73,11 @@ public Authentication authenticate(Authentication authentication) throws Authent
...
+                throw new NoPasskeyFoundException("No passkey credential found for id " + credentialId);
+            }
```
[the remark this answers is not in the document]
Comment (florian-glombik) [reply src/main/java/de/tum/cit/aet/artemis/core/security/passkey/ArtemisWebAuthnAuthenticationProvider.java:79]: Is the credentialId really that sensitive? What is the attack vector that you have in mind? To me it seems like rather public information.

**Review by Claudia-Anthropica — DISMISSED** [review]
@florian-glombik Nice work — the error differentiation is clean and the HTTP status mapping makes sense. Previous feedback addressed, tests cover the new paths. Approving.

**Review by Claudia-Anthropica — DISMISSED** [review]
@florian-glombik Looks good — previous feedback addressed, the error differentiation is clean, and the new deactivated-user integration test is solid. Nice work.

File: src/main/webapp/app/core/user/settings/passkey-settings/webauthn.service.ts [hunk 3]
```diff
@@ -218,12 +219,12 @@ export class WebauthnService {
...
+                this.alertService.addErrorAlert('artemisApp.userSettings.passkeySettingsPage.error.loginDeactivated');
+            } else if (error.status === HttpStatusCode.NotFound) {
+                this.alertService.addErrorAlert('artemisApp.userSettings.passkeySettingsPage.error.noPasskeyFound');
             } else {
-                if (error.status === 401) {
-                    this.alertService.addErrorAlert('artemisApp.userSettings.passkeySettingsPage.error.loginDeactivated');
-                } else {
-                    this.alertService.addErrorAlert('artemisApp.userSettings.passkeySettingsPage.error.login');
-                }
+                this.alertService.addErrorAlert('artemisApp.userSettings.passkeySettingsPage.error.login');
```
Comment (anian03) [inline src/main/webapp/app/core/user/settings/passkey-settings/webauthn.service.ts:232]: Not sure if this is easily possible, but currently we also show this error when the user cancels the login from their authenticator (i.e. click on "Login with Passkey", but then cancel/close the authenticator window). It would be nicer if we could show a different error message (or none?) in that case.

**Review by anian03 — DISMISSED** [review]
Code looks good overall, approving. New/updated tests also cover the new not found & forbidden behavior.

One minor UX improvement suggestion for improvement below, but this is not too important imo.

File: src/main/webapp/app/core/user/settings/passkey-settings/webauthn.service.ts (hunk 3 above)
Comment (florian-glombik) [reply src/main/webapp/app/core/user/settings/passkey-settings/webauthn.service.ts:232]: I agree, it should fail silently in the background instead of displaying an error message in that case 👍 

Adressed in https://github.com/ls1intum/Artemis/pull/12482/commits/6c82adb8330a34fcb901011e0e357245e2a86d3f

**Review by Claudia-Anthropica — DISMISSED** [review]
@florian-glombik Clean work — the exception hierarchy, HTTP status mapping, and client-side error differentiation are all well done. The user cancellation handling is a nice touch too. The server-tests CI failure is unrelated (ProgrammingExerciseLocalVCIntegrationTest). Approving.

**Review by anian03 — DISMISSED** [review]
Thanks for incorporating the changes, code looks good now. Approving.

File: src/main/java/de/tum/cit/aet/artemis/core/security/passkey/ArtemisWebAuthnAuthenticationProvider.java [hunk 4]
```diff
@@ -69,6 +73,11 @@ public Authentication authenticate(Authentication authentication) throws Authent
         try {
             String credentialId = webAuthnRequest.getWebAuthnRequest().getPublicKey().getId();
 
+            if (this.passkeyCredentialsRepository.findByCredentialId(credentialId).isEmpty()) {
+                log.warn("Passkey login attempt with unregistered credential id '{}'", credentialId);
+                throw new NoPasskeyFoundException("No passkey credential found for id " + credentialId);
+            }
```
Comment (dogusaytok) [inline src/main/java/de/tum/cit/aet/artemis/core/security/passkey/ArtemisWebAuthnAuthenticationProvider.java]: Coderabbit had left a nitpick comment in here about unnecessary round trip and I think it has a valid point. We're querying the DB twice for the same `credentialId` (here, and again inside `createAuthenticationDetailsWithPasskeyApprovalStatus`). We may save a DB round trip by fetching it just once here, using orElseThrow, and passing the PasskeyCredential object directly to the method like this;

```
PasskeyCredential credential = this.passkeyCredentialsRepository
    .findByCredentialId(credentialId)
    .orElseThrow(() -> {
        log.warn("Passkey login attempt with unregistered passkey credential");
        return new NoPasskeyFoundException("No passkey credential found");
    });
```

and then after auth flow;

`Map<String, Object> details = createAuthenticationDetailsWithPasskeyApprovalStatus(credential)`

And refactor the private method to accept a `PasskeyCredential` directly. 

It's kind of a low priority but definitely a valid point. What do you think?

File: src/test/java/de/tum/cit/aet/artemis/core/security/passkey/ArtemisWebAuthnAuthenticationProviderTest.java
Comment (dogusaytok) [inline src/test/java/de/tum/cit/aet/artemis/core/security/passkey/ArtemisWebAuthnAuthenticationProviderTest.java:1]: This is also a finding from coderabbit but was flagged as "outside diff range", but I think should definitely be included.

Looks like we're missing a unit test for the new `NoPasskeyFoundException` path when a credential isn't found. Even though the integration test covers it, it would be great to have a dedicated unit test for faster feedback. Could be something like;

```
@Test
void testAuthenticateThrowsNoPasskeyFoundExceptionWhenCredentialMissing() {
    String credentialId = "unknown-credential-id";
    WebAuthnAuthenticationRequestToken requestToken = createMockRequestToken(credentialId);
    when(passkeyCredentialsRepository.findByCredentialId(credentialId)).thenReturn(Optional.empty());

    assertThatThrownBy(() -> provider.authenticate(requestToken))
        .isInstanceOf(NoPasskeyFoundException.class);
}
```

What do you think?

File: src/main/webapp/app/core/auth/passkey-authentication-page/passkey-authentication-page.component.spec.ts [hunk 5]
```diff
@@ -182,6 +182,17 @@ describe('PasskeyAuthenticationPageComponent', () => {
...
         });
 
+        it('should silently return when loginWithPasskey throws (e.g., user cancellation)', async () => {
+            vi.spyOn(webauthnService, 'loginWithPasskey').mockRejectedValue(new DOMException('User cancelled', 'NotAllowedError'));
+            const identitySpy = vi.spyOn(accountService, 'identity');
+            const redirectSpy = vi.spyOn(component, 'redirectToOriginalUrlOrHome');
+
+            await component.signInWithPasskey();
+
+            expect(identitySpy).not.toHaveBeenCalledWith(true);
```
Comment (dogusaytok) [inline src/main/webapp/app/core/auth/passkey-authentication-page/passkey-authentication-page.component.spec.ts]: Also from coderabbit as a nitpick:

The current assertion is a bit loose and would still pass if `identity() `happens to be called with other arguments. We can use `not.toHaveBeenCalled()` instead to ensure it isn't called at all when the user cancels.

Should be a quick fix. What do you think?

File: src/main/java/de/tum/cit/aet/artemis/core/security/passkey/ArtemisWebAuthnAuthenticationProvider.java (hunk 4 above)
Comment (dogusaytok) [reply src/main/java/de/tum/cit/aet/artemis/core/security/passkey/ArtemisWebAuthnAuthenticationProvider.java]: It's a small performance improvement, you can simply resolve this comment if you think it's not necessary 🙌

Comment (florian-glombik) [reply src/main/java/de/tum/cit/aet/artemis/core/security/passkey/ArtemisWebAuthnAuthenticationProvider.java]: Valid point, changed it in https://github.com/ls1intum/Artemis/pull/12482/commits/d07bd6c021ca0902ed937d1a69e7b880a77d3e8a

File: src/test/java/de/tum/cit/aet/artemis/core/security/passkey/ArtemisWebAuthnAuthenticationProviderTest.java
Comment (florian-glombik) [reply src/test/java/de/tum/cit/aet/artemis/core/security/passkey/ArtemisWebAuthnAuthenticationProviderTest.java:1]: Addressed in https://github.com/ls1intum/Artemis/pull/12482/changes/90f928a72f2646023b51b72913aac1d91b143a00

File: src/main/webapp/app/core/auth/passkey-authentication-page/passkey-authentication-page.component.spec.ts (hunk 5 above)
Comment (florian-glombik) [reply src/main/webapp/app/core/auth/passkey-authentication-page/passkey-authentication-page.component.spec.ts]: Adressed in https://github.com/ls1intum/Artemis/pull/12482/changes/61ce9a668ecb8d8ac77d9a596ba2c66277af0532

**Review by Claudia-Anthropica — APPROVED** [review]
@florian-glombik All previous feedback addressed — the log level fix, saved DB query, unit test for the NoPasskeyFoundException path, stricter test assertion, and user cancellation handling are all solid. Clean implementation, good test coverage. Nice work.

**Review by dogusaytok — APPROVED** [review]
Thanks for the additions! All looks good now, approved 🚀

**Review by anian03 — APPROVED** [review]
Tested on TS3, works as expected for all described cases :)

One minor note, unrelated to this PR: The hover tooltip for the login with passkey button on the login page appears to be missing a call to the translation utility. It says "global.menu.account.loginWithPasskey" instead of the actual string
