### PR TITLE
[Bugfix] Return always a score for an exam quiz

### LINKED ISSUE #2753: Translation of Scoring Explanation does not work for '0'
### Describe the bug

Apparently the translate pipe is not working correctly if a referenced variable has the value 0.
The error happens only in an exam quiz. 

#### To Reproduce

1. Create a quiz exercise
2. Create two questions with each having 1 point
3. Start the quiz and participate
4. See your result of the quiz and click on 'Your Score 0/1'

#### Expected behavior

The message should replace the placeholder with the correct value. So the message should be:
"You have achieved 0 points of the 5 possible points, ..."

#### Screenshots

Click here to see the info message:
image

Error during the exam mode:
image

### PR DESCRIPTION
**Pull request by derLalla**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Fixes #2753.  
If the score of an exam quiz is 0, the received score is undefined instead of 0. Therefore the info message contains the variable name {{ paramScore }} instead of 0.

### Description

When getting the score of a quiz exercise, we now check if a score is !== undefined instead of just using it's boolean representation. As the score 0 results into false and leads to an undefined score.

### Steps for Testing

1. Log in to Artemis
2. Create an exam with a quiz exercise
3. Participate in the exam and do not solve the quiz correctly. You need to receive 0 points.
4. After the exam has finished go to the exam summary and click on the `?` of `Your Score 0 / 5 (?)`
5. Verify that the text is correct and no variable names are shown

### Test Coverage

This is just a display bugfix. No changes in the code coverage.

### Screenshots

The false info message containing the variable name: 
image

The correct info message:
image

### CODE REVIEW

File: src/main/webapp/app/exam/participate/summary/exercises/quiz-exam-summary/quiz-exam-summary.component.ts [hunk 1]
```diff
@@ -116,10 +116,11 @@ export class QuizExamSummaryComponent implements OnInit {
             const submittedAnswer = this.submission.submittedAnswers.find((answer) => {
                 return answer && answer.quizQuestion ? answer.quizQuestion.id === quizQuestionId : false;
             });
-            if (submittedAnswer && submittedAnswer.scoreInPoints) {
+            if (submittedAnswer && submittedAnswer.scoreInPoints !== undefined) {
```
Comment (ivanchimeno) [inline src/main/webapp/app/exam/participate/summary/exercises/quiz-exam-summary/quiz-exam-summary.component.ts:119]: hmm that's weird, normally `submittedAnswer.scoreInPoints` is more than enough since `null, undefined, 0` are all evaluated to false

Comment (ivanchimeno) [reply src/main/webapp/app/exam/participate/summary/exercises/quiz-exam-summary/quiz-exam-summary.component.ts:119]: Maybe the change on line 123 is enough to fix the bug?

Comment (derLalla) [reply src/main/webapp/app/exam/participate/summary/exercises/quiz-exam-summary/quiz-exam-summary.component.ts:119]: the change on line 123 was after the change of line 119. 
This would be enough, yes. But the line 119 was falsy to begin with ;)

Comment (derLalla) [reply src/main/webapp/app/exam/participate/summary/exercises/quiz-exam-summary/quiz-exam-summary.component.ts:119]: > hmm that's weird, normally `submittedAnswer.scoreInPoints` is more than enough since `null, undefined, 0` are all evaluated to false

Only after this change to check for undefined, I had added the `return 0` statement.

Comment (ivanchimeno) [reply src/main/webapp/app/exam/participate/summary/exercises/quiz-exam-summary/quiz-exam-summary.component.ts:119]: Yeah that's correct but leaving `if (submittedAnswer && submittedAnswer.scoreInPoints)` would ensure that `scoreInPoints` is both defined and a positibe number which is what we want for the rounding :D

**Review by ivanchimeno — APPROVED** [review]

**Review by krusche — APPROVED** [review]
