### PR TITLE
Only log warning when user is missing in VCS

### LINKED ISSUE #2201: If user does not exist in the VCS user none active can not be deleted
### Describe the bug
Somehow I ended up with a user that was never created in the VCS. When trying to create the user again, deleting the old user fails. Not existing in the VCS should not stop the deletion of the user.

#### To Reproduce

Unknown

#### Expected behavior
Issue a warning about the failed deletion and delete the user anyway.

#### Screenshots
```
artemis                    | 2020-10-14 16:07:03.765 ERROR 1 --- [io-8080-exec-10] o.z.problem.spring.common.AdviceTraits   : Internal Server Error                            
artemis                    |                                                                                                                                                   
artemis                    | de.tum.in.www1.artemis.service.connectors.gitlab.GitLabException: Unable to get ID for user s6alvont                                              
artemis                    |    at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabUserManagementService.getUserId(GitLabUserManagementService.java:303)                
artemis                    |    at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabUserManagementService.deleteUser(GitLabUserManagementService.java:246)               
artemis                    |    at de.tum.in.www1.artemis.service.UserService.lambda$removeNonActivatedUser$7(UserService.java:325)                                            
artemis                    |    at java.base/java.util.Optional.ifPresent(Optional.java:176)                                                                                   
artemis                    |    at de.tum.in.www1.artemis.service.UserService.removeNonActivatedUser(UserService.java:325)                                                     
artemis                    |    at de.tum.in.www1.artemis.service.UserService.lambda$registerUser$5(UserService.java:278)                                                      
artemis                    |    at java.base/java.util.Optional.ifPresent(Optional.java:176)                                                                                   
artemis                    |    at de.tum.in.www1.artemis.service.UserService.registerUser(UserService.java:277)                                                               
artemis                    |    at de.tum.in.www1.artemis.service.UserService$$FastClassBySpringCGLIB$$a0f9bdbe.invoke(<generated>)                                            
artemis                    |    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)                                                                    
artemis                    |    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)                               
artemis                    |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)                                   
artemis                    |    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
```
### Environment

<details><pre>
 - Branch: develop
</pre></details>

### PR DESCRIPTION
**Pull request by axel1200**
Fixes #2201

I can write a test that tests this behaviour if you approve the change this way.

### CODE REVIEW

**Review by krusche — DISMISSED** [review]
The changes look good to me! Thanks! A test case would be awesome. Please note that we mock the REST api calls to gitlab in the tests. There should be some examples if you search for gitlab in the test folder

**Comment by axel1200** [comment]
I will try writing the test and come back to you if I fail ;)

**Review by axel1200 — COMMENTED** [review]
I think I got it right

File: src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabUserManagementService.java [hunk 1]
```diff
@@ -246,8 +246,8 @@ public void deleteUser(String login) {
             final var userId = getUserId(login);
             gitlab.getUserApi().deleteUser(userId, true);
         }
-        catch (NullPointerException e) {
-            log.warn("Cannot delete user in GitLab. User does not exist! " + login);
+        catch (GitLabUserDoesNotExistException e) {
+            log.warn("Cannot delete user in GitLab. User does not exist! %s".formatted(login));
```
Comment (MaisiKoleni) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabUserManagementService.java:250]:
```suggestion
            log.warn("Cannot delete user in GitLab. User does not exist! {}", login);
```
I don't know why it wasn't like that before. (This is the standard logging string format for SLF4J)

**Review by MaisiKoleni — COMMENTED** [review]
Code looks good to me, I just have a minor suggestion.

File: src/test/java/de/tum/in/www1/artemis/AccountResourceWithGitLabIntegrationTest.java [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+    @AfterEach
+    public void tearDown() {
+        database.resetDatabase();
+        gitlabRequestMockProvider.reset();
+    }
+
+    @BeforeEach
+    public void setUp() {
+        gitlabRequestMockProvider.enableMockingOfRequests();
+    }
```
Comment (MaisiKoleni) [inline src/test/java/de/tum/in/www1/artemis/AccountResourceWithGitLabIntegrationTest.java:48]:
```suggestion
    @BeforeEach
    public void setUp() {
        gitlabRequestMockProvider.enableMockingOfRequests();
    }

    @AfterEach
    public void tearDown() {
        database.resetDatabase();
        gitlabRequestMockProvider.reset();
    }
```
I am not sure here, this might be highly opinionated, but I think swapping `@BeforeEach` and `@AfterEach` here would make the code quicker to read.

File: src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabUserManagementService.java [hunk 3]
```diff
@@ -246,8 +246,8 @@ public void deleteUser(String login) {
             final var userId = getUserId(login);
             gitlab.getUserApi().deleteUser(userId, true);
         }
-        catch (NullPointerException e) {
-            log.warn("Cannot delete user in GitLab. User does not exist! " + login);
+        catch (GitLabUserDoesNotExistException e) {
+            log.warn("Cannot delete user ''{}'' in GitLab. User does not exist! ", login);
```
Comment (MaisiKoleni) [inline src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabUserManagementService.java:250]:
```suggestion
            log.warn("Cannot delete user ''{}'' in GitLab. User does not exist!", login);
```

**Review by MaisiKoleni — CHANGES_REQUESTED** [review]
Apart from the leftover space, the code looks good to me now and I would approve.

**Review by MaisiKoleni — APPROVED** [review]
Code looks good to me now.

**Review by krusche — APPROVED** [review]
