### PR TITLE
fixed diyplaying bug

### LINKED ISSUE #2733: Exercise assessment dashboard displaying all assessments as draft
### Describe the bug
Graded exercises appear as drafts in the exercise assessment dashboard and the date of the last build is shown. Feedback and grading remains saved in the exercises, so this seems only to affect the exercise assessment dashboard.
This issue is not present at older exercises with their assessment due dated already passed (can't confirm whether assessments submitted before the Artemis update with their due date not passed yet are affected or not).

#### To Reproduce
1. Start a new assessment
2. Add feedback, submit the assessment
3. Click "Assess Next Submission" (not sure if this is necessary for reproducing)
4. Open the exercise assessment dashboard for the exercise

#### Expected behavior
The exercises should be shown as graded with their score shown.

#### Screenshots
Exercise Assessment Dashboard (these exercises are all graded and are displayed wrongly):
grafik

Assessment after opening via the exercise assessment dashboard (feedback and grading remain saved correctly, "Override assessment" and "Assess Next Submission" button are displayed correctly):
grafik

### Environment
<details><pre>
 - OS: Windows 10
 - Browser: Latest Firefox, latest Google Chrome
 - Artemis version: 4.9.1
</pre></details>

#### Additional context
This seems to be a regression after having Artemis 4.9.1 deployed.

### PR DESCRIPTION
**Pull request by SimonEntholzer**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).

### Motivation and Context
Fixes #2733

### Description
Graded exercises appear as drafts in the exercise assessment dashboard and the date of the last build is shown.

### Source of the bug
The query that retrieves the submissions from the database `findAllByParticipationExerciseIdAndResultAssessor` returns each submission with a list of results. Each automatic result of this list is retrieved as `null` as those results don't have an assessor. By filtering out those null elements the client again only receives a submission with 1 result.

### Steps for Testing

1. Start a new programming exercise assessment
2. Add feedback, submit the assessment
3. Open the exercise assessment dashboard for the programming exercise

### Screenshots
image
---->
image

### CODE REVIEW

**Review by nicolasruscher — APPROVED** [review]
looks good! 👍

**Comment by Strohgelaender** [comment]
It seems like this only fixes the additional null-value included in the results-array. In my comparison of older and newer assessment-data also the type-Property was set to "INSTRUCTOR" instead of "MANUAL". Will this also be addressed here? Or is this unrelated / an other issue?

File: src/main/java/de/tum/in/www1/artemis/domain/Submission.java [hunk 1]
```diff
@@ -155,11 +155,24 @@ public boolean hasResultForCorrectionRound(int correctionRound) {
...
      * (do not save it like this in the database, as it could remove the automatic results!)
      */
+    @Nullable
     @JsonIgnore
     public void removeAutomaticResults() {
         this.results = this.results.stream().filter(result -> result == null || !result.isAutomatic()).collect(Collectors.toList());
     }
 
+    /**
+     * removes all elemnts from the results list, which are null.
```
Comment (fde312) [inline src/main/java/de/tum/in/www1/artemis/domain/Submission.java:165]:
```suggestion
     * removes all elements from the results list, which are null.
```

File: src/main/java/de/tum/in/www1/artemis/repository/SubmissionRepository.java [hunk 2]
```diff
@@ -117,6 +117,9 @@
     long countByExerciseIdSubmittedAfterDueDate(@Param("exerciseId") long exerciseId);
 
     /**
+     * returns submissions for a exercise. Returns only a submissoin that has a result with a matching assessor. Since the results list may also contain
```
Comment (fde312) [inline src/main/java/de/tum/in/www1/artemis/repository/SubmissionRepository.java:120]:
```suggestion
     * Returns submissions for a exercise. Returns only a submission that has a result with a matching assessor. Since the results list may also contain
```

File: src/main/java/de/tum/in/www1/artemis/domain/Submission.java [hunk 3]
```diff
@@ -155,11 +155,24 @@ public boolean hasResultForCorrectionRound(int correctionRound) {
      * removes all automatic results from a submissions result list
      * (do not save it like this in the database, as it could remove the automatic results!)
      */
+    @Nullable
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/domain/Submission.java:158]: remove

File: src/main/java/de/tum/in/www1/artemis/domain/Submission.java [hunk 4]
```diff
@@ -155,11 +155,24 @@ public boolean hasResultForCorrectionRound(int correctionRound) {
...
         this.results = this.results.stream().filter(result -> result == null || !result.isAutomatic()).collect(Collectors.toList());
     }
 
+    /**
+     * removes all elements from the results list, which are null.
+     *
+     * This can be use to prepare a submission before sending it to the client. In some cases the submission is loaded from the database
+     * with a results list which contains undesired null values. To get rid of them this function can be used.
+     */
+    @Nullable
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/domain/Submission.java:170]: remove

File: src/main/java/de/tum/in/www1/artemis/domain/Submission.java [hunk 5]
```diff
@@ -155,11 +155,24 @@ public boolean hasResultForCorrectionRound(int correctionRound) {
...
     @JsonIgnore
     public void removeAutomaticResults() {
         this.results = this.results.stream().filter(result -> result == null || !result.isAutomatic()).collect(Collectors.toList());
     }
 
+    /**
+     * removes all elements from the results list, which are null.
+     *
+     * This can be use to prepare a submission before sending it to the client. In some cases the submission is loaded from the database
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/domain/Submission.java:167]:
```suggestion
     * This can be uses to prepare a submission before sending it to the client. In some cases the submission is loaded from the database
```

File: src/main/java/de/tum/in/www1/artemis/domain/Submission.java [hunk 6]
```diff
@@ -155,11 +155,24 @@ public boolean hasResultForCorrectionRound(int correctionRound) {
...
+     * with a results list which contains undesired null values. To get rid of them this function can be used.
```
Comment (krusche) [inline src/main/java/de/tum/in/www1/artemis/domain/Submission.java:168]: add an example: when the results are filtered for specific assessors.
Also add that Hibernate wants to maintain the index in the list in order to maintain the ordered column

**Comment by krusche** [comment]
> It seems like this only fixes the additional null-value included in the results-array. In my comparison of older and newer assessment-data also the type-Property was set to "INSTRUCTOR" instead of "MANUAL". Will this also be addressed here? Or is this unrelated / an other issue?

Basically "MANUAL" means the student pushed a commit. "INSTRUCTOR" means that the tests have been executed after the exercise due date which until now creates an additional submission.

I think it does not matter if the submission type is set to "INSTRUCTOR" or "MANUAL". In the future "INSTRUCTOR" will not be used any more. Then running the tests again on the same student commit will not lead to a new submission, but simply to a new result on the same submission.

**Review by nicolasruscher — DISMISSED** [review]
Reapprove

**Review by krusche — APPROVED** [review]

**Review by krusche — APPROVED** [review]
