### PR TITLE
`Programming exercises`: Fix online editor and long feedback performance issues 

### LINKED ISSUE #11695: Opening 'see more' section of programming exercise feedback sometimes not working (online editor)
### Describe the bug

When the feedback of a programming exercise is too long to display immediately, a 'see more' button is shown.
However, sometimes it did not work at all, sometimes I had to open and close the dialog several times and sometimes just waiting made it work. 

Even after testing, I could not find out under what circumstances it does and when it doesn't. I could only reproduce it in online editor view and not on the exercise's overview page, but I remember students experiencing this also on the overview page.

Why not just use the overview page? - My exams only allow working with the online editor and if that is active students cannot access the usual overview page.

I have some logs from testing attached in the screenshots section.

### To Reproduce

1. Create a programming exercise allowing online editor.
2. Create at least one test case that puts out a long feedback.
3. Participate in the exercise with any account and submit a solution that will trigger to long feedback message.
4. Open the feedback on the exercise overview page and in the online editor page and try to open the 'see more' section.
5. See the bug.

### Expected behavior

Just open and close the section on the first click.

### Screenshots

Image

Image

### Which version of Artemis are you seeing the problem on?

8.5.0, 8.6.0

### What browsers are you seeing the problem on?

Microsoft Edge, Firefox

### Additional context

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by FelixTJDietrich**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the [client coding guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

Currently the online editor has critical performance issues preventing performant syntax highlighting, file switching and looking at long feedbacks. 

Fixes #11695

Performance bug sometimes even crashes the editor:
Performance Bug mov

### Description

This pull request focuses on improving the performance and reliability of several code editor-related Angular components by adopting the OnPush change detection strategy and ensuring UI updates are triggered correctly. Additionally, it cleans up some debounce logic and enhances error handling and resource cleanup.

The most important changes are:

**Change Detection & Performance Improvements:**
- Switched multiple components (`CodeEditorBuildOutputComponent`, `CodeEditorFileBrowserComponent`, `CodeEditorContainerComponent`, `CodeEditorActionsComponent`, and `FeedbackCollapseComponent`) to use `ChangeDetectionStrategy.OnPush` for more efficient change detection. [[1]](diffhunk://#diff-913d597ae7270fa8184b94a8e4ed477f374fc2dfbffc0615a475f8b3f51ac3fbR44-R52) [[2]](diffhunk://#diff-c39b45edede61d70a60c6c5cd587c2518f8d01f46cbaf596d1512ad02701b57eL20-R21) [[3]](diffhunk://#diff-2a64039c2b1a53bb5d5154d7728d3a34260ebcf4e855c2c42bc4be221270d326R43) [[4]](diffhunk://#diff-4e98b52c09a9ace28c01246651f19a6839d6c2ff7a471be5877cc79f7af59a8dR43) [[5]](diffhunk://#diff-3711d562c779be35c580d8d3e43bcbeb9c7ab808eb96492aecb953b4732731ccL1-R12)
- Added explicit calls to `ChangeDetectorRef.markForCheck()` after state changes in these components to ensure the UI updates as expected when using OnPush. [[1]](diffhunk://#diff-913d597ae7270fa8184b94a8e4ed477f374fc2dfbffc0615a475f8b3f51ac3fbL98-R125) [[2]](diffhunk://#diff-913d597ae7270fa8184b94a8e4ed477f374fc2dfbffc0615a475f8b3f51ac3fbL147-R172) [[3]](diffhunk://#diff-913d597ae7270fa8184b94a8e4ed477f374fc2dfbffc0615a475f8b3f51ac3fbL164-R201) [[4]](diffhunk://#diff-c39b45edede61d70a60c6c5cd587c2518f8d01f46cbaf596d1512ad02701b57eR307) [[5]](diffhunk://#diff-c39b45edede61d70a60c6c5cd587c2518f8d01f46cbaf596d1512ad02701b57eL335-R353) [[6]](diffhunk://#diff-4e98b52c09a9ace28c01246651f19a6839d6c2ff7a471be5877cc79f7af59a8dR54-R55) [[7]](diffhunk://#diff-4e98b52c09a9ace28c01246651f19a6839d6c2ff7a471be5877cc79f7af59a8dL63-R99) [[8]](diffhunk://#diff-4e98b52c09a9ace28c01246651f19a6839d6c2ff7a471be5877cc79f7af59a8dR115-R173)

**Code Cleanup & Reliability:**
- Removed the unused debounce logic from `FeedbackCollapseComponent` and replaced all usages with direct calls to `toggleCollapse()`, simplifying the collapse/expand logic. [[1]](diffhunk://#diff-c1f6f11747b748f8580591ed79542b5afd418a141cd4dfbaeaa616419113338cL7-R7) [[2]](diffhunk://#diff-c1f6f11747b748f8580591ed79542b5afd418a141cd4dfbaeaa616419113338cL16-R16) [[3]](diffhunk://#diff-3711d562c779be35c580d8d3e43bcbeb9c7ab808eb96492aecb953b4732731ccL34-L35)
- Improved resource cleanup by unsetting interact.js resizable objects on component destroy, preventing potential memory leaks.

**Error Handling Enhancements:**
- Improved error handling and loading state management in `CodeEditorFileBrowserComponent` by using the `finalize` operator to always clear loading indicators and update the UI, even when errors occur.

**Other Improvements:**
- Enhanced the autosave timer in `CodeEditorActionsComponent` to run outside Angular’s zone, reducing unnecessary change detection cycles and only re-entering Angular when a save is triggered.

These changes collectively improve the responsiveness, maintainability, and reliability of the code editor features.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Programming Exercise with test cases that return really long feedback 
  - Enable **online editor in advanced mode**
  - Edit test repository test cases and add long `fail` feedback:
> For example: `fail("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quis purus ornare, laoreet sapien a, gravida leo. Aliquam erat volutpat. Nam aliquam tempor erat, sit amet ornare sapien ornare in. Sed tempus turpis varius, efficitur ex non, ullamcorper erat. Quisque fringilla magna elit, ut ullamcorper elit suscipit sit amet. Vestibulum lacus dolor, egestas vitae tincidunt vel, pulvinar a tellus. Sed pellentesque eu massa ut semper. Nunc dapibus nulla at orci malesuada congue. Integer dictum scelerisque laoreet. Duis quis urna in tellus egestas hendrerit. Curabitur ultricies malesuada leo, ac tristique mi sagittis vel. Vivamus pretium interdum ornare. Aliquam ornare, nulla nec ultricies consectetur, mi velit efficitur massa, pretium consequat ex sapien at enim. Quisque faucibus arcu quis odio vehicula rutrum. Pellentesque bibendum lacus purus, nec venenatis nunc fermentum nec. Curabitur ullamcorper, augue sed dignissim porttitor, sapien ligula tristique ipsum, nec mollis felis sapien eget elit. Etiam sodales a massa porttitor iaculis. Nulla tristique ex a dui consequat, nec tempus sem auctor. Fusce congue in nulla id lacinia. Maecenas rhoncus felis lorem. Suspendisse potenti. Donec eget dictum risus. Donec sed egestas arcu. Suspendisse vitae nisl enim. Vestibulum lobortis tristique justo, id consequat odio interdum ut. Phasellus vitae augue ipsum. Praesent ac leo a tortor eleifend volutpat at at sem. Integer sapien enim, dapibus vel convallis vitae, pharetra nec tellus. Maecenas dapibus faucibus ante id dapibus. Morbi vel tristique ligula. Phasellus rhoncus, magna eu dapibus imperdiet, magna risus egestas ante, eu bibendum mauris sem laoreet metus. Nulla in convallis sapien. Cras vel dolor.")`

1. Log in to Artemis as Student
2. Navigate to Course with Programming Exercise
3. Click on Programming Exercise
4. Click on "Open code editor"
5. Type in editor and observe that syntax highlighting is (almost) immediate. It should not be able to write some text that stays white for a few milliseconds, e.g. `// this is a test` should be syntax highlighted as comment immediately.
6. Switching between files should feel responsive with the loading spinner not lagging
7. Submit and wait for build results
8. Press on the build result, e.g. `0% (a few seconds ago)` 
9. Scroll to long feedback with "see more"
10. Press "see more"
11. It should open immediately without lagging

### Testserver States
You can manage test servers using [Helios](https://helios.aet.cit.tum.de/). Check environment statuses in the [environment list](https://helios.aet.cit.tum.de/repo/69562331/environment/list). To deploy to a test server, go to the [CI/CD](https://helios.aet.cit.tum.de/repo/69562331/ci-cd) page, find your PR or branch, and trigger the deployment.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Performance Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Unchanged

### Screenshots

Fixed mov

## Summary by CodeRabbit

* **Performance Improvements**
  * Broad adoption of OnPush change detection and improved zone usage for faster, more efficient UI updates.
  * Frame-synchronized rendering for feedback widgets to reduce re-renders and jank.

* **Bug Fixes**
  * Improved feedback collapse toggle responsiveness.
  * Better cleanup to avoid memory leaks (animation frames, subscriptions) and more robust file/load error handling.

* **Tests**
  * Tests updated for changed detection/timing behavior and more resilient timing assertions.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/main/webapp/app/programming/manage/code-editor/build-output/code-editor-build-output.component.ts [hunk 1]
```diff
@@ -234,5 +264,8 @@ export class CodeEditorBuildOutputComponent implements AfterViewInit, OnInit, On
         if (this.submissionSubscription) {
             this.submissionSubscription.unsubscribe();
         }
+        if (this.interactResizable) {
+            this.interactResizable.unset();
```
Comment (Michael-Breu-UIbk) [inline src/main/webapp/app/programming/manage/code-editor/build-output/code-editor-build-output.component.ts:268]: I cannot understand, why this was relevant here. Perhaps later.

**Review by sawys777 — APPROVED** [review]
Tested on TS 4, syntax highlighting and switching file behaviour works as described, as for seeing long error message, sometimes it takes a second to display, sometimes is immediate. Below is a video showing the see more for long error msg.

https://github.com/user-attachments/assets/96cabca4-faf0-490a-a621-7019a84a0318

File: src/main/webapp/app/programming/manage/code-editor/build-output/code-editor-build-output.component.ts (hunk 1 above)
Comment (FelixTJDietrich) [reply src/main/webapp/app/programming/manage/code-editor/build-output/code-editor-build-output.component.ts:268]: Claude Opus 4.5 says:
> Prevents `interact.js` memory leak - event handlers stay attached after destroy without `.unset()`. Spotted this while adding OnPush; the file-browser component has the same issue but that's out of scope for this PR.

**Comment by FelixTJDietrich** [comment]
I tested also the manual assessment on TS1 and it works as expected:
image

File: src/main/webapp/app/programming/manage/code-editor/build-output/code-editor-build-output.component.ts (hunk 1 above)
Comment (FelixTJDietrich) [reply src/main/webapp/app/programming/manage/code-editor/build-output/code-editor-build-output.component.ts:268]: I would still categorize it as a performance improvement

**Review by HawKhiem — APPROVED** [review]
Tested on TS1, everything works great 👍. Code looks good to me too 👍
